### ISSUE TITLE
xonsh appears to be closing file descriptors in subprocesses

### ISSUE THREAD

**Issue by nkabir** [xonsh/xonsh#2984] opened 2019-01-15 13:23 UTC
## xonfig

```
+------------------+---------------------+
| xonsh            | 0.8.8               |
| Git SHA          | b64a2126            |
| Commit Date      | Jan 2 19:02:13 2019 |
| Python           | 3.6.7               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.7               |
| shell type       | prompt_toolkit2     |
| pygments         | 2.3.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | ubuntu              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

## Expected Behavior

`$ redo hello` should produce `hello` executable

## Current Behavior

```
$ redo hello
redo  hello
Traceback (most recent call last):
  File "/home/nkabir/.local/bin/redo-ifchange", line 11, in <module>
    sys.exit(main())
  File "/home/nkabir/.local/lib/python2.7/site-packages/redo/cmd_ifchange.py", line 41, in main
    jobserver.setup(0)
  File "/home/nkabir/.local/lib/python2.7/site-packages/redo/jobserver.py", line 238, in setup
    'prefix your Makefile rule with a "+"')
ValueError: broken --jobserver-auth from make; prefix your Makefile rule with a "+"
hello

```

## Steps to Reproduce

```
$ pip install --user redo-tools
$ pip3 install --user xonsh
```
Place `hello.do` and `hello.c` into the same folder:

`hello.do`
```
#!/usr/bin/env xonsh

#del $MAKEFLAGS
#del $REDO_CHEATFDS

gcc -o $3 hello.c

redo-ifchange hello.c

```
`hello.c`
```
#include <stdio.h>
int main()
{
   printf("Hello, World!");
   return 0;
}

```
Finally, execute 

```
$ redo hello
```
Note that explicitly deleting `MAKEFLAGS` and `REDO_CHEATFDS` is a work-around that forces the process to be serial.

**Comment by scopatz** [comment] 2019-01-31 17:08
Thanks for reporting @nkabir! I am not familar with what redo is or how it works.  Is there a more minimal example that you can show?  I use make and compilers in xonsh all the time....

**Comment by nkabir** [comment] 2019-01-31 18:48
Hi @scopatz 

Thanks for getting back! I created a minimal demonstration repository here

https://github.com/nkabir/fdcheck

Clone the repository to an Ubuntu 18.04 host and run `make all` and `make flagged` to reproduce the error. Please let me know if you encounter any issues. Xonsh is wonderful.-)

**Comment by scopatz** [comment] 2019-02-01 16:15
Hmmm redo-tools seems to require Python 2, which I don't have anymore. Do you have an example that doesn't rely on Python 2 or is there a docker container that you can point me to? Sorry for all the trouble just getting started with this one.

**Comment by scopatz** [comment] 2019-02-04 21:21
What happens if you do:

```python
__xonsh__.commands_cache.threadable_predictors['redo'] = lambda *a, **k: False
```

in your current session or xonshrc?  Does this fix the issue?

**Comment by nkabir** [comment] 2019-02-04 21:39
Hi Anthony.

I placed the line at the top of my `.xonshrc` and then executed `redo` from within `xonsh` and there was no change. Could this be an issue with running Python2.7 processes inside `xonsh` hosted on Python3.6?

```
Traceback (most recent call last):
  File "/home/nkabir/.local/bin/redo-ifchange", line 11, in <module>
    sys.exit(main())
  File "/home/nkabir/.local/lib/python2.7/site-packages/redo/cmd_ifchange.py", line 41, in main
    jobserver.setup(0)
  File "/home/nkabir/.local/lib/python2.7/site-packages/redo/jobserver.py", line 238, in setup
    'prefix your Makefile rule with a "+"')
ValueError: broken --jobserver-auth from make; prefix your Makefile rule with a "+"

```

**Comment by scopatz** [comment] 2019-02-04 21:46
No, it shouldn't be a problem to run Python 2 inside of xonsh.  I am curious as to why you think this is a  xonsh filehandle error and not a redo error. The traceback seems to indicate an incorrect redo configuration and doesn't mention anything about xonsh.  Does this work in bash or another shell?

**Comment by nkabir** [comment] 2019-02-04 22:17
It works in `bash`. The error appeared when I ported redo scripts to `xonsh`.

I've brought this to the attention of Avery (`redo` author) and he suspected it was a `xonsh` issue. It's briefly covered here:
https://redo.readthedocs.io/en/latest/FAQParallel/

It's not a blocker for me at the moment--I'm disabling parallel builds with 

```
del $MAKEFLAGS
del $REDO_CHEATFDS
```

at the top of my scripts. I can report back once I need parallel builds and have time to dig deeper. Another thanks for `xonsh`. My build scripts are much easier to maintain with `xonsh`'s seamless integration with Python. `xonsh` has been a pleasure to use!

**Comment by scopatz** [comment] 2019-02-04 23:08
Oh interesting, so redo is actually launching xonsh, potentially via make.  That is very interesting.  I am still not sure why you / Avery think that this is a file descriptor issue. Can you rope Avery into this conversation to explain? Or is there a minimal Makefile that I can use to test this out?  

I am not sure how many folks have tried to use xonsh inside of make or gdb or other tools with assume that $SHELL is a posix-compatible shell. We, of course, want xonsh to work with these tools.

> xonsh has been a pleasure to use!

Thanks again!

**Comment by rdpate** [comment] 2019-02-05 01:18
I have followed this issue from the redo mailing list.  I was unable to make xonsh after cloning because I do not have xonsh installed as required by Makefile.  I do not see bootstrap instructions.

A minimal example should be:

```sh
xonsh -c 'echo x | dd of=/dev/fd/3' 3>&1
```

Which should do the same as: `xonsh -c 'echo x | dd'`, but I expect the above will fail given that xonsh reportedly keeps the Python3's subprocess.popen(close_fds=True) default, which was False in Python2.

My understanding of the problem is that:
1. xonsh closes file descriptors when running commands (hence using /dev/fd/3 in the example)
2. redo expects the POSIX behavior of inherited descriptors (fd 3 in my example) not being closed

A more complex example that is also more similar to what the issue reporter encountered would be:

```sh
export FD=3
exec 3>&1  # actually a pipe(2) in the situation the OP encountered
xonsh -c 'echo x | dd of=/dev/fd/"$FD"'
```

**Comment by apenwarr** [comment] 2019-02-05 04:14
Below is a test program that doesn't use redo that demonstrates the problem with xonsh.  It uses os.pipe2() to create two file descriptors connected to each other by a pipe.  It then launched a subprocess, closes its own copy of the 'write' side of the pipe, and waits for the 'read' side to become ready.  Since nobody ever writes to the write side, this happens only when the no more processes exist that inherited the write fd.  Our parent process closed its copy, so the only copy is inherited by our subprocess and its children.

We run this test twice, once with each of two different subprocesses:
1) sh -c 'sleep 2 & exit'
2) xonsh -c 'sleep 2 &; exit'

In case (1), we end up waiting a full two seconds, even though 'sh' has exited right away.  (In sh, the 'exit' is not necessary, but I include it for symmetry with xonsh.)  In case (2), we end up exiting before the 'sleep' command has returned.  This proves that the sleep command did not inherit the write fd as it should have.  On the other hand, if I remove the '; exit', then it waits 2 seconds, but that's because xonsh itself refuses to exit while it has a child process still running, even though that child was backgrounded.

This test reveals several weirdnesses in xonsh:

i) It shouldn't touch file descriptors that it didn't personally open.  I opened the write fd, I didn't refer to it from my xonsh command, and so the correct behaviour is to leave it alone.  Doing this wrong will break parallel builds in make and redo, but also break any programs that rely on fd passing to children, and others that rely on the above trick to determine if an entire process pipeline has ended before continuing.

ii) xonsh should exit right away if a background process exists and there are no remaining commands.  It isn't helping anyone by converting "xonsh -c 'sleep 2 &'" from an explicit background into a foreground process.

iii) The "don't exit until everything is done" behaviour might perhaps be nice in interactive mode, but in interactive mode, the "; exit" also doesn't exit, which is at least consistent.  In batch mode, it behaves differently depending whether or not you have "; exit" at the end, which is pretty strange.

`#!/usr/bin/python3
import os, subprocess, sys, time

def test(argv):
    t0 = time.time()
    print('\ntesting %r' % argv)
    r, w = os.pipe2(0)
    p = subprocess.Popen(argv, close_fds=False)
    os.close(w)
    b = os.read(r, 4096)
    assert not b
    t1 = time.time()
    t = t1 - t0
    print('pipe closed; p exit status = %r; t = %r' % (p.poll(), t))
    assert t >= 2.0, 'sleep did not inherit write fd'
    print('ok.')

test(['sh', '-c', 'sleep 2 & exit'])
test(['xonsh', '-c', 'sleep 2 &; exit'])
`

**Comment by apenwarr** [comment] 2019-02-05 04:35
Here's another example that uses just GNU make.

```
$ time make -sj2 SHELL=sh
real	0m2.010s
user	0m0.000s
sys	0m0.000s

$ time make -sj2 SHELL=xonsh
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
real	0m5.001s
user	0m0.764s
sys	0m0.164s
```

Makefile:
```
default: all
all:
	$(MAKE) s
s:
	$(MAKE) a b
a:
	sleep 2
b:
	sleep 2
```

**Comment by scopatz** [comment] 2019-02-05 16:53
Thanks @rdpate @apenwarr for the detailed descriptions here! I am still trying to piece together what the underlying issue is here.  Part of the problem, I suspect, is that the two example cases @apenwarr listed are not semantically equivalent.  

>   1. `sh -c 'sleep 2 & exit'`

This means: run the sleep for 2 sec AND if the exit code is zero (ie successful completion), run the exit command

>   2. `xonsh -c 'sleep 2 &; exit'`

This means: run the sleep for 2 sec in the background. Then run the exit command.

A proper translation of (1) would be either:

3. `xonsh -c "sleep 2 && exit"`, or the more Pythonic `xonsh -c "sleep 2 and exit"`

(3) behaves as expected in that it runs for two seconds and then exits. A proper translation of (2) into bash would be:

4. `sh -c "bg sleep 2 && exit"`

This fails because there is no job control in Bash when not running as a REPL.  Maybe it is a little strange that xonsh has job control even when not in interactive mode, but it shouldn't get in anyone's way usually.

Can you please clarify which semantics, (1) or (2), are actually important?

**Comment by scopatz** [comment] 2019-02-05 18:36
Hmm I didn't think xonsh supported `>&` at all.  It must be there for posix compatibility, but clearly isn't implemented generally enough.

**Comment by apenwarr** [comment] 2019-02-05 18:38
That doesn't matter.  3>&1 is interpreted by bash in that one-liner.  xonsh *still* manages to then eat fd #3.

**Comment by rdpate** [comment] 2019-02-05 23:09
> Hmm I didn't think xonsh supported `>&` at all. It must be there for posix compatibility, but clearly isn't implemented generally enough.

My minimal test case is intended to be run from a shell such as zsh or bash, which then runs xonsh and shows the failure.  (As @apenwarr mentioned.)

You might see the other test case I presented, in which I was explicit in /bin/sh calling xonsh.

**Comment by scopatz** [comment] 2019-02-06 03:15
Also, `sh -c "sleep 2 & exit"` does not return right away for me, but rather waits 2 seconds.

**Comment by scopatz** [comment] 2019-02-06 03:17
Oddly, it only returns right away in bash, but waits in xonsh

**Comment by apenwarr** [comment] 2019-02-06 04:56
> Oddly, it only returns right away in bash, but waits in xonsh

Wow, you're right.  I just tried to strace what xonsh does when it launches a subprocess and... it's pretty complicated, involves starting several subthreads, and will surely lead to weird bugs.  But that's for another day!

**Comment by scopatz** [comment] 2019-02-06 19:55
A potential fix is in  #3015, please test it out with redo

**Comment by nkabir** [comment] 2019-02-06 21:06
Thanks, Anthony! I do not have enough knowledge about the internals of either tool to make an authoritative assessment but wanted to provide smoke test results as soon as possible. The patch appears to work based on my build scripts and an example from above. 

This is on a clean Ubuntu 18.04:

```
xonsh -c 'echo x | dd of=/dev/fd/3' 3>&1
x
0+1 records in
0+1 records out
2 bytes copied, 0.000256735 s, 7.8 kB/s
```
I've also removed the `xonsh` workarounds from my `redo` scripts

```
del $MAKEFLAGS
del $REDO_CHEATFDS
```
and `redo` is no longer complaining.

**Comment by scopatz** [comment] 2019-02-06 21:08
excellent!

**Closed** 2019-02-06 21:49 UTC

**Comment by melund** [comment] 2019-02-06 21:51
@nkabir #3015 is merged now. Thanks a lot for all the work hunting down this bug. It is really appreciated .

**Comment by scopatz** [comment] 2019-02-06 21:52
Much agreed with @melund! If there are lingering problems, please open new issues.

**Comment by nkabir** [comment] 2019-02-06 22:12
Much gratitude to @apenwarr and @rdpate for their deep and insightful low-level analysis...
