### ISSUE TITLE
cat can't seem to get its input - anyone else seeing this?

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1498] opened 2016-07-27 21:12 UTC
This works fine from the xonsh commandline:
> $(cat somefile).splitlines()
> ['line one',
> 'line two']

This doesn't:
> $(cat).splitlines()
> I can type all day long
> control-D appears to be getting swallowed
> cant end the file
> have to abort my login session
> ouch

This is with a just-now built master. I was seeing this problem on an earlier version so I updated to the latest master before penning this issue.

Anyone else seeing problems with running commands that read stdin?

**Comment by scopatz** [comment] 2016-07-27 21:37
Yup, I can reproduce this.  It seems to work on Bash, for what what it is worth:

```console
 x=$(cat)
jhdjds^D
(awm-trusty)scopatz@localhost:~/xonsh$ echo $x
jhdjds
```

**Comment by scopatz** [comment] 2016-07-27 21:39
Actually it seems like if I hit Ctrl-D twice in a row it will work.

**Comment by PaulReiber** [comment] 2016-07-27 21:41
Both of the behaviours you showed in response are of things working fine.

I'm seeing xonsh get hung up on this - no more prompt, no more connection.

The only thing that worked was "~." to break out of the ssh session I have
with the linux box where I test.

I'll investigate further when I'm back online a little later today.

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by adqm** [comment] 2016-08-18 23:26
I can't reproduce this.  Has this already been taken care of?  Or am I an anomaly?

**Comment by laerus** [comment] 2016-08-18 23:34
yup this works with both Ctrl-D and Ctrl-C, when bugs fix themselves i blame dark wizardry. closing this, @PaulReiber feel free to reopen if you still have this problem on the latest release!

**Closed by laerus** 2016-08-18 23:34 UTC
Labels: bug
