### ISSUE TITLE
xonsh failed to pickup the modules installed

### ISSUE THREAD

**Issue by paulhybryant** [xonsh/xonsh#1766] opened 2016-09-26 07:32 UTC
I am using OSX.

Installing xonsh through
brew install xonsh

After that installed xontrib module (e.g. z)
pip3 install xontrib-z

The python module is installed in the site-packages of homebrew python in /usr/local/lib/python3.5/site-packages.

When starting xonsh, it complains about unable to find the xontrib module z.

In xonsh, by adding /usr/local/lib/python3.5/site-packages through site.addsitedir, xontrib load z finishes without error.

In linux, I can resolve this issue by putting a homebrew.pth file in ~/.local/lib/python3.5/site-packages.
However, that does't seem to work for OSX.

**Comment by gforsyth** [comment] 2016-09-26 10:49
Thanks for reporting, @paulhybryant!  This is a duplicate of #1733.  

> In xonsh, by adding /usr/local/lib/python3.5/site-packages through site.addsitedir, xontrib load z finishes without error.

That's good to know.  This seems like it's an issue with the homebrew recipe and it also looks like you've already found a workaround.  Is it possible to include the `side.addsitedir` to the homebrew recipe?  ping @OJFord

**Comment by OJFord** [comment] 2016-09-26 11:16
@gforsyth Is `site` a xonsh thing? Not familiar with that, but if so I doubt it would be possible in the brew formula, since it would need to be run inside xonsh (`xonsh -c "..."`?) - and I rather suspect the Homebrew folks wouldn't like that.

It ought to be possible to change its existing location though, but I haven't looked into it yet.

Just to reiterate what I said in #1733, a workaround on OS X is:
```
import sys                                                                                                                  
sys.path.extend([                                                                                                           
    p for p in eval($(python3 -c 'import sys; print(sys.path)'))                                                            
    if p not in sys.path                                                                                                    
])
```

**Comment by gforsyth** [comment] 2016-09-26 11:19
`site` is part of the standard library.  I think `site.addsitedir` would accomplish the same thing as your workaround but without the `eval` statement.

**Comment by astronouth7303** [comment] 2016-09-26 16:53
[`site`](https://docs.python.org/3/library/site.html)

This is very strange. On Linux, I have no trouble with having system and user sites. On Windows, I'm using a user-installed Python and a _lot_ of venvs, so I can't confirm behavior.

This smells like you've got too many versions of Python running around, and you're actually using two different installations. It's either that or a bug in `brew` or `site`.

What's the value of `sys.path` without any of the workaround? (Note that `site` does not add directories that don't actually exist.)

**Comment by gforsyth** [comment] 2016-09-26 17:32
Here's the brew recipe for `xonsh`: https://github.com/Homebrew/homebrew-core/blob/9c2c13e62cb3336953dc8c1599f1a5efe2712398/Formula/xonsh.rb

It installs `xonsh` in a virtualenv, so it won't have access to anything installed with `pip`.  I'm strongly leaning towards labelling this `wontfix` and punting to whoever handles the brew recipe

**Comment by paulhybryant** [comment] 2016-09-27 01:48
I ended up adding this in the brew formula.

def post_install
     pth_contents = "import site; site.addsitedir('#{HOMEBREW_PREFIX}/lib/python3.5/site-packages')\n"
     (libexec/"lib/python3.5/site-packages/homebrew.pth").write pth_contents
end

I will send a PR to homebrew and see what they say.

The strange thing is the different behavior between OSX and linux.
It seems the python in linux will look at ~/.local/lib/python3.5/site-packages for *.pth files,
but not in OSX.

**Comment by gforsyth** [comment] 2016-10-01 16:26
Ok @paulhybryant -- I'm going to close this as it appears to be a brew issue but please reopen if you have any issues on the xonsh side.

**Closed by gforsyth** 2016-10-01 16:26 UTC
Labels: bug, duplicate, mac osx, wontfix
