### ISSUE TITLE
Creation of anomalous folders when setting `$XDG_DATA_DIR` and `$XONSH_DATA_DIR` in config.json

### ISSUE THREAD

**Issue by derekbrokeit** [xonsh/xonsh#1782] opened 2016-09-30 05:47 UTC
In the `config.json` file, I had the following items:

``` json
"XDG_DATA_HOME": "~/.local/share",
"XONSH_DATA_DIR": "~/.local/share/xonsh",
```

I found that whenever a new terminal was created, it would create a folder `~` in whatever the initial open folder is. So, there will end up being `~` folders everywhere if I open up `tmux` or start new terminals. This doesn't really affect me because I do not need to set these items, which are just defaults, but it may be good to have proper way to reference `$HOME` from the config files.

**Comment by gforsyth** [comment] 2016-09-30 11:00
Hey @derekbrokeit, thanks for reporting!  I can't reproduce this.  Could you post the output of `xonfig`?  Thanks!

**Comment by derekbrokeit** [comment] 2016-09-30 14:14
I think the problem is more peculiar that I originally thought. The folder tree is actually fairly complicated, but it may help point to the source of the problem. 

```
~
└── .local
    └── share
        └── xonsh
            └── xonsh_script_cache
                └── _users
                    └── derek
                        └── _.xonshrc.cpython-35
```

My xonfig is as follows:
```
+------------------+-----------------+
| xonsh            | 0.4.6.dev282    |
| Git SHA          | ad557bb         |
| Python           | 3.5.1           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.1           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |y 
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

A more peculiar outcome is also that replacing the '~' in those fields with the absolute path actually seems to force `xonsh` to startup without a `.xonshrc` file at all.

```json
# the following causes xonsh to not use my .xonshrc file
"XDG_DATA_HOME": "/Users/myusername/.local/share",
"XONSH_DATA_DIR": "/Users/myusername/.local/share/xonsh",
```

I am currently traveling, but if I find more information for you, I will document it here.

**Comment by gforsyth** [comment] 2016-09-30 14:55
@derekbrokeit -- that is really weird.  I still can't reproduce this so it might be an OSX thing?  But that's very odd.  

If you use the absolute paths, what's the value of `$XONSHRC` after startup?

**Comment by derekbrokeit** [comment] 2016-10-01 11:30
I tried both options and the value of `$XONSHRC` Was the default built in value from xonsh for both cases.

**Comment by gforsyth** [comment] 2016-10-01 16:23
hey @derekbrokeit , could you try out the fix in #1788?  Thanks!

**Comment by derekbrokeit** [comment] 2016-10-02 07:10
I just checked out this commit, but unfortunately, that did not change the situation:

1. not setting `$XDG_DATA_DIR` and `$XONSH_DATA_DIR` (or setting with an absolute path) causes `~/.xonshrc` file to never run
2. setting `$XDG_DATA_DIR` and `$XONSH_DATA_DIR` to `~/any/path` causes anomalous folder creation in the start directory

**Comment by derekbrokeit** [comment] 2016-10-10 23:14
It would be good to re-open this ticket. Not only do I continue to see this in my OSX computer, but I just checked my windows computer as well. The problem persists in both systems.

**Comment by gforsyth** [comment] 2019-07-14 16:53
I'm closing this as we no longer support `config.json`

**Closed by gforsyth** 2019-07-14 16:53 UTC
