### ISSUE TITLE
Xonsh hang in some weird cases

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [xonsh/xonsh#853] opened 2016-05-12 12:55 UTC
Hello,

In some cases xonsh just stop responding. I have been facing it in my Ubuntu and Arch Linux setup.

But not on a Mac OSx.

I can reproduce it by doing this (I know it does not really make sense but it's only way I found to reproduce the bug consistently):

```
cat $(which xonch)
which xonch
```

After this command is executed nothing is executed, xonsh seems ignoring my inputs

**Comment by GuillaumeLeclerc** [comment] 2016-05-12 13:51
I happened to me again just when I was typing `cd ..`
I don't get what's causing this

**Comment by scopatz** [comment] 2016-05-12 22:22
Do you think that this is caused by the branch checking issue?

**Comment by GuillaumeLeclerc** [comment] 2016-05-12 22:26
@scopatz I don't know about this issue sorry

**Comment by GuillaumeLeclerc** [comment] 2016-05-15 08:46
Are we using `communicate` when communicating with subprocesses ? 

Because I saw this on the python docs:

```
Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.
```

Could it come from this ?

**Comment by melund** [comment] 2016-05-15 17:33
This was/is actually a problem, but one that may soon be fixed https://github.com/scopatz/xonsh/pull/875

**Comment by GuillaumeLeclerc** [comment] 2016-05-15 19:52
since #875 was merge I will assume it's fixed and reopen if I ever see it again

**Comment by GuillaumeLeclerc** [comment] 2016-05-15 20:14
It just happened to me while doing a `cd ..` again

**Comment by melund** [comment] 2016-05-15 21:36
Are you using prompt_toolkit?

**Comment by GuillaumeLeclerc** [comment] 2016-05-15 21:45
yes

**Comment by adqm** [comment] 2016-05-18 03:13
I get these random hangs occasionally, too, and I only use the readline shell.

That said, I can't reproduce with the example from the original post.  AFAICT, no noticeable pattern as to when the hanging happens.

I might put a bunch of print statements throughout my local install to see if I can catch what is going on when this happens, and where xonsh is getting stuck...

**Comment by scopatz** [comment] 2016-05-18 03:18
For what it is worth, I have yet to see this.

**Comment by GuillaumeLeclerc** [comment] 2016-05-18 06:46
The frequency of these hangs has significantly decreased since I started being up to date with master. it went from 2 times an hour to one time every 3 days or so (which is way less annoying)

**Comment by laerus** [comment] 2016-07-10 11:10
Hey @GuillaumeLeclerc do you still have this issue with the latest master?

**Comment by laerus** [comment] 2016-09-01 00:22
this seems fixed on current master, feel free to reopen if the problem still persists!

**Comment by sopoforic** [comment] 2016-09-11 16:27
I've been seeing this bug myself with 0.4.5 and it is still happening when I update from master:

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.4.6           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | False           |
| prompt toolkit   | 1.0.3           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

It's happening very frequently, with no pattern I can discern. After executing a subprocess, changing directories, or whatever, xonsh just hangs without printing a new prompt and doesn't accept input.

**Comment by laerus** [comment] 2016-09-11 16:41
this may be related to command caching but this is just a wild guess.

**Comment by scopatz** [comment] 2016-09-11 17:52
Hopefully my `run_subproc()` refactor will address this.  It is still not usable, yet, though.

**Comment by sopoforic** [comment] 2016-09-16 19:08
I've been trying to pay attention to when this happens, and I *believe* that it is much more common when I haven't interacted with the prompt for a while. It seems to happen most of the time when I first open a new prompt (necessitating killing that one and opening another, which rarely-to-never fails), and often when coming back from long ssh sessions, but very rarely (or maybe never) immediately after another command.

**Comment by sopoforic** [comment] 2016-09-19 05:37
Some more information: after a bit more testing, I believe that xonsh *always* hangs after commands when enough time has passed (a quarter hour is probably enough--it's more than just a few minutes, but not terribly long). If it has been a while since I used the terminal, I can open a new terminal session, which will hang before printing the prompt the first time, then kill it and continue working with my old xonsh session without issue. If I don't open the new xonsh session, the old one will hang, instead.

I hope this observation is useful. Let me know if there's any further information I can provide that will be helpful.

**Comment by scopatz** [comment] 2016-09-21 00:45
This seems very strange.  Thanks for reporting @sopoforic.  Maybe it is a Windows thing?  If there is a wrok around, we'd be happy to implement it.

**Comment by sopoforic** [comment] 2016-12-29 17:42
I think it's likely that this issue is a result of the prompt taking a long time to generate. Today, I had an internet outage, so requests to github would fail after a short period, which made it take longer to generate. During the time when my internet was out, xonsh always hung, no matter what--it never successfully gave me a prompt. My prompt is:

```
$PROMPT = '{env_name}{BOLD_INTENSE_GREEN}{user}@{hostname}{BOLD_INTENSE_CYAN} {cwd} {branch_color}{curr_branch}{NO_COLOR}\n{BOLD_INTENSE_CYAN}{prompt_end}{NO_COLOR} '
```

I don't know how this ties into my previous observation (which is still accurate). Perhaps some caching makes this happen faster after the first time?

**Comment by astronouth7303** [comment] 2016-12-29 17:55
@sopoforic Nothing in that prompt should be calling out to the network. `{branch_color}{curr_branch}` can be slow, but as far as I know they only go out to the filesystem.

**Comment by sopoforic** [comment] 2016-12-29 19:17
```
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
```

Then how does this work?

**Comment by scopatz** [comment] 2016-12-29 19:20
It works based on the last time you pulled.  `origin/master` is a local reference to a branch outside of this repo (a remote).

**Comment by sopoforic** [comment] 2016-12-29 19:23
You're right, of course. I forgot that it doesn't fetch automatically. My mistake. But my point still stands: while my internet was out xonsh was hanging and I had to use another shell, and it started working as soon as my internet became available. Git bash was also very slow to give me a prompt during that period, so I assumed that both xonsh and git bash must be trying to hit the network, but if not, then I have no idea what the problem is.

**Comment by scopatz** [comment] 2016-12-29 19:39
Did you try to remove all git related keys from the prompt to verify this? I am confident we can hunt this down. I wonder if it not the prompt that is doing this. Also did this occur everywhere or only in certain repos?

**Comment by sopoforic** [comment] 2016-12-29 22:56
I tried as you suggest. New prompt:

```
$PROMPT = '{BOLD_INTENSE_CYAN}{cwd}\n{prompt_end}{NO_COLOR} '
```

I twice tried leaving it alone for at least an hour and then opening a prompt. Both times, it was successful. Previously, it would definitely hang if I did that. So I think it must be related to the removed prompt keywords.

With the previous prompt, it happens even when I'm in a directory that doesn't contain a git repo, so I don't think it's anything specific to the directories. It happens when opening a new console (which opens into a directory with no repo), when ending a long ssh session, when executing a command (anything--`cd foo`, `git status`, `vim`, whatever) after a period of idleness. When it hangs, I can see in ConEmu the running process changing: python.exe -> git.exe -> python.exe (at which point it hangs).

If there's any more information that might be useful, let me know.

**Comment by sopoforic** [comment] 2016-12-30 21:21
After another day's use, I'm not as confident. I've had it hang after coming back from a subprocess a few times, but still never when opening a new prompt. So changing the prompt may have had some impact, but it's also possible I was just seeing patterns where there were none.

**Comment by laerus** [comment] 2017-01-29 18:20
Closing this since a lot has changed since the issue opened, feel free to open a new issue!

**Closed by laerus** 2017-01-29 18:20 UTC
Labels: bug
