### ISSUE TITLE
`open .some_file` attempts to call `open.some_file` in python

### ISSUE THREAD

**Issue by rltbennett** [xonsh/xonsh#2536] opened 2017-11-17 00:31 UTC
On macOS, if you type `open .some_file` in an attempt to use subprocess mode, xonsh will instead enter Python mode and call `open.some_file`, which fails with error `AttributeError: 'builtin_function_or_method' object has no attribute 'some_file'`.

Ideally, xonsh would recognize the space between `open` and `.` and use subprocess mode.

**Comment by gforsyth** [comment] 2017-11-17 22:25
Hey @rltbennett -- thanks for reporting!  I can confirm the issue.  

As a temporary workaround, `$[open .dotfile]` works.

**Comment by rltbennett** [comment] 2017-11-18 00:52
Thanks. `open! .some_file` also works.

**Comment by scopatz** [comment] 2017-11-27 03:58
Hahah wow, thanks for reporting @rltbennett.  This is actually not a bug per-se, because `open` is a Python builtin function (so it is in the namespace) and attribute access can have whitespace (even in pure Python).  So you *have* to use different syntax for this to work.  Would you mind if we closed this as a question?

**Comment by scopatz** [comment] 2017-11-27 04:01
Yeah, this is a dirty secret of the Python spec. ;)

**Closed** 2017-11-27 04:01 UTC
Labels: question

**Comment by scopatz** [comment] 2017-11-27 04:03
Maybe we should allow a way for certain command to supercede Python-mode.  This would be a potentially nice feature.

**Comment by adqm** [comment] 2017-11-27 14:19
Or maybe just disallow whitespace in attribute access?

It breaks the "xonsh is a superset of Python" story, but maybe in an acceptable way.

**Comment by rltbennett** [comment] 2017-11-27 16:00
That’s a tough call. While spaces are not particularly useful in attribute access, newlines definitely are, especially when chaining together multiple lengthy attribute accesses. I don’t think it would be a good idea for xonsh to break python compatibility in this case. Perhaps spaces should make the interpreter switch to subprocess mode, while newlines leave it in python mode? Hard to say. Might be worth making it a config option.

**Comment by scopatz** [comment] 2017-11-27 21:58
Perhaps we should just open an issue in Python to change the spec to be stricter in this regard.  I can't imagine that much code in the world would break....

**Comment by astronouth7303** [comment] 2017-11-28 22:26
`open .some_file` is particularly problematic because `open` is both a builtin function and a common command. It fails a lot of heuristics I can think of.
