### ISSUE TITLE
Keypresses to less appear to be swallowed when piping in fewer lines than the terminal size

### ISSUE THREAD

**Issue by gotgenes** [xonsh/xonsh#1898] opened 2016-10-26 21:16 UTC
xonsh has difficulty sending keypresses to `less` when `less` is fed fewer lines of content than the size of the terminal, via a pipe.

Below we create a file of a single line and pipe its contents into `less`:

```
echo junk > junk.txt
cat junk.txt | less
```

To exit less in this scenario, I must press Ctrl-C followed by Q.

Below we produce a file of 100 lines and pipe its contents into `less`:

```
for i in range(100):
     echo junk @(i) >> morejunk.txt
cat morejunk.txt | less
```

Here `less` appears to receive keypresses until one gets to the bottom of the file, then it locks up again.

It is worth noting that when one scrolls down to the end of a file with `less`, `less` will emit an `(END)` on the final line. I'm wondering if `less` is sending this into xonsh but xonsh is not handling it, and somehow this locked behavior is the result.

This follows up #1801.

Here is my `xonfig`

```
clasher@clasher-MBP ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.4.7.dev398    |
| Git SHA          | 99eb2ea         |
| Python           | 3.5.2           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by gforsyth** [comment] 2016-10-26 21:17
Thanks for reporting @gotgenes !  I can confirm this behavior on current master.

**Comment by scopatz** [comment] 2016-10-27 01:00
Thanks for reporting @gotgenes! This is odd. I cannot reproduce this on my Ubuntu box.  Less works exactly how it works in Bash for me.  Is this maybe a mac (or a mac version of less) issue?

**Comment by gforsyth** [comment] 2016-10-27 02:13
Hey @scopatz, quick check: are you piping to less or using it directly? When I use it directly everything is fine but when I pipe to it that's when I see the behavior described

**Comment by scopatz** [comment] 2016-10-27 02:18
Yes, I am piping.  If I do `echo x | less` or `cat file | less`, it works as expected.

**Comment by scopatz** [comment] 2016-10-27 02:19
On linux.  Trying to figure out windows less right now (windows 9?)

**Comment by gforsyth** [comment] 2016-10-27 13:39
Weird... now it works fine on my machine?  No complaints!
Maybe since the piping fixes were also merged in?  
What about you @gotgenes -- can you still reproduce this on master?

**Comment by gotgenes** [comment] 2016-10-27 21:21
@gforsyth @scopatz Confirming latest on `master` does **not** exhibit this bug.

New `xonfig`

```
clasher@clasher-MBP ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.4.7.dev422    |
| Git SHA          | 7c8cf35         |
| Python           | 3.5.2           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

Feel free to mark this as resolved.

**Comment by gforsyth** [comment] 2016-10-27 21:22
Awesome.   Thanks!

**Closed by gforsyth** 2016-10-27 21:22 UTC
Labels: bug
