### ISSUE TITLE
fdjskflj --arg=$ENV kills xonsh

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#776] opened 2016-04-01 17:23 UTC
I was trying to debug some other issue when I got this. `fdjskflj` is not a real command.

```
xonshmaster=🐚 fdjskflj --arg=$ENVTraceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/xonsh", line 6, in <module>
    sys.exit(xonsh.main.main())
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/main.py", line 236, in main
    shell.cmdloop()
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 111, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 80, in singleline
    display_completions_in_columns=multicolumn)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shortcuts.py", line 104, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/interface.py", line 353, in run
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 150, in run
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 373, in feed
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 292, in _input_par
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/terminal/vt100_input.py", line 325, in _call_hanr
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/interface.py", line 830, in feed_key
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 172, in fey
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 144, in _ps
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/input_processor.py", line 187, in _cr
  File "/Users/aaronmeurer/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.57-py3.5.egg/prompt_toolkit/key_binding/registry.py", line 32, in call
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 110, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/key_bindings.py", line 80, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 95, in compile
    code = compile(tree, filename, mode)
ValueError: expression which can't be assigned to in Store context
```

This is in master with the prompt toolkit backend. After this, xonsh has been killed.

Also note again that there is no newline before the `Traceback`.

**Comment by scopatz** [comment] 2016-04-11 03:51
I can confirm this error.

**Comment by adqm** [comment] 2016-06-08 22:22
I was going to take this, but I can't reproduce this on current master in readline or ptk.  Closing for now.  If this is still an issue, please feel free to reopen.

**Comment by asmeurer** [comment] 2016-06-09 01:01
Still happens.

**Comment by asmeurer** [comment] 2016-06-09 01:02
FYI, I apparently can't "reopen". Only those with push access can.

**Comment by adqm** [comment] 2016-06-09 01:03
Just reopened.  Sorry about that.  I can't reproduce, with ptk or readline. Maybe some of the others can?

**Comment by adqm** [comment] 2016-06-09 01:04
@asmeuerer, are you running the most recent xonsh version (0.3.4), from master, or something else?

**Comment by adqm** [comment] 2016-06-09 01:59
Okay, so I see the error message just the same, but xonsh doesn't die completely.  Maybe I was misreading your original message.

In order to "inject" environment variables, you need to wrap them in a string (otherwise, the env lookup doesn't happen).  So for example:
```
hartz@virtual1 ~ $ echo "--arg=$HOME"
--arg=/home/hartz
hartz@virtual1 ~ $ echo --arg=$HOME
ValueError: expression which can't be assigned to in Store context
```

Oh, I see.  This is really a syntax error (and so should fall back to trying subprocess mode), but for some reason we're not reporting it as such.  This is indeed a bug.  Sorry for the confusion.

**Comment by asmeurer** [comment] 2016-06-09 03:44
Just checked very latest master (I hadn't pulled). Now it doesn't seem to crash xonsh:

```
xonshmaster%=🐚 fdjskflj --arg=$ENV
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/ptk/shell.py", line 101, in push
    locs=None)
  File "/Users/aaronmeurer/Documents/xonsh/xonsh/execer.py", line 103, in compile
    code = compile(tree, filename, mode)
ValueError: expression which can't be assigned to in Store context
```

It used to before.

**Comment by scopatz** [comment] 2016-06-09 05:38
@asmeurer, so is this closable?

**Comment by adqm** [comment] 2016-06-09 05:44
@scopatz, I think it should stay open, actually.  Even though it isn't a _crash_ anymore, I think we aren't handling this properly.  This is actually a syntax error in Python (despite the fact that it comes to us as a `ValueError`), and thus I think it should fall through to `try_subproc_toks`.

**Comment by scopatz** [comment] 2016-06-09 06:16
Ok sounds good!

**Comment by laerus** [comment] 2016-09-01 00:10
this is solved on current master

```
>>> fdjskflj --arg=$ENV
xonsh: subprocess mode: command not found: fdjskflj
```

**Closed by laerus** 2016-09-01 00:10 UTC
Labels: bug
