### ISSUE TITLE
xonsh parse error during expansion of env var expression in subprocess mode

### ISSUE THREAD

**Issue by riccardomurri** [xonsh/xonsh#622] opened 2016-01-12 16:35 UTC
Expansion of a string expression which involves environmental
variables does not behave as expected.

A simple reference to an env. var. works fine::

         xonsh$ /bin/echo $HOME
         /home/rmurri

As soon as the env. var. is part of a larger expression, things start
to go bad::

         xonsh$ /bin/echo $HOME/foo

         Traceback (most recent call last):
           File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 151, in _parse_ctx_free
             debug_level=self.debug_level)
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 265, in parse
             tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
             return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
             tok = call_errorfunc(self.errorfunc, errtoken, self)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
             r = errorfunc(token)
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 2553, in p_error
             column=p.lexpos))
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 336, in _parse_error
             raise err
           File "<string>", line None
         SyntaxError: <xonsh-code>:1:17: ('code: /',)

         During handling of the above exception, another exception occurred:

         Traceback (most recent call last):
           File "/home/rmurri/sw/src/xonsh/xonsh/ptk/shell.py", line 54, in push
             locs=self.ctx)
           File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 95, in compile
             tree = self.parse(input, ctx, mode=mode)
           File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 70, in parse
             tree = self._parse_ctx_free(input, mode=mode)
           File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 193, in _parse_ctx_free
             raise original_error
           File "/home/rmurri/sw/src/xonsh/xonsh/execer.py", line 151, in _parse_ctx_free
             debug_level=self.debug_level)
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 265, in parse
             tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 331, in parse
             return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
             tok = call_errorfunc(self.errorfunc, errtoken, self)
           File "/home/rmurri/.local/lib/python3.4/site-packages/ply/yacc.py", line 193, in call_errorfunc
             r = errorfunc(token)
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 2553, in p_error
             column=p.lexpos))
           File "/home/rmurri/sw/src/xonsh/xonsh/parser.py", line 336, in _parse_error
             raise err
           File "<string>", line None
         SyntaxError: <xonsh-code>:1:0: ('code: /',)

I'm running code from the "master" branch, at commit e7d6772.

**Comment by gforsyth** [comment] 2016-01-12 17:05
Thanks for reporting @riccardomurri.  This looks like a duplicate of #385 to me.

**Comment by scopatz** [comment] 2016-01-12 23:19
As a temporary fix, note that it does work if you put the envvar expr in quotes:

```console
$ /bin/echo "$HOME/foo"
```

**Comment by laerus** [comment] 2016-09-01 00:14
this is solved on current master:
```
$ /bin/echo $HOME/foo
/home/laerus/foo
```
feel free to reopen!

**Closed by laerus** 2016-09-01 00:14 UTC
Labels: bug, duplicate
