### ISSUE TITLE
ctrl-z problem on Linux

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1103] opened 2016-06-05 03:24 UTC
Launching a command (like emacs) followed by ctrl-z suspends
the process but doesn't return keyboard control to xonsh. So there
is no way to detach the process with bg and continue typing. The
documentation only mentions that ctrl-z doesn't work on Windows.

xonfig
+------------------+----------+
| xonsh | 0.3.2 |
| Python | 3.4.3 |
| PLY | 3.7 |
| have readline | True |
| prompt toolkit | None |
| shell type | readline |
| pygments | None |
| on posix | True |
| on linux | True |
| distro | Fedora |
| on darwin | False |
| on windows | False |
| is superuser | False |
| default encoding | utf-8 |
+------------------+----------+

**Comment by adqm** [comment] 2016-06-05 03:26
This one I can't reproduce.  For me, the ctrl-z functionality is working just as I would expect (control goes back to the terminal).

Does this happen for all commands (e.g., `sleep 10`)?  Or just for certain ones like `emacs`?

**Comment by adqm** [comment] 2016-06-05 03:28
Okay, wait.  I can reproduce this from within a graphical `emacs` window.  I had been testing with text emacs (`emacs -nw`).  This does indeed look like a bug.

**Comment by adqm** [comment] 2016-06-05 03:37
For reference, just tested now...

In Bash, after opening emacs:
* hitting ctrl-z when the terminal has focus _stops the job and returns control to the terminal_ (correct)
* hitting ctrl-z when the emacs window has focus _does nothing_ (correct)

In xonsh, after opening emacs:
* hitting ctrl-z when the terminal has focus _stops the job and returns control to the terminal_ (correct)
* hitting ctrl-z when the emacs window has focus _stops the job and does not return control to the terminal_ (incorrect)

**Comment by adqm** [comment] 2016-06-05 03:42
Again, thanks for reporting, @mburo!

**Comment by adqm** [comment] 2016-06-26 19:07
Actually, @mburo, I'm not sure I can consider this a bug, as xonsh seems to exhibit the exact same behavior as bash in this situation.  I think if anything, one could consider this to be a problem with emacs.

**Comment by PaulReiber** [comment] 2016-06-26 22:12
I tested this as well - it works fine for me, in both cases.

pbr@mongo:~$ emacs
(....text-based emacs takes over screen)
^Z
[1]+  Stopped                 emacs
pbr@mongo:~$ fg
emacs
^X^C
pbr@mongo:~$ emacs
^Z
[1]+  Stopped                 emacs
pbr@mongo:~$ fg
emacs
(...takes over screen again)
^Z
[1]+  Stopped                 emacs
pbr@mongo:~$ jobs
[1]+  Stopped                 emacs
pbr@mongo:~$ ls|cat /dev/tty
^Z
[2]+  Stopped                 ls --color=auto | cat /dev/tty
pbr@mongo:~$ fg
ls --color=auto | cat /dev/tty
^C
pbr@mongo:~$ fg
(...emacs takes over the screen again)

In the above, ^Z is working properly.   When I tested with xonsh it worked exactly the same.

**Comment by mburo** [comment] 2016-06-26 22:50
I just tested this again (this time with xonsh 0.3.4 and python 3.5.1). Seems to work now.

**Comment by adqm** [comment] 2016-06-26 23:27
Okay!  In that case, I'm going to go ahead and close this issue.  If it crops up again, feel free to reopen.

**Comment by guyromm** [comment] 2017-01-10 15:37
issue is present again.

xonsh --version
xonsh/0.5.2
python --version
Python 3.5.2
(venv3.5) milez@dev-guy-automerge:~/AutoMerge$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by laerus** [comment] 2017-01-10 15:49
hey @guyromm, thanks for reporting! We are aware of the issue and it's being addressed on  #2071,
any more information is welcomed!

**Comment by leonqli** [comment] 2018-06-21 20:17
ctrl-z doesn't work.... 

%sleep 10                                                                                  
^Z^Z    

xonsh/0.6.7

**Comment by leonqli** [comment] 2018-06-21 20:20
ctrl-z doesn't work....

%sleep 10
^Z^Z^Z^Z

xonsh/0.6.7

**Comment by laerus** [comment] 2018-06-22 10:30
@leonqli i can reproduce, 

also this makes the `sleep` command and xonsh to hang

**Comment by dvolgyes** [comment] 2018-09-19 17:42
Same here (using 0.7.9, on Ubuntu 18.04).
I mean: both command line (e.g. sleep command) and GUI programs (e.g. gedit) hang 
if I press ctrl+z. As people said: the processes have to be killed.

Even a temporary workaround would be nice, e.g. an option to disable ctrl+z completely,
because even though I know the problem, I hit ctrl+z from muscle memory, and I kill 
my processes.

**Comment by dvolgyes** [comment] 2018-09-24 19:46
Dear @scopatz. I can live with it, and I am sorry that I cannot contribute more at this moment.
In 2 months I will have more time. If the problem still exists at that time, I will try to make a pull request.
This time I just wanted to mention that the issue still exists.

**Comment by scopatz** [comment] 2018-10-01 22:32
Thanks! Help here is deeply appreciated

**Comment by con-f-use** [comment] 2019-09-18 10:17
Just wanted to say, also waiting for a fix on this. Muscle memory is strong and hard to unlearn.

**Comment by scopatz** [comment] 2019-10-02 17:50
Yep, still working on this

**Closed** 2019-10-17 17:02 UTC
Labels: bug
