### ISSUE TITLE
Nonsensical SyntaxError

### ISSUE THREAD

**Issue by kahrkunne** [xonsh/xonsh#1960] opened 2016-11-18 20:59 UTC
The following code: http://pastebin.com/M0ZNXgT7
Gives me this error:
```
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib64/python3.5/site-packages/xonsh/main.py", line 233, in main
    loc=None, mode='exec')
  File "/usr/lib64/python3.5/site-packages/xonsh/codecache.py", line 143, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/lib64/python3.5/site-packages/xonsh/codecache.py", line 104, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode)
  File "/usr/lib64/python3.5/site-packages/xonsh/execer.py", line 103, in compile
    transform=transform)
  File "/usr/lib64/python3.5/site-packages/xonsh/execer.py", line 73, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib64/python3.5/site-packages/xonsh/execer.py", line 177, in _parse_ctx_free
    raise original_error from None
  File "/usr/lib64/python3.5/site-packages/xonsh/execer.py", line 164, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 329, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/yacc.py", line 325, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/yacc.py", line 1175, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/yacc.py", line 187, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 2679, in p_error
    column=p.lexpos))
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 460, in _parse_error
    raise err
SyntaxError: panel.xsh:30:7: ('code: "$fifo"',)
mkfifo "$fifo"
       ^
```

Which is of course nonsensical. As a matter of fact, copying this script up to and including line 30 (the mkfifo "$fifo" line) and running it gives no errors and executes correctly...
What exactly is going on here?

**Comment by gforsyth** [comment] 2016-11-18 21:01
Hey @kahrkunne -- can you try `mkfifo $fifo` instead?

**Comment by gforsyth** [comment] 2016-11-18 21:02
hmmm, and weirdly, I can't duplicate that error...

**Comment by gforsyth** [comment] 2016-11-18 21:03
Could you post the output of `xonfig`, please?  Thanks.

**Comment by kahrkunne** [comment] 2016-11-18 21:06
I get the same error without the quotes (e.g. `mkfifo $fifo`). I also get the same error with `echo "test"`. I *also* get the same error if I put `echo "test"` as the first line of the script. None of this happens with any other scripts.

Here's the output of xonfig:
```
+------------------+--------------------+
| xonsh            | 0.4.7              |
| Git SHA          | None               |
| Python           | 3.5.1              |
| PLY              | 3.8                |
| have readline    | True               |
| prompt toolkit   | 1.0.9              |
| shell type       | prompt_toolkit     |
| pygments         | 2.1.3              |
| on posix         | True               |
| on linux         | True               |
| distro           | Gentoo Base System |
| on darwin        | False              |
| on windows       | False              |
| on cygwin        | False              |
| is superuser     | False              |
| default encoding | utf-8              |
| xonsh encoding   | utf-8              |
| encoding errors  | surrogateescape    |
+------------------+--------------------+
```

**Comment by gforsyth** [comment] 2016-11-18 21:07
Can you try installing current master and see if the issue persists?

**Comment by kahrkunne** [comment] 2016-11-18 21:09
Issue persists in xonsh 0.4.7.dev559

**Comment by gforsyth** [comment] 2016-11-18 21:13
Can you clarify for me: when you say `echo "test"` -- that works when typed interactively, yes?  It's just in the script that there's a problem?

What if you change the shebang to `#!/usr/bin/env xonsh` ?

**Comment by kahrkunne** [comment] 2016-11-18 21:15
Yes, it works interactively, and also in any other script. 
Changing the shebang doesn't work, and neither does running the script directly (as in, `xonsh script.xsh`)

**Comment by gforsyth** [comment] 2016-11-18 21:19
Sorry I can't be of more help @kahrkunne -- if you have a minimal example that can reproduce the error I'm happy to take a look at it, but on the surface now I can't see what's wrong and I also can't reproduce the error.

**Comment by kahrkunne** [comment] 2016-11-18 21:22
I'll try and reproduce it. The code I'm trying to run is probably not bug-free (I had just finished writing it and was about to test it), but xonsh giving a syntax error in this place is very clearly a bug in xonsh.

**Comment by kahrkunne** [comment] 2016-11-18 21:33
@gforsyth 

I've singled it out:
```python
echo "kek"

$mpd_width = $(expr $mpd_width + $($textwidth "$font" inpt[0]))
```
Is this most minimal example where I can reproduce the problem. Any occurrence of the latter line will cause any not-python-code to throw a SyntaxError. (I can't remember the xonsh terminology at the moment, but what I mean is that a line such as `echo "test"` will fail, while a line such as `print("test")` will not. Interestingly, incorrect but valid python code such as `import adsasdfasd` will also not give an error).

If there is no code like that before this line, this line will instead throw a SyntaxError as follows:

```
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 18735, in main
    loc=None, mode='exec')
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 2043, in run_script_with_cache
    ccode = compile_code(filename, code, execer, glb, loc, mode)
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 2004, in compile_code
    ccode = execer.compile(code, glbs=glb, locs=loc, mode=mode)
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 18138, in compile
    transform=transform)
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 18108, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 18212, in _parse_ctx_free
    raise original_error from None
  File "/usr/lib64/python3.5/site-packages/xonsh/__amalgam__.py", line 18199, in _parse_ctx_free
    debug_level=(self.debug_level > 1))
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 333, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib64/python3.5/site-packages/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 2683, in p_error
    column=p.lexpos))
  File "/usr/lib64/python3.5/site-packages/xonsh/parsers/base.py", line 464, in _parse_error
    raise err
SyntaxError: kek.xsh:3:58: ('code: [',)
$mpd_width = $(expr $mpd_width + $($textwidth "$font" inpt[0]))
                                                          ^
```

**Comment by santagada** [comment] 2016-11-20 11:49
I could get it down to this: `$($textwidth "$font" inpt[0])`

**Comment by scopatz** [comment] 2016-11-20 18:38
@kahrkunne `inpt[0]` is a Python expression, but you are trying to run it in a subprocess because it is wrapped by `$(...)`.  So this is a valid syntax error and the error message points you to the character that is the problem.  
 
If you mean for this to be a Python expression, then you need to wrap it in @(...), 

```
$($textwidth "$font" @(inpt[0]))
```

If you want this to literally say "inpt[0]" then you should put this part in quotes:

```
$($textwidth "$font" "inpt[0]")
```

Does this make sense?

**Comment by kahrkunne** [comment] 2016-11-20 22:02
That does make sense.

However, why would this throw a syntax error in valid code, *100 lines before this part*? That's clearly an error on the end of the xonsh parser - I could put this line at the end of a 10,000 line script and it would throw a syntax error on the first subprocess code it encountered (which could very well be the first line of the script).

**Comment by scopatz** [comment] 2016-11-20 22:09
That is a fair point. The original error does seem to be in the wrong spot.

**Comment by scopatz** [comment] 2019-07-14 20:27
I believe this is fixed in recent versions

**Closed by scopatz** 2019-07-14 20:27 UTC
