### ISSUE TITLE
Broken multiline support in interactive mode

### ISSUE THREAD

**Issue by utgarda** [xonsh/xonsh#2472] opened 2017-08-10 14:38 UTC
Multiline input mode continuous after closing `"""` , 
multiline string can't be started with just `"""`, i.e. can't start with `\n`

```shell
etsvigun@Jotunheim ~ $ multiline="""a
...................... b
...................... c"""
...................... d
...................... 
xonsh: subprocess mode: command not found: d
Did you mean one of the following?
    dd:  Command (/usr/bin/dd)
    cd:  Alias
    du:  Command (/usr/bin/du)
    od:  Command (/usr/bin/od)
    [:   Command (/usr/bin/[)
etsvigun@Jotunheim ~ $ multiline="""
xonsh: subprocess mode: command not found: multiline="""
multiline="""
```

```shell
[etsvigun@Jotunheim ~]$ xonsh --version
xonsh/0.5.12```

**Comment by gforsyth** [comment] 2017-08-28 20:20
Thanks for reporting @utgarda! This is a bug in how we're handing carriage returns in the prompt toolkit backend. 
There needs to be logic added to https://github.com/xonsh/xonsh/blob/master/xonsh/ptk/key_bindings.py#L18 to not trigger execution when a line ends in `"""`

Let me know if you're interested in trying to put in a PR to fix this, or I'll get to it eventually, otherwise.

**Comment by scopatz** [comment] 2017-08-29 15:54
Thanks for reporting this @utgarda! I noticed this myself yesterday :)

**Comment by gforsyth** [comment] 2017-09-28 00:28
Huh...
Sorry for the delay @utgarda -- could you try out the current master and see if this issue persists?  I can reproduce it on 0.5.12 but not on current master.  The weird thing is that I have no idea when it was fixed...

**Comment by gforsyth** [comment] 2017-12-11 01:15
Closing this.   
In `0.6.0` multiline strings can "begin" with a `\n`. 
The extra newline at the end is required since a valid expression is necessary but not sufficient for deciding to execute in a multiline block.

**Closed by gforsyth** 2017-12-11 01:15 UTC
