### ISSUE TITLE
Tab autocomplete gets totally messed up if path has a space

### ISSUE THREAD

**Issue by battaglia01** [xonsh/xonsh#2699] opened 2018-07-02 23:07 UTC
Suppose in the current directory, I have the folder "test 1", which contains "test 2", which contains "test 3". Then suppose I first type `$ ls te`, and then hit tab. It will autocomplete to `ls t'test 1/'`. Note the extra letter `t` before the `'test 1'`.

In general, here is a table of autocomplete values, where the first column is the thing I type, and after the `->` is what you get after hitting tab:

`$ ls t` -> `$ ls 'test 1/'` <-- this is the only one that works
`$ ls te` -> `$ ls t'test 1/'` <-- extra t at beginning
`$ ls tes` -> `$ ls t'test 1/'` <-- extra t at beginning
`$ ls test` -> `$ ls t'test 1/'` <-- extra t at beginning

You get some even weirder results if you have something already in quotes. For instance:

`$ ls "t"` -> `$ ls "test 1/"` <-- works
`$ ls "te"` -> `$ ls "test 1/"` <-- works
`$ ls "tes"` -> `$ ls "test 1/"` <-- works
`$ ls "test"` -> `$ ls "test 1/"` <-- works
`$ ls "test "` -> `$ ls "test "test 1/"` <-- gets totally screwed up
`$ ls "test 1"` -> `$ ls "test 1/"` <-- works
`$ ls "test 1/"` -> `$ ls "test 2/"` <-- this screws up and reads the `"test 2"` subdirectory of `"test 1"`

This gets really frustrating and accumulates. For instance, consider

`$ mkdir "test 1/test 2.1"`
`$ cd "test 1/t` <-- HIT TAB HERE
`$ cd "test "test 1/test 2` <-- turns into that, gets screwed up

In general things get worse as there are more levels of directories with spaces in them. I've seen this behavior both in WSL and running on Ubuntu.

**Comment by gforsyth** [comment] 2018-07-03 14:43
Hey @battaglia01 -- thanks for reporting!  I can confirm this behavior.  I think it's a regression due to a separate fix I put in for our bash completion.  As a temporary workaround, you can reorder the completers so that our non-bash path completer gets called before the bash completer.  It handles the spaces and adding of quotes correctly and should fire for commands like `ls`, `cd`, `mkdir`, etc.

```
_, path_comp = __xonsh_completers__.popitem('path')
completer add path path_comp "<bash"
```

There's a larger discussion to have, too, around the ordering of the completers.  There are also some older issues to rework how the completion lists are returned since we don't preserve ordering right now and sometimes that's a desired behavior.

**Comment by battaglia01** [comment] 2018-07-04 12:57
I still get the behavior here. Log:

```
$ mkdir "test 1"
$ mkdir "test 1/test 2"
$ mkdir "test 1/test 2/test 3"
$ cd 'test 'test 1/test 2/'
```

I got to the last line by typing `cd 'test 1/[tab]'`

**Comment by gforsyth** [comment] 2018-07-04 13:18
can you post the output of `completer list` in the same session that you get that error?

There are a couple of things happening here (almost all of them because spaces are terrible)

I have the same directory structure you have set up and I have moved the `path` completer ahead of the `bash` completer.

```
cd test[tab] -> cd 'test 1/'   # this seems correct
cd 'test 1/[tab] -> cd 'test 1/test 2/'   # also seems correct, but doesn't match your report
```

then there are the fuzzy weird cases (but I posit that these aren't errors)

```
cd test 1[tab] -> cd test 'test 1/'
```

That seems wrong, but I think it's correct. The only directory name with a `1` is `test 1` in my `cwd` and tokens/words here are space delimited because that's just how shells mostly work.  That completion is as if I only typed `cd 1[tab]`

```
cd 1[tab] -> cd 'test 1/'
```

and that's from a separate feature that does subsequence path completions.  If you set `$SUBSEQUENCE_PATH_COMPLETION=False` then 

```
cd test 1[tab] -> cd test 1   # nothing happens because no valid completion found
```

There are still some kinks to iron out, but I want to make sure we isolate which unexpected results are features and which are bugs.

**Comment by gforsyth** [comment] 2018-07-04 13:18
And can you also please post the output of the `xonfig` command?  Thanks!

**Comment by battaglia01** [comment] 2018-07-04 13:50
OK, here is the new log. I'm seeing that the behavior is intermittent here - sometimes it happens and sometimes not.

```
~ $ mkdir -p "test 1/test 2/test 3"
~ $ cd test[tab] -> cd 'test 1/'
~ $ ls test[tab] -> ls t'test 1/'
~ $ _, path_comp = __xonsh_completers__.popitem('path')
~ $ completer add path path_comp "<bash"
~ $ cd test[tab] -> cd 'test 1/'
~ $ ls test[tab] -> ls 'test 1/'
~ $ cd 'test 1/t[tab] -> cd 'test 'test 1/test 2/'
~ $ ls 'test 1/t[tab] -> ls 'test 'test 1/test 2/'
~ $ completer list
Registered Completer Functions: 
python_mode : Python-mode completions for @( and ${
       base : If the line is empty, complete based on valid commands, python names, and paths.
              If we are completing the first argument, complete based on valid
              commands and python names.
  completer : Completion for "completer"
       skip : Skip over several tokens (e.g., sudo) and complete based on the rest of the
              line.
        pip : Completes python's package manager pip
       xpip : Completes python's package manager pip
         cd : Completion for "cd", includes only valid directory names.
      rmdir : Completion for "rmdir", includes only valid directory names.
     xonfig : Completion for ``xonfig``
    xontrib : Completion for ``xontrib``
       path : Completes based on a path name.
       bash : Completes based on results from BASH completion.
        man : Completes an option name, based on the contents of the associated man page.
     import : Completes module names and contents for "import ..." and "from ... import ..."
     python : Completes based on the contents of the current Python environment, the Python
              built-ins, and xonsh operators. If there are no matches, split on
              common delimiters and try again.
```

Note that before changing completers, the bug is dependent on what command I'm running - it happens for `ls` but not `cd`.

To replicate the bug after changing completers, I typed `cd 'test 1/t[tab]`. I think before I said that I tried `cd test 1/[tab]`, but it's the additional `t` that seems to make it happen. Here is another before/after test with that. Note that this is a new session where I have reset the completers:

```
~ $ cd 'test 1/[tab] -> cd 'test 'test 1/test 2/'
~ $ ls 'test 1/[tab] -> ls 'test 'test 1/test 2/'
~ $ _, path_comp = __xonsh_completers__.popitem('path')
~ $ completer add path path_comp "<bash"
~ $ cd 'test 1/[tab] -> cd 'test 1/'
~ $ ls 'test 1/[tab] -> ls 'test 'test 1/test 2/'
```

However, after running this again, it just sometimes happens and sometimes not. I thought that hitting "Ctrl-C" at the command line caused subsequent autocompletes to misfire, but now, after exiting and relaunching xonsh, it just seems to happen all the time now. Example:

```
~ $ _, path_comp = __xonsh_completers__.popitem('path')
~ $ completer add path path_comp "<bash"
~ $ cd 'test 1/[tab] -> cd 'test 'test 1/test 2/' (hit backspace and delete, don't hit enter)
~ $ ls 'test 1/[tab] -> ls 'test 'test 1/test 2/' (hit backspace and delete, don't hit enter)
~ $ completer list
Registered Completer Functions: 
python_mode : Python-mode completions for @( and ${
       base : If the line is empty, complete based on valid commands, python names, and paths.
              If we are completing the first argument, complete based on valid
              commands and python names.
  completer : Completion for "completer"
       skip : Skip over several tokens (e.g., sudo) and complete based on the rest of the
              line.
        pip : Completes python's package manager pip
       xpip : Completes python's package manager pip
         cd : Completion for "cd", includes only valid directory names.
      rmdir : Completion for "rmdir", includes only valid directory names.
     xonfig : Completion for ``xonfig``
    xontrib : Completion for ``xontrib``
       path : Completes based on a path name.
       bash : Completes based on results from BASH completion.
        man : Completes an option name, based on the contents of the associated man page.
     import : Completes module names and contents for "import ..." and "from ... import ..."
     python : Completes based on the contents of the current Python environment, the Python
              built-ins, and xonsh operators. If there are no matches, split on
              common delimiters and try again.
```

**Comment by gforsyth** [comment] 2018-07-04 14:10
I see `xpip` in your current completer list which means there should be a newer version of xonsh available than what you have installed.  Can you upgrade to the latest release and see if you can still replicate these issues (you'll still need to do the completer reordering thing)

**Comment by battaglia01** [comment] 2018-07-04 14:39
Sorry, updated xonsh and now have 0.6.8. The behavior is still there - got it on the first try this time:

```
~ $ _, path_comp = __xonsh_completers__.popitem('path')
~ $ completer add path path_comp "<bash"
~ $ cd 'test 1/[tab] -> cd 'test 'test 1/test 2/'
~ $ completer list
Registered Completer Functions: 
python_mode : Python-mode completions for @( and ${
       base : If the line is empty, complete based on valid commands, python names, and paths.
              If we are completing the first argument, complete based on valid
              commands and python names.
  completer : Completion for "completer"
       skip : Skip over several tokens (e.g., sudo) and complete based on the rest of the
              line.
        pip : Completes python's package manager pip
         cd : Completion for "cd", includes only valid directory names.
      rmdir : Completion for "rmdir", includes only valid directory names.
     xonfig : Completion for ``xonfig``
    xontrib : Completion for ``xontrib``
       path : Completes based on a path name.
       bash : Completes based on results from BASH completion.
        man : Completes an option name, based on the contents of the associated man page.
     import : Completes module names and contents for "import ..." and "from ... import ..."
     python : Completes based on the contents of the current Python environment, the Python
              built-ins, and xonsh operators. If there are no matches, split on
              common delimiters and try again.
~ $ xonfig
+------------------+----------------------+
| xonsh            | 0.6.8                |
| Git SHA          | a88a485f             |
| Commit Date      | Jun 28 20:10:30 2018 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | neon                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by gforsyth** [comment] 2018-07-04 15:17
Ahhh, ok.  I didn't realize you were using the `readline` backend.  I can duplicate the issue if I switch to readline.  Ok, yep, that's definitely a bug -- for now, you can work around it by installing `prompt_toolkit` with a `xpip install "prompt_toolkit<2"`

**Comment by battaglia01** [comment] 2018-07-04 15:29
Tried that - I get the following error:

```
$ xpip install "prompt_toollkit<2"
The directory '/home/mike/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mike/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting prompt_toollkit<2
  Could not find a version that satisfies the requirement prompt_toollkit<2 (from versions: )
No matching distribution found for prompt_toollkit<2
```

**Comment by battaglia01** [comment] 2018-07-04 15:33
Thanks - this is much better!

**Comment by gforsyth** [comment] 2018-07-04 16:53
Great!  There are only the two backends.  The readline one is the original and we support it because it makes `xonsh` have no dependencies other than Python 3 (many of the core devs have a background in scientific computing and have worked with clusters that have frustratingly restrictive policies around installing packages from the public internet).  The `prompt_toolkit` backend is much nicer (I think) and has a few features that readline can't support (like the selection box for completions and true multiline editing).

There's some stuff about the backends just on the main page of http://xon.sh but we really need to write up a proper manual.

**Comment by gforsyth** [comment] 2018-07-05 00:21
Hey @battaglia01 -- are you still shuffling the completers?  I don't get the leading `t` if I put the `path` completer before the `bash` completer. 

And thanks for noticing the discrepancy between single and double quotes, that _definitely_ shouldn't happen.

That led me down a bit of a rabbit hole but I think I have a fix for that in #2701 and it also takes care of the completion issues in the readline backend, too!

**Comment by melund** [comment] 2018-07-05 11:52
#2701 is merged. @battaglia01 I hope this fixes it for you. Otherwise, please reopen the issue.

**Closed by melund** 2018-07-05 11:52 UTC

**Comment by battaglia01** [comment] 2018-07-06 15:56
Thanks - yes, helpful! I must not have fixed the completers again. This is good.

Just curious, I notice that sometimes path completion completes with previous paths I entered, even if not valid anymore. Is there any way to tweak this so it only looks at currently available paths?

**Comment by gforsyth** [comment] 2018-07-06 20:10
Hey @battaglia01 -- that invalid path can be avoided if you set `$AUTO_SUGGEST_IN_COMPLETIONS=False`.  If it's set to `True` then the ghosted autosuggest options also appear in the completion list and aren't checked for validity

**Comment by battaglia01** [comment] 2018-07-07 20:42
Thanks - I set that environment variable but I'm still getting the weird autocompletes. Is there some other variable that also must be set? I also have the completers set the way you described before.

**Comment by battaglia01** [comment] 2018-08-12 03:00
@gforsyth - just did a quick install of xonsh 0.7.3 on a new computer and found that `xpip install "prompt_toolkit<2"` crashes it. I dropped that and installed the latest prompt_toolkit and it works. So now in my .xonshrc file, I still have this

```
#fix for path completion
_, path_comp = __xonsh_completers__.popitem('path')
completer add path path_comp "<bash"
$AUTO_SUGGEST_IN_COMPLETIONS=False
```

Do you still recommend leaving it like this for xonsh 0.7.3? Or is the space bug fixed?
