### ISSUE TITLE
git stash pop command hangs when referencing a specific "stash"

### ISSUE THREAD

**Issue by corbinbs** [xonsh/xonsh#462] opened 2015-11-02 17:11 UTC
Hi,

I often flip between sets of changes and will `git stash` and `git stash pop` frequently.  
This morning, I noticed that attempting to pop a stash further down in my stash list would cause the output of some `.`s and then hang.  Here's what I saw:
```
$ git stash pop stash@{1}
..................................................
```
(control-c'ed to get out of it)
I'm suspecting that this may have to do with the use of `{}` in that command which may clash with some formatting statements.  I ended up running `bash` and then `git stash pop stash@{1}` and exited bash to go back to xonsh.

I'm on `xonsh/0.2.0` and running with
```
3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

This is not a huge deal for me right now but I wanted to share it in case other folks encounter it before I can help contribute a fix back for it.  I promise to start sending more pull requests than issues soon, too!

Thanks,

Brian

**Comment by scopatz** [comment] 2015-11-02 17:17
Thanks for reporting @corbinbs. I think that you can fix this by putting the ref in quotes, ie

```console
$ git stash pop "stash@{1}"
```

This could also be triggered by the `@` sign in addition to the `{}`.

**Comment by corbinbs** [comment] 2015-11-03 21:10
Confirmed that: 
```
$ git stash pop "stash@{0}"
```
works well.  Thanks for the tip!

**Comment by auscompgeek** [comment] 2015-11-04 01:49
That's not actually a hang. xonsh is actually waiting for end of input. You'll notice that the number of dots correspond to the length of the prompt. Indeed, xonsh will keep reading input until you give it a blank line:

```pytb
seedbox@kairi ~ $ echo a {1}
................. hello world
................. what is going on
................. 
Traceback (most recent call last):
  File "/home/seedbox/dev/contrib/xonsh/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 2505, in p_error
    column=p.lexpos))
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 334, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:11: ('code: {',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seedbox/dev/contrib/xonsh/xonsh/base_shell.py", line 158, in push
    locs=self.ctx)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/execer.py", line 94, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/execer.py", line 69, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/execer.py", line 163, in _parse_ctx_free
    raise original_error
  File "/home/seedbox/dev/contrib/xonsh/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.5/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 2505, in p_error
    column=p.lexpos))
  File "/home/seedbox/dev/contrib/xonsh/xonsh/parser.py", line 334, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: a',)
```

Whatever xonsh is doing, it's not even remotely close to brace expansion:
```console
seedbox@kairi ~ $ echo a {1,2} b
................. 
```

The braces alone are enough to break the parser.

**Comment by auscompgeek** [comment] 2015-11-04 01:53
See #413.

**Comment by corbinbs** [comment] 2015-11-05 19:22
Just encountered a `curl` command that seems to cause the same behavior (with no `{`, `}`, or `@` in the mix):
```
curl -L http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar -o jython-installer.jar
```
quoting the url does work:
```
curl -L "http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar" -o jython-installer.jar
```

**Comment by scopatz** [comment] 2015-11-05 19:23
It is probably the `?` in this case

**Comment by laerus** [comment] 2016-09-09 15:25
Closing this in favor of #1432, also there is a duplicate of this in #1549 which is closed atm.

**Closed by laerus** 2016-09-09 15:25 UTC
Labels: bug, feature, help wanted, question
