### ISSUE TITLE
Funny command parsing

### ISSUE THREAD

**Issue by tdsmith** [xonsh/xonsh#231] opened 2015-05-15 18:49 UTC
Google Chrome Canary's binary ships as `/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary`. I want to pass it a command-line option, so I chdir'd to `/Applications/Google Chrome Canary.app/Contents/MacOS` and typed:

`./G[tab]`

which autocompleted to

`'./Google Chrome Canary'`

Then, I added `--enable-new-bookmark-apps`, and hit enter.

xonsh complains:

```
tim@darkside /Applications/Google Chrome Canary.app/Contents/MacOS $ './Google Chrome Canary' --enable-new-bookmark-apps
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/HEAD/libexec/lib/python3.5/site-packages/xonsh/shell.py", line 132, in default
    self.execer.exec(code, mode='single', glbs=self.ctx)  # no locals
  File "/usr/local/Cellar/xonsh/HEAD/libexec/lib/python3.5/site-packages/xonsh/execer.py", line 127, in exec
    return exec(code, glbs, locs)
  File "<xonsh-code>", line 1, in <module>
NameError: name 'enable' is not defined
```

Using `$['./Google Chrome Canary' --enable-new-bookmark-apps]` works.

This feels like a bad interaction between tab-completion and command parsing, but I'm not sure if it can be improved.

**Comment by scopatz** [comment] 2015-05-15 19:59
Hi @tdsmith - Thanks for reporting! I see what the problem is here.  Basically `--enable-new-bookmark-apps` is a valid Python expression, ie `-(-enable) - new - bookmarks - apps`.  Normally, this wouldn't matter because the command would not be in the execution context. and so the parser would auto-wrap this in `$[]`.  However, the command here is given as string, and so this is a theoretically valid Python expression.

For now, the work around is as you found.  Another solution would be to support space escaping (`Google\ Chrome`).  I think you may be able to add this token to the lexer's suproc name and have this work. Would you like to take a stab at this?  Maybe @wrywerytwreywery has some ideas too...

**Comment by scopatz** [comment] 2017-01-12 02:49
I think that these ambiguous cases will have to be resolved by some form of explicit subprocess syntax of subprocess call.  Please feel free to open new issues, if any arise.

**Closed by scopatz** 2017-01-12 02:49 UTC
Labels: bug
