### ISSUE TITLE
Registering and using a custom style then causes a xonsh subshell to crash

### ISSUE THREAD

**Issue by egnor** [xonsh/xonsh#4371] opened 2021-07-17 06:18 UTC
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.19               |
| shell type       | prompt_toolkit       |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | apt_tabcomplete      |
| xontrib 2        | direnv               |
| xontrib 3        | kitty                |
+------------------+----------------------+
```

</details>

## Expected Behavior
I defined and registered a custom style [per the tutorial instructions](https://xon.sh/customization.html#registering-custom-styles). My `.xonshrc` registers the style, then sets `$XONSH_COLOR_STYLE` to my custom style. This works fine.

I would further expect to be able to start a xonsh subshell without problems... however...

## Current Behavior

```
$ xonsh
pygments.util.ClassNotFound: Could not find style module 'egnor'.
pygments.util.ClassNotFound: Could not find style module 'egnor'.
pygments.util.ClassNotFound: Could not find style module 'egnor'.
Traceback (most recent call last):
  ... [elided, included below] ...
pygments.util.ClassNotFound: Could not find style module 'egnor'.
Xonsh encountered an issue during launch
Failback to /bin/zsh
```

This error happens right away on startup, before the `.xonshrc` has an opportunity to re-register the style. (For example, any attempt to `xontrib load` will fail in this way, and that's normally the first thing in a `.xonshrc`.)

This immediate failure can be mitigated by making this the very first line of `.xonshrc`:

```
$XONSH_COLOR_STYLE = "default"
```

This allows an interactive xonsh to start without crashing, and then the `.xonshrc` can re-define and re-register the custom style before re-assigning `$XONSH_COLOR_STYLE` to use it. BUT, any xonsh scripts (`.xsh` files) run without loading the `.xonshrc` and immediately crash with the same problem.

If _nothing_ else, it would be nice if there were a more graceful fallback to the `"default"` style, rather than crashing the entire shell. Perhaps it would be better to not export `$XONSH_COLOR_STYLE` (the same way `$PROMPT` is not exported) to subshells?

### Traceback (if applicable)

<details>

```
$ $XONSH_DEBUG = 1
$ xonsh
pygments.util.ClassNotFound: Could not find style module 'egnor'.
pygments.util.ClassNotFound: Could not find style module 'egnor'.
pygments.util.ClassNotFound: Could not find style module 'egnor'.
Traceback (most recent call last):
  File "/home/egnor/.local/lib/python3.9/site-packages/pygments/styles/__init__.py", line 74, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.egnor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/main.py", line 420, in main
    args = premain(argv)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/main.py", line 356, in premain
    env = start_services(shell_kwargs, args)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/main.py", line 309, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/shell.py", line 212, in __init__
    env=env.detype(), ts=[time.time(), None], locked=True
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/environ.py", line 1730, in detype
    deval = detyper(val)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/tools.py", line 1163, in detype
    return x.detype()
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/environ.py", line 413, in detype
    style = self.style
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/environ.py", line 447, in style
    self._style = ansi_style_by_name(style_name)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/ansi_colors.py", line 1164, in ansi_style_by_name
    pstyle = get_style_by_name(name)
  File "/home/egnor/.local/lib/python3.9/site-packages/xonsh/pygments_cache.py", line 433, in get_style_by_name
    style = get_style_by_name(name)
  File "/home/egnor/.local/lib/python3.9/site-packages/pygments/styles/__init__.py", line 76, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'egnor'.
Xonsh encountered an issue during launch
Failback to /bin/zsh
```

</details>

## Steps to Reproduce

1. Follow the tutorial instructions to create and register a custom color style.
2. Set `$XONSH_COLOR_STYLE` to use that style.
3. Launch a `xonsh` subshell.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment] 2021-07-17 14:59
> If nothing else, it would be nice if there were a more graceful fallback
to the "default" style, rather than crashing the entire shell.

Agreed. If I recall correctly there is code that fallbacks to default
gracefully when setting to a bad style interactively. It probably doesn't
catch this specific flow.

**Comment by egnor** [comment] 2021-07-17 16:56
Correct, bad style is detected during interactive assignment:

```
$ $XONSH_COLOR_STYLE = "xyzzy"
pygments.util.ClassNotFound: Could not find style module 'xyzzy'.
Exception raised in event handler; ignored.
Could not find style 'xyzzy', using default
$ $XONSH_COLOR_STYLE
'default'
```

(Using `$XONSH_STYLE_OVERRIDES` instead of registering a style "solves" this problem for the use-case of "I want custom colors in my `.xonshrc`". Honestly if we were starting from scratch I might suggest just having a `$XONSH_STYLE` dict with the semantics of `$XONSH_STYLE_OVERRIDES` and not bothering with named styles -- canned style sets could be provided as constants somewhere that could be assigned to `$XONSH_STYLE`. That way changes would be fully inheritable without weirdness.)

**Comment by yaxollum** [comment] 2021-07-20 14:48
Hi @egnor!

If I'm understanding correctly, you have code similar to the block below **in your `.xonshrc`**, right?
```xonsh
from xonsh.tools import register_custom_style
mystyle = {
    "Literal.String.Single": "#ff88aa",
    "Literal.String.Double": "#ff4488",
    "RED": "#008800",
}
register_custom_style("mystyle", mystyle, base="monokai")
$XONSH_COLOR_STYLE="mystyle"
```

When you launch a subshell, the subshell should load the `.xonshrc` (which includes the definition of `mystyle`), so why are you getting that error?

**Comment by egnor** [comment] 2021-07-20 14:51
That error happens on startup before the .xonshrc is loaded. Does this not
repro for you?

**Comment by yaxollum** [comment] 2021-07-20 22:43
Ok, I think I understand your issue now. To work around the issue, you can try moving the `register_custom_style()` code to the top of your `.xonshrc` (right after any `import` statements that you have).

Addressing your two points:

1. I think this depends on what xontribs you're loading. The problem may be with the particular xontribs which you're using, not xonsh. I tried doing `xontrib load coreutils` at the top of my `.xonshrc` and I'm not getting any errors. You can try disabling all of your xontribs and then enabling them one at a time to see which ones are causing the errors.

2. I don't think this is a problem. Since non-interactive xonsh does not care about styles, there shouldn't be any errors. For example, I tried running `xonsh -c "echo $XONSH_COLOR_STYLE"`, and I got the output `mystyle` without any errors.

Also, you can try running `xonsh --no-rc`, and you should get an error message like: `Could not find style 'mystyle', using default`

**Comment by egnor** [comment] 2021-07-21 18:02
To be clear: I didn't file this issue looking to find a workaround (as mentioned above, I got things working, and eventually diverted from registering a new style entirely), though I certainly appreciate the attention! :yellow_heart: 

Instead, I'm just calling out issues that should probably be fixed
- total shell crash when `$XONSH_COLOR_STYLE` is unrecognized at start, instead of graceful handling
- more general skew between `$XONSH_COLOR_STYLE` which is environment-exported and the list of registered styles which is not

Looking deeper into my original crash report, I think it's actually related to #4383, except manifesting differently in release rather than mainline. The traceback shows an exception in the detyper for `LsColors`, which is being invoked during startup because of some scramble between `$UPDATE_OS_ENVIRON` (exported to 1 by default) and `$LS_COLORS` (set by default if not already defined). I can revert from main back to the release to try to investigate further and construct a more specific repro case (avoiding xontribs and other customizations), if that would be helpful.

**Comment by gforsyth** [comment] 2021-07-23 03:21
pinging @dyuri who may have insight into this

**Comment by dyuri** [comment] 2021-07-23 08:44
I remember fixing something similar not long ago, gonna take a look.

**Comment by dyuri** [comment] 2021-07-23 09:01
Yep the fix was https://github.com/xonsh/xonsh/pull/4253.

I tried to reproduce the issue with a `.xonshrc` only having the styling code, but everything works fine for me. (And I also have a custom style in my xonshrc, with plenty of other stuff, it doesn't break neither.)

```
$ xonsh --rc test.xsh
dyuri@chaos ~ $ $XONSH_COLOR_STYLE
'mystyle'
dyuri@chaos ~ $ xonsh
dyuri@chaos ~ $ xonsh -c 'echo $XONSH_COLOR_STYLE'
'mystyle'
dyuri@chaos ~ $ xonsh --no-rc
Could not find style 'mystyle', using default
# ... welcome and such
dyuri@chaos ~ $ $XONSH_COLOR_STYLE
'default'
```

**Comment by gforsyth** [comment] 2021-07-27 13:53
Sweet -- thanks @dyuri !

@egnor can you try out the latest release and see if the issue is fixed on your end?

**Closed** 2021-08-07 18:27 UTC
