### ISSUE TITLE
xonsh doesn't recognize a long shell command with line continuation

### ISSUE THREAD

**Issue by dclong** [xonsh/xonsh#3290] opened 2019-08-29 01:18 UTC
xonsh fails to recognize the following long command with line continuation as a shell command. 
![image](https://user-images.githubusercontent.com/824507/63902832-09649000-c9c0-11e9-903f-ffa58cacacf4.png)

## Expected Behavior
xonsh should be able to recognize the command line the screenshot above as a shell command.
## Current Behavior
A SyntaxError is thrown as shown in the screenshot.

**Comment by astronouth7303** [comment] 2019-08-29 01:49
That's not because of the line continuation, that's because of the backticks.

```
🐚 echo foo=`bar`
```

Bash uses backticks as a substitute for `$()` (which is a bash-specific thing). xonsh uses them for file globbing.

The only potential bug here is that you can't use `$()` and friends in the middle of an argument. I'm pretty sure this has been discussed elsewhere, although my searching skills are failing at the moment.

Closing this as Working As Designed.

**Closed by astronouth7303** 2019-08-29 01:49 UTC

**Comment by dclong** [comment] 2019-08-29 19:32
@astronouth7303 Is it an open issue discussed in this repository?

**Comment by astronouth7303** [comment] 2019-08-29 20:16
> I'm pretty sure this has been discussed elsewhere, **although my searching skills are failing at the moment.**

Sorry, I have not memorized the 300 open issues or the 1500 total issues.
