### ISSUE TITLE
Raw $PROMPT

### ISSUE THREAD

**Issue by Kilte** [xonsh/xonsh#1372] opened 2016-06-30 13:39 UTC
Sometimes it shows me a prompt template: `{cwd}{branch_color}{curr_branch} {prompt_end} `
Its very hard to reproduce and I cannot figure out a reason of this problem.

My `$PROMPT`:  

```
$PROMPT = '{BOLD_BLUE}{cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} '
```

And xonsh version:

```
~ $ xonsh --version
('xonsh/0.4.2.dev54',)
```

**Comment by melund** [comment] 2016-06-30 14:05
Can you post the output of running: `xonfig`?

Also where do you see the raw prompt?

**Comment by Kilte** [comment] 2016-06-30 14:27
xonfig:
```
+------------------+-------------+
| xonsh            | 0.4.2.dev54 |
| Python           | 3.4.2       |
| PLY              | 3.7         |
| have readline    | True        |
| prompt toolkit   | None        |
| shell type       | readline    |
| pygments         | 2.0.2       |
| on posix         | True        |
| on linux         | True        |
| distro           | debian      |
| on darwin        | False       |
| on windows       | False       |
| on cygwin        | False       |
| is superuser     | False       |
| default encoding | utf-8       |
| git SHA          | None        |
+------------------+-------------+
```

>Also where do you see the raw prompt? 

In terminal emulator, if I've understood you correctly.

**Comment by melund** [comment] 2016-06-30 19:14
Well. More in what context . Do you see it instead of the normal  as prompt or as part of output from subprocess. Can you post a print-screen when you see it.

**Comment by Kilte** [comment] 2016-06-30 20:18
![Imgur](http://i.imgur.com/cpnRm3q.png)

**Comment by scopatz** [comment] 2016-06-30 20:22
Can you start simplifying the prompt by removing `{key}` elements until you find one that works, please?

**Comment by Kilte** [comment] 2016-06-30 20:24
@scopatz, It's very hard to catch it, but I will try.

**Comment by scopatz** [comment] 2016-06-30 20:28
Ok! Thanks.  My suspicion is that it is the version control branch stuff, if that helps...

**Comment by Kilte** [comment] 2016-06-30 20:33
Yeah! I can reproduce it!
1. Open the terminal.
2. Press and keep Enter key for several seconds.
3. Press Ctrl+C
4. ???
![Imgur](http://i.imgur.com/WTkj5Yp.png)
`$PROMPT = '{branch_color}{cwd}{NO_COLOR}'`

**Comment by Kilte** [comment] 2016-06-30 20:41
IMO it does not depend on branch stuff. Reproduced with `{BOLD_BLUE}{cwd}{NO_COLOR}`.
But in this case I have the following output: `^C{BOLD_BLUE}~{NO_COLOR}`
Perhaps the problem is a delay before displaying prompt.

**Comment by scopatz** [comment] 2016-06-30 20:49
@Kilte, yeah I am begining to agree.  I tried reproducing it your way and could not.  Maybe it is a terminal emulator problem?  What terminal application are you using?

**Comment by Kilte** [comment] 2016-07-01 05:43
@scopatz Gnome Terminal and Xfce4 Terminal

**Comment by Kilte** [comment] 2016-07-01 05:48
Maybe this will help
[![asciicast](https://asciinema.org/a/0erjrh2x51r1kmzbfnaaah4x4.png)](https://asciinema.org/a/0erjrh2x51r1kmzbfnaaah4x4)

**Comment by melund** [comment] 2016-07-01 06:41
Interesting. I haven't seen this before. 

@BlaXpirit is working on re implementing the 'prompt' formatting in #1369. Maybe he has a clue why you would see this. This may also be fixed with the improvements he makes.

**Comment by BlaXpirit** [comment] 2016-07-01 06:59
Nope, my changes aren't going to affect this. I was able to reproduce, even - it's pretty easy, just hold Enter and press Ctrl+C.

```
bx-pc-arch blaxpirit  prompt-optional-items* 09:55:40 
~/pro/rep/xonsh⟫ 
bx-pc-arch blaxpirit  prompt-optional-items* 09:55:41 
~/pro/rep/xonsh⟫ 
^C{sysinfo}{last_return:{} }{last_duration:{} }{hostname} {user}{term: {}}{branch: {}} {time} {date: {}}
{short_cwd_dir}{cwd_base}{prompt_color}{prompt_end} 
```

I think the gist of it is, due to the very bad practice of using bare `except:`, somewhere in the code the KeyboardInterrupt exception is caught and is perceived as something going wrong during the formatting, and the fallback is to print the string as is.

**Comment by BlaXpirit** [comment] 2016-07-01 07:04
Yup, it's this bad boy https://github.com/xonsh/xonsh/blob/acd372a3/xonsh/environ.py#L1226

Using `except Exception:` instead prevents the problem.

**Closed** 2016-07-01 14:16 UTC
Labels: bug
