### ISSUE TITLE
NixOS: coreutils are not captured because unthredable

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5003] opened 2022-11-28 04:34 UTC
_Originally posted by @amacfie in https://github.com/xonsh/xonsh/issues/4214#issuecomment-1328288341_:

On Debian/Arch:
```python
docker run --rm -it python:3.10-slim /bin/bash -c "pip install 'xonsh[full]' && xonsh"

xonsh --version  
# xonsh/0.13.3

!(echo hi) == 'hi\n'
# True
!(echo hi).out == 'hi\n'
# True
```
But on NixOS:
```bash
docker run --rm -it nixos/nix:2.3.16 /bin/sh

nix-channel --update
nix-shell -p xonsh

xonsh --version  
# xonsh/0.13.3
xonsh

!(echo hi) == 'hi\n'
# hi
# False
!(echo hi).out == 'hi\n'
# hi
# False
```
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment] 2022-11-28 15:41
Might be that something in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/xonsh.nix (maybe in everything that gets `source`d) is screwing up our piping.

**Comment by SamLukeYes** [comment] 2022-12-12 16:21
> Might be that something in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/xonsh.nix (maybe in everything that gets `source`d) is screwing up our piping.

Actually, the xonshrc defined in this module is not loaded by default without https://github.com/NixOS/nixpkgs/pull/204252, which was merged a few hours ago and is not yet in nixos-unstable (though will be landed very soon).

**Comment by gforsyth** [comment] 2022-12-12 16:40
Thanks @SamLukeYes -- that at least rules out a bunch of things that would be very annoying to check.

The only thing left that I can think of is that we're getting some behavior from `subprocess.PIPE` that is different than what we expect.

**Comment by yaxollum** [comment] 2022-12-15 04:31
This issue is specific to the `echo` command. On NixOS, when I run something like
```
!(python -c "print('hi')") == 'hi\n'
```
I get the expected output.

I think the cause of this issue is that xonsh thinks `echo` is not threadable, so it runs it using the `Popen` class instead of the `PopenThread` class and doesn't pipe its stdout/stderr:
https://github.com/xonsh/xonsh/blob/bcf2592b7dc628ba4f64bb3e9744199edc42cfa5/xonsh/procs/specs.py#L747-L761

I can also reproduce this issue on Fedora by running
```
!(cat /etc/passwd)
```
The `cat` command is not threadable, so its output is not captured.

**Comment by SamLukeYes** [comment] 2024-05-23 08:07
> Is it right that `cmds_cache.predict_threadable` returns False for nix `cat`?

I'm not sure if I'm doing it right, but I observe this on my NixOS:

```xonsh
$ import xonsh

$ xonsh.commands_cache.CommandsCache($(env)).predict_threadable('cat')
True

$ xonsh --version
xonsh/0.15.1
```

> What is the difference between nix `cat` and gnu `cat`?

The default `cat` on NixOS is provided by GNU coreutils. There are also some other packages providing `cat` in nixpkgs tho, e.g. uutils, toybox, gash-utils, etc.

**Comment by bestlem** [comment] 2024-05-23 12:26
If using nix what does running the nixpklgs version do e.g. `nix run "nixpkgs#xonsh"` do?

Unfortunately my nix rather deeply embedded so can't give a simple case. These are just observations.

I don't understand docker either - although I would note anything using docker is running linux even if running from a mac.

I have xonsh installed via a nix flake on a mac mini apple silicon  and I get (and also via nix run
```
🐚 xonsh --version
xonsh/0.15.1
🐚 !(echo hi).out == 'hi\n'
True
🐚 !(echo hi) == 'hi\n'
True
```

I would note that - the docker line I think is an old nix version
```
🐚 nix --version
nix (Nix) 2.19.4
```

xonsh question - Why don't I get hi printed out 
I repeated starting the shell as xonsh -i -l --no-rc and with the nix run and these gave the same.

However as I ran xonsh from an existing shell I get
```
zsh ❯  xonsh
[1]  + 93454 suspended (tty output)  xonsh
```

**Comment by SamLukeYes** [comment] 2024-05-23 14:37
> what's the output of
> 
> ```python
> !(echo hi) == "hi"
> ```

```xonsh
$ !(echo hi) == 'hi'
hi
False
```

Still the same :confused:

**Comment by SamLukeYes** [comment] 2024-05-23 16:08
> I'm not familiar with podman/docker and have trouble accessing the internet inside the container, probably because of my proxy setting.

The issue was because I use a local http proxy. Passing `--net host` to `podman` solves the issue for me.

Also, I found venv works inside the container:

```command
$ nix-shell -p python3
$ python3 -m venv venv
$ source venv/bin/activate
```

And then you can use pip :)

> But I faced with the question of how to install root CA certification on clean nix os.

AFAIK, the docker image `nixos/nix` is a distroless container with nix package manager available, but not an actual NixOS with its module system. I can still reproduce the issue in the container tho.

**Comment by SamLukeYes** [comment] 2024-05-24 15:00
> @SamLukeYes please take a look:
> 
> ```python
> docker run --rm -it nixos/nix bash
> nix-shell -p python3
> python3 -m venv venv
> source venv/bin/activate
> pip install git+https://github.com/xonsh/xonsh@fix_nix  # @fix_nix
> xonsh
> !(echo Nix is nice)
> # CommandPipeline(
> #   returncode=0,
> #   pid=148,
> #   args=['echo', 'Nix', 'is', 'nice'],
> #   executed_cmd=['echo', 'Nix', 'is', 'nice'],
> #   timestamps=[1716552319.09322, 1716552319.1041143],
> #   input='',
> #   output='Nix is nice'
> # )
> ```
> 
> The full case described in PR #5440.

I can confirm this works in a venv on NixOS. However, in a conda-shell environment, the output is still like this:

```
Nix is nice
CommandPipeline(
  returncode=0,
  pid=74595,
  args=['echo', 'Nix', 'is', 'nice'],
  executed_cmd=['echo', 'Nix', 'is', 'nice'],
  timestamps=[1716561398.5684817, 1716561398.5894334],
  input='',
  output=''
)
```

I noticed that `echo` has more symlink layers in this case than outside of conda-shell, which is `/usr/bin/echo -> /nix/store/mh1pbbg0h7swfv5vn0v6rlxh8yx5ga5j-conda-shell-usr-target/bin/echo -> /nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin/echo -> coreutils`. This should be a common case in an [FHS environment](https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments).

**Closed** 2024-05-24 20:51 UTC
Labels: linux, threading
