### ISSUE TITLE
install from homebrew on macos: Python Icon Jumping on the Dock

### ISSUE THREAD

**Issue by fzhwenzhou** [xonsh/xonsh#5641] opened 2024-08-01 09:33 UTC
## Current Behavior
When starting `xonsh`, Python appears on the Dock and jumps immediately. If quitting `xonsh`, the icon will soon disappear. Force quitting Python from the dock will also kill `xonsh` in the terminal.

Running any other Python terminal program won't cause this issue.

Although it wouldn't affect the functions, it's fairly ugly because it's the ONLY terminal app that appears in the Dock I've ever seen.  Thus, I sincerely hope you can find the reasons and fix the bug. Thank you in advance!

https://github.com/user-attachments/assets/dcd10e63-da52-486d-be6f-ed313c91ffcc

## Expected Behavior
The icon does not appear on the Dock. 

## Additional Information
Operating System: macOS Sequoia 15.0
CPU: Apple M2 Pro
`uname -a` output:
```
Darwin zhangsandeMacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Sat Jul 13 00:57:33 PDT 2024; root:xnu-11215.0.165.0.4~50/RELEASE_ARM64_T6020 arm64
```
`python3` output:
```
Python 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
```
`xonsh --version` output:
```
xonsh/0.18.2
```

Installation Source: Homebrew 4.3.12
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by fzhwenzhou** [comment] 2024-08-01 14:58
> Hey! Wow! First time seeing this :)
> 
> 1. Please tell us more about the terminal app and it's version.
> 
> 2. What if you try the same in iTerm2 or another terminal emulator?
> 
> 3. What if you run xonsh from original zsh?
> 
> 
> 
> PS: I can't repeat this on my mac with default terminal and with iTerm2

1. Terminal app: Terminal, 2.14(453), Apple Inc.

2. It always occurs no matter what the terminal is, including the terminal in VSCode.

3. It always occurs no matter how to run it, including running from any other shells (bash, zsh, fish, etc.), or setting it to be the login shell.

In addition, I tried to install it from pip, and it became normal. It may only occur when it's installed from Homebrew.

**Comment by bestlem** [comment] 2024-08-01 19:58
Homebrew might have done some patches - what is the shebang in Homebrew's songs 
That is what are the first few lines?

**Comment by fzhwenzhou** [comment] 2024-08-02 03:55
> Homebrew might have done some patches - what is the shebang in Homebrew's songs That is what are the first few lines?
The first line of `xonsh` in Homebrew is:
```
#!/opt/homebrew/Cellar/xonsh/0.18.2/libexec/bin/python
```
While the one in pip is:
```
#!/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```
The former refers to a symlink, while the latter refers to the actual Python executable file.
To find out what is the symlink, I tried this command:
```
@ ls -alh /opt/homebrew/Cellar/xonsh/0.18.2/libexec/bin/
total 40
drwxr-xr-x  10 zhangsan  admin   320B  8  2 11:28 .
drwxr-xr-x   6 zhangsan  admin   192B  8  2 11:25 ..
-rwxr-xr-x   1 zhangsan  admin   251B  8  2 11:25 pygmentize
lrwxr-xr-x   1 zhangsan  admin    87B  7 18 21:27 python -> ../../../../../opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
lrwxr-xr-x   1 zhangsan  admin    87B  7 18 21:27 python3 -> ../../../../../opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
lrwxr-xr-x   1 zhangsan  admin    87B  7 18 21:27 python3.12 -> ../../../../../opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
-rwxr-xr-x   1 zhangsan  admin   245B  8  2 11:25 xonsh
-rwxr-xr-x   1 zhangsan  admin   254B  8  2 11:25 xonsh-cat
-rwxr-xr-x   1 zhangsan  admin   256B  8  2 11:25 xonsh-uname
-rwxr-xr-x   1 zhangsan  admin   257B  8  2 11:25 xonsh-uptime
```
It seems it links to the Python installed by Homebrew rather than the one in the system PATH.

To verify if it is related to the Homebrew Python, I tried to relink the symbol to the system Python, but the bug still occurs. Thus, it is unrelated to Python.

An interesting thing is that, opening the Homebrew xonsh from the pip xonsh won't cause this issue. And opening another Homebrew xonsh from an existing Homebrew xonsh won't increase the icon on the dock.

**Comment by bestlem** [comment] 2024-08-02 07:58
What happens if you run Hombrew Python `/opt/homebrew/Cellar/xonsh/0.18.2/libexec/bin/python` on its own - does python open a new Terminal.

**Comment by fzhwenzhou** [comment] 2024-08-02 10:51
> What if you run xonsh from https://github.com/anki-code/xonsh-install ?

Everything is fine.

> What happens if you run Hombrew Python `/opt/homebrew/Cellar/xonsh/0.18.2/libexec/bin/python` on its own - does python open a new Terminal.

No. Everything is fine.

**Comment by bartheerman** [comment] 2024-09-18 07:59
maybe adding this to xonsh will work:

```python
from AppKit import NSBundle

app_info = NSBundle.mainBundle().infoDictionary()
app_info["LSBackgroundOnly"] = "1"  # run as background application
```

**Comment by rafiv** [comment] 2024-09-19 12:25
I can confirm the issues in this thread and installed xonsh now also via xonsh-install. The issue only occurs when using homebrew.

macOS Version: Sequoia 15.0 (24A335)

**Comment by ladyrick** [comment] 2024-11-14 12:07
I encountered the same problem on MacOS Sequoia 15.0.1, xonsh 0.18.4

**Comment by gforsyth** [comment] 2024-11-18 22:55
This seems to be an issue with how homebrew is packaging `xonsh`, so I'm going to close this out.  Thanks for suggesting alternatives, everyone!

**Closed by gforsyth** 2024-11-18 22:55 UTC
Labels: mac osx, upstream, integration-with-other-tools

**Comment by p-linnane** [comment] 2024-11-20 20:37
Hi. I'm a Homebrew maintainer. All we are doing to package xonsh is using `pip` to install it in a venv. We made no configuration changes for our build.
