### ISSUE TITLE
stderr is not captured for captured commands launched inside functions

### ISSUE THREAD

**Issue by zardus** [xonsh/xonsh#2107] opened 2017-01-25 05:12 UTC
I'm seeing strange behavior for stderr redirection. First, this works as expected:

```
# cd /
# x = !(git rev-parse --show-toplevel)
# print(bool(x))
False
```

Cool. git does print an error about not being in a git repo, but it's captured by xonsh. However, doing the same thing in a function results in the error escaping onto the console:

```
# def wtf():
.     x = !(git rev-parse --show-toplevel)
.     print(bool(x))
.     del x
. 
# wtf()
fatal: Not a git repository (or any of the parent directories): .git
False
```

Specifically, the rogue print happens when the boolean conversion happens. Any ideas?

**Comment by gforsyth** [comment] 2017-01-25 17:07
Thanks for reporting @zardus! Could you post the output of `xonfig` please?

I actually can't reproduce your first example -- if I run the command, the git error is passed through to stderr despite the capture command.  Definitely a problem, but weird that it's appearing in different ways.

**Comment by gforsyth** [comment] 2017-01-25 19:25
Ahh -- ok, there are two separate issues here.  I can confirm your error like this:

```console
$ x = !(ls -e)
$ print(bool(x))
False
```

then
```
def wtf():
    x = !(ls -e)
    print(bool(x))
    del x
$ wtf()
ls: invalid option -- 'e'
Try 'ls --help' for more information.
False
```

**Comment by gforsyth** [comment] 2017-01-25 19:42
but then this works just fine:

```console
$ a = !(ls -e)
$ def p(a):
      print(bool(a))
$ p(a)
False
```

**Comment by zardus** [comment] 2017-01-27 01:21
Yeah, it's kinda bizarre. That's why I thought that it was a GC issue, but it happens without things getting deleted. For example:

```
class A:
    def __init__(self):
        self.x = !(ls -e)
        self.b = bool(self.x)
a = A()
```

It really seems to only capture stderr from processes launched from the main scope...

**Comment by scopatz** [comment] 2017-01-27 02:54
Oof da, this is weird. I checked the ASTs and the `x = !(ls -e)` part is evaluated to the same subtree. Also `expand_path('-e') == '-e'`  This has gotta be coming from the subproc spec/pipeline code?

**Comment by scopatz** [comment] 2017-01-27 03:24
Ok, I think that the problem is that `!(cmd)` was not designed for assignment, but rather for iteration.  The following seems to work for me:

```console
scopatz@artemis ~ $ for line in !(ls -e):
`·.,¸,.·*¯`·.,¸,.·*     print(line)
`·.,¸,.·*¯`·.,¸,.·*     
ls: invalid option -- 'e'
Try 'ls --help' for more information.
scopatz@artemis ~ $ def wtf():
`·.,¸,.·*¯`·.,¸,.·*     for line in !(ls -e):
`·.,¸,.·*¯`·.,¸,.·*         print(line)
`·.,¸,.·*¯`·.,¸,.·*         
scopatz@artemis ~ $ 
scopatz@artemis ~ $ wtf()
ls: invalid option -- 'e'
Try 'ls --help' for more information.
```

**Comment by zardus** [comment] 2017-01-27 09:39
Are you saying that stderr *shouldn't* be captured by `!()`? I think what's happening in your example is that it's not being captured:

```ShellSession
yans@lath ~ master $ for line in !(ls -e):
....................     print("LINE")
....................     print("CONTENT",repr(line))
ls: invalid option -- 'e'
Try 'ls --help' for more information.
```

That ls output doesn't come from the for loop, but is dumped to stderr in some other way. I don't think the iteration should necessarily return stderr, for the record, but `!()` claims that it should capture it, or am I misunderstanding?

BTW, simply executing `!(ls -e)`, even in the console scope, also dumps stderr to the console, so the "special case" that's different is definitely that console-scope assignment `$ x = !(ls -e)` *does* capture it, unlike any of the other options. That capture behavior is how I'd expect all the cases to work, though.

Additionally, on a philosophical note about the purpose of `!()`, shouldn't we be able to check the return code *and* iterate over the output? Is there a way to do that without assigning the resulting `CommandPipeline` object to a variable?

**Comment by scopatz** [comment] 2017-01-28 19:12
> Are you saying that stderr shouldn't be captured by !()?

Yes, that is correct. Like with most unix-gazing tools, capture only applies to stdout, and if you want to capture stderr, stderr needs to be redirected to stdout. E.g. `!(cmd err>out)`  !(cmd e> /dev/null) or similar.

> Additionally, on a philosophical note about the purpose of !(), shouldn't we be able to check the return code and iterate over the output? Is there a way to do that without assigning the resulting CommandPipeline object to a variable?

You are correct that `!()` is the way to do this. But this is an important happy accidient of the original purpose of this operator. The original motivation was to have a streaming operator that could act on commands that produced output (much) larger than the OS buffer size. `!()` is xonsh's non-blocking operator. 

However, some operations, like getting the return code, have to block. What we were seeing here was a bug in that part of the code. The command would block, but the pipeline wasn't being finalized properly so you wouldn't see stderr error. This gave the impression that stderr was being captured when it was actually just being delayed.

```console
scopatz@artemis ~ $ x = !(ls -e)
scopatz@artemis ~ $ bool(x)  # stderr should print here
False
scopatz@artemis ~ $ x.out  # # but instead it prints here.
ls: invalid option -- 'e'
Try 'ls --help' for more information.
''
```

I have put in #2118 to address this.

**Comment by scopatz** [comment] 2017-01-28 19:28
Also, @zardus let us know if this makes sense :)

**Comment by zardus** [comment] 2017-01-29 01:03
Ah, I see how it works now. Several things came into play at once:

1. I was missing the `err>out` syntax. For my purposes, that could have avoided this dive into `!()` subtleties.
2. I didn't realize that `CommandPipeline.stderr` and `CommandPipeline.stdout` were completely non-blocking; I expected them to block. It seems that the reason I was getting different results on the console directly versus in a function was the delay in typing the second console command.
3. The return code thing further confused matters.

I do think that the fact that un-processed data in stderr is dumped onto the console in some cases of `!()`, but not others, is confusing. For example:

```
yans@lath ~ master $ def asdf():
...........................     x = !(bash -c "echo one >&2; sleep 1; echo two>&2")
...........................     s = ''
...........................     while not s:
...........................         s = x.stderr.read()
...........................     print(repr(s))
...........................     print(bool(x))
yans@lath ~ master $ asdf()
b'one\n'
two
True
yans@lath ~ master $ def fdsa():
...........................     x = !(bash -c "echo one >&2; sleep 1; echo two>&2")
...........................     s = ''
...........................     while not s:
...........................         s = x.stderr.read()
...........................     print(repr(s))
yans@lath ~ master $ fdsa()
b'one\n'
```

`one` is captured in both cases, because I keep reading until something ends up in `stderr`, but `two` is dumped to the console in `asdf` and silently suppressed in `fdsa`, because `x.end()` is never called. Adding a destructor to `CommandPipeline` that calls `self.end()` fixes the issue.

```diff
diff --git a/xonsh/proc.py b/xonsh/proc.py
index ed52361..80dbc4b 100644
--- a/xonsh/proc.py
+++ b/xonsh/proc.py
@@ -1693,6 +1693,9 @@ class CommandPipeline:
         self.lines = []
         self._stderr_prefix = self._stderr_postfix = None
 
+    def __del__(self):
+        self.end()
+
     def __repr__(self):
         s = self.__class__.__name__ + '('
         s += ', '.join(a + '=' + str(getattr(self, a)) for a in self.attrnames)
```

Can you see any issues with that?

**Comment by scopatz** [comment] 2017-01-29 17:46
> I do think that the fact that un-processed data in stderr is dumped onto the console in some cases of !(), but not others, is confusing

I agree, that is what #2118 fixes.

> Adding a destructor to CommandPipeline that calls self.end() fixes the issue. Can you see any issues with that?

Yeah, I think that this probably best avoided. The reason is that if we are trying to prematurely destroy a pipeline, perhaps due to an exception or the Python interpreter exiting, we should not have to wait for the current process to exit completely.  I think this has the potential to cause deadlocks in such situations. 

That said, we probably do want to ensure that the file handles are cleaned up. Something like the following would probably be appropriate:

```python
def __del__(self):
    if not self.ended:
        self._close_prev_procs()
        self._close_proc()
```

Pull requests welcome!

**Comment by scopatz** [comment] 2017-01-29 23:04
BTW #2118 has been merged into master

**Comment by scopatz** [comment] 2017-02-05 16:50
@zardus do you feel that this is closable?

**Comment by zardus** [comment] 2017-02-06 09:50
I think that destructor PR would be enough to close it, as there are still special cases (like the one I mentioned above) that's act weird, but a) I haven't had time to create that yet and b) it's not quite exactly the same issue (though it's very related), so I can see this one being closeable.

**Comment by scopatz** [comment] 2017-02-06 15:59
Great! Please feel free to open more issues!

**Closed by scopatz** 2017-02-06 15:59 UTC
Labels: bug, help wanted
