### ISSUE TITLE
xonsh start fails after update 0.5.2 to 0.5.3

### ISSUE THREAD

**Issue by sejktmcsdlmfhsc** [xonsh/xonsh#2143] opened 2017-02-01 21:04 UTC
..after an update from 0.5.2 to 0.5.3, 
my favorite shell refuses to load.. 
here my xonfig before update to 0.5.3:
``` python
+------------------+---------------------+
| xonsh            | 0.5.2               |
| Git SHA          | f1f19f7             |
| Commit Date      | Jan 4 17:47:31 2017 |
| Python           | 3.4.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | debian              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```
and this is the error message I get 
(unfortunately I cannot make too much sense of it atm. 
line 4152 of the amalgam is the line:
'//': DOUBLESLASH,
in the EXACT_TOKEN_TYPES dict):

Traceback (most recent call last):
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 18346, in main
    return main_xonsh(args)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 18369, in main_xonsh
    shell.shell.cmdloop()
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 144, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 107, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/amnesia/.local/lib/python3.4/site-packages/pygments/style.py", line 63, in __new__
    for token in ttype.split():
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 4152, in __getattr__
    return tuple.__getattribute__(self, val)
AttributeError: '_TokenType' object has no attribute 'split'
Xonsh encountered an issue during launch
Failback to /bin/sh

Best,
Sej

**Comment by gforsyth** [comment] 2017-02-01 21:07
Hey @sejktmcsdlmfhsc -- thanks for reporting and sorry about that! 
Two questions:
Can you paste a traceback after running `env XONSH_DEBUG=1 xonsh`?

Does `xonsh --shell-type readline` work?

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-01 21:19
Hej @gforsyth,
sure. Thanks for the quick reply! 
No worries, at worst I would revert to 0.5.2.

Aha - yes it works on readline! 
(Although some prompt colors are of..)
[I also tried updating prompt-toolkit to 1.10 but the error persists]

Here is the traceback with debug:
amnesia@amnesia:~$ env XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 294, in main
    return main_xonsh(args)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 144, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 107, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/amnesia/.local/lib/python3.4/site-packages/pygments/style.py", line 63, in __new__
    for token in ttype.split():
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/style_tools.py", line 16, in __getattr__
    return tuple.__getattribute__(self, val)
AttributeError: '_TokenType' object has no attribute 'split'
Xonsh encountered an issue during launch
Failback to /bin/sh

**Comment by gforsyth** [comment] 2017-02-01 21:21
Thanks! 

Yeah, this is my fault -- I'm just curious why I can't reproduce it. I'll try to figure out a fix.

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-01 21:26
All right, thanks!  I'll  stay on readline in the meantime.

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-01 21:32
..interesting - now my editor notified me of the updated __amalgam__ 
and now at line 4152 the return of the _TokenType class appears 
as mentioned in the traceback.
Is the amalgam put together at each xonsh startup?

**Comment by gforsyth** [comment] 2017-02-01 21:56
That's seems strange. NO, amalgam is run at install time, but not at startup

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-01 22:04
hm.. maybe I had it opened for longer than I thought 
and the update was between changing between 0.5.2 to 0.5.3 or back..

As you could probably already tell from the tracebacks, I have xonsh 
installed with pip --user - hopefully that is not causing the irreproducibility..

**Comment by gforsyth** [comment] 2017-02-01 22:21
Hey @sejktmcsdlmfhsc -- can you check out #2144 and see if that fixes your issue?

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-01 22:40
Hej @gforsyth , 
yeah seems like that fixed the style_tools.py part, 
but pygments still complains. Now I only get:

amnesia@amnesia:~$ env XONSH_DEBUG=1 xonsh 
Traceback (most recent call last):
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 294, in main
    return main_xonsh(args)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 144, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 107, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/amnesia/.local/lib/python3.4/site-packages/pygments/style.py", line 66, in __new__
    ndef = _styles.get(token.parent, None)
AttributeError: 'str' object has no attribute 'parent'
Xonsh encountered an issue during launch
Failback to /bin/sh

**Comment by gforsyth** [comment] 2017-02-02 02:24
Thanks for trying it out @sejktmcsdlmfhsc ! Could you try it again now and see if the errors are resolved?  Thanks!

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-03 20:44
Hi @gforsyth , sorry for the delay, things were pretty busy at work. I actually got to upgrade xonsh from 0.5.2 to 0.5.3 on a windows box there with the same result. That led me to the conclusion, that at least parts of the problem would be connected with my .xonshrc. So I step-by-step commented out parts and found the origin. If I commented all the lines out that call colorize() [I copied that from another xonshrc from github - now I probably need to look for another way to do that] then my shell would run normally(except sadly for the missing color, of course). 
Here the mentioned section of my .xonshrc:

```python
def _xonsh_colorize(text, base_col, before_col=None, final_col=False):
    result = ''
    if before_col:
        result += '{' + before_col + '}{BACKGROUND_' + base_col + '}'
    result += '{BLACK}{BACKGROUND_' + base_col + '}' + text
    if final_col is True:
        result += '{BACKGROUND_#252525}{' + base_col + '}{NO_COLOR} '
    return result


$PROMPT = '\n'
$PROMPT += _xonsh_colorize('🐍 xonsh ', 'YELLOW', 'YELLOW')
$PROMPT += _xonsh_colorize(' {user} ', '#00adee', 'YELLOW')
$PROMPT += _xonsh_colorize(' {hostname} ', '#8be8ac', '#00adee')
$PROMPT += _xonsh_colorize('{cwd} ',  '#50a0a0', '#8be8ac')
$PROMPT += _xonsh_colorize('{curr_branch} ', 'INTENSE_GREEN', '#50a0a0', True)
$PROMPT += '\n'
$PROMPT += ''
```
Yes I will try also with the current github version of xonsh 
(usually I run with the pip install version) and let you know 
if that resolved the issue.
Thank you!!

**Comment by gforsyth** [comment] 2017-02-03 21:12
Hy @sejktmcsdlmfhsc -- no worries and thanks for letting us know!

I think that the issue was caused by the custom colors -- the `{INTENSE_GREEN}` and stuff will work fine but the `{BACKGROUND_#00adee}` ones are what was throwing the error. That should work now in the PR I have open.

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-03 21:25
Cool - thanks a lot! That is PR #2144 right?

**Comment by gforsyth** [comment] 2017-02-03 21:26
That's the one!

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-03 22:39
ok, I cloned current xonsh from github and applied the changes from #2144. 
On top of that I only kept the following part of colorize in my .xonshrc:

```python
$PROMPT = '\n'
$PROMPT += _xonsh_colorize('🐍xonsh ', 'YELLOW', 'YELLOW', True)
$PROMPT += '\n'
$PROMPT += '>'
```

I get this msg:

```bash
amnesia@amnesia:~$ env XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 294, in main
    return main_xonsh(args)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 147, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 110, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/amnesia/.local/lib/python3.4/site-packages/pygments/style.py", line 63, in __new__
    for token in ttype.split():
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/style_tools.py", line 16, in __getattr__
    return tuple.__getattribute__(self, val)
AttributeError: '_TokenType' object has no attribute 'split'
Xonsh encountered an issue during launch
Failback to /bin/sh

```

if I add back the split() method in _TokenType() in style_tools I get this msg:
```bash
amnesia@amnesia:~$ env XONSH_DEBUG=1 xonsh
Traceback (most recent call last):
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 294, in main
    return main_xonsh(args)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/main.py", line 317, in main_xonsh
    shell.shell.cmdloop()
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 147, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/ptk/shell.py", line 110, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/home/amnesia/.local/lib/python3.4/site-packages/xonsh/pyghooks.py", line 467, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/amnesia/.local/lib/python3.4/site-packages/pygments/style.py", line 66, in __new__
    ndef = _styles.get(token.parent, None)
AttributeError: 'str' object has no attribute 'parent'
Xonsh encountered an issue during launch
Failback to /bin/sh
```
with the colorize() line commented out it runs.

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-04 15:29
After toying around with it, it seems that it not only breaks with special colors, 
but also as soon as "BACKGROUND_" comes into play..

**Comment by pgoelz** [comment] 2017-02-09 11:14
I’m experiencing the same problems on 0.5.4. Removing custom colors from my xonshrc works.
I think that it would be useful to release shortly after this bug is fixed. That way, other people upgrading using version control will not experience the same problem.

**Comment by moigagoo** [comment] 2017-02-09 11:16
I'm getting this error when using powerline. Otherwise, everything works fine.

**Comment by gforsyth** [comment] 2017-02-09 17:46
@pgoelz and @moigagoo -- could you try out the fixes in #2144 and see if they resolve your issues?  Thanks!

**Comment by moigagoo** [comment] 2017-02-11 07:27
@gforsyth Installed xonsh from style_hotfix branch, enabled powerline xontrib, the issue is still there. Maybe I'm doing something wrong, please correct me.

**Comment by gforsyth** [comment] 2017-02-11 16:40
Thanks for letting me know, @moigagoo -- I've just pushed up an additional fix that handles the powerline xontrib on my end -- could you try out the `style_hotfix` branch again and see if it works on your end?  Thanks!

**Comment by moigagoo** [comment] 2017-02-13 17:16
@gforsyth Tried it again—seems to work OK! Thanks for the fix!

**Comment by scopatz** [comment] 2017-02-13 18:57
Closing this since #2144 was merged.

**Closed by scopatz** 2017-02-13 18:57 UTC

**Comment by sejktmcsdlmfhsc** [comment] 2017-02-13 19:41
@gforsyth yay!! works all fine on my end, too.Thanks a lot!!
