### ISSUE TITLE
Error For full traceback set $XONSH_SHOW_TRACEBACK = True termios error: (5, 'Input/output error')

### ISSUE THREAD

**Issue by ErickTucto** [xonsh/xonsh#2568] opened 2017-12-19 15:33 UTC
I installed Ubuntu Server 16.04 LTS on virtualbox.
I installed xonsh with python3.5.2 and my default shell is xonsh
I installed with pip3:
- ply
- prompt-toolkit
- setproctitle
- pygments
- distro

After, I installed php7.1, mysql 5.7.20  and nginx 1.13.7 on my Ubuntu Server
I'm set nginx, when execute `sudo service nginx configtest`, show error:

![imagen](https://user-images.githubusercontent.com/22831024/34164287-2760e978-e4a7-11e7-8de2-44376d8eac23.png)

To exit this error, I have close my terminal. Ctrl + d or Ctrl + w or Ctrl + q don't work. I have close my terminal.

After when I connect to my virtual machine and execute `sudo service mysql configtest` (the same command) the error is not shown

**Comment by astronouth7303** [comment] 2017-12-19 16:14
#2309 #2366 ?

**Comment by scopatz** [comment] 2017-12-19 17:29
Thanks for reporting @ErickTucto - This does look like a duplicate of those issues.  I wonder if #2559 fixes this issue.

**Closed** 2021-02-11 20:10 UTC
Labels: duplicate
