### ISSUE TITLE
<unknown>:1: DeprecationWarning: invalid escape sequence \[

### ISSUE THREAD

**Issue by orrinjelo** [xonsh/xonsh#3414] opened 2019-12-30 19:03 UTC
## xonfig

<details>

```+------------------+-----------------+
| xonsh            | 0.6.0           |
| Python           | 3.6.9           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | readline        |
| pygments         | 2.5.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## Expected Behavior
I use xonsh as the default shell on my system, running it both through the MATE Terminal and Guake.  Before restart it was doing just fine. I don't recall installing anything in the previous MATE session (this is my work computer, and so I hardly ever update packages beyond the first setup/install for stability).  I've customized my prompt in my .xonshrc, but I'm not entirely sure it is even related to this error.
```$PROMPT='[{BOLD_CYAN}{current_time}{NO_COLOR}] {BOLD_BLUE}{cwd} {NO_COLOR}{git_tag}{retcolor}{prompt_end}{NO_COLOR} '
$BOTTOM_TOOLBAR = '{#FF007F}{env_name:{} }{#FF4500}{user}{#baddad}@{#FFDEAD}{hostname}{NO_COLOR}{retstr} -\
 {BOLD_WHITE}Memory: {usedmemcolor}{usedmem}{NO_COLOR} ({usedmemcolor}{usedmempc}%{NO_COLOR}) / {BOLD_WHITE}{totmem}{NO_COLOR} -\
 {BOLD_WHITE}CPU: {cpucolor}{cpu}%{NO_COLOR} -\
 {BOLD_WHITE}Disk: {diskcolor}{diskpc}%{NO_COLOR} -\
 {datum}'
```

## Current Behavior

I can't even launch into xonsh without doing `xonsh --shell-type=readline`.  I get the error message and traceback below (sometimes I don't even get the first line with DeprecationWarning).

### Traceback (if applicable)

<details>

```
<unknown>:1: DeprecationWarning: invalid escape sequence \[
Traceback (most recent call last):
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24016, in main
    return main_xonsh(args)
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24045, in main_xonsh
    shell.shell.cmdloop()
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 176, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 141, in singleline
    pyghooks.xonsh_style_proxy(self.styler)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_pygments.py", line 64, in __new__
    return style_from_dict(pygments_style_cls.styles)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 124, in style_from_dict
    attrs = attrs._replace(color=_colorformat(part))
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 39, in _colorformat
    raise ValueError('Wrong color format %r' % text)
ValueError: Wrong color format 'ansibrightblack'
```

</details>

## Steps to Reproduce

<details>

```
sudo apt install virtualenv
virtualenv xonsh
source xonsh/bin/activate
python3 -m pip install xonsh
python3 -m xonsh
Traceback (most recent call last):
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24016, in main
    return main_xonsh(args)
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24045, in main_xonsh
    shell.shell.cmdloop()
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 176, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/tylerp/.local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 141, in singleline
    pyghooks.xonsh_style_proxy(self.styler)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_pygments.py", line 64, in __new__
    return style_from_dict(pygments_style_cls.styles)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 124, in style_from_dict
    attrs = attrs._replace(color=_colorformat(part))
  File "/usr/lib/python3/dist-packages/prompt_toolkit/styles/from_dict.py", line 39, in _colorformat
    raise ValueError('Wrong color format %r' % text)
ValueError: Wrong color format 'ansibrightblack'
Xonsh encountered an issue during launch
Failback to /bin/sh
(xonsh) \[\e]0;\u@\h: \w\a\]\u@\h:\w$ 
```

</details>

Seems like there's something external to the environment that is affecting this, so I'm not sure about reproducibility.  

## What I have done to solve this

- I have tried xonsh versions 0.6.0 and tried upgrading to 0.9.13.  Same thing happens.
- I have tried upgrading to 2.5.2 of pygments (not sure what the older version was).
- Disabled my .xonshrc.  It's nothing in there that's affecting this.
- Completely uninstalled xonsh both via apt and pip.  Reinstalled.  Got a slightly different traceback:

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20658, in main
    return main_xonsh(args)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 20685, in main_xonsh
    shell.shell.cmdloop()
  File "/usr/lib/python3/dist-packages/xonsh/ptk/shell.py", line 153, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/usr/lib/python3/dist-packages/xonsh/ptk/shell.py", line 116, in singleline
    prompt_args['style'] = PygmentsStyle(pyghooks.xonsh_style_proxy(self.styler))
  File "/usr/lib/python3/dist-packages/xonsh/pyghooks.py", line 476, in xonsh_style_proxy
    class XonshStyleProxy(Style):
  File "/home/tylerp/.local/lib/python3.6/site-packages/pygments/style.py", line 114, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/home/tylerp/.local/lib/python3.6/site-packages/pygments/style.py", line 81, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format '#ansidarkgray'
Xonsh encountered an issue during launch
Failback to /bin/sh
```

</details>

What are some additional steps I can take to figure out what is interfering with xonsh?

**Comment by orrinjelo** [comment] 2019-12-30 19:12
After uninstalling `pygments` and reinstalling, I no longer get the traceback.  I still get:
```
<unknown>:1: DeprecationWarning: invalid escape sequence \[
```
but successfully launch into xonsh.

**Comment by bobhy** [comment] 2020-01-12 03:37
What version of prompt-toolkit do you have installed? Although you rarely update packages (and I wish I had that luxury), it might be worth updating both prompt-toolkit and Pygmentsto latest and greatest.  FWIW,  prompt-toolkit 3.0.2 and Pygments 2.5.2 are working OK for me.

**Comment by orrinjelo** [comment] 2020-01-13 17:10
It looks like I have 1.0.15 installed.  I'll try updating that and seeing if that works.

**Comment by orrinjelo** [comment] 2020-01-14 17:04
Updated prompt-toolkit and pygments to their latest versions (3.0.2 and 2.5.2 respectively), and this still hasn't got rid of the DeprecationWarning.  It has also made my $BOTTOM_TOOLBAR have coloured backgrounds instead of coloured text, even with trying to force it differently with {BACKGROUND_BLACK}.

**Comment by orrinjelo** [comment] 2020-01-14 18:31
Note: It would seem the inverted background may be related to if not https://github.com/santagada/xontrib-powerline/issues/18, which I can workaround with `$PTK_STYLE_OVERRIDES['bottom-toolbar'] = 'noreverse'`.

**Comment by anki-code** [comment] 2020-10-07 10:35
@cafehaine Please take a look at this issue. I tried to use `RESET` to check that this issue solved but still got backgrounds:

```
pip install -U git+https://github.com/xonsh/xonsh
$BOTTOM_TOOLBAR = '{#FF007F}{env_name:{} }{#FF4500}{user}{#baddad}@{#FFDEAD}{hostname}{RESET}{retstr} -\
 {BOLD_WHITE}Memory: {usedmemcolor}{usedmem}{RESET} ({usedmemcolor}{usedmempc}%{RESET}) / {BOLD_WHITE}{totmem}{RESET} -\
 {BOLD_WHITE}CPU: {cpucolor}{cpu}%{RESET} -\
 {BOLD_WHITE}Disk: {diskcolor}{diskpc}%{RESET} -\
 {datum}'
```
And:
![Screenshot_20201007_133504](https://user-images.githubusercontent.com/1708680/95320279-f0582f00-08a1-11eb-9f48-295be1b4397c.png)

**Comment by cafehaine** [comment] 2020-10-07 10:37
@anki-code it should be solved by my last PR #3847

**Comment by anki-code** [comment] 2020-10-07 10:39
@cafehaine I've made `pip install -U git+https://github.com/cafehaine/xonsh` but get the same result.

**Comment by cafehaine** [comment] 2020-10-07 10:39
oh wait, I didn't look close enough, does it happen with the readline backend ?

**Comment by anki-code** [comment] 2020-10-07 10:40
No, In the `readline` there is no BOTTOM_TOOLBAR )

**Comment by cafehaine** [comment] 2020-10-07 10:41
alright, I'll try to look into it, but that kinda confirms what I thought, the PTK backend will probably need to be rewritten, at least the color handling part

**Comment by anki-code** [comment] 2020-10-07 10:42
Meanwhile @orrinjelo could you please check that the problem is actual to you? I see xonsh 0.6.0 in the first message but now we have xonsh 0.9.22 :)

**Comment by cafehaine** [comment] 2020-10-07 10:47
@anki-code from what I can see, the reversed color is the intended behaviour, and can be changed with `$PTK_STYLE_OVERRIDES['bottom-toolbar'] = 'noreverse'` as mentioned above. The `noreverse` could maybe be set as the default, but it's mostly a preference issue.

I however can't reproduce the deprecation warning, so this issue is probably no longer relevent.

**Comment by anki-code** [comment] 2020-10-07 10:51
Ah, really, the toolbar reversed by default but I'm just interesting why the color of background is black?

![Screenshot_20201007_135100](https://user-images.githubusercontent.com/1708680/95321766-2a2a3500-08a4-11eb-96e3-aa56a6bb6a4b.png)

**Comment by cafehaine** [comment] 2020-10-07 10:56
Since technically there is no color, and the "reverse" effect is probably implemented in PTK, PTK doesn't know how to reverse "nothing"

Not sure how it could be fixed, except by rewriting the color handling

**Comment by anki-code** [comment] 2020-10-07 11:02
@cafehaine thanks!

Meanwhile @orrinjelo could you please check that the issue is actual to you? I see xonsh 0.6.0 in the first message but now we have xonsh 0.9.22 :) 
As I understand there is two issues: about DeprecationWarning and about colors. The first issue should gone after xonsh update and I think this thread could be closed. 
The second issue is around colors and should be created.

**Comment by orrinjelo** [comment] 2020-10-16 20:09
```
<unknown>:1: DeprecationWarning: invalid escape sequence \[
[13:49:44] orrinjelo ~/git/project/build (Radar_3.7.0|+3⚑7)$ python3 -m pip freeze
...
prompt-toolkit==3.0.8
...
xonsh==0.9.23
...
[13:50:01] orrinjelo ~/git/project/build (Radar_3.7.0|+3⚑7)$

```
I've installed the latest. Still not sure what the deal with the invalid escape sequence.  I think I am even on a different laptop now, running 18.04 Ubuntu.  

I try again with `$PTK_STYLE_OVERRIDES['bottom-toolbar'] = 'noreverse'` disabled:
![Screenshot from 2020-10-16 14-08-04](https://user-images.githubusercontent.com/12236285/96304315-1f188880-0fb9-11eb-8e32-d6ff3a0a2179.png)

**Comment by anki-code** [comment] 2021-05-12 21:45
I'm going to close this issue because I can't repeat this on Ubuntu 20.04 with `xonsh --no-rc`.

**Closed by anki-code** 2021-05-12 21:45 UTC
Labels: prompt-toolkit
