### ISSUE TITLE
AssertionError typing a command while xonsh still initialising

### ISSUE THREAD

**Issue by jonathanhogg** [xonsh/xonsh#2339] opened 2017-03-23 11:53 UTC
It's not a big deal, but often if I start typing a command while `xonsh` is still loading – which is pretty common as I tend to open a new terminal window and immediately start typing a command – then I get (some variant of) the following:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916
    self.run()
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/history.py", line 62, in run
    buf.reset(initial_document=buf.document)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 451, in document
    self.text, self.cursor_position, self.selection_state]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/document.py", line 89, in __init__
    'cursor_position=%r, len_text=%r' % (cursor_position, len(text)))
AssertionError: cursor_position=3, len_text=2

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 164, in run
    t()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 333, in redraw
    self._redraw()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 177, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_chil
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 128, in <listcomp>
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/controls.py", line 616, in create_content
    document = buffer.document
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 451, in document
    self.text, self.cursor_position, self.selection_state]                                                              
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/document.py", line 89, in __init__
    'cursor_position=%r, len_text=%r' % (cursor_position, len(text)))
AssertionError: cursor_position=3, len_text=2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 109, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 425, in run
    self._redraw()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 358, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 177, in <listcomp>
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_chil
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 128, in <listcomp>
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/containers.py", line 1000, in preferred_height
    cli, width - total_margin_width, max_available_height, wrap_lines),
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/controls.py", line 502, in preferred_height
    content = self.create_content(cli, width, None)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/layout/controls.py", line 616, in create_content
    document = buffer.document
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 451, in document
    self.text, self.cursor_position, self.selection_state]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/document.py", line 89, in __init__
    'cursor_position=%r, len_text=%r' % (cursor_position, len(text)))
AssertionError: cursor_position=3, len_text=2
```

It doesn't seem to actually break anything, but it is a bit of a pain having the terminal window immediately fill with text. The error appears to be very timing-specific as I can't reliably reproduce it. Looks like this is happening deep inside `prompt_toolkit`, so I'm not sure if there's anything you can do about it.

This is with 0.5.9 on macOS 10.12.3, but I think it's always done it as long as I've been using it.

**Comment by gforsyth** [comment] 2017-03-23 15:59
Thanks for reporting @jonathanhogg! I've also seen this off-and-on for a little while now but never came up with a way to reproduce it reliably. 

I think it's probably due to how we reset the buffer after we finish loading in order to _capture_ text that was previously just lost (if you typed it in while xonsh is still loading up). 

Yeah, it's annoying. Not sure how we might go about fixing it but it's possible @jonathanslenders might have some ideas?

**Comment by stilllman** [comment] 2017-06-14 09:34
Same issue here, I have a 100% repro, each time I open a new terminal and start typing. If you have a correction that you want to test at some point, feel free to ping me (though I never installed xonsh from the github repo).

**Comment by jonathanslenders** [comment] 2017-06-14 20:44
Sorry for the late reply.

Rather than raising an exception, we could make sure that the cursor position in the ``prompt_toolkit.document.Document`` class ensures that the cursor is always in range.

Could you try to change this file in prompt_toolkit? Something like this:
```python
def __init__(self, text='', cursor_position=None, selection=None):
    if cursor_position > len(text):
        cursor_position = len(text)
```

That should prevent this error. But the bug should be elsewhere, earlier, so I'm curious what would happen if you change that. There is something going on that causes the ``prompt_toolkit.buffer.Buffer`` class to be inconsistent.

I also wonder whether Xonsh manipulates the ``Buffer`` class somehow without going through its ``cursor_position`` or ``text`` properties. There are assertions everywhere that should prevent this from happening.

If somehow you're able to log all methods of ``prompt_toolkit.buffer.Buffer`` to a file, that could help as well. I guess that some interaction is done, before you start typing, but I'm not sure what.

**Comment by stilllman** [comment] 2017-06-20 08:48
@jonathanslenders I tried changing the document.py file in prompt_toolkit to clamp the cursor_position. I no longer have a crash, but the cursor keeps coming back to the beginning of the line, erasing the characters I just typed, until xonsh is initialized.

**Comment by bartwojcik** [comment] 2017-07-24 16:52
The most annoying bug in xonsh/prompt_toolkit currently - that is the only thing reminding me that I am using relatively new software.

**Comment by scopatz** [comment] 2017-07-25 18:26
@jonathanslenders I don't think that we are manipulating Buffer in any way.  

I guess my main question right now is if this is a prompt-toolkit bug or a xonsh bug? 

I have never seen this bug personally, so I am not sure how much help I can be in fixing it.  Is there a way to consistently reproduce this?

**Comment by scopatz** [comment] 2017-07-25 18:27
I am happy to review a PR that fixes it, of course :smile:

**Comment by jonathanslenders** [comment] 2017-07-25 21:14
So far, I have not come across any other prompt_toolkit application which had this issue...

I'll see if I find some time to go through the buffer.py source code and add some additional exceptions to help discover the bug. I still think it's not necessary in prompt_toolkit, but I'm not sure.

**Comment by jonathanhogg** [comment] 2017-07-26 11:21
I've actually not seen this problem for a little while, so I just spent a few minutes repeatedly opening **Terminal.app** windows/tabs and typing into them. It took me a fair few goes, but I managed to trigger the exception – it looks to be exactly the same traceback, so I'll not bother including it in here again.

The important numbers are:

```
resistance$ import xonsh
resistance$ xonsh.__version__
'0.5.12'
resistance$ import prompt_toolkit
resistance$ prompt_toolkit.__version__
'1.0.14'
resistance$ import sys
resistance$ sys.version
'3.6.2 (default, Jul 17 2017, 16:44:45) \n[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]'
```

These are as installed with `brew` and `pip`.

I'm happy to test fixes, but reliably reproducing is another matter!

**Comment by jonathanhogg** [comment] 2017-07-26 11:24
Actually, possibly of note, the assertion error was again exactly off-by-one:

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, 
    self.run()
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/history.py", line 62, in run
    buf.reset(initial_document=buf.document)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 452, in document
    self.text, self.cursor_position, self.selection_state]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/document.py", line 89, in __init__
    'cursor_position=%r, len_text=%r' % (cursor_position, len(text)))
AssertionError: cursor_position=11, len_text=10
```

**Comment by scopatz** [comment] 2017-07-26 22:16
That is a nice observation @jonathanhogg!

**Comment by jonathanhogg** [comment] 2017-07-29 13:40
Interestingly, I just got another exception when opening a new terminal, but here I started typing *after* the prompt had appeared (full traceback elided):

```
resistance$ cdxonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, 
    self.run()
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/history.py", line 62, in run
    buf.reset(initial_document=buf.document)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 452, in document
    self.text, self.cursor_position, self.selection_state]
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/cache.py", line 90, in __missing__
    result = self.get_value(*key)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/document.py", line 89, in __init__
    'cursor_position=%r, len_text=%r' % (cursor_position, len(text)))
AssertionError: cursor_position=3, len_text=2
```

You can see from the above that my prompt (`resistance$ `) had been echoed to the terminal before I started typing, but clearly I managed to type `cd` before whatever thread is blowing up here was ready. It's possible that it blew up as I hit the spacebar, but I can't remember whether I had gotten that far when it exploded.

Not visible in this excerpt is the fact that the prompt and the `cd` are both colourised correctly (blue for my prompt and green for the recognised command).

Perhaps this will help narrow down the window of what is going wrong.

**Comment by jonathanslenders** [comment] 2017-07-29 14:40
That is helpful, actually. I didn't realize that we're calling ``Buffer.reset`` in another thread.
This function is not thread safe, just like most prompt_toolkit functions.

It looks like ``buf.reset()`` is possibly called many times over here: https://github.com/xonsh/xonsh/blob/5cb3e8dd5545a7448b2a393379e3405c1942d1e0/xonsh/ptk/history.py#L62
The right way to call it in a thread safe way, is by using ``cli.eventloop.call_from_executor(...)``, this will schedule it in the event loop in the main thread.

But I wonder actually why loading the history needs to be asynchronous. It should be really huge before somebody would notice a delay. Is the history stored in a database? Let me know.

**Comment by stilllman** [comment] 2017-08-16 08:51
@jonathanslenders I tried commenting the call to `buf.reset` and I no longer have the assertion error (I'm not sure how my history is impacted though). So it seems this call is indeed the cause of the issue. If that may help, I also noticed that the text variable in `Document.__init__` was sometimes completely unrelated to what I had typed, and instead contained what I think is some old history entry, so the data race hypothesis seems very much plausible.

**Comment by mitnk** [comment] 2017-08-25 12:54
One of my colleagues using xonsh also encounter this issue recently (while I cannot). It happens in almost every new opened terminal tap.

Like @stilllman has said, [this patch](https://github.com/xonsh/xonsh/compare/master...mitnk:hist-thread?expand=1) can fix this issue. So the question here is what is the reason to call `reset()` on PTK's `buffer`? Could we remove it since it's not thread-safe? I didn't find any impact on history loading after this too.

Another thing I noticed the load histories (in a thread) is quite slow, when there are 10k history items, it takes 15s to finish with sqlite history backend (should be longer with JSON backend).

**Comment by qwenger** [comment] 2020-02-19 21:22
Hi,

This bug started appearing for me just a couple weeks ago on ArchLinux.

**Comment by astronouth7303** [comment] 2020-02-19 22:00
That's odd. I do this occasionally and don't get any errors.

**Comment by jonathanhogg** [comment] 2020-02-20 10:59
Odd. I haven't seen this problem in ages now. Had been meaning to close this issue in fact…

**Comment by qwenger** [comment] 2020-02-20 14:18
Actually my traceback is not exactly the same:

```
Unhandled exception in event loop:
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/utils.py", line 70, in schedule
    func()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 455, in redraw
    self._redraw()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 522, in _redraw
    self.context.run(run_in_context)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 508, in run_in_context
    self.renderer.render(self, self.layout)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 568, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 792, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 2595, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1620, in preferred_height
    return self._merge_dimensions(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1648, in _merge_dimensions
    preferred = get_preferred()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1613, in preferred_content_height
    return self.content.preferred_height(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 639, in preferred_height
    content = self.create_content(width, height=1)  # Pass a dummy '1' as height.
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 761, in create_content
    document = buffer.document
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 524, in document
    return self._document_cache[
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/cache.py", line 98, in __missing__
    result = self.get_value(*key)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/document.py", line 98, in __init__
    assert cursor_position is None or cursor_position <= len(text), AssertionError(

Exception cursor_position=1, len_text=0
Press ENTER to continue...     
```

My prompt is not visible, but it did appear shortly before the traceback hid it.

Pressing ENTER just reprints the same message again.

**Comment by gforsyth** [comment] 2020-02-20 16:28
Ahh, @qwenger , I believe that issue is because we do not yet support prompt_toolkit>=3 -- if you downgrade to a 2.x version of prompt_toolkit you should be good.

@jonathanhogg -- are we good to close this issue?

**Comment by jonathanhogg** [comment] 2020-02-20 16:35
@gforsyth yes, please do

**Comment by gforsyth** [comment] 2020-02-20 16:47
@qwenger -- if downgrading doesn't fix your issue, please open a new issue so we can figure that problem out.

Thanks, both!

**Closed by gforsyth** 2020-02-20 16:47 UTC
Labels: bug

**Comment by qwenger** [comment] 2020-02-20 17:30
Ok, done, i'll see if the error comes again. PTK is very probably the cause, as ArchLinux updated it recently to 3.0.x and the bug appeared after updating my OS.

However: I get both PTK and xonsh from my distro's package manager, so it should not be my responsibility to downgrade versions.
- I'll notify the package maintainer on the Arch end.
- Did you explicitly specify that PTK>=3 is not supported?

Is supporting PTK3 already on the schedule?

**Comment by qwenger** [comment] 2020-02-20 17:41
See https://bugs.archlinux.org/task/65574.

**Comment by gforsyth** [comment] 2020-02-20 19:37
> * Did you explicitly specify that PTK>=3 is not supported?

No, it didn't even exist when we cut our last release

> Is supporting PTK3 already on the schedule?

It's on there, unsure when that will happen, though.

**Comment by qwenger** [comment] 2020-02-20 23:56
Thanks.

**Comment by qwenger** [comment] 2020-05-18 14:33
So, now that 0.9.18 is out and claims to support PTK3, I upgraded both... and the error is back:

```
Unhandled exception in event loop:
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/utils.py", line 72, in schedule
    func()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 456, in redraw
    self._redraw()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 523, in _redraw
    self.context.run(run_in_context)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 509, in run_in_context
    self.renderer.render(self, self.layout)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 598, in render
    layout.container.write_to_screen(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 381, in write_to_screen
    sizes = self._divide_heights(write_position)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 435, in _divide_heights
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 435, in <listcomp>
    dimensions = [c.preferred_height(width, height) for c in self._all_children]
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 792, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 324, in preferred_height
    dimensions = [
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 325, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 2595, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1620, in preferred_height
    return self._merge_dimensions(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1648, in _merge_dimensions
    preferred = get_preferred()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/containers.py", line 1613, in preferred_content_height
    return self.content.preferred_height(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 639, in preferred_height
    content = self.create_content(width, height=1)  # Pass a dummy '1' as height.
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/layout/controls.py", line 761, in create_content
    document = buffer.document
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 524, in document
    return self._document_cache[
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/cache.py", line 98, in __missing__
    result = self.get_value(*key)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/document.py", line 98, in __init__
    assert cursor_position is None or cursor_position <= len(text), AssertionError(

Exception cursor_position=2, len_text=1
Press ENTER to continue... 
```

This only (and not always) happens when first typing in a freshly opened terminal, sometimes even when I wait for several seconds before typing in. It often doesn't happen directly, but after typing in a couple characters.
For reference, I use xonsh in xfce4-terminal in qtile.
