### ISSUE TITLE
Command output incomplete

### ISSUE THREAD

**Issue by arkhan** [xonsh/xonsh#3289] opened 2019-08-27 23:59 UTC
sometimes the exits of the commands or password request do not appear as they should, attached an image in this case of pacman's confirmation to update some packages.

![img-2019-08-27-185435](https://user-images.githubusercontent.com/3141865/63816120-99410600-c8fc-11e9-85a7-8a3a831a7838.png)

![img-2019-08-27-193410](https://user-images.githubusercontent.com/3141865/63817401-c7751480-c901-11e9-8d53-e980b41f4c8f.png)

## xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.11          |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | ignore          |
+------------------+-----------------+

```

Thanks

**Comment by gforsyth** [comment] 2019-08-31 02:01
Hey @arkhan -- thanks for reporting!  I believe this is a duplicate of #2129, which is a long-standing and complicated issue.  If you look at your first screenshot, I believe the command is not _incomplete_ it's just not ordered in the usual way you expect.  

Note that the prompt to continue installation is there, but it's above the list of packages to be installed (this is obviously an unexpected result).

**Closed** 2021-02-13 16:56 UTC
Labels: duplicate
