### ISSUE TITLE
Interrupted system call in clients

### ISSUE THREAD

**Issue by daym** [xonsh/xonsh#2160] opened 2017-02-06 09:36 UTC
When I use xonsh 0.5.3 I get interrupted system call really really often.

To reproduce, run xterm -e xonsh, then maximize the xterm window (that's important) and then run top.

top will fail (!).

top: failed tty set: Interrupted system call

I've also had similar problems with guix environment, ssh sessions etcetc. But the above is an easy way to reproduce the problem.

**Comment by scopatz** [comment] 2017-02-06 16:02
Hii @daym, thanks for reporting. It seems like this is a duplicate of an issue that was fixed in #2158. Would you mind trying out current master and seeing if that works for you? Also, could you please post the output of the `xonfig` command and the contents of your xonshrc.

**Comment by daym** [comment] 2017-02-06 16:21
Yeah, seems to work now.

**Comment by scopatz** [comment] 2017-02-06 16:27
OK great! Feel free to close this then.

**Comment by daym** [comment] 2017-03-02 20:28
But doesn't work with 0.5.5.

**Comment by gforsyth** [comment] 2017-03-02 20:29
Hi @daym -- can you try upgrading to 0.5.7 and see if the issue persists there?  Thanks!

**Comment by daym** [comment] 2017-03-02 20:45
Yes, I tried it now. Doesn't work (same as before).

**Comment by scopatz** [comment] 2017-03-03 03:07
What you mean by "top fails" @daym? Can you provide a traceback or an asciinema or a video?

**Comment by daym** [comment] 2017-03-03 07:12
I mean top just says "Interrupted system call" and then dies. 

I'll check how to provide asciinema or a video.

**Comment by scopatz** [comment] 2017-03-03 07:20
Thanks! I really appreciate it!

**Comment by gforsyth** [comment] 2019-07-14 20:58
I believe this has been fixed.

**Closed by gforsyth** 2019-07-14 20:58 UTC
