### ISSUE TITLE
[alt-.] gives last word of last line, but including dangerous redirection.

### ISSUE THREAD

**Issue by alekibango** [xonsh/xonsh#2580] opened 2018-01-26 12:36 UTC
example of me working:
```
# command_that_takes_ages | sort -n  >sorted_ids
# less  [alt-.]
```
this completes to:
```
# less  >sorted_ids
```

if i press [enter] without deleting this '>', my data gets lost. and believe me, it happened to me few times already. I am just too used to bash, which removes redirection in front of last word before completing the line for me. The same in bash results into:
```
# less sorted_ids
```

**Comment by gforsyth** [comment] 2018-01-30 21:34
Hey @alekibango -- thanks for reporting.  Can you please post the output of `xonfig`?

This is a function of either readline or prompt_toolkit (I think)

**Comment by alekibango** [comment] 2018-02-06 12:05
here it goes, thanks for interest :)  i am on prompt toolkit
+------------------+-----------------+
| xonsh            | 0.4.7           |
| Git SHA          | None            |
| Python           | 3.5.3           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.9           |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

**Comment by gforsyth** [comment] 2018-02-06 13:06
I don't think this is the root cause, but could you try upgrading xonsh to the latest version? (0.6.0)
And what terminal emulator are you using?

Thanks

**Comment by alekibango** [comment] 2018-02-06 18:36
My $TERM is  'xterm-256color'   and i am using xfce4-terminal.

After installing latest version in virtualenv, it suddenly started working well, but only until i noticed that it uses readline. After installing prompt_toolkit, the bug is there again.

after few minutes of lurking around, i found probable source of my problem in 
`prompt_toolkit/buffer.py`, in definition of function `yank_nth_arg`.
my fast fix:
```diff
         # Insert new argument.
         if state.previous_inserted_word:
             self.delete_before_cursor(len(state.previous_inserted_word))
+        if word.startswith('>'):
+            word = word[1:]
         self.insert_text(word)
```
if you agree with me that this should be fixed in prompt_toolking, i will bring my issue there.

**Comment by gforsyth** [comment] 2018-02-06 18:44
Hey @alekibango -- awesome!  Nice work tracking that down. 
Definitely raise an issue with prompt_toolkit, although it's probably worth checking the dev branch.  @jonathanslenders has been working on version 2.0 for a while now and it's possible this is already fixed upstream.  But I am going to close this for now as an upstream issue. 

Thanks again!

**Closed by gforsyth** 2018-02-06 18:44 UTC

**Comment by jonathanslenders** [comment] 2018-02-07 07:42
Hi @alekibango, @gforsyth,

This is not yet fixed in prompt_toolkit, I was not aware of this issue.
Be careful, your fix doesn't work yet if ``>`` appears in the middle, without surrounding spaces. E.g, if you have ``echo test>hello``. In this case, ``M-.`` will then take ``test>hello``. We have the same issue with ``<``.

I noticed that this is implemented in readline, not in Bash, because in the python shell we have the same behavior.

I think the right way to solve  this is by checking whether the last item from ``_QUOTED_WORDS_RE.split()`` doesn't start with quotes. If not, then split on ``<`` and ``>`` characters, and take the last item from there.

Feel free to send a pull request to prompt_toolkit. Otherwise, I'll do it in the next couple of days.

**Comment by alekibango** [comment] 2018-02-07 12:51
@jonathanslenders -- thanks :)   I agree, this small patch was just a test to see if it will work.
I was reading readline sources to have similar results. The code is in  `readline/histexpand.c`, in function `history_tokenize_word` (if you are interested). 
You need to also mind  `<>`, `&>`, `2>`, `20</tmp/file`, `cat;bat`,  `ps|grep`, `<-`,

I started by writing some unittests. That was easy. Code might follow.

Question for you: would it make sense to make prompt-toolkit tokenizer (splitting words on line for history), or should i just fix the problem inside of  yank_nth_arg function? If you would like to have tokenizer, please make some placeholder for it which i can edit to work as required.

**Comment by jonathanslenders** [comment] 2018-02-07 13:20
Thanks for the reference to the readline source code!
This can be a separate function in ``buffer.py`` that takes a single string, and returns a list of strings.
The ``Buffer`` class could be made parametrizable, so that it becomes possible to change the tokenizer. Something like ``Buffer(split_args_func=default_split_args)``.

**Comment by alekibango** [comment] 2018-02-27 17:32
Please give me few more days (or even weeks), i would like to finish this one, even if my time is so limited now.
