### ISSUE TITLE
Find a way to integrate "thefuck" into xonsh

### ISSUE THREAD

**Issue by BYK** [xonsh/xonsh#928] opened 2016-05-18 20:31 UTC
We don't have to use the alias "fuck" but I think this is a neat thing to have in xonsh: https://github.com/nvbn/thefuck/

It is written in Python so shouldn't be too hard to integrate. What do you think?

**Comment by melund** [comment] 2016-05-18 21:23
It is a candidate for a built-in xontrib ;) I would use it a lot

**Comment by GuillaumeLeclerc** [comment] 2016-05-19 07:48
Id' love it

**Comment by adqm** [comment] 2016-05-19 10:37
Really cool!  I had had a similar thought recently when looking at the "suggestions" after mis-typing a command, but this seems to be much more general.

Not a big fan of the profanity, as it might turn some people off; maybe "oops" or something like that?

It also looks like it has a lot of dependencies that do similar things to what other pieces of xonsh do (e.g., colorama).  Maybe we could grab/modify [the pieces that are relevant for actually generating the suggestions](https://github.com/nvbn/thefuck/tree/master/thefuck/rules), and wrap that in a little xontrib package.

**Comment by BYK** [comment] 2016-05-19 11:00
@adqm not a fan of profanity either. How about `fixit`? Also I was able to integrate this into my workflow quite easily: `pip install thefuck` and then add the following to the RC file:

```py
# thefuck
$THEFUCK_REQUIRE_CONFIRMATION='false'
$THEFUCK_ALTER_HISTORY='false'
$THEFUCK_HISTORY_LIMIT=1
aliases['fixit'] = lambda args, stdin=None: execx($(thefuck @(__xonsh_history__.inps[-1])))
```

**Comment by BYK** [comment] 2016-05-19 11:00
> Maybe we could grab/modify the pieces that are relevant for actually generating the suggestions, and wrap that in a little xontrib package.

+1k to that.

**Comment by scopatz** [comment] 2016-05-19 21:36
agree with the profanity thing.  Note that the WTFPL just leaves it as an acronym. There are creative ways to handle this. Would love to see this get in!

**Comment by laerus** [comment] 2016-09-09 15:27
closing since  #1675 has been merged.

**Closed by laerus** 2016-09-09 15:27 UTC
Labels: feature

**Comment by deeuu** [comment] 2019-03-07 20:47
The xontrib is currently broken (see [this issue](https://github.com/meatballs/xontrib-thefuck/issues/1) for some discussion).

@BYK Did you ever get the `thefuck` to work when `$THEFUCK_REQUIRE_CONFIRMATION=True` ? i.e. get the confirmation prompt to display and then execute the confirmed and corrected cmd?

I'm currently using:

```python
$THEFUCK_REQUIRE_CONFIRMATION=False
aliases['fuck'] = lambda args, stdin=None: execx($(thefuck $(history -1)))
```

**Comment by KazWolfe** [comment] 2020-04-09 19:28
@deeuu I got it working with the below snippet:

```
# fuck dev
def __fuckit(fuck_path, fuck_hist):
    p = subprocess.Popen([fuck_path, fuck_hist], stdout=subprocess.PIPE)
    out, _ = p.communicate()
    execx(out.decode('utf-8'))

aliases['fuck'] = "__fuckit($(which thefuck), $(history -1))"
```

I should probably make this a xontrib, but lazies.

**Comment by BYK** [comment] 2023-07-11 11:26
This seems to do it
```py
aliases['fuck'] = lambda args, stdin=None: execx($(thefuck @(__xonsh__.history.inps[-1])))
```
