### ISSUE TITLE
Xonsh crashes when Python code contains a typo.

### ISSUE THREAD

**Issue by xlorepdarkhelm** [xonsh/xonsh#4948] opened 2022-09-26 13:42 UTC
## xonfig

```
+------------------+--------------------------------------------------------------------+
| xonsh            | 0.13.0                                                             |
| Python           | 3.10.2                                                             |
| PLY              | 3.11                                                               |
| have readline    | True                                                               |
| prompt toolkit   | 3.0.30                                                             |
| shell type       | prompt_toolkit                                                     |
| history backend  | <class 'xontrib.history_encrypt.XontribHistoryEncrypt'>            |
| pygments         | 2.12.0                                                             |
| on posix         | True                                                               |
| on linux         | True                                                               |
| distro           | ubuntu                                                             |
| on wsl           | False                                                              |
| on darwin        | False                                                              |
| on windows       | False                                                              |
| on cygwin        | False                                                              |
| on msys2         | False                                                              |
| is superuser     | False                                                              |
| default encoding | utf-8                                                              |
| xonsh encoding   | utf-8                                                              |
| encoding errors  | surrogateescape                                                    |
| on jupyter       | True                                                               |
| jupyter kernel   | /home/darkhelm/.local/pipx/venvs/xonsh/share/jupyter/kernels/xonsh |
| xontrib 1        | gitinfo                                                            |
| xontrib 2        | pyenv                                                              |
| xontrib 3        | autovox                                                            |
| xontrib 4        | coreutils                                                          |
| xontrib 5        | jedi                                                               |
| xontrib 6        | avox                                                               |
| xontrib 7        | output_search                                                      |
| xontrib 8        | pdb                                                                |
| xontrib 9        | argcomplete                                                        |
| xontrib 10       | direnv                                                             |
| xontrib 11       | mpl                                                                |
| xontrib 12       | voxapi                                                             |
| xontrib 13       | xog                                                                |
| xontrib 14       | pipeliner                                                          |
| xontrib 15       | whole_word_jumping                                                 |
| xontrib 16       | jupyter                                                            |
| xontrib 17       | apt_tabcomplete                                                    |
| xontrib 18       | langenv_common                                                     |
| xontrib 19       | sh                                                                 |
| xontrib 20       | vox                                                                |
| xontrib 21       | readable-traceback                                                 |
| xontrib 22       | vox_tabcomplete                                                    |
| xontrib 23       | fish_completer                                                     |
| xontrib 24       | history_encrypt                                                    |
| xontrib 25       | commands                                                           |
| xontrib 26       | avox_poetry                                                        |
| RC file 1        | /home/darkhelm/.xonshrc                                            |
+------------------+--------------------------------------------------------------------+
```

<details>
Typos in Python cause catastrophic crashes.

</details>

## Expected Behavior

Nice clean traceback of error, stay in xonsh.

## Current Behavior

Xonsh crashes, drops to /bin/sh

### Traceback (if applicable)

<details>

```
$ print(pf)                                                               12:44:12
Traceback (most recent call last):
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/base_shell.py", line 391, in default
    raise exc_info[1]
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "<stdin>", line 1, in <module>
NameError: name 'pf' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/main.py", line 468, in main
    sys.exit(main_xonsh(args))
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/main.py", line 512, in main_xonsh
    shell.shell.cmdloop()
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/ptk_shell/shell.py", line 407, in cmdloop
    self.default(line, raw_line)
  File "/home/darkhelm/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/base_shell.py", line 402, in default
    print_exception(exc_info=exc_info)
TypeError: _print_exception() got an unexpected keyword argument 'exc_info'
Xonsh encountered an issue during launch
Failback to /bin/sh
$
```

</details>

## Steps to Reproduce

```
print(pf) # Without pf being defined.
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by gforsyth** [comment] 2022-09-26 14:45
Thanks for reporting @xlorepdarkhelm -- can you post the output of `xonfig`, please?

I'm assuming that you meant for the final curly-brace to be a `)`?

Either way, I can't reproduce a crash from this:
```
(base) gil@stravaig ~ 🐚  ls @(fp.name for fp in pg`*.txt` if pf.name is not in {"example.txt"}})
.........................
  File "<stdin>", line 1
    ls @(fp.name for fp in pg`*.txt` if pf.name is not in {"example.txt"}})
      ^
SyntaxError: ('code: @(',)
(base) gil@stravaig ~ 🐚  ls @(fp.name for fp in pg`*.txt` if pf.name is not in {"example.txt"})
.........................
  File "<stdin>", line 1
    ls @(fp.name for fp in pg`*.txt` if pf.name is not in {"example.txt"})
      ^
SyntaxError: ('code: @(',)
```

And if I wrap an extra set of parens around to make the comprehension work, still no crash:
```
(base) gil@stravaig ~/tmp 🐚  ls @((fp.name for fp in pg`*.tar.gz` if fp.name not in {"xonsh-0.11.0.tar.gz"}))
v0.10.1.tar.gz  v2.3.3.tar.gz  xonsh-0.10.1.tar.gz
(base) gil@stravaig ~/tmp 🐚  ls @((fp.name for fp in pg`*.tar.gz` if pf.name not in {"xonsh-0.11.0.tar.gz"}))
NameError: name 'pf' is not defined
```

**Comment by xlorepdarkhelm** [comment] 2022-09-26 16:40
I will try and see if I can repeat the problem again, and get a better example. I also will get my xonshrc in there.

**Comment by xlorepdarkhelm** [comment] 2022-09-26 16:41
Ok, try this:

```
print(pf)
```
with that variable not being assigned/defined.

**Comment by xlorepdarkhelm** [comment] 2022-09-26 16:45
I updated the original issue with more details. Previously, I was doing that from my phone away from the computer.

**Comment by gforsyth** [comment] 2022-09-26 16:56
```
(base) gil@stravaig ~ 🐚  print(pf)
NameError: name 'pf' is not defined
```

Can you see if this happens if you start with `xonsh --no-rc` -- I suspect that one of those xontribs is causing a problem

**Comment by dyuri** [comment] 2022-09-29 11:56
@xlorepdarkhelm try updating the `readable-traceback` xontrib:
https://github.com/vaaaaanquish/xontrib-readable-traceback/issues/7

**Comment by xlorepdarkhelm** [comment] 2022-11-06 13:49
That did seem to fix it.

**Comment by gforsyth** [comment] 2022-11-07 14:07
Great.  Thanks for the assist, @dyuri!

Closing this out.

**Closed by gforsyth** 2022-11-07 14:07 UTC
Labels: to-close-in-the-future
