### ISSUE TITLE
Slowdown on windows

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1286] opened 2016-06-19 20:56 UTC
The windows experience have become extremely slow on master. 

This was also reported by @JohnLunzer  on #1268 

It is caused by `locate_binary()` and I believe it is a side effect of #1214. 

Here are some timings. (`ex` is a binary found at the first element of the path, and `sudo` is not on path. )

This is just before #1214 was merged in:
```
snail@sea ~ $ timeit('locate_binary("ex")',setup='from xonsh.environ import locate_binary', number=1)
0.0009769861104445
snail@sea ~ $ timeit('locate_binary("sudo")',setup='from xonsh.environ import locate_binary', number=1)
0.03263836817640353
```

I can run the same tests just after the #1214 since it broke windows builds. But here is the speed on master.

```
snail@sea ~$ timeit('locate_binary("ex")',setup='from xonsh.environ import locate_binary', number=1)
0.0036606361906024176
snail@sea ~$ timeit('locate_binary("sudo")',setup='from xonsh.environ import locate_binary', number=1)
0.4961102283689911
```
Half a second if it doesn't find the binary :sob: 

I chose `sudo` as an example of a non-existing binary because xonsh looks for that when starting on Windows: 
https://github.com/xonsh/xonsh/blob/master/xonsh/aliases.py#L555
@BYK. We ought to make this lazy and maybe put the sudo stuff in a xontrib. 

I think this line is to blame for the slowdown: 
https://github.com/xonsh/xonsh/blob/ff53f02950498fcd4171deddc39c331f34ee9618/xonsh/tools.py#L488

Do anyone have a good idea to speed this up?

**Comment by scopatz** [comment] 2016-06-19 21:42
Thanks for opening this @melund, this slowdown is unacceptable

**Comment by scopatz** [comment] 2016-06-19 22:18
are you on python v3.4?

**Comment by JohnLunzer** [comment] 2016-06-19 23:35
Probably the question was aimed at @melund but when I was experiencing my original slowdowns in #1268 I was using python 3.5, I haven't been able to test the most current master since my last posting for that issue.

**Comment by scopatz** [comment] 2016-06-20 06:46
I have a partial fix on the `cc` branch, but I'll have to finish it off tomorrow.  Too sleepy right now.

**Comment by scopatz** [comment] 2016-06-20 16:25
Oh no!  I see what the problem is.  $PATHEXT is getting set to be an EnvPath, which makes no sense.

**Comment by scopatz** [comment] 2016-06-20 16:25
It is causing recursive file system lookups.

**Comment by melund** [comment] 2016-06-20 16:33
Yes. As I wrote in #1214 . We need to make it a list again and then have ensures like this 
`is_list, str_to_list, list_to_str`

**Comment by scopatz** [comment] 2016-06-20 16:47
@melund Does the order really matter? Or should PATHEXT be a set?

**Comment by melund** [comment] 2016-06-20 16:51
No the order does not matter. I can't see any reason  why it could not be  a set.

**Comment by melund** [comment] 2016-06-20 20:23
Yes. Sorry. I was clearly wrong about that.

**Comment by scopatz** [comment] 2016-06-20 20:28
No worries! We probably wanted that functionality anyway.

**Comment by BYK** [comment] 2016-06-22 17:40
Same here. My `xonsh` is almost unusable right now :(

@melund I'll try to make it lazy, thanks for bringing it up!

**Comment by BYK** [comment] 2016-06-22 17:43
@melund on second look, that is only evaluated once at startup time. Don't think we can make it lazy. :(

**Comment by melund** [comment] 2016-06-22 19:14
I think @scopatz has some good tools for doing that. Are there not some lazy object from the amalgamate PR that could be used for this?

 We want to delay everything as much as possible to get initial startup time down.

**Comment by melund** [comment] 2016-06-22 19:19
If not possible. Then we could make a xontrib. We also need some cool windows only xontribs. If it is a xontrib there is no need to check if sudo is on the path already

**Comment by scopatz** [comment] 2016-06-22 21:21
@BYK - is it slow even after #1296 was merged?

**Comment by scopatz** [comment] 2016-06-22 21:22
Also, @melund, yes, look at `xonsh.lazyasd` for some lazy attributes!

**Comment by BYK** [comment] 2016-08-18 09:50
Sorry for not responding for a while. Xonsh is quite snappy for a while now (guess it was after #1296) so closing this.

@melund reopen if that's not the case for you.

**Closed by BYK** 2016-08-18 09:50 UTC
Labels: bug
