### ISSUE TITLE
Buggy glob expansion

### ISSUE THREAD

**Issue by ghost** [xonsh/xonsh#2794] opened 2018-08-27 17:21 UTC
Run these command:

    cd /tmp
    touch abc

and then type `ls a*` and hit tab. The glob expands to `ls a*abc`.

## xonfig
    +------------------+----------------------+
    | xonsh            | 0.7.6.dev5           |
    | Git SHA          | 837c714a             |
    | Commit Date      | Aug 25 18:35:16 2018 |
    | Python           | 3.7.0                |
    | PLY              | 3.9                  |
    | have readline    | True                 |
    | prompt toolkit   | 1.0.15               |
    | shell type       | prompt_toolkit1      |
    | pygments         | 2.2.0                |
    | on posix         | True                 |
    | on linux         | True                 |
    | distro           | arch                 |
    | on darwin        | False                |
    | on windows       | False                |
    | on cygwin        | False                |
    | on msys2         | False                |
    | is superuser     | False                |
    | default encoding | utf-8                |
    | xonsh encoding   | utf-8                |
    | encoding errors  | surrogateescape      |
    +------------------+----------------------+

**Comment by scopatz** [comment] 2018-08-27 19:57
Thanks for reporting @gsaga! I can reproduce this...

**Comment by alex-bender** [comment] 2018-09-19 11:16
@scopatz Could you please suggest where to look for the beginning to fix that?

**Comment by scopatz** [comment] 2018-09-20 23:05
@alex-bender - I am only seeing this under prompt-toolkit, and not under readline. So the right place to implement the fix for this is probable in [`xonsh/ptk2/completer.py`](https://github.com/xonsh/xonsh/blob/master/xonsh/ptk2/completer.py).  A backported fix to PTK v1 would also be welcome.

**Comment by scopatz** [comment] 2018-09-20 23:05
Any help here is most appreciated!

**Comment by jmcrawford45** [comment] 2018-09-29 22:01
This is an issue with how [https://github.com/xonsh/py-bash-completion/blob/master/bash_completion.py#L349](py-bash-completion) determines the replaceable length. It assumes that the `prefix` arg is a prefix of the common prefix of the completions (which is not the case here since `'/tmp/abc'.startswith('/tmp/a*')` is False).  Replacing the linked line with `if commprefix[strip_len] == strip_prefix[strip_len]:` upstream fixes this issue and other similar glob expansion bugs (e.g. `ls /tmp/[a]*`).

**Comment by scopatz** [comment] 2018-10-02 00:55
Potential fix in #2851

**Comment by gforsyth** [comment] 2018-10-02 12:58
It looks like #2851 fixed this on master

**Comment by anki-code** [comment] 2020-10-07 20:12
Looks like not actual and should be closed.

**Closed** 2020-10-07 20:42 UTC
Labels: bug
