### ISSUE TITLE
sequence of command that crash Xonsh

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#1012] opened 2016-05-25 19:59 UTC
So this is a weird one, that need many step, and I have issues to get a minimal example.

I'll past the full reproducible case in a gist:

https://gist.github.com/Carreau/17593cdede95551e4a122941efdf6487

Basically from xonsh:
- `ipython > foo` , lead IPython to crash (that's an IPython ptk/bug)
-  `cat foo` , make xonsh ring the bell, as foo has some weird binary blob.
-  `cat foo` a second time send xonsh to background
-  `fg` crash xonsh. 

IPython 05280f2bb65656c45df88beca80608b3a0ef8d9d
xonsh 1a698ce7ac492863ad0d99c6e011d9eab98ec022
prompt_toolkit 121195f1b11a381c279d8f59353918c2afa4889c

Note that if you exit xonsh, and restart a new xonsh in between any of above step, all is fine. 
If you create `foo` (with the same bytes) differently, it does not crash....

Weird one...

**Comment by scopatz** [comment] 2016-05-25 22:17
Hi @Carreau - thanks for reporting! This is a weird one.  I installed the hashes that you mention for these three projects and I can reproduce the ipython/ptk crash.  However, no matter how many times I cat foo, nothing changes, I don't hear the bell, and it doesn't go into the background.  The file is simply displayed to the screen as normal.  This was on linux, of course.  Maybe there is something strange about Mac's cat?  This is another thing that xoreutils would potentially fix, though :)

**Comment by Carreau** [comment] 2016-05-25 22:27
> Maybe there is something strange about Mac's cat? This is another thing that xoreutils would potentially fix, though :)

Ha !

Indeed, `brew install coreutils` and using `gcat` instead of  I cannot get the above behavior ! 

So now I need to figure out what macos `cat` does... 

(sidenote, I can reproduce the bug on terminal emulators other than iterm2, and I see a `^[[46;1R` before each prompt)

**Comment by scopatz** [comment] 2016-05-26 00:56
Good to know, also, `^[[46;1R` seems to indicate that the cursor is on line 46 column 1  http://bluesock.org/~willg/dev/ansi.html

**Comment by Carreau** [comment] 2016-05-27 20:26
more info, as now I enabled showing traceback.
Slightly different case though, but still triggered by `cat`

```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/base_shell.py", line 154, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/built_ins.py", line 671, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/built_ins.py", line 573, in run_subproc
    wait_for_active_job()
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/jobs.py", line 117, in wait_for_active_job
    _continue(active_task)
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/jobs.py", line 58, in _continue
    _send_signal(job, signal.SIGCONT)
  File "/Users/bussonniermatthias/dev/xonsh/xonsh/jobs.py", line 64, in _send_signal
    os.killpg(job['pgrp'], signal)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by scopatz** [comment] 2016-05-28 05:53
Weird, I wonder what signal it is sending....

**Comment by Carreau** [comment] 2016-06-03 22:01
So I'm leaning toward a **python** bug, I replaced `os.killpg(job['pgrp'], signal)` as I've been working for a couple of hours with the following patch:

```
diff --git a/xonsh/jobs.py b/xonsh/jobs.py
index 9255215..36f109b 100644
--- a/xonsh/jobs.py
+++ b/xonsh/jobs.py
@@ -63,3 +63,5 @@ else:
     def _send_signal(job, signal):
-        os.killpg(job['pgrp'], signal)
+        for pid in job['pids']:
+            os.kill(pid, signal)
```

And have not experienced any crash, while usually I get a similar tracback and xonsh failure every now and then. 

I just get a few now and then: `cat: stdin: Interrupted system call` or similar (sometime ls instead of cat, somethime cd)` but at least I'm not loosing my work. 

wrapping  in a `try/except PermissionError` the `os.killpg` does **not** work.

**Comment by scopatz** [comment] 2016-06-03 22:20
Thanks for the footwork here.  would you mind putting in a PR for this change.  I think that @asmeurer was also experiencing this issue. So if this fixes it for him, we know we have a winner.

**Comment by Carreau** [comment] 2016-06-03 22:37
I'll play a bit longer with it, just to be sure. But yes, will send a PR later if it proves effective.

**Comment by adqm** [comment] 2016-06-03 22:40
That said, there was a reason we moved to killpg (see [this comment](https://github.com/scopatz/xonsh/pull/867#issuecomment-220414815) and related discussion in #867).  Maybe the "right" thing is to try killing the process group first, and then fall back to trying to kill the individual processes?

**Comment by scopatz** [comment] 2016-06-03 22:42
Additionally, this seems to only occur on Macs. So this may be another platform distinction we need to make for job control.

**Comment by Carreau** [comment] 2016-06-03 22:47
> Maybe the "right" thing is to try killing the process group first, and then fall back to trying to kill the individual processes?

can't do that. Trying to kill the group literally kill the python process, and there is no way to catch it.

**Comment by adqm** [comment] 2016-06-03 22:51
> Additionally, this seems to only occur on Macs.

Ah, yes; then I would bet this is related to #1051.  Something weird about process group management on OSX seems likely.

> Trying to kill the group literally kill the python process, and there is no way to catch it. 

Oh, really?  Weird.  Okay, sorry, I was misunderstanding.  I wonder if somehow the new process still "attached" to the parent in some way.  This would happen if the [preexec_fn](https://github.com/scopatz/xonsh/blob/master/xonsh/built_ins.py#L527-L528) wasn't being called (or wasn't working properly), but I'm not sure how else it could happen.

**Comment by mitnk** [comment] 2016-06-04 18:08
Tried several commands, all related to access files: `touch foo` or `echo foo > foo`. If you repeat one of these commands quickly, it's not hard to reproduce the `PermissionError ` issue.

Also, a plain `try-except` on `os.killpg()` works for me as a workaround.

```
$ xonfig
+------------------+-------+
| xonsh            | 0.3.2 |
| Python           | 3.5.0 |
| PLY              | 3.7   |
| have readline    | True  |
| prompt toolkit   | None  |
| pygments         | None  |
| on posix         | True  |
| on linux         | False |
| on darwin        | True  |
| on windows       | False |
| is superuser     | False |
| default encoding | utf-8 |
+------------------+-------+
```

**Comment by scopatz** [comment] 2016-06-05 00:45
Well, I have never been able to reproduce this on linux.  If someone wants to put in a PR with this fix, that would be great! I also think we need a dev with push rights whose normal work machine is a mac.

**Comment by scopatz** [comment] 2016-06-05 00:45
If anyone is interested!

**Comment by mitnk** [comment] 2016-06-05 03:05
@scopatz I'm interested in that :)

@Carreau I tried [your patch](#issuecomment-223705309), it works for me. you can go ahead to send the PR now I think.

**Comment by scopatz** [comment] 2016-06-05 03:15
@mitnk - great! I think if you get a few pull requests in, read and abide by the developers guide (http://xon.sh/devguide.html), and help review a couple of other PRs, we'd be happy to vote on it :).  Probably the most important thing, though, is to make sure that you are friendly and kind while working on xonsh.

Any labels that have the "newcomer" tag are probably a good place to start (https://github.com/scopatz/xonsh/labels/newcomer), though you are welcome to work on anything that strikes your fancy!  You can even take some old, stalled PRs and fix them up if you want.

Thanks a million for offering to help out!  We really could use the help keeping up.

**Comment by Carreau** [comment] 2016-06-05 03:18
@mitnk I'd like to figure out in details what's happening. It's nice to see that a base `except:` works, be we should try not use that. We should at least figure out a class of exception to catch. 

Also from https://github.com/scopatz/xonsh/issues/1012#issuecomment-223711661 we can guess that removing `killpg` might also be needed on mac otherwise you'll end up with zombies process.
So it would be great to figure out **why**.

I guess we can conditionally use a loop on OS X, and maybe try to log something to a file to figureout what's happening.

so as @scopatz say, feel free to send a PR !

**Comment by mitnk** [comment] 2016-06-05 03:31
@scopatz ack, thanks!

@Carreau you're right. Let's make xonsh not crash first and keep figuring out the reasons.

**Comment by scopatz** [comment] 2016-06-05 03:36
@mitnk It really isn't as scary as I might have made it seem :). This approach is pretty normal in the Python community.

**Comment by mitnk** [comment] 2016-06-05 09:37
Found some informations [here](http://stackoverflow.com/a/12522688/665869):

> You apparently can't kill a process group that consists of zombies.
> When a process exits, it becomes a zombie until someone calls waitpid on it

and from one of its comments:

> Since zombie processes eventually become init's responsibility, 
> it's possible that if all of a process group's children are zombies
> the entire group gets owned by init, and the erstwhile grandparent
> no longer has permission to kill it.

I tested with [psutil](https://pythonhosted.org/psutil/) and the processes' status were 'zombie' when raise exceptions.

So I think use plain try-catch to bypass PermissionError exceptions, or use `os.kill()` are both safe for this issue.

Only mac got this issue.

**Comment by adqm** [comment] 2016-06-05 13:46
@mitnk, that's really good to know; thanks for looking into this!

It sounds to me like a better solution might be to try/except around the call to `killpg`, but inside the branch where we catch the `PermissionError`, call `waitpid` on the processes and then try killing the group again (and/or the individual processes in the process group).

**Comment by mitnk** [comment] 2016-06-06 05:08
@adqm From my understanding - since zombie processes will be handled by `init`, so we don't need to do any thing here. And there shouldn't be any dead zombie hanging there.

@Carreau We're merged #1106 with your solution. We can now testing it. If no more crashes, then we can close this issue I think. Thank you very much!

**Comment by jstasiak** [comment] 2016-06-10 06:37
For me if I ran ``echo $PROMPT`` right after starting ``xonsh`` it'd fail with ``PermissionError`` (I'm running OS X). After upgrading to d77d7cad24e693cc56716fcc7f53183a546276e9 (which includes #1106 I believe) I can't reproduce it anymore.

**Comment by scopatz** [comment] 2017-02-19 07:15
Is this closable at this point? A lot has been fixed and changed since this was originally filed.

**Comment by scopatz** [comment] 2017-02-20 02:19
Closing as this is likely fixed at this point. Please feel free to reopen if needed.

**Closed by scopatz** 2017-02-20 02:19 UTC
Labels: bug
