### ISSUE TITLE
Xonsh breaks ssh-copy-id

### ISSUE THREAD

**Issue by minecraft2048** [xonsh/xonsh#1302] opened 2016-06-21 00:45 UTC
I have Xonsh both on server and client as default shell, and this happens:

```
feanor@render_slave ~ $ ssh-copy-id feanor@10.42.0.1
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/feanor/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
feanor@10.42.0.1's password: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xonsh/built_ins.py", line 472, in run_subproc
    **subproc_kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1541, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'exec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 241, in main
    run_code_with_cache(args.command, shell.execer, mode='single')
  File "/usr/local/lib/python3.5/dist-packages/xonsh/codecache.py", line 182, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/codecache.py", line 57, in run_compiled_code
    func(code, glb, loc)
  File "74c9f1de0f9d47f6f60e067c2c822ae0", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/xonsh/built_ins.py", line 607, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.5/dist-packages/xonsh/built_ins.py", line 482, in run_subproc
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: exec
Did you mean one of the following?
    ex:     Command (/usr/bin/ex)
    xexec:  Alias
    xev:    Command (/usr/bin/xev)
    xgc:    Command (/usr/bin/xgc)
    jexec:  Command (/usr/bin/jexec)

No command 'exec' found, did you mean:
 Command 'pexec' from package 'pexec' (universe)
 Command 'gexec' from package 'gexec' (universe)
 Command 'kexec' from package 'kexec-tools' (main)
 Command 'jexec' from package 'openjdk-8-jre-headless' (main)
 Command 'jexec' from package 'default-jre' (main)
 Command 'jexec' from package 'openjdk-9-jre-headless' (universe)
 Command 'hexec' from package 'hexec' (universe)
feanor@render_slave ~ $ 

```

**Comment by scopatz** [comment] 2016-06-21 01:02
Thanks for reporting @minecraft2048! Are you using xonsh as your login shell? Also what is the output of the `xonfig` command for you? Does the following workaround work for you?

```
$ env SHELL=sh ssh-copy-id feanor@10.42.0.1
```

**Comment by minecraft2048** [comment] 2016-06-22 23:35
Yes, I'm using Xonsh as login shell with `chsh -s` option, and here is xonfig:

```
feanor@silmaril ~ $ xonfig
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | True           |
| on linux         | True           |
| distro           | Ubuntu         |
| on darwin        | False          |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
feanor@silmaril ~ $ 
```
Unfortunately I don't have other computer right now, so I cannot test SSH yet

**Comment by scopatz** [comment] 2016-06-23 01:26
OK.

**Comment by mitnk** [comment] 2016-06-26 05:16
I think I found the same issue. I use `MacVim` with `mvim script` on my mac. The steps reproduce the issue is:

1) open a file with mvim. e.g. `$ mvim foo`, which will open an GUI version of MacVim.
2) Change focus to MacVim, and type `Command + N` to open a new MacVim window. Which will fail, and a error message `subprocess mode: command not found: exec` would show up in the xonsh session where mvim was called in step 1.

I tried a hack way to fix it, like this:

```diff
diff --git a/xonsh/built_ins.py b/xonsh/built_ins.py
index 41dd209..0012fed 100644
--- a/xonsh/built_ins.py
+++ b/xonsh/built_ins.py
@@ -350,6 +350,11 @@ def run_subproc(cmds, captured=False):

     Lastly, the captured argument affects only the last real command.
     """
+    if cmds and cmds[0] and cmds[0][0] == 'exec':
+        print(cmds)
+        _cmds = list(cmds)
+        _cmds[0] = cmds[0][1:]
+        cmds = tuple(_cmds)
     global ENV
     background = False
     procinfo = {}
```

I'm not sure what the correct way to do it.

@minecraft2048 So, If I'm right, we could change the issue title to something like `subprocess mode: command not found: exec` would be better for future issue search.

**Comment by scopatz** [comment] 2016-06-28 04:11
Hi @mitnk, could you put in a PR for this so it can undergo a proper review, please? That would be great! Thanks!

**Comment by scopatz** [comment] 2016-08-17 01:43
Closing since #1560 has been merged.  Please feel to reopen if needed.

**Closed by scopatz** 2016-08-17 01:43 UTC
Labels: bug
