### ISSUE TITLE
CommandPipeline has 'out' attribute, but shows it as 'output'

### ISSUE THREAD

**Issue by FynnFreyer** [xonsh/xonsh#4590] opened 2021-12-08 10:39 UTC
During a quick gloss over the open issues, I have not found anything for this

## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.11.0               |
| Git SHA          | e1a64bc2             |
| Commit Date      | Nov 30 09:48:22 2021 |
| Python           | 3.9.9                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.23               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
| RC file 1        | /home/fynn/.xonshrc  |
+------------------+----------------------+

```

</details>

## Expected Behavior

`!(which cd).output` should produce the output OR the CommandPipeline returned by `!(which cd)` should denote the output attribute with `out` instead of `output`

## Current Behavior

Currently, Xonsh tells me, that I can get the output of the captured subproc by calling it's output attribute, but then it returns an empty string instead of the expected value. I like the shorthand with 'out' better btw, but this still seems like an inconsistency that should be addressed

```
fynn@desktop : ~
$> !(which cd)
CommandPipeline(
  stdin=None,
  stdout=<_io.BufferedWriter name=9>,
  stderr=<_io.TextIOWrapper name=11 mode='w' encoding='UTF-8'>,
  pid=None,
  returncode=0,
  args=['which', 'cd'],
  alias=<function which at 0x7f91f5dcdee0>,
  stdin_redirect=['<stdin>', 'r'],
  stdout_redirect=[9, 'wb'],
  stderr_redirect=[11, 'w'],
  timestamps=[1638959309.0110285, 1638959309.012964],
  executed_cmd=['cd'],
  input='',
  output='<function cd at 0x7f91f765b1f0>\n',
  errors=None
)
fynn@desktop : ~
$> !(which cd).out
'<function cd at 0x7f91f765b1f0>\n'
fynn@desktop : ~
$> !(which cd).output
''

```

### Traceback (if applicable)

<details>

```
traceback
```

</details>

## Steps to Reproduce

see the 'current behaviour' section
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by FynnFreyer** [comment] 2021-12-08 12:15
To be fair, the returned representation only really tells you, how you would instantiate the CommandPipeline object, but it still seems very misleading

**Comment by FynnFreyer** [comment] 2021-12-08 12:33
Also, after reading `help(!(which cd))` I have to concede, that this is actually properly documented behavior and makes sense. I would still say that not making the output available under `!(which cd).output` is unintuitive, but that is a design choice and not really an issue.

I won't close this issue, so someone might have another look at it, but if you decide that the current behaviour is better, then feel free to disregard and close this.

**Comment by jnoortheen** [comment] 2022-02-21 13:14
@FynnFreyer do you have any suggestions or ideas to improve the situation? we can't put out in the `repr` since it will block .

**Comment by FynnFreyer** [comment] 2022-03-09 19:05
Renaming the 'out' attribute to 'output' would probably not be feasible, because you would break a lot of other peoples code that way, but would it be possible to mirror it with a property?

Consider this for example

```python3
class Foo:
    def __init__(self):
        self.out = 'foo'

    @property
    def output(self):
        return self.out

if __name__ == '__main__':
    foo = Foo()
    print(foo.output)
```

**Comment by yaxollum** [comment] 2022-09-12 22:59
This appears to be a duplicate of #3394

**Closed by yaxollum** 2022-09-12 22:59 UTC
Labels: docs, needs-discussion
