### ISSUE TITLE
The and/or is not working in (un)captured subprocess

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4163] opened 2021-03-11 04:50 UTC
Hi! The and/or is not working in captured/uncaptured subprocess:

```python
echo 1 && echo 2
# 1
# 2

$[echo 1 && echo 2]
# SyntaxError: <xonsh-code>:1:9: ('code: and',)
```

As a workaround for simple cases:
```python
execx('echo 1 && echo 2')
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment] 2021-03-11 19:21
Duplicate of https://github.com/xonsh/xonsh/issues/4020

**Closed** 2021-03-12 04:31 UTC
Labels: bug, parser
