### ISSUE TITLE
Document usage of bash_completion with xonsh on Windows

### ISSUE THREAD

**Issue by reflog** [xonsh/xonsh#648] opened 2016-01-24 21:34 UTC
Hi and thanks for an awesome project!

One request - can we get some sort of a walkthrough for setting up bash_completion support on Windows?
I've got the bash_completion tgz and pointed xonsh with $BASH_COMPLETIONS to it - but nothing happens and I'm not sure how to debug the issue.

Thanks in advance!

**Comment by gforsyth** [comment] 2016-01-24 21:39
Hey @reflog -- not sure if/how bash completion works on Windows, but on *nix they live in a directory.  Have you extracted the `tgz` archive and tried pointing `$BASH_COMPLETIONS` to the extracted path?

**Comment by reflog** [comment] 2016-01-24 21:45
yep. that what I did. should I point to the root of bash_completion or 'completions' folder?

**Comment by gforsyth** [comment] 2016-01-24 21:48
the former and also to any specific files (e.g. `git`) that you want in the `completions` folder

**Comment by reflog** [comment] 2016-01-25 07:54
Tried both approaches. No dice. Any way to add some tracing/verbose printing to xonsh to check why the completion files are not loaded?

**Comment by scopatz** [comment] 2016-01-25 20:30
Hi @reflog, What does the following return at the command line?  This assumes you have ls installed.

```python
__xonsh_shell__.shell.completer.bash_complete('', 'ls ', 3, 3)
```

**Comment by scopatz** [comment] 2016-01-25 20:30
Or at least the completions for `ls`

**Comment by reflog** [comment] 2016-01-25 21:35
reflo@REFLOG-W10 ~ $ __xonsh_shell__.shell.completer.bash_complete('', 'ls ', 3, 3)
set()

**Comment by gforsyth** [comment] 2016-01-25 21:37
hrrrr.

@melund, @BYK do either of you have bash completion working in windows?

**Comment by scopatz** [comment] 2016-01-25 21:40
This may be a dumb question, @reflog, but do you have bash installed and is it on the PATH?  You can test this with `which bash` at the command line.  What does that give you?

**Comment by BYK** [comment] 2016-01-25 21:40
@gforsyth yeah I do. I have the following in my `.xonshrc` file:
```py
$BASH_COMPLETIONS = `~/AppData/Roaming/xonsh/completions/.*` + [
    r'C:\Progra~1\nodejs\node_modules\npm\lib\utils\completion.sh'
]
```

And `~/AppData/Roaming/xonsh/completions` has `git-completion.bash` in it, yanked off from a git installation.

**Comment by BYK** [comment] 2016-01-25 21:41
Side note: I definitely have `bash` on my `$PATH` :)

**Comment by reflog** [comment] 2016-01-25 21:45
I have the msys/git bash in the path.

**Comment by scopatz** [comment] 2016-01-25 21:49
Ok, Let's try to narrow this down a bit more.  What does `__xonsh_shell__.shell.completer.bash_complete_files` look like?  This will let us know if the initial loading is failing or if it is the actual completion that is failing.

**Comment by reflog** [comment] 2016-01-25 21:52
neat. running that command stalled xonsh and I have a nice 100% cpu eating python.exe process :)

**Comment by gforsyth** [comment] 2016-01-25 21:58
Weird.  That should just be a dictionary.  Can you paste in the lines from your `xonshrc` where you set `$BASH_COMPLETIONS`?  And also the output of `xonfig`?

**Comment by scopatz** [comment] 2016-01-25 21:59
Ahh now we are getting somewhere!  Try running:

```console
echo @(__xonsh_shell__.shell.completer.bash_complete_files) > temp.txt
```

And then give us the top few lines of the the temp.txt file.  Also, what is the result of `echo "$BASH_COMPLETIONS"`

**Comment by reflog** [comment] 2016-01-25 22:04
Bizzare. Now it does return without eating CPU.

reflo@REFLOG-W10 ~ $ __xonsh_shell__.shell.completer.bash_complete_files
{'npm': '/c/Progra~1/nodejs/node_modules/npm/lib/utils/completion.sh'}

**Comment by scopatz** [comment] 2016-01-25 22:07
OK, I think I see the potential issue.  Note this uses `/c/...` rather than `C:\\...`. Also, is this the only entry? Can you tell us what the `echo "$BASH_COMPLETIONS"` value is?

**Comment by scopatz** [comment] 2016-01-25 22:07
Also, does npm have bash completions working?

**Comment by reflog** [comment] 2016-01-25 22:11
reflo@REFLOG-W10 ~ $ echo "$BASH_COMPLETIONS"
C:\Progra~1\nodejs\node_modules\npm\lib\utils\completion.sh

and yes, npm's completion seems to work!

**Comment by gforsyth** [comment] 2016-01-25 22:22
@reflog can you post the portion of your `xonshrc` where you define `$BASH_COMPLETIONS`?

**Comment by reflog** [comment] 2016-01-26 06:19
```
$SHELL_TYPE='prompt_toolkit'
$BASH_COMPLETIONS = `~/AppData/Roaming/xonsh/completions/.*` + [
    r'C:\Progra~1\nodejs\node_modules\npm\lib\utils\completion.sh'
]
```

**Comment by scopatz** [comment] 2016-01-26 06:24
What does ``` `~/AppData/Roaming/xonsh/completions/.*` ``` evaluate to? I have a feeling that this is where the problem is coming in.  Also, what does `ls ~/AppData/Roaming/xonsh/completions/` actually display? What are the files present?

**Comment by BYK** [comment] 2016-01-26 08:00
Node/npm completion does not work on Windows since they disable it programmatically assuming Windows is weird/broken. You have to remove those lines if npm is your only problem. Git and a few others are working properly for me.

**Comment by reflog** [comment] 2016-01-26 17:52
```
reflo@REFLOG-W10 ~ $ `~/AppData/Roaming/xonsh/completions/.*`
[]
```

```
reflo@REFLOG-W10 ~ $ ls ~/AppData/Roaming/xonsh/completions/
"C:/Users/reflo/appdata/local/scoop/apps/coreutils/5.97.3/bin/ls.exe": C:\Users\reflo/AppData/Roaming/xonsh/completions/: No such file or directory
```

@BYK - npm completion is the one that actually works for me :)

**Comment by scopatz** [comment] 2016-01-26 17:59
OK, I think that this might be a [`$FORCE_POSIX_PATHS`](http://xonsh.org/envvars.html#force-posix-paths) issue, or lack of it.  Note that in the `ls` call there is `C:\Users\reflo/AppData`.  This is mixing the forward and back slashes.  Another potential problem with this is the `\r`, which if it is literally that, then we have a problem with the carriage return character.  

Basically, I think the problem must lie with `expandvars()` function here: https://github.com/scopatz/xonsh/blob/master/xonsh/tools.py#L958

**Comment by scopatz** [comment] 2016-01-26 17:59
This doesn't seem to use `FORCE_POSIX_PATH`

**Comment by scopatz** [comment] 2016-01-26 18:01
Whoops sorry, it is `expand_path()` here https://github.com/scopatz/xonsh/blob/master/xonsh/built_ins.py#L180 that does the tilde expansion and is not repecting in the force posix path.

**Comment by BYK** [comment] 2016-01-26 19:22
>Whoops sorry, it is expand_path() here https://github.com/scopatz/xonsh/blob/master/xonsh/built_ins.py#L180 that does the tilde expansion and is not respecting in the force posix path.

I think that is expected since `FORCE_POSIX_PATH` should only be a visual thing. Any directory operations in the backend should be handled by native FS path separator. If bash completions require POSIX paths, then we should do the conversion at that point.

**Comment by gforsyth** [comment] 2019-07-14 14:56
Closing in favor of meta-issue (to be opened very shortly)

**Closed by gforsyth** 2019-07-14 14:56 UTC
Labels: question
