### ISSUE TITLE
arrows not working correctly in emacs multi-term

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#1354] opened 2016-06-27 15:04 UTC
I've started using spacemacs and I'm trying to integrate `xonsh` into my workflow from within spacemacs. However when using `prompt-toolkit` and emacs' `mutli-term` (or `ansi-term`) the arrows aren't working normally. The left and right arrows is moving between words rather than characters. The up and down arrow down do anything.

When `readline` is selected manually as prompt then arrows and input work as expected.

I realize this could easily be some issue with spacemacs, but bash and zsh work out of the gate so I just wanted to be sure to cover my bases.

@jonathanslenders, I'm adding you to this on the off chance you've come across this with ptk.

Here is my xonfig:

```
+------------------+--------------------------------------+                                                                                           
| xonsh            | 0.4.2                                |                                                                                           
| Python           | 3.5.1                                |                                                                                           
| PLY              | 3.7                                  |                                                                                           
| have readline    | True                                 |                                                                                           
| prompt toolkit   | 1.0.0                                |                                                                                           
| shell type       | prompt_toolkit                       |                                                                                           
| pygments         | 2.0.2                                |                                                                                           
| on posix         | True                                 |                                                                                           
| on linux         | True                                 |                                                                                           
| distro           | Red Hat Enterprise Linux Workstation |                                                                                           
| on darwin        | False                                |                                                                                           
| on windows       | False                                |                                                                                           
| on cygwin        | False                                |                                                                                           
| is superuser     | False                                |                                                                                           
| default encoding | utf-8                                |                                                                                           
| git SHA          | None                                 |                                                                                           
+------------------+--------------------------------------+ 
```

Thanks again, if anyone knows what's going on.

**Comment by YLSL2016** [comment] 2016-06-27 15:22
It was writen by python?

**Comment by scopatz** [comment] 2016-06-27 16:02
Thanks for reporting @JohnLunzer! Just to verify, does it work as expected when you run the same from bash or zsh?

**Comment by JohnLunzer** [comment] 2016-06-27 16:30
If I run emacs from any shell and then run xonsh-with-ptk from within emacs I get the erroneous arrow behavior. If I run Emacs from any shell and then zsh/bash/xonsh-with-readline from within emacs I get normal arrow behavior. 

The erroneous combo is xonsh-with-ptk from within emacs.

**Comment by scopatz** [comment] 2016-06-27 17:22
@JohnLunzer, can you post an asciinema or something, please?  I don't use emacs and I am not 100% sure what the error is.

**Comment by scopatz** [comment] 2016-06-27 17:23
Though it sound like ctrl is being held down, for some reason.

**Comment by gforsyth** [comment] 2016-06-27 17:41
I can't reproduce this, @JohnLunzer -- if you are going to use xonsh in spacemacs, you should probably disable `VI_MODE` if it's set.  It could be that spacemacs evil mode is interfering somehow?  

If I open in spacemacs, xonsh is definitely not functioning correctly and there are all kinds of display issues, but the arrows work as I expect.

**Comment by jonathanslenders** [comment] 2016-06-27 18:12
It looks like Emacs always terminal doesn't understand application key mode: http://www.tldp.org/HOWTO/Keyboard-and-Console-HOWTO-21.html (I think almost all terminals support it.)

However, I can consider this also a bug in prompt-toolkit:
Probably, the following lines need to be fixed by removing control: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_input.py#L154:L157
I had them like this, because -- if I understand correctly -- apparently, tmux switches between application and cursor key when control has been hold.

**Comment by JohnLunzer** [comment] 2016-06-27 18:52
@gforsyth, ha! spacemacs without evil mode doesn't sound very appealing :smiling_imp:. Besides putting spacemacs into the emacs editing style does not resolve the issue.

@jonathanslenders, thanks for looking into it on your side! If you felt like you had a fix I would be willing to test it out.

**Comment by jonathanslenders** [comment] 2016-06-27 19:36
@JohnLunzer: It would be great if you could clone prompt-toolkit, checkout out the following pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/330  , install it and test it. Thanks.

**Comment by JohnLunzer** [comment] 2016-06-27 20:16
@jonathanslenders , works like a charm! Looks like `xonsh` might be viable in spac(emacs).

Let me know when you merge this into the master.

**Comment by YLSL2016** [comment] 2016-06-29 23:14
I will do my best to gain 

2016-06-30 

xjguoquanliang2015 



发件人：John Lunzer <notifications@github.com>
发送时间：2016-06-28 04:16
主题：Re: [xonsh/xonsh] arrows not working correctly in emacs multi-term (#1354)
收件人："xonsh/xonsh"<xonsh@noreply.github.com>
抄送："YLSL2016"<xjguoquanliang2015@163.com>,"Comment"<comment@noreply.github.com>

@jonathanslenders , works like a charm! Looks like xonsh might be viable in spac(emacs).
Let me know when you merge this into the master.

**Comment by scopatz** [comment] 2017-02-19 07:06
Closing as this has been merged for a while. Please feel free to reopen if needed.

**Closed by scopatz** 2017-02-19 07:06 UTC
Labels: bug
