### ISSUE TITLE
can't get negative index of string

### ISSUE THREAD

**Issue by yobleck** [xonsh/xonsh#4045] opened 2021-01-03 18:06 UTC
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.8           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | manjaro         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior

x = "hello world";
x[-1];
should return "d" 
side note: print(x[-1]); and x[int(-1)]; also fail but if index is a variable like y = -1; x[y]; it works
(works in python shell and in scripts)

## Current Behavior

returns assertion error
### Traceback (if applicable)

<details>

```
I tried debug mode but it got stuck on this line: "... Enumerated    1175 history files.istory files."
so here's the trace back in non debug mode:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xonsh/ptk_shell/shell.py", line 238, in _push
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib/python3.9/site-packages/xonsh/execer.py", line 219, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError

```

</details>

## Steps to Reproduce

1. open terminal running xonsh
2. create a variable equal to a string
3. attempt to get the last index of string

**Comment by gforsyth** [comment] 2021-01-04 17:53
I'm going to close this out as a duplicate of #4028 -- thanks for reporting @yobleck, this is an issue with the new AST changes in Python 3.9.  The current workaround is to run xonsh on Python <3.9

**Closed by gforsyth** 2021-01-04 17:53 UTC

**Comment by yobleck** [comment] 2021-01-04 22:17
> I'm going to close this out as a duplicate of #4028 -- thanks for reporting @yobleck, this is an issue with the new AST changes in Python 3.9.  The current workaround is to run xonsh on Python <3.9

Cool thanks. I really need to get better at searching for duplicates.

**Comment by gforsyth** [comment] 2021-01-05 14:27
> Cool thanks. I really need to get better at searching for duplicates.

All good -- I only remembered it because I'd just been looking at it :grin:
