### ISSUE TITLE
missing library reported on startup

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1160] opened 2016-06-07 19:33 UTC
When starting xonsh in roughly 1 in 10 cases I get this error message:

libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)

when using this .xonshrc file:

$PROMPT="> "
completer remove bash &> /dev/null

This library is installed on my system in /usr/lib/

When I remove the completer line, I haven't seen an error message.

```
> xonfig 
+------------------+----------+
| xonsh            | 0.3.2    |
| Python           | 3.4.3    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | True     |
| distro           | Fedora   |
| on darwin        | False    |
| on windows       | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+
```

**Comment by scopatz** [comment] 2016-06-07 23:23
Thanks for reporting @mburo. Do you see this if you run with prompt-toolkit?

**Comment by mburo** [comment] 2016-06-08 00:17
How to setup prompt-toolkit?

**Comment by scopatz** [comment] 2016-06-08 00:18
What package manager do you use?

**Comment by mburo** [comment] 2016-06-08 00:40
dnf. I just installed the package and was surprised that xonsh uses it automatically.

Using it doesn't change the reported behavior, though.

**Comment by scopatz** [comment] 2016-06-17 03:33
Does this still happen on the current master?

**Comment by mburo** [comment] 2016-06-17 04:01
yes.

**Comment by scopatz** [comment] 2016-06-17 04:08
hmmmm what does `ldd @$(which completer)` say?  Also where does this completer command come from? I can't find anything about it online. Is there a better error message if you remove the `&> /dev/null`

**Comment by mburo** [comment] 2016-06-17 05:27
I guess completer is a built-in xonsh command. It's run to get around a bash completer issue I reported elsewhere. &> /dev/null is used to ignore error messages when sourcing ~/.xonshrc a second time.

Anyway, without redirection I ran xonsh 30 times without error message.

With > /dev/null and &> /dev/null it takes a few trials to see it.

**Comment by scopatz** [comment] 2016-06-17 15:44
Hmm I can't reproduce this even after hundreds of time.

**Comment by mburo** [comment] 2016-06-17 16:35
Here, it happens quite often. Perhaps there is a race condition triggered by invoking the completer function. Or maybe my ~/.bashrc is read at the beginning and it somehow interferes with xonsh. We could wait investigating this until there is a way to fully separate xonsh startup from bash.

Latest test:

foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:xonsh
> 

foo6[xonsh]:xonsh
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
foo6[xonsh]:

**Comment by scopatz** [comment] 2016-06-17 16:44
Can you try the `LD_PRELOAD` trick described here: https://bugs.python.org/issue18748

That is something like:

```
$ env LD_PRELOAD=libgcc_s.so.1 xonsh
```

**Comment by mburo** [comment] 2016-06-17 16:58
seems to be a valid workaround

**Comment by scopatz** [comment] 2016-06-17 19:55
Well, maybe the best thing to do would be to add an alias for this in whatever environment you call xonsh frome?  We should add this work around to the docs too.

**Comment by mburo** [comment] 2016-06-18 00:28
Sure. It's odd, though. Makes me wonder if other built-in commands (or user scripts) can suffer from the same issue. The Python bug discussion didn't really resolve the issue. So this may be a Python upstream problem. Anyway - using LD_PRELOAD seems to work. Now I am waiting for the startup speed to improve and I am good to go using xonsh regularly :-)

**Comment by scopatz** [comment] 2016-06-19 19:45
>  So this may be a Python upstream problem. 

I think so.

> Anyway - using LD_PRELOAD seems to work.

Great! Would you mind adding some docs to the linux guide about this? I'd *really* appreciate it. It would hopefully help other people who run into this.

> Now I am waiting for the startup speed to improve and I am good to go using xonsh regularly :-)

Master is about an order of magnitude faster than v0.3.4 for startup. prompt-toolkit shell is still slower than the readline shell, but they are both pretty quick now.

**Comment by scopatz** [comment] 2017-02-17 07:23
Closing this issue, since this has made it into the docs. Please feel free to reopen if needed.

**Closed by scopatz** 2017-02-17 07:23 UTC
Labels: bug
