### ISSUE TITLE
Prompt colors are different between readline and prompt_toolkit 

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#726] opened 2016-03-08 02:27 UTC
The readline shell looks like 

<img width="143" alt="screen shot 2016-03-07 at 9 25 48 pm" src="https://cloud.githubusercontent.com/assets/71486/13590097/2e3ad716-e4ab-11e5-9ff8-4f62888ba4e4.png">

The prompt_toolkit shell looks like

<img width="157" alt="screen shot 2016-03-07 at 9 26 15 pm" src="https://cloud.githubusercontent.com/assets/71486/13590100/38003520-e4ab-11e5-9da3-c07c55d8425b.png">

I am using BOLD_CYAN (see https://github.com/asmeurer/dotfiles/blob/a55ec501eed8e99de0e2f33d0a9031fa78569539/.xonshrc#L156).  My bash prompt looks like the readline one here, and is what I want.

**Comment by scopatz** [comment] 2016-03-08 14:44
You should simply be getting whatever the terminal sets as the color for [`1;36`](https://github.com/scopatz/xonsh/blob/master/xonsh/ansi_colors.py#L413).  You can pass in a hex color code (eg `#FFFFFF`) instead of `BOLD_CYAN` if you want.  Not sure why this is that different on readline and ptk.  I am assuming that you are on master.

**Comment by asmeurer** [comment] 2016-03-08 18:33
Yep, that's what the cyan text itself is saying :)

**Comment by scopatz** [comment] 2016-03-08 18:40
What color does the following give in both Bash and xonsh?

```console
$ echo -e "\x1b[1;36mHello\x1b[0m"
```

**Comment by asmeurer** [comment] 2016-03-08 18:46
They both give the lighter blue (what I believe is the correct one). FWIW xonsh also prints the `-e` (I guess that flag is only a part of the bash builtin `echo`, not the command `echo`).

**Comment by scopatz** [comment] 2016-03-08 18:48
Hmmm xonsh does not print the `-e` for me.  You might not have echo installed.

```console
scopatz@localhost ~ $ echo -e "\x1b[1;36mHello\x1b[0m"
Hello
scopatz@localhost ~ $ which echo
/bin/echo
```

**Comment by scopatz** [comment] 2016-03-08 18:49
Ok @Carreau has implemented an `#ansicolor` fix for the ptk shell once it propagates up to a pygments release.

**Comment by asmeurer** [comment] 2016-03-08 18:49
`-e` must be a nonstandard option. `/bin/echo -e "\x1b[1;36mHello\x1b[0m"` prints `-e \x1b[1;36mHello\x1b[0m` in bash for me (also my `man echo` doesn't mention any `-e` option).

**Comment by gforsyth** [comment] 2016-03-08 19:07
For reference: OSX is following the POSIX specification listed here: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html -- specifically "Implementations shall not support any options" re: `echo`

`printf` should work cross-platform (on *nix, not windows) and correctly interpret the escape sequences.

**Comment by Carreau** [comment] 2016-03-08 21:22
It's probably possible to fix the ptk shell by providing a custom style just for it. 
The last version of prompt_toolkit does not need the latest of pygments (IIRC) to support that.

**Comment by scopatz** [comment] 2016-05-07 21:55
Is this closable?

**Comment by asmeurer** [comment] 2016-05-07 23:57
Still does it for me in xonsh master.

**Comment by melund** [comment] 2016-05-08 06:39
I am not sure it it the same issue that I see on Windows but the latest pygments (that support the #ansicolor keyword) fixes it for me. I don't know how far they are from 2.2 release..

**Comment by cryzed** [comment] 2016-06-01 18:30
I have the same issue unfortunately, running Arch Linux:

```
cryzed@arch ~ $ pacaur -Si xonsh python-pygments python-prompt_toolkit | grep Version -B 1
Name            : python-pygments
Version         : 2.1.3-1
--
Name           : xonsh
Version        : 0.3.0-1
--
Name           : python-prompt_toolkit [installed]
Version        : 1.0.0-1
```

So, I am understanding correctly that this is a Pygments issue? I am using KDE's Konsole and modifying the color scheme through it works perfectly fine without the prompt-toolkit, however the colors for my prompt look off and don't seem to change as they do without it.

**Comment by Carreau** [comment] 2016-06-01 18:42
> So, I am understanding correctly that this is a Pygments issue? I am using KDE's Konsole and modifying the color scheme through it works perfectly fine without the prompt-toolkit, however the colors for my prompt look off and don't seem to change as they do without it.

Yes, you need Pygments master. 

Basically with Pygments stable, color will be hard coded as rgb values, while with master you **can** say "the green of your terminal emulator". Which astonishingly you can do more easily when using the readline interface. You can try to install pygments master to see if it fixes things, and install it in user-space, not to overwrite the system one.

**Comment by cryzed** [comment] 2016-06-01 19:13
Awesome, that worked! I made a minimal [PKGBUILD](https://gist.github.com/cryzed/ecd0a28ada95e81918420a92e3fa0c97) for Arch Linux if anyone else is interested.

**Comment by jeremydonahue** [comment] 2016-06-10 17:56
I can also confirm that Pygments master (version 2.2?) fixes the color discrepancy. Maybe warning (or info) should be printed at startup if pygments <2.2 is installed?

**Comment by melund** [comment] 2016-06-10 18:22
I don't think it is really necessary. Most users probably wouldn't care, or bother with a special installation of pygments. Let us just hope the release a new version soon.

**Comment by scopatz** [comment] 2016-06-10 20:32
I don't think a warning is really needed either. This will go away in time after a new pygments release.

**Comment by gqmelo** [comment] 2016-06-20 18:37
I can confirm that Pygments master solve the problem for the prompt, but it does not solve it for syntax highlighting. For example, I can barely see an environment variable:

![screenshot from 2016-06-20 15-30-38](https://cloud.githubusercontent.com/assets/12578273/16206005/d8320462-36fc-11e6-8a8d-94b59e0e6444.png)

**Comment by scopatz** [comment] 2016-06-20 18:39
@gqmelo - Great! Well, please feel free to change your color style http://xon.sh/envvars.html#xonsh-color-style

**Comment by gqmelo** [comment] 2016-06-20 18:44
@scopatz Thanks, I changed it. ```native``` style seems to be fine for now, but other styles may also be "broken"

**Comment by scopatz** [comment] 2016-06-20 18:47
What do you mean by broken?

**Comment by gqmelo** [comment] 2016-06-20 19:08
Sorry, I mean that they may have use some colors that are not visible.

I would expect syntax highlighting colors to have the same behaviour as with the prompt.

So taking my screenshot as example the ```$PROMPT``` I typed would have the same color as ```~``` and ```$```.
Before updating the Pygments they had but then I could not see ```~``` and ```$```. Updating Pygments made ```BOLD_BLUE``` to be lighter and visible for the prompt (following my terminal scheme), but not for syntax highlighting.

**Comment by scopatz** [comment] 2016-06-20 19:16
Well, syntax highlighting is handled by Pygments itself and does tokenizes based on the syntax and does not use xonsh's color specification.  However, the xonsh colors try to match the palette that pygnments uses.

**Comment by scopatz** [comment] 2016-06-20 19:17
You basically have to find a color style that works for you for all of your needs.

**Comment by asmeurer** [comment] 2016-06-20 19:20
It would be nice if the default colors worked well on both white and black backgrounds. I realize that any color background is possible, but those two are the most common, at least on OS X and Linux (I don't know if PowerShell blue is also xommon on Windows).

**Comment by scopatz** [comment] 2016-06-20 19:28
My understanding is that is what the 'default' color style will get us once they release the next version of pygments. This effectively hands all color management off to the terminal emulator, which decides how to render the the foreground and background colors.

**Comment by Carreau** [comment] 2016-06-21 16:59
I'm unsure if the "default" will make complete use of the `#ansi...` things. IIRC, the completer menu for example does not. 

We can/should probably get together for all the project using PTK & Pygments for interface and syntax highlighting and make a unified theme. 

Maybe that can be a project for @ellisonbg students ?

**Comment by scopatz** [comment] 2016-06-21 17:00
+1 to that @Carreau

**Comment by santagada** [comment] 2016-07-10 21:59
still colors look different for me:
![colors](https://cloud.githubusercontent.com/assets/225897/16716335/f2e4c56c-46f9-11e6-8e9b-6bc6317d42c7.png)

(try to not look at the escape sequences also broken)

tested on both native, default and monokai styles.

**Comment by scopatz** [comment] 2016-07-12 06:33
@santagada are you using the development version of pygments?

**Comment by santagada** [comment] 2016-07-12 10:26
nope 2.1.3 here

**Comment by santagada** [comment] 2016-07-12 10:30
same colors with pygments 2.2a0 (master as of now)

**Comment by santagada** [comment] 2016-07-12 10:32
the color I see most difference is hex 333, the arrows look ok now.

**Comment by scopatz** [comment] 2016-07-12 13:24
Ahh Ok great, that is basically what I would expect. On pygments master, default colors should be the same. 

Hex colors, however, are a little different. Not all terminal emulators support ANSI hex escape sequences. To prevent errors when using readline, we downgrade hex colors to the closest 256 color. Pygments does the same thing, actually, if I recall correctly.

The problem is that for any hex color there may be many 256 Colors that are equally close. In such cases, we just have to pick one. However, it is possible that xonsh and pygments pick differently. If someone wants to modify our algorithm to always pick the same as pygments, that would be great!

**Comment by scopatz** [comment] 2017-02-05 04:26
pygments was finally released. I am closing this. Please open a new issue if it persists.

**Closed by scopatz** 2017-02-05 04:26 UTC
Labels: bug

**Comment by asmeurer** [comment] 2017-02-06 01:21
Yep, looks correct now.
