### ISSUE TITLE
xonsh script, properly setting a command line variable or a default

### ISSUE THREAD

**Issue by ahundt** [xonsh/xonsh#2521] opened 2017-11-02 18:06 UTC
I'm trying to write a simple xonsh script that sets an env variable for the program [defining the visible GPU devices](https://stackoverflow.com/questions/36668467/change-default-gpu-in-tensorflow) but lets the user change it, is `@()` the way to go? Here is what I've tried:
 
```
import sys
import os

# usage: xonsh eval_many.xsh <filename_substring_to_match> <grasp_model_string> <cuda_visible_devices>
# this xonsh shell script (https://github.com/xonsh/xonsh) i
# will run the evaluation step on a whole set of model files in a folder.
# all parameters are optional.
# cuda_visible_devices can be "0" for gpu 0, "0,1" for gpus 0 and 1, "-1" for cpu only.

model_str = ''
cuda_dev = ''

if len(sys.argv) > 1:
    matchstr = sys.argv[1]
if len(sys.argv) > 2:
    model_str = sys.argv[2]
if len(sys.argv) > 3:
    cuda_dev = sys.argv[1]

if not model_str:
    model_str = 'grasp_model_levine_2016'
if not cuda_dev:
    cuda_dev = "\"0\""

listvar = $(ls).split('\n')
for weightsfile in reversed(listvar):
    # print(weightsfile)
    if '.h5' in weightsfile and matchstr in weightsfile and 'evaluation_dataset' not in weightsfile:
        print(weightsfile)
        $[echo @(weightsfile)]
        #CUDA_VISIBLE_DEVICES="-1"
        #os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
        #$CUDA_VISIBILE_DEVICES = @(cuda_dev)
        CUDA_VISIBLE_DEVICES = @(cuda_dev)
        CUDA_VISIBLE_DEVICES="0" && python train.py --load_weights @(weightsfile) --grasp_model @(model_str)
        print('evaluation complete for: ' + weightsfile)
```

This is what works on bash/zsh, and essentially the command I'm looking to create, except I can vary the devices available, etc:
`CUDA_VISIBLE_DEVICES="0" && python train.py --load_weights myfile.h5 --grasp_model mymodel`

I'd appreciate your advice!

**Comment by astronouth7303** [comment] 2017-11-02 18:11
Try [argparse](https://docs.python.org/3/library/argparse.html), [click](http://click.pocoo.org/5/), [fire](https://github.com/google/python-fire), or one of the other argument parsers.

Environment variables can be treated like regular variables, just prefixed with `$`, eg:

```
$SPAM = "eggs"
open_canned_spam --opener=electric
```

`@()` is only necessary in commands.

**Comment by scopatz** [comment] 2017-11-09 02:07
Thanks for asking this @ahundt.  Inside of xonsh scripts there are also the environment variables `$ARGS` (which is a list of the arguments) and `$ARG<N>` (which is the nth argument).  The documentation can be found here: http://xon.sh/tutorial.html#executing-commands-and-scripts

Also, if you start doing anything mildly sophisticated, I recommend you follow @astronouth7303's advice and use a library :).

**Comment by ahundt** [comment] 2017-11-09 02:54
Thanks, yes the program I run uses FLAGS, exactly such an arg library. This script is just tiny and simple so I didn't bother. 

Please allow me to clarify, because the first thing I consulted was that tutorial link. The problem wasn't with reading the args, it is with the environment variable not having the same effect it did in bash. In other words, when I run the program, it is not picking up CUDA_VISIBLE_DEVICES and accordingly limiting the graphics devices available to the program I am calling (`train.py`).

These are the key lines of where I'm having trouble, with various attempts commented:
```
        #CUDA_VISIBLE_DEVICES="-1"
        #os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
        #$CUDA_VISIBILE_DEVICES = @(cuda_dev)
        CUDA_VISIBLE_DEVICES = @(cuda_dev)
        CUDA_VISIBLE_DEVICES="0" 
```

I can't get an environment variable to be set with a string the right way, which I believe isn't covered in that tutorial link. Perhaps I'm misunderstanding your suggestion?

**Comment by scopatz** [comment] 2017-11-10 01:31
Hi @ahundt - Sorry I think it was I who misunderstood what you were asking. I think the problem is the the line:

```
$CUDA_VISIBILE_DEVICES = @(cuda_dev)
```

should actually be,

```
$CUDA_VISIBILE_DEVICES = cuda_dev
```

The `@(expr)` operator is only valid in subprocess mode.  I think the confusion here is that environment variables are set and manipulated in Python mode.  (In subpocess mode, environment variables are necessarily strings.)

Hopefully this clears things up!

**Comment by gforsyth** [comment] 2018-04-24 23:59
Closing this out as I think it has been answered, but please reopen if there are still issues.

**Closed by gforsyth** 2018-04-24 23:59 UTC
