### ISSUE TITLE
hangs around `source` operator

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3302] opened 2019-09-02 13:49 UTC
## xonfig

<details>

```
+------------------+-----------------------------------------------+
| xonsh            | 0.9.11                                        |
| Git SHA          | dd16d59d                                      |
| Commit Date      | Aug 25 13:21:16 2019                          |
| Python           | 3.7.4                                         |
| PLY              | 3.11                                          |
| have readline    | False                                         |
| prompt toolkit   | 2.0.9                                         |
| shell type       | prompt_toolkit2                               |
| pygments         | None                                          |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x02783FD0> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x02783E90> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

</details>

## Expected Behavior
Use dynamic source w/o problems.

## Current Behavior
Random `source` hangs for no reason.

## Steps to Reproduce
**test.xsh**:
```
import sys, os, inspect

SOURCE_FILE = os.path.abspath(inspect.getsourcefile(lambda:0)).replace('\\','/')
SOURCE_DIR = os.path.dirname(SOURCE_FILE)

def source_module(dir_path, module_name, dummy1 = ['111', '222'], dummy2 = True):
  source_module_path = os.path.abspath(os.path.join(dir_path, module_name)).replace('\\', '/')

  # hell I know why this hangs..
  if dummy2:
    if not 'dummy' in globals():
      globals()['dummy'] = {}

  echo @('source: ' + source_module_path)
  evalx('source r"{0}"'.format(source_module_path))

source_module(SOURCE_DIR, 'testlib1.xsh')
```
**testlib1.xsh**:
```
SOURCE_FILE = os.path.abspath(inspect.getsourcefile(lambda:0)).replace('\\','/')
SOURCE_DIR = os.path.dirname(SOURCE_FILE)

source_module(SOURCE_DIR, 'testlib2.xsh')
```
**testlib2.xsh**:
```
# nothing here
```
```
python -m xonsh ./test.xsh
```
**Output**:
```
"source: .../testlib1.xsh"
"source: .../testlib2.xsh"
```
... and hangs

*Another question*:
Why the echo (` echo @('source: ' + source_module_path)`) does print the "-quotes when it is not a part of the echo command?

**Comment by andry81** [comment] 2019-09-22 13:07
Seems replacement of the `evalx(...)` by the `source` with pf-strings can workaround this: https://github.com/xonsh/xonsh/issues/3299#issuecomment-533876369

**Comment by scopatz** [comment] 2019-10-02 01:30
This is very strange, thanks for reporting!  I copied this exactly and could not reproduce the error. I am on current master, though, so maybe something has changed since v0.9.11

**Comment by andry81** [comment] 2019-10-02 20:28
Strange, the issue is disappeared 0.o

I can not remember what has changed since the last time I had the issue. May be a side package related to the xonsh package?

**Comment by andry81** [comment] 2019-10-02 20:49
I 've replaced site packaged to packages from the master and is nothing changed.

My steps to repro:
1. install `Python x64 3.7.4` to the `c:\python\x64\37`
2. open cmd console in the `c:\python\x64\37`
3. run `python -m pip install pip --upgrade`
4. run `python -m pip install xonsh`
5. copy code above to the respective scripts in the `c:\python\x64\37` directory
6. run `python -m xonsh test.xsh`
7. repeat from step (5) for other scripts

**Comment by andry81** [comment] 2019-10-02 20:54
May be important to mention a need to avoid the of `source` statement, because with it all works.
I've tested the scripts both in the host Windows 7 and in the guest virtualboxed Windows 7.

**Comment by scopatz** [comment] 2019-10-02 21:10
If someone on windows (@melund?) could reproduce this, that would be great!

**Comment by melund** [comment] 2019-10-04 06:31
@andry81 and @scopatz... I could reproduce it, but the good news is that it seem to be fixed on the current master branch :)

**Comment by melund** [comment] 2019-10-04 06:34
Maybe it was related to #3328 and the fix in #3329

**Comment by andry81** [comment] 2019-10-04 09:25
Ye, it fixed in 50155c66e3eb465c1bc328fad515220899acd361

**Comment by scopatz** [comment] 2019-10-04 12:29
excellent!

**Comment by scopatz** [comment] 2019-10-04 12:30
please feel free to reopen if needed!

**Closed by scopatz** 2019-10-04 12:30 UTC
