### ISSUE TITLE
history not working

### ISSUE THREAD

**Issue by SanketDG** [xonsh/xonsh#1612] opened 2016-08-23 19:49 UTC
I get the following while running history:

```
Did you mean one of the following?
    cc:  Command (/usr/bin/cc)
    w:   Command (/usr/bin/w)
    nc:  Command (/bin/nc)
    9:   Alias
    [:   Command (/usr/bin/[)

The program 'fc' is currently not installed. You can install it by typing:
sudo apt-get install f2c
```

`f2c` is a fortran to c compiler?

**Comment by gforsyth** [comment] 2016-08-23 19:52
Hey @SanketDG -- I believe this is a duplicate of #1577.  Do you use `zsh`?  They alias history to `fc` which is a builtin.  There is a workaround here: https://github.com/xonsh/xonsh/issues/1577#issuecomment-240600295

**Comment by gforsyth** [comment] 2016-08-23 19:54
And thanks for reporting!

**Comment by SanketDG** [comment] 2016-08-23 20:03
Uh I see, sorry for not doing  a quick search.

Although, why is `history` overrided? IMO it should be in a `ignore_list` where nothing can override it.

**Comment by gforsyth** [comment] 2016-08-23 20:04
Agreed.  I think @laerus is discussing just that in #1577

**Comment by laerus** [comment] 2016-08-23 20:10
also #1155, means it's time we go about fixing this. PRs are welcomed!

**Comment by SanketDG** [comment] 2016-08-24 16:12
@laerus Is this fixed? I still get the same thing on the latest master.

**Comment by laerus** [comment] 2016-08-24 17:38
i can't reproduce this anymore, when starting xonsh i get:
`aliases: alias 'history' of shell 'zsh' tries to override xonsh alias, xonsh wins!`
then `history` is the builtin alias. 

can you post the output of `xonfig` and `which -v history` please?

**Comment by SanketDG** [comment] 2016-08-24 19:35
> i can't reproduce this anymore, when starting xonsh i get:
> aliases: alias 'history' of shell 'zsh' tries to override xonsh alias, xonsh wins!
> then history is the builtin alias.

```
+------------------+-----------------+
| xonsh            | 0.4.5           |
| Git SHA          | 62cb089         |
| Python           | 3.4.3           |
| PLY              | 3.7             |
| have readline    | True            |
| prompt toolkit   | 1.0.3           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | LinuxMint       |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

> can you post the output of xonfig and which -v history please?

```
aliases['history'] = ['fc', '-l', '1']
```

**Comment by gforsyth** [comment] 2016-08-24 19:45
Hey @SanketDG, it looks like you're a few commits behind the alias fix on master.  If you update your clone and reinstall this issue should be resolved.

**Comment by SanketDG** [comment] 2016-08-24 21:09
> If you update your clone and reinstall this issue should be resolved.

I did, and I am surprised why it shows an older SHA.

**Comment by gforsyth** [comment] 2016-08-24 22:11
Hmm, using any virtualenvs or conda environments or similar?

**Comment by SanketDG** [comment] 2016-08-25 12:16
@gforsyth yeah! and I am on a `pip install -e .` so not sure why it isn't working.

**Comment by gforsyth** [comment] 2016-08-25 12:18
Can you try another `git pull` and then  `python setup.py install` and see if it will update?

**Comment by laerus** [comment] 2016-08-25 12:21
hey @SanketDG, also i see that you've forked xonsh and its a lot of commits behind, maybe you're pulling from your fork?

**Comment by SanketDG** [comment] 2016-08-25 12:29
> also i see that you've forked xonsh and its a lot of commits behind, maybe you're pulling from your fork?

@laerus Um, no I do have a upstream remote pointed to this repo.


> Can you try another git pull and then python setup.py install and see if it will update?

I did not try this, but instead restarted everything and it seems to work. Thanks.

Although, I am not sure why you would try to override everything. Ideally, you will only want to override commands that are builtin in only yours, so no commands like `ls` and `grep` should be overridden. They could have their own config.

**Comment by gforsyth** [comment] 2016-08-25 12:34
Well, at least it's working!  We're overriding any alias collisions with xonsh defaults -- these themselves can be easily overridden using foreign shell support or setting things in `.xonshrc`.

**Closed by gforsyth** 2016-08-25 12:34 UTC
Labels: bug, duplicate

**Comment by laerus** [comment] 2016-08-25 12:36
@SanketDG you'll have to restart xonsh when in develop mode in order for the changes to take effect.

**Comment by SanketDG** [comment] 2016-08-25 14:01
> you'll have to restart xonsh when in develop mode in order for the changes to take effect.

@laerus I see, thanks. :+1:
