### ISSUE TITLE
Copying long lines managed by prompt_toolkit splits those lines

### ISSUE THREAD

**Issue by nh2** [xonsh/xonsh#2444] opened 2017-07-19 12:20 UTC
When I have a long command line in the termnial, like the `asdf ...` below:

```
$ dmesg
[1295378.894358] audit: type=1400 audit(1500410975.835:93): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/evince-thumbnailer//sanitized_helper" pid=14121 comm="apparmor_parser"
[1326903.865084] Process accounting resumed

niklas@ares ~/src/xonsh nh2fixes| +1 🔎 2 ☰ 2 $
asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa                                                                                  
```

and it gets wrapped to the next line by prompt_toolkit (because the terminal window is not wide enough to contain it on one line), and I then select everything with the mouse and copy it into my editor, I get:

```
$ dmesg
[1295378.894358] audit: type=1400 audit(1500410975.835:93): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/evince-thumbnailer//sanitized_helper" pid=14121 comm="apparmor_parser"
[1326903.865084] Process accounting resumed

niklas@ares ~/src/xonsh nh2fixes| +1 🔎 2 ☰ 2 $
asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa asdf asdfa as
df asdfa                                                                                  
```

See how the last line is split into 2 lines?

Other shells don't have this problem. How can I make it work in xonsh?

**Comment by scopatz** [comment] 2017-07-22 20:44
Thanks for reporting @nh2! This is likely a problem caused by prompt toolkit.  Have you tried reporting it to https://github.com/jonathanslenders/python-prompt-toolkit? Perhaps @jonathanslenders can confirm?

**Comment by scopatz** [comment] 2017-07-22 20:44
Maybe there is an easy option we can set?

**Comment by jonathanslenders** [comment] 2017-07-23 12:26
Hi @nh2,

Unfortunately, this doesn't work, and there is no option to configure. The rendering works different from how GNU Readline renders to the terminal. In fact, prompt_toolkit works much closer to how Vim or many text editors render their output. I guess if you copy/paste from Vim, you'll have the same issue. Prompt_toolkit doesn't rely on the terminal to do the line wrapping, but it does it manually (this gives us much more control of the rendering, but unfortunately you get this side effect.)

**Comment by scopatz** [comment] 2017-07-25 18:31
So is it fair to say that this is a "won't fix" for the moment?  I sometimes find this behaviour a little bothersome myself.  @nh2 - if you really need the wrapping behaviour, you can try the readline shell: http://xon.sh/envvars.html#shell-type

**Comment by jonathanslenders** [comment] 2017-07-25 21:00
Yes, for prompt_toolkit, this will probably be a wontfix. Sorry about that, but I don't see any solution.

**Closed** 2017-07-25 21:05 UTC

**Comment by nh2** [comment] 2017-07-26 15:03
OK, thanks for all the answers!

I will try to move my xonsh config to work also with readline (first problem: #2442), because copypasting output is a thing I do most frequently -- I hope it will one day be supported so I can get back the pretty popup menus!

**Comment by scopatz** [comment] 2017-07-26 20:54
@nh2 - I have also thought about having an urwid/ncurses based front end to xonsh, but have yet to find the time to work on it.  Pull requests welcome if anyone is interested :)
