### ISSUE TITLE
Void Linux: git log does not work properly

### ISSUE THREAD

**Issue by fillipe-gsm** [xonsh/xonsh#4243] opened 2021-04-25 15:21 UTC
## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.26               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.16               |
| shell type       | prompt_toolkit       |
| pygments         | 2.8.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | void                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib 1        | jedi                 |
+------------------+----------------------+
```

</details>

## Expected Behavior

When entering `git log` in any git project, we should be able to navigate in the commits by pressing the up and down arrows (or `j` and `k` keys) and to return to the shell by pressing `q`.

## Current Behavior

The terminal hangs, and any key press is just printed at the bottom of the terminal while the screen is fixed. Even `q` does not quit the command, and the terminal tab (or window) must be killed for that.

The next figure shows this behavior in the Xonsh repository. 
![image](https://user-images.githubusercontent.com/10814987/115998690-d3294a80-a5be-11eb-81c2-b3115877e706.png)

I tested with Terminology and Xfce4-terminal. No problem occurs in other shells such as zsh.

## Steps to Reproduce

Enter the directory of any git project and type `git log`.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment] 2021-04-25 15:39
Hi! I can't reproduce this in Konsole on Arch.

```
xonsh --no-rc
cd /tmp
git clone https://github.com/xonsh/xonsh
cd xonsh
git log
# everything perfect
```

**Comment by fillipe-gsm** [comment] 2021-04-25 18:09
Hi, @anki-code, thanks for the quick answer!

I tried updating my xonsh to 0.9.27 and running `xonsh --no-rc`, and even on Konsole the problem persists. (Actually, now the backspace works by erasing the keys in my previous picture, but git is still hanging and the navigation keys do not work).

For reference:

```bash
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.4                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.16               |
| shell type       | prompt_toolkit       |
| pygments         | 2.8.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | void                 |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

My `~/.xonshrc` file:

```
# XONSH WEBCONFIG START
$PROMPT = '{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {BOLD_BLUE}{prompt_end}{RESET} '
xontrib load argcomplete jedi
# XONSH WEBCONFIG END
```

And not sure if this helps, but if I type `git log` and press only ENTER, the terminal scrolls down but with blank lines:

![image](https://user-images.githubusercontent.com/10814987/116004199-04624480-a5d8-11eb-8737-51c7fa91444c.png)

**Comment by anki-code** [comment] 2021-04-26 07:21
I can repeat this in the Void Linux docker container:
```python
docker run -it --rm voidlinux/voidlinux sh -c @("""
xbps-install -Suy
xbps-install -y python3 python3-pip git bash
pip install 'xonsh[full]'

git clone https://github.com/xonsh/xonsh
cd xonsh
xonsh --no-rc
""")

git log
```
Personally I can't help with this.

**Comment by gregdan3** [comment] 2021-04-26 21:24
I am able to replicate this complete with circumstances and observed behavior on Arch Linux. For reference, I am also running `i3-gaps`, and my terminal is `st`. Termite and urxvt exhibit this behavior as well, so I would suspect it is environmental and not related to the terminal.

**Comment by ion201** [comment] 2021-04-29 17:11
Related: https://github.com/xonsh/xonsh/issues/3263

I also had this issue with `paru` on arch (more generally, any command which started `less` as a subprocess hits this problem). Rather than setting THREAD_SUBPROCS, the workaround I used was to mark specific commands as unthreadable in my `.xonshrc` like so:

```
import builtins
import xonsh

builtins.__xonsh__.commands_cache.threadable_predictors['git'] = xonsh.commands_cache.predict_false
builtins.__xonsh__.commands_cache.threadable_predictors['paru'] = xonsh.commands_cache.predict_false
```

**Comment by Techcable** [comment] 2021-05-01 12:04
I also have this problem with `kitty`

**Comment by anki-code** [comment] 2021-05-02 15:31
Link to #4214

**Comment by anki-code** [comment] 2021-05-02 15:34
Hi @fillipe-gsm! Could you please try to run `$[git log]` and report the result?

**Comment by fillipe-gsm** [comment] 2021-05-02 22:06
Hi, @anki-code, just tried `$[git log]`, and it works fine, I can quit, and navigate with both up/down and j/k keys!

By the way, this works on both versions 0.9.26 and 0.9.27.

**Comment by fillipe-gsm** [comment] 2021-05-02 22:16
@ion201, I tried you approach and it also works with the usual `git log` instead of `$[git log]`, so far with no colateral effects.
I will probably use it as a workaround as well.

**Comment by anki-code** [comment] 2021-05-03 07:13
Thank you for the detailed testing. This means that we have the threading issue again. So I close this with reference to #4214.

**Closed by anki-code** 2021-05-03 07:13 UTC
Labels: help wanted, linux
