### ISSUE TITLE
Generator as argument parsed differently in python and xonsh

### ISSUE THREAD

**Issue by pgoelz** [xonsh/xonsh#1217] opened 2016-06-12 22:54 UTC
I'm running xonsh 0.3.4 with python 3.5.

`max(i for i in [], default=0)` works fine in xonsh and returns `0`, while the same piece of code results in a `SyntaxError: Generator expression must be parenthesized if not sole argument` in python.

@adqm suggested that this is a parser bug in https://github.com/xonsh/xonsh/pull/1216#issuecomment-225465063

**Comment by scopatz** [comment] 2016-06-13 19:46
Maybe it is a parser feature :)  I think that there are a few cases where CPython's grammar generator is too strict, largely by accident.  Consider the following case of unpacking a zero-length tuple.  Xonsh handles this just fine, but Python borks.

```
scopatz@localhost ~/xonsh master $ () = []
scopatz@localhost ~/xonsh master $ python -c "() = []"
  File "<string>", line 1
SyntaxError: can't assign to ()
```

In any event I think this is pretty low priority.  The guarantee is that everything that is valid Python is valid xonsh. Neither of these odd cases violate that, and one could argue that CPython should.

Thanks for reporting @pgoelz :)

**Comment by pgoelz** [comment] 2016-06-23 10:50
I agree. Should we close this issue as there seems to be good reason for "wontfix"?

**Comment by Russell-Jones-OxPhys** [comment] 2016-06-23 11:25
`max(i for i in [1,2,3], default=0)` gives the same error. The zero length is a red herring, I think. The problem is that a bare generator needs to be the only parameter.

On a related note, `ls @([1,2,3])` works, but `ls @(x for x in [1,2,3])` does not, which makes me think iterator handling is a bit off. My intuition is that goose typing may be needed to disentangle the different cases. One would not want `ls @("hi there")` to list h, i, " ", t, ...

**Comment by scopatz** [comment] 2016-06-23 21:55
@Russell-Jones-OxPhys, please see http://xon.sh/tutorial.html#python-evaluation-with:

> If the result is a string, it is appended to the argument list. If the result is a list or other non-string sequence, the contents are converted to strings and appended to the argument list in order. Otherwise, the result is automatically converted to a string.

We also have another case (on master at least) where if the expr is a callable and is the first command, we will treat this callable as an alias.

So we don't do anything special for generators passed in as arguments to `@()`, we simply convert them to a list like everything else.  However, as you say would could special case this and iterate through them.

> Allowing, in syntax, unpacking to an immutable (which is what () or (1, 2) would be, e.g. (1,2)=[1,2]) seems odd to me, but there we go.

Also as an aside, Python almost always assigns into an immutable, because tuples are defined by commas, not parentheses.  So the left-hand side of `x, y = 1, 42` is a tuple and is equivalent to the parenthetical grouping `(x, y) = 1, 4`.  Why it is legal Python to assign into a mutable `[x, y] = 1, 42` I have never seen this in the wild.

**Comment by scopatz** [comment] 2016-08-21 23:30
I am closing this as won't fix for the time being.  If there is a compelling reason to change this, or if someone whats to make the parser more consistent with Python's restrictions, please open a PR!

**Closed** 2017-02-18 07:03 UTC
Labels: bug, wontfix
