### ISSUE TITLE
interrupt (INT) signal sent by Terminal Emulator crashes Xonsh

### ISSUE THREAD

**Issue by Megaguy32** [xonsh/xonsh#3628] opened 2020-06-18 21:43 UTC
Hello. I use Konsole and when I send an INT signal on an empty prompt, Xonsh crashes.

## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 26475146            |
| Commit Date      | May 5 06:42:28 2020 |
| Python           | 3.6.9               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.5               |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | linuxmint           |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

In bash it simply prints ^C goes to a new line

## Current Behavior

in Xonsh the shell crashes and falls back to sh.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last): 
  File "/home/ethan/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24210, in main
    return main_xonsh(args)
  File "/home/ethan/.local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24239, in main_xonsh
    shell.shell.cmdloop()
  File "/home/ethan/.local/lib/python3.6/site-packages/xonsh/ptk_shell/shell.py", line 197, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/ethan/.local/lib/python3.6/site-packages/xonsh/ptk_shell/shell.py", line 166, in singleline
    line = self.prompter.prompt(**prompt_args)
  File "/home/ethan/.local/lib/python3.6/site-packages/prompt_toolkit/shortcuts/prompt.py", line 994, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/ethan/.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/ethan/.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 614, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
Xonsh encountered an issue during launch
Failback to /bin/sh
$
```

</details>

## Steps to Reproduce

open Konsole
launch xonsh
In Konsole menu press Edit > Send Signal > Interrupt Task
and it crashes

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment] 2020-06-18 21:51
Hi @Megaguy32, thanks for reporting! I can confirm the issue.

**Comment by laloch** [comment] 2020-06-18 22:05
The issue is specific to prompt_toolkit `$SHELL_TYPE`.

**Comment by laloch** [comment] 2020-06-18 22:12
Thinking about it, this seems to me to be an upstream prompt_toolkit bug. @jonathanslenders, what do you think?

**Comment by anki-code** [comment] 2021-12-09 18:40
I also can repeat this.

**Comment by jonathanslenders** [comment] 2021-12-09 21:39
If I recall correctly, prompt_toolkit does not set any signal handlers, because potentially it runs in a different thread (where setting signal handlers doesn't work in Python). However, it handles control-c by setting the terminal in raw mode and reading control-c literally from the input.

Would you like an external SIGINT to behave exactly like pressing control-c?
(assuming prompt_toolkit does run in the main thread.)

If so, feel free to open a issue in the prompt_toolkit issue tracker. That way I won't forget.

**Comment by anki-code** [comment] 2021-12-09 22:23
> Would you like an external SIGINT to behave exactly like pressing control-c?

@jonathanslenders I think yes because it's default behavior for bash/zsh/fish. Thank you for the reply and here is the issue https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1537

**Comment by anki-code** [comment] 2022-01-31 08:55
Fixed in the latest prompt-toolkit - https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1537#issuecomment-1025502570

> open Konsole, launch xonsh, In Konsole menu press Edit > Send Signal > Interrupt Task

Tested. Now it works as expected:

> it simply prints ^C goes to a new line

**Closed by anki-code** 2022-01-31 08:55 UTC
Labels: prompt-toolkit, upstream, good first issue
