### ISSUE TITLE
Another slow startup issue

### ISSUE THREAD

**Issue by MissingNoIOI** [xonsh/xonsh#2394] opened 2017-05-31 17:36 UTC
xonsh has a rather slow startup on my desktop with OpenSUSE Tumbleweed, AMD FX-6100, 16GB RAM and SSD.

```
time xonsh -c exit                                                                                                                                                        
4.08user 0.07system 0:04.13elapsed 100%CPU (0avgtext+0avgdata 46076maxresident)k
0inputs+32outputs (0major+17387minor)pagefaults 0swaps
```

I also tried it with Readline to no avail:
```
time xonsh --shell-type readline -c exit                                                                                                                                       
4.10user 0.07system 0:04.14elapsed 100%CPU (0avgtext+0avgdata 46064maxresident)k
0inputs+32outputs (0major+18223minor)pagefaults 0swaps
```

Ignoring the startup file also didn't make a difference
```
time xonsh --no-rc -c exit                                                                                                                                                    
4.20user 0.10system 0:04.24elapsed 101%CPU (0avgtext+0avgdata 46000maxresident)k
0inputs+32outputs (0major+18432minor)pagefaults 0swaps
```

These are the timings:
```
xonsh --no-rc --timings                                                                                                                                                       
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.041   |   0.041   |
|post_execer_init  |   0.494   |   0.453   |
|on_pre_rc         |   0.494   |   0.000   |
|on_post_rc        |   0.495   |   0.001   |
|on_ptk_create     |   4.180   |   3.686   |
|on_post_init      |   4.181   |   0.000   |
|on_pre_cmdloop    |   4.181   |   0.000   |
|on_pre_prompt     |   5.172   |   0.992   |
|------------------|-----------|-----------|
```

**Comment by laerus** [comment] 2017-05-31 17:55
hey @MissingNoIOI indeed that doesn't seem good enough.

mind checking timings with readline too?

thank you for the benchmarking!

**Comment by MissingNoIOI** [comment] 2017-05-31 18:17
Thank you for the quick reply, here are the timings with readline:

```
xonsh --no-rc --timings --shell-type readline                                                                                                                                 22  20:14 
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.040   |   0.040   |
|post_execer_init  |   0.144   |   0.105   |
|on_pre_rc         |   0.144   |   0.000   |
|on_post_rc        |   0.145   |   0.000   |
|on_post_init      |   2.299   |   2.154   |
|on_pre_cmdloop    |   2.299   |   0.000   |
|on_pre_prompt     |   2.299   |   0.000   |
|------------------|-----------|-----------|
```

**Comment by laerus** [comment] 2017-05-31 18:58
```
Welcome to Termux!
$ uname -a
Linux localhost 3.10.49-8935060 #1 SMP PREEMPT Fri Mar 24 15:04:43 KST 2017 armv7l Android
$ time xonsh -c exit

real    0m2.035s
user    0m1.800s
sys     0m0.220s
$ time xonsh --shell-type=readline -c exit

real    0m1.974s
user    0m1.880s
sys     0m0.090s
$ xonsh --timings

Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.370   |   0.370   |
|post_execer_init  |   0.470   |   0.100   |
|on_pre_rc         |   0.480   |   0.010   |
|on_post_rc        |   0.480   |   0.000   |
|on_ptk_create     |   1.500   |   1.020   |
|on_post_init      |   1.500   |   0.000   |
|on_pre_cmdloop    |   2.120   |   0.620   |
|on_pre_prompt     |   2.420   |   0.300   |
|------------------|-----------|-----------|
<user>@localhost ~ $ exit

$ xonsh --shell-type=readline --timings

Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.380   |   0.380   |
|post_execer_init  |   0.480   |   0.100   |
|on_pre_rc         |   0.490   |   0.010   |
|on_post_rc        |   0.500   |   0.010   |
|on_post_init      |   0.660   |   0.160   |
|on_pre_cmdloop    |   0.750   |   0.090   |
|on_pre_prompt     |   0.750   |   0.000   |
|------------------|-----------|-----------|
<user>@localhost ~ $ exit
```

:)

**Comment by laerus** [comment] 2017-05-31 19:00
Not sure whats the case here yet.

**Comment by spongeboburu** [comment] 2018-09-18 04:56
I just tried xonsh for the first time, but the 2+ second delay when starting a new terminal is not ideal. I'll stick with bash for now, but yeah looking forward to getting some Python in my shell.

**Comment by melund** [comment] 2018-09-18 06:50
@spongeboburu There is probably something in your setup slowing it down. Maybe parsing you bashrc setup or other stuff. It starts in 0.6 sec for me on Win. @scopatz has a startup time below 0.2 sec.

**Comment by scopatz** [comment] 2018-09-22 15:11
@spongeboburu - could you share your setup, please so that we can try to figure out what is causing this issue?

**Comment by ndemou** [comment] 2018-12-14 15:49
I've upgraded from 0.7.?? to 0.8.4 and my startup time doubled (from ~1.5sec to ~3sec). Ignoring xonshrc and using readline doesn't help at all: 
```
time xonsh --shell-type=readline --no-rc  -c exit
real	0m2.829s
````
Some info about my setup follows but I'm happy to provide more:
```
ndemou@ndhp ~ $ xonfig 
+------------------+---------------------+
| xonsh            | 0.8.4               |
| Git SHA          | 8405b8dd            |
| Commit Date      | Dec 7 10:39:36 2018 |
| Python           | 3.5.2               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 1.0.15              |
| shell type       | readline            |
| pygments         | 2.3.0               |
| on posix         | True                |
| on linux         | True                |
| distro           | Ubuntu              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
ndemou@ndhp ~ $ uname -a
Linux ndhp 4.15.0-42-generic #45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ndemou@ndhp ~ $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

**Comment by scopatz** [comment] 2018-12-14 22:08
Hi @MissingNoIOI - hmm very strange.  Sorry about this!  Is it fair to say that the run time increases are no just on the first time after update, but happen each time you start xonsh?

**Comment by scopatz** [comment] 2018-12-14 22:09
Also @MissingNoIOI - can you please try starting up with the `--timings` option and report the results here?

**Comment by ndemou** [comment] 2018-12-16 15:47
@scopatz I guess these questions were destined to me and not MissingNoIOI so here I go:

>  Is it fair to say that the run time increases are no just on the first time after update, but happen each time you start xonsh?

Yes and I've also rebooted the PC and pip `install --update` a few packages that I know xonsh depends on. Oh! and `--shell-type=readline --no-rc` seems to make no difference at all.

> Sorry about this!

No worries: I've been 99% happy with xonsh for so long and the price is unbeatable :-)  

> can you please try starting up with the --timings option and report the results here?

The results of `--timings` are extremely variable while `time xonsh -c exit` is very stable (from 2.73 to 2.87sec).  Below I give two extremes from 10 runs. Please also note that after the table with timings is printed another 1 to 2 seconds pass until I get a prompt so that in practice the it needs almost 3secs to print the prompt. 
```
xonsh --shell-type=readline --no-rc --timings

|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.025   |   0.025   |
|post_execer_init  |   0.091   |   0.066   |
|on_pre_rc         |   0.091   |   0.000   |
|on_post_rc        |   0.092   |   0.000   |
|on_post_init      |   1.893   |   1.801   |
|on_pre_cmdloop    |   1.920   |   0.028   |
|on_pre_prompt     |   1.920   |   0.000   |
|------------------|-----------|-----------|

xonsh --shell-type=readline --no-rc --timings

|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.025   |   0.025   |
|post_execer_init  |   0.081   |   0.056   |
|on_pre_rc         |   0.081   |   0.000   |
|on_post_rc        |   0.081   |   0.000   |
|on_post_init      |   0.110   |   0.029   |
|on_pre_cmdloop    |   0.112   |   0.002   |
|on_pre_prompt     |   0.112   |   0.000   |
|------------------|-----------|-----------|
```

**Comment by ndemou** [comment] 2018-12-18 16:48
I've installed all versions of xonsh from 0.8.**0** to 0.8.**4** and noticed that all versions up to 0.8.**2** need about ~0.2sec to startup but 0.8.**3** & **4** needs more than 10 times that (~2.7).
```
# sudo -H pip3 install 'xonsh==0.8.3' --force-reinstall
...
# time  /usr/local/bin/xonsh -c exit
real	0m2.774s

# sudo -H pip3 install 'xonsh==0.8.2' --force-reinstall
...
# time  /usr/local/bin/xonsh -c exit
real	0m0.231s
```
I'm obviously on 0.8.2 for the moment :-)

**Comment by gforsyth** [comment] 2018-12-19 03:35
Hey @ndemou -- there was  regression in 0.8.2 specifically around the `--timings` flag, so that error is expected.  The stark startup time difference is not so expected.  
When you have a moment, can you perform the same startup time comparison but when you switch each version, can you delete the entire `xonsh` directory from your `site-packages` directory?  

Often slowdowns of that magnitude are because the parser table is being regenerated at startup.

**Comment by gforsyth** [comment] 2018-12-19 03:36
> I've been 99% happy with xonsh for so long and the price is unbeatable

also, bumper sticker slogan?  tshirt, maybe?

**Comment by ndemou** [comment] 2018-12-19 09:51
> also, bumper sticker slogan? tshirt, maybe?

Sure -- here's a logo proposal :-)
![xonsh-logo](https://user-images.githubusercontent.com/4411400/50210653-63b44800-037f-11e9-8af6-b6335a14030f.png)

**Comment by ndemou** [comment] 2018-12-19 10:06
> When you have a moment, can you perform the same startup time comparison but when you switch each version, can you delete the entire `xonsh` directory from your `site-packages` directory?

Nothing changed gforsyth.

```
# ndemou  @ ndhp  ~  
locate site-packages|grep python3|grep '\/site-packages$'|uniq|xargs -i sudo rm -rf "{}/*"
# ndemou  @ ndhp  ~  
locate site-packages|grep python3|grep '\/site-packages$'|uniq|xargs -i ls "{}"
# ndemou  @ ndhp  ~  
sudo -H pip3 install 'xonsh==0.8.3' --force-reinstall
Collecting xonsh==0.8.3
Installing collected packages: xonsh
  Found existing installation: xonsh 0.8.3
    Uninstalling xonsh-0.8.3:
      Successfully uninstalled xonsh-0.8.3
Successfully installed xonsh-0.8.3
# ndemou  @ ndhp  ~  
time  /usr/local/bin/xonsh -c exit


real	0m2.840s
```

**Comment by gforsyth** [comment] 2018-12-19 13:23
>        88    1.324    0.015    1.324    0.015 {built-in method time.sleep}

wait... what!?  I mean, that would certainly bump startup time by around 1.3 seconds...

**Comment by gforsyth** [comment] 2018-12-19 18:46
Also, can we confirm that `pip3` and `python3` are pointing to the same distribution?  Do you get the same results if you instead do a `python3 -m pip install ...`?

**Comment by ndemou** [comment] 2018-12-20 11:18
Same results:
```
# ndemou  @ ndhp  ~  
sudo -H python3 -m pip install 'xonsh==0.8.3' --force-reinstall
[sudo] password for ndemou: 
Collecting xonsh==0.8.3
Installing collected packages: xonsh
  Found existing installation: xonsh 0.8.2
    Uninstalling xonsh-0.8.2:
      Successfully uninstalled xonsh-0.8.2
Successfully installed xonsh-0.8.3
# ndemou  @ ndhp  ~  
time  /usr/local/bin/xonsh -c exit


real	0m2.827s
user	0m2.783s
sys	0m0.063s
# ndemou  @ ndhp  ~  
sudo -H python3 -m pip install 'xonsh==0.8.2' --force-reinstall
Collecting xonsh==0.8.2
Installing collected packages: xonsh
  Found existing installation: xonsh 0.8.3
    Uninstalling xonsh-0.8.3:
      Successfully uninstalled xonsh-0.8.3
Successfully installed xonsh-0.8.2
# ndemou  @ ndhp  ~  
time  /usr/local/bin/xonsh -c exit


real	0m0.249s
user	0m0.210s
sys	0m0.041s

# ndemou ~ $
python3 -m pip -V ; pip3 -V
pip 18.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
pip 18.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

**Comment by scopatz** [comment] 2018-12-22 00:41
There are only a few things in xonsh which call `time.sleep()` on startup:

1. `ptk2/__init__.py`, when it lazily imports `pkg_resources`
2. The history backends on load and garbage collection.
3. The parser waits until it is loaded, which might be caused if you have to regenerate the parser each time.
4. Some things in proc, which shouldn't happen until you are running commands (what is in your xonshrc?)

**Comment by scopatz** [comment] 2018-12-22 00:49
Also, the only thing that happens between `on_post_rc` and `on_post_init` is that the `Shell` instance is constructed.

**Comment by scopatz** [comment] 2018-12-22 00:52
That actually limits this to either being a history or a ptk2 thing.  I thought that you were on ptk1 @ndemou. If so, that indicates that this is a history thing.

**Comment by ndemou** [comment] 2019-01-31 10:22
> **scopatz wrote at** https://github.com/xonsh/xonsh/issues/2965#issuecomment-4590062
> Would it be possible for you to do a `git bisect` between these two [0.8.2, 0.8.4] and figure out the commit where it becomes painfully slow? That would help us a lot!

(moved this comment back here where it belongs)

I'm a git newbie but I think I can manage it. However I'd like to invest the time only if this issue matters to others (I'm OK with the workaround). @scopatz do you this this is important?

**Comment by scopatz** [comment] 2019-01-31 16:42
We take slowdowns pretty seriously, and I don't want you to have to be stuck on 0.8.2 forever :wink: But if it is too much effort, don't worry about it.  It just would be good to know!

**Comment by micimize** [comment] 2019-09-18 18:35
I wish there was some utility for maintaining a [small pool of warmed up shells](https://github.com/tmux/tmux/issues/1087#issuecomment-532810362) so that slow startup wasn't such a show stopper

**Comment by scopatz** [comment] 2019-10-02 17:49
Yep, that would be great!

**Comment by anki-code** [comment] 2020-10-09 15:19
Current version is 0.9.23 could you please add actual commands to repeat the issue or close this issue?

**Comment by ndemou** [comment] 2020-10-11 08:22
I moved to another system where I don't have the issue and the original reporter is silent for 3 years. 

Closing seems appropriate.

BTE, what is missing from this issue is not commands to repeat (they are: "xonsh").

**Comment by anki-code** [comment] 2020-10-11 09:48
@scopatz let's close until new/actual info.

**Closed** 2020-10-11 14:11 UTC
