### ISSUE TITLE
ctrl-r not working for reverse search on OS X 10.10.5 with Python 3.5

### ISSUE THREAD

**Issue by corbinbs** [xonsh/xonsh#394] opened 2015-09-27 00:36 UTC
I've not been able to get ctrl-r to work for reverse search on OS X 10.10.5 with Python 3.5.
I pip installed the latest xonsh release (0.2.0) and I've also tried with the latest master code.
I'll post a pull request if I figure out what's going on but I wanted to file an issue in case others encountered the same behavior.  

Thanks,

Brian

**Comment by scopatz** [comment] 2015-09-27 05:16
Hi @corbinbs - do you know if you have GNU readline or libedit? This seems like it could be a Mac specific issue...

**Comment by corbinbs** [comment] 2015-09-28 00:32
Looks like I might have `libedit` in the mix
```
$ ls -l /usr/lib/libreadline.dylib
lrwxr-xr-x  1 root  wheel  15 Oct 20  2014 /usr/lib/libreadline.dylib -> libedit.3.dylib
```
I'm running with the latest Python 3.5 install from python.org

**Comment by scopatz** [comment] 2015-09-29 04:02
OK - then I bet that this is a libedit issue. I don't have a good way of testing this personally, so if you are anyone comes up with a fix, I'll gladly merge it.

**Comment by blarghmatey** [comment] 2015-10-02 18:59
I am having a similar issue using prompt-toolkit on Manjaro Linux (an Arch derivative) using Python 3.5. I am unable to use Ctl-R, Ctl-D, Ctl-C, Ctl-Z at all unless I am using readline mode.

**Comment by scopatz** [comment] 2015-10-02 19:01
I am not even sure that prompt-toolkit supports that (though it probably does). @jonathanslenders or @melund would know :)

**Comment by scopatz** [comment] 2015-10-02 19:01
Thanks for reporting @blarghmatey

**Comment by blarghmatey** [comment] 2015-10-02 19:05
Looking [here](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_input.py#L48), it appears that it does support control sequences. I'm not sure why it would fail given my setup. I will try running everything on Python 3.4 and see if that works any different.

**Comment by blarghmatey** [comment] 2015-10-03 13:13
So, it started working again. I'm not sure what I may have changed, sorry I can't be more help on that front :)

**Comment by corbinbs** [comment] 2015-10-16 13:46
I stumbled across this recently:
http://hints.macworld.com/article.php?story=20080313113705760

adding a line to your .editrc file:
```
$ cat ~/.editrc
bind "^R" em-inc-search-prev
```
ctrl-r works but still doesn't display quite like I'd expect.   (sometimes long commands get wrapped or the first part of them is chopped off with no way to go back to edit, etc)

I'll keep looking for a decent solution that will work for folks "out of the box" when they install xonsh

**Comment by scopatz** [comment] 2015-10-16 14:05
Thanks @corbinbs - I wonder if this looks weird because of the order it is loaded in.  Could you try adding a additional line [here in readline_shell.py](https://github.com/scopatz/xonsh/blob/master/xonsh/readline_shell.py#L55) that looks like:

```python
readline.parse_and_bind("bind ^R em-inc-search-prev")
```

**Comment by jonathanslenders** [comment] 2015-10-16 15:08
Hi all,
Sorry for the late reply. prompt_toolkit does support reverse-i-search. Ctrl-C and Ctrl-D should also be handled correctly. I can have a look this weekend.

By the way, I get a lot of "UnboundLocalError: local variable 'p0' referenced before assignment" errors when running Xonsh. (latest master.)

**Comment by scopatz** [comment] 2015-10-16 15:13
> I can have a look this weekend.

Thanks!

> By the way, I get a lot of "UnboundLocalError: local variable 'p0' referenced before assignment" errors when running Xonsh. (latest master.)

Weird. Can you post a full traceback? Also what version of Python are you on?

**Comment by jonathanslenders** [comment] 2015-10-16 15:19
This one is Python 3.4.0. But looking at the code, there is a code path in ``p_power`` that does not assign to ``p0``, but uses it anyway. Maybe other functions have the same issue.

**Comment by scopatz** [comment] 2015-10-16 15:25
So we were seeing this issue in #399, but that code path should be impossible to access.  I wonder if it is a PLY version issue.  Do you know what PLY you are on?

**Comment by jonathanslenders** [comment] 2015-10-16 15:27
```
Traceback (most recent call last):
  File "/home/jonathan/git/xonsh/xonsh/base_shell.py", line 158, in push
    locs=self.ctx)
  File "/home/jonathan/git/xonsh/xonsh/execer.py", line 94, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/home/jonathan/git/xonsh/xonsh/execer.py", line 69, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/home/jonathan/git/xonsh/xonsh/execer.py", line 150, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/home/jonathan/git/xonsh/xonsh/parser.py", line 263, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/jonathan/git/xonsh/.eggs/ply-3.6-py3.4.egg/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jonathan/git/xonsh/.eggs/ply-3.6-py3.4.egg/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/jonathan/git/xonsh/xonsh/parser.py", line 1625, in p_power
    p[0] = p0
UnboundLocalError: local variable 'p0' referenced before assignment
```

**Comment by scopatz** [comment] 2015-10-16 15:32
And this happens with any command? I am not able to reproduce this on Python 3.4 on Ubuntu on PLY v3.6

**Comment by jonathanslenders** [comment] 2015-10-16 15:34
Yes. ``p`` has length 3. It is ``[None, <_ast.Name object at 0xb5e9a3ac>, None]``.

**Comment by scopatz** [comment] 2015-10-16 15:39
Woah! That definitely looks like a ply bug. Are you on ply 3.5? From the website: 

> 4/26/2015. PLY-3.6 is released. A fair bit of cleanup and a few new features. Note: PLY-3.5 had some critical bugs and has been withdrawn.

http://www.dabeaz.com/ply/

**Comment by santagada** [comment] 2016-07-27 11:20
Tested this today on:

```
xonfig
+------------------+----------------+
| xonsh            | 0.4.4          |
| Git SHA          | None           |
| Python           | 3.5.2          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.3          |
| shell type       | prompt_toolkit |
| pygments         | 2.2a0          |
| on posix         | True           |
| on linux         | False          |
| on darwin        | True           |
| on windows       | False          |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+
```

and ctrl+r seems to be working fine (I think it was broken for me on xonsh 0.4.3 too)

**Comment by scopatz** [comment] 2016-07-27 15:37
Ok I am going to go ahead and close.  Please feel free to reopen.

**Closed by scopatz** 2016-07-27 15:37 UTC
Labels: bug, help wanted
