### ISSUE TITLE
pip points to wrong environment when xonsh is installed with pipx

### ISSUE THREAD

**Issue by halloleo** [xonsh/xonsh#3283] opened 2019-08-25 10:18 UTC
### Description

Let's say, in xonsh I enter a virtual environment via `vox`, like this:

    vox activate /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-

Then I check on the the packages of the virtual environment:

    python -m pip -V

I *expect* the following:

    pip 19.2.2 from /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/lib/python3.7/site-packages/pip (python 3.7)

(These are the packages installed under the virtual environment `cmpdisktree-Q2PWYfc-`.) However in reality I get:

    pip 19.0.2 from /Users/Shared/Python/pipx/venv/xonsh/lib/python3.7/site-packages/pip (python 3.7)

These are the packages installed of the xonsh virtual environment.

The same thing happens when i just call the appropriate python binary:

    /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/nin/python3 -m pip -V

Somehow xonsh messes here wrongly with some paths, because in bash I get what I expect:

    $ /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/nin/python3 -m pip -V
    pip 19.2.2 from /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/lib/python3.7/site-packages/pip (python 3.7)

It is to note that **I have installed xonsh via `pipx`**.

### xonfig

<details>

```
+------------------+---------------------+
| xonsh            | 0.9.8               |
| Git SHA          | cb485817            |
| Commit Date      | Jul 1 20:35:24 2019 |
| Python           | 3.7.1               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.9               |
| shell type       | dumb                |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+

```

</details>

**Comment by scopatz** [comment] 2019-08-25 17:44
Thanks for reporting @halloleo. Can you update to the latest xonsh to see if this is still occuring? I know there have been some vox fixes recently

**Comment by cjrh** [comment] 2019-08-27 12:32
I also install xonsh via pipx, but on xonsh 0.9.11, Windows 10, my pip resolution works correctly. Suggests there might be something mac-related.

**Comment by halloleo** [comment] 2019-08-27 23:52
@scopatz  wrote:

> Can you update to the latest xonsh to see if this is still occuring? I know there have been some vox fixes recently

Still happens in 0.9.11.

@astronouth7303 wrote:

> What's the output of which python with venv activated? How about which python3?

    $ which python
    /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin/python

    $ which python3
    /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin/python3

**Comment by cjrh** [comment] 2019-08-28 00:06
@halloleo After activating the venv, can you show your `$PATH`?

**Comment by halloleo** [comment] 2019-08-28 23:33
@cjrh wrote:

>  After activating the venv, can you show your `$PATH`?

`echo $PATH` after activating the venv gives me:

    /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin:/Users/bridge/bin:/Users/bridge/share/bin:/Users/Shared/Python/pipx/bin:/usr/local/bin:/Library/TeX/Distributions/Programs/texbin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by astronouth7303** [comment] 2019-08-28 23:36
Ok, now I have to ask: What's the contents of `/Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin`?

**Comment by astronouth7303** [comment] 2019-08-28 23:39
I'm starting to lean towards "your venv is incomplete or corrupted".

**Comment by halloleo** [comment] 2019-08-29 03:26
I will check when I am at the macOS machine.

However I doubt that the venv is corrupted, because I can activate it perfectly fine through pipenv:

    pipenv run python ...

with `pipenv --venv` showing `/Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-`.

**Comment by halloleo** [comment] 2019-08-31 06:22
@astronouth7303 The content of `/Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin` is:

```
activate
activate.csh
activate.fish
activate.ps1
activate_this.py
easy_install
easy_install-3.7
pip
pip3
pip3.7
py.test
pytest
python
python-config
python3
python3.7
tqdm
wheel
```

I'd say that;s what you expect in the `bin` directory of a venv.

**Additional info:** I raised this issue with using an *absolute path* (`vox activate /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-`). The same problem occurs when I specify the venv just with its *name in vox's list of venvs* (`vox activate cmpdisktree-Q2PWYfc-`).

**Comment by astronouth7303** [comment] 2019-09-01 00:48
Wait, the venv bin is leading $PATH, and it contains a python, but the system is choosing a different python????

**Comment by halloleo** [comment] 2019-09-01 01:29
@astronouth7303  No, it is using the python binary according to $PATH, but pip then still resorts to the xonsh venv. Even when I issue *in xonsh*

    $ /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/bin/python -m pip -V

I get the output

    pip 19.2.3 from /Users/Shared/Python/pipx/venv/xonsh/lib/python3.7/site-packages/pip (python 3.7)

This happens both before and after `vox activate ...`. *In bash* however I get the correct result

    pip 19.2.2 from /Users/Shared/Python/venv/cmpdisktree-Q2PWYfc-/lib/python3.7/site-packages/pip (python 3.7)

I suspect xonsh somehow mangles with paths for subsequent python subprocesses...

**Comment by astronouth7303** [comment] 2019-09-01 16:57
Oh, I see. Xonsh is in its own venv, but then you activate your own.

Yeah, running xonsh from a venv isn't super common (I think brew, system, and conda environments are most common.)

I'm unable to reproduce this from a vanilla venv, though, so maybe it's a pipx thing?

```
$ python3 -m venv /tmp/xenv
$ source /tmp/xenv/bin/activate
$ pip install "xonsh[ptk]"
$ /tmp/xenv/bin/xonsh
🐚 vox create tmp
🐚 vox activate tmp
```

Test results:
```
(tmp) /tmp/xenv 🐚 which pip                                                                           
/home/astraluma/.virtualenvs/tmp/bin/pip
(tmp) /tmp/xenv 🐚 which python                                                                        
/home/astraluma/.virtualenvs/tmp/bin/python
(tmp) /tmp/xenv 🐚 pip -V                                                                              
pip 18.1 from /home/astraluma/.virtualenvs/tmp/lib/python3.7/site-packages/pip (python 3.7)
(tmp) /tmp/xenv 🐚 python -m pip -V                                                                    
pip 18.1 from /home/astraluma/.virtualenvs/tmp/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by halloleo** [comment] 2019-09-03 04:13
Ok, more detailed testing reveals: It *only seems to happen to venvs created with pipenv*. (I.e. venvs created with vox are fien - as your test shows.)

**Comment by halloleo** [comment] 2019-09-05 01:47
I compared venvs created by pipenv and created by vox: The venv created by vox contains a `pyvenv.cfg` file, which is not present in the venv created by pipenv. 

I recall I had a similar issue before: #2929. It was fixed by #2937. But that issue relates only to recognition in vox *activation* itself, maybe there is more to be fixed in vox to work with venvs *without* pyvenve.cfg...

**Comment by astronouth7303** [comment] 2019-09-05 03:29
Looking at the source, that file is only used during upgrade to restore some flags

https://github.com/xonsh/xonsh/blob/dd16d59d86930da322e30502c024e6e328fcb215/xontrib/voxapi.py#L203-L214

**Comment by halloleo** [comment] 2019-09-07 08:38
You are right! I can confirm: Adding an appropriate `pyvenv.cfg` to a venv created with `pipenv` does _not_ help...

So I am at a loss: Why can venvs created with `pipenv` not be activated with `vox`? After all [pipenv is the officially  recommended dependency manager](https://packaging.python.org/tutorials/managing-dependencies/)...

**Comment by astronouth7303** [comment] 2019-09-07 21:09
(Opinion: I think the PSF was premature in blessing pipenv, although I think Pipfile/etc has promise.)

The big difference I can see is that on my machine (Debian) standard virtual environments symlink to the system python:

```
🐚 ls -lh awsgi/bin/                                                                            
total 40K
-rw-r--r-- 1 astraluma astraluma 2.2K Jul 27 19:16 activate
-rw-r--r-- 1 astraluma astraluma 1.3K Jul 27 19:16 activate.csh
-rw-r--r-- 1 astraluma astraluma 2.4K Jul 27 19:16 activate.fish
-rwxr-xr-x 1 astraluma astraluma  263 Jul 27 19:16 easy_install
-rwxr-xr-x 1 astraluma astraluma  263 Jul 27 19:16 easy_install-3.7
-rwxr-xr-x 1 astraluma astraluma  245 Jul 27 19:16 pip
-rwxr-xr-x 1 astraluma astraluma  245 Jul 27 19:16 pip3
-rwxr-xr-x 1 astraluma astraluma  245 Jul 27 19:16 pip3.7
-rwxr-xr-x 1 astraluma astraluma  238 Jul 27 19:16 py.test
-rwxr-xr-x 1 astraluma astraluma  238 Jul 27 19:16 pytest
lrwxrwxrwx 1 astraluma astraluma    7 Jul 27 19:16 python -> python3
lrwxrwxrwx 1 astraluma astraluma   16 Jul 27 19:16 python3 -> /usr/bin/python3
``

Whereas pipenv environments copy it:

```
🐚 ls -lh demo-PHuzL64m/bin                                                                     
total 4.8M
-rw-r--r-- 1 astraluma astraluma 2.1K Jul 29 12:56 activate
-rw-r--r-- 1 astraluma astraluma 1.5K Jul 29 12:56 activate.csh
-rw-r--r-- 1 astraluma astraluma 3.1K Jul 29 12:56 activate.fish
-rw-r--r-- 1 astraluma astraluma 1.8K Jul 29 12:56 activate.ps1
-rw-r--r-- 1 astraluma astraluma 1.2K Jul 29 12:56 activate.xsh
-rw-r--r-- 1 astraluma astraluma 1.5K Jul 29 12:56 activate_this.py
-rwxr-xr-x 1 astraluma astraluma  274 Aug  1 15:33 chardetect
-rwxr-xr-x 1 astraluma astraluma  283 Jul 29 12:56 easy_install
-rwxr-xr-x 1 astraluma astraluma  283 Jul 29 12:56 easy_install-3.7
-rwxr-xr-x 1 astraluma astraluma  261 Jul 29 12:56 flask
-rwxr-xr-x 1 astraluma astraluma  270 Jul 29 13:29 gunicorn
-rwxr-xr-x 1 astraluma astraluma  272 Jul 29 13:29 gunicorn_paster
-rwxr-xr-x 1 astraluma astraluma  265 Jul 29 12:56 pip
-rwxr-xr-x 1 astraluma astraluma  265 Jul 29 12:56 pip3
-rwxr-xr-x 1 astraluma astraluma  265 Jul 29 12:56 pip3.7
-rwxr-xr-x 1 astraluma astraluma  265 Jul 31 15:46 pyrsa-decrypt
-rwxr-xr-x 1 astraluma astraluma  265 Jul 31 15:46 pyrsa-encrypt
-rwxr-xr-x 1 astraluma astraluma  263 Jul 31 15:46 pyrsa-keygen
-rwxr-xr-x 1 astraluma astraluma  286 Jul 31 15:46 pyrsa-priv2pub
-rwxr-xr-x 1 astraluma astraluma  259 Jul 31 15:46 pyrsa-sign
-rwxr-xr-x 1 astraluma astraluma  263 Jul 31 15:46 pyrsa-verify
lrwxrwxrwx 1 astraluma astraluma    7 Jul 29 12:56 python -> python3
-rwxr-xr-x 1 astraluma astraluma 4.7M Jul 29 12:56 python3
lrwxrwxrwx 1 astraluma astraluma    7 Jul 29 12:56 python3.7 -> python3
-rwxr-xr-x 1 astraluma astraluma 2.4K Jul 29 12:56 python-config
-rwxr-xr-x 1 astraluma astraluma  261 Jul 29 12:56 wheel
```

However, I am still not able to replicate the behavior you describe.

My only thought is that you moved a venv? virtual environments are hard-coded to their initial location and cannot simply be moved.

**Comment by halloleo** [comment] 2019-09-10 01:25
Mmmh, I have checked with a completely new venv created via pipenv:

```
$$$ mkdir pipenv-project && cd pipenv-project
$$$ pipenv install cowsay
Creating a virtualenv for this project…
.
[More lines here]
.
Virtualenv location: /Users/Shared/Python/venv/pipenv-project-E52XaIcn
.
[More lines here]
.
✔ Success! 
```

After this on macOS the following happens:

### macOS

```
$$$ python3 -V
Python 3.7.4
$$$ python3 -m pip -V
pip 19.2.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$$$ xpip -V
pip 19.2.3 from /Users/Shared/Python/pipx/venv/xonsh/lib/python3.7/site-packages/pip (python 3.7)
$$$ pipenv --venv
/Users/Shared/Python/venv/pipenv-project-E52XaIcn
$$$ pipenv run python -m pip -V
pip 19.2.3 from /Users/Shared/Python/venv/pipenv-project-E52XaIcn/lib/python3.7/site-packages/pip (python 3.7)
$$$ vox activate pipenv-project-E52XaIcn
Activated "pipenv-project-E52XaIcn".
(pipenv-project-E52XaIcn) $$$ pip -V
pip 19.2.3 from /Users/Shared/Python/pipx/venv/xonsh/lib/python3.7/site-packages/pip (python 3.7)
```

The problem is here the last line: **After activating the venv via vox, pip still points to the xonsh packages** as xpip does. For comparison on Centos/RHEL everything is correct:

### Centos

<details>

```
$$$ python3 -V
Python 3.7.4
$$$ python3 -m pip -V
pip 19.2.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$$$ xpip -V
pip 19.0.3 from /working/software/broleo/share/pipx/xonsh/lib/python3.6/site-packages/pip (python 3.6)
$$$ pipenv --venv
/working/software/venv/pip_test_project-75Vawv54
$$$ pipenv run python -m pip -V
pip 19.2.3 from /working/software/venv/pip_test_project-75Vawv54/lib/python3.7/site-packages/pip (python 3.7)
$$$ vox activate pip_test_project-75Vawv54
Activated "pip_test_project-75Vawv54".
(pip_test_project-75Vawv54) $$$ pip -V
pip 19.2.3 from /working/software/venv/pip_test_project-75Vawv54/lib/python3.7/site-packages/pip (python 3.7)
```

On the last line pip pomts to the correct packages in the just activated venv.

</details>

**Comment by jackhall** [comment] 2019-11-05 15:24
This happens for me too (on Mac Catalina), and it was very confusing. Any virtual environments created with `vox` all point `pip` (or `xpip`) to the base `xonsh` environment. No matter what I install in a `vox` virtual environment, no matter which `pip` - I tried both `xpip` and `pip` - I use to install it, the site-packages for that environment stay empty. The problem might have something to do with `pip` missing from the `<vox-env>/bin` directory. I used `brew` to install `xonsh`, originally, if that makes a difference. 

This is a pretty crippling bug. I'm working around it now by using `venv` to create virtual environments. The big drawback to this is that the `deactivate` command doesn't work (which is not `xonsh`'s fault, as I understand).

**Comment by gforsyth** [comment] 2019-11-05 16:10
Hey @jackhall --
`xpip` should only ever point to the base `xonsh` environment, since that is the environment that determines which packages can be imported _in_ `xonsh`.
If `pip` is missing from the `<vox-env>/bin` directory, that sounds like a separate problem.  I don't trust `homebrew` for python stuff (perhaps unfairly) but you might try installing `xonsh` using `conda` instead, since `brew` does some aggressive sandboxing that might be screwing with things.

**Comment by jackhall** [comment] 2019-11-05 21:37
Ok, that makes sense about `xpip`. Given this particular bug, the intended functionality was unclear. 

I suspect that `pip` missing from `vox`-created environments would lead the shell to use the system's `pip`, which is not pointed at the virtual environments. I guess it could be different problem, but it would be something of a coincidence. 

I get that it's popular for package developers to hate on homebrew, there really isn't a general-purpose alternative for Mac, and the benefits of having a single package manager often outweigh the drawbacks of having an imperfect one or having several. Also, homebrew installation is the first option in the `xonsh` docs. It's your package, but doesn't it make sense to support functionality that's both documented and likely to see wide use?

**Comment by halloleo** [comment] 2019-11-06 00:21
Actually for me installing via `brew` works (meaning I *can* "vox into" a venv), but installing via `pipx` didn't work (meaning I *couldn't* "vox into" a venv).

The whole thing is somewhat a mess...

**Comment by gforsyth** [comment] 2022-05-05 18:15
Closing as this seems to only impact venvs created with `pipenv`.

**Closed by gforsyth** 2022-05-05 18:15 UTC
Labels: bug, xpip
