### ISSUE TITLE
Duplicate completions provided for subdirectories

### ISSUE THREAD

**Issue by airdrik** [xonsh/xonsh#575] opened 2015-12-18 22:11 UTC
Given file: someDocument.txt in Documents/subDir
When I try:
cd Documents/subDir/someDoc<tab>

Instead of completing someDocument.txt, it will display suggestions with and without the parent directory/ies, and not fill in any more of the document name.

(using vanilla xonsh 0.2.3 installed via pip on python3.4 on ubuntu 14.04)

**Comment by scopatz** [comment] 2015-12-19 01:05
HI @airdrik, thanks for reporting! This doesn't seem to happen for me with the current master. 

```console
scopatz@localhost ~ $ ls temp/
aaa  aab
scopatz@localhost ~ $ mkdir temp/t
scopatz@localhost ~ $ touch temp/t/aaa
scopatz@localhost ~ $ touch temp/t/aab
scopatz@localhost ~ $ cd temp/t/aa[TABTAB]
temp/t/aaa  temp/t/aab  
scopatz@localhost ~ $ cd temp/t/aa
```

Can you tell us a bit more about your system, are you using readline or prompt-toolkit, etc.

**Comment by scopatz** [comment] 2015-12-19 01:06
Or could you try this on the current master and see if it is still an issue, please? Thanks

**Comment by adqm** [comment] 2015-12-22 08:23
I can see this happening on the current master, actually, though I'm not sure about the current pip release.  One issue is that the bash completer and the path completer can both suggest equivalent (though slightly different) completions (e.g., one wrapped in quotes and one not, or one with a space appended and one without).

I'm working on a fix.

**Comment by scopatz** [comment] 2015-12-22 17:49
Ahh I see.

**Comment by airdrik** [comment] 2015-12-22 19:50
A related item.  Don't know if it will help:
The bug seems to be triggered by having a CDPATH environment variable set.  When I tried it on my home machine (PCLinuxOS, Python 3.4, Xonsh 2.3 from pip), it provided the expected behavior when I didn't have CDPATH defined, but then when I had it defined then the bug manifest itself.

I'll try installing master and try again shortly.

**Comment by airdrik** [comment] 2015-12-22 20:22
Reproduced using master.  

I found something else which may be related: with $CDPATH set to: ":~/:~/Downloads", current directory ~/Pictures, I tried "cd Documents/sub[TAB]", instead of completing to "cd Documents/subDir" it completed it to "cd subDir".  Such behavior is fine for replacing paths in CDPATH, but in this case ~/Documents was not in said path and shouldn't have been removed.
When $CDPATH was omitted, no such replacements occurred.

**Comment by scopatz** [comment] 2015-12-22 23:28
Was `$CDPATH` the literal string `":~/:~/Downloads"` or was this a list `["", "~/", "~/Downloads"]`?

**Comment by airdrik** [comment] 2015-12-31 00:31
I had it set up like that in bash prior to running xonsh.  In xonsh it split it into the list (as expected).
(I also tried setting it to just the string as described and xonsh took care of splitting it into a list (also as expected)).
It didn't make a difference if the '~'s were expanded or not.

If $CDPATH was an empty list then it used the original behavior, but if it contained even a single empty-string then the described behavior occurs.

**Comment by airdrik** [comment] 2016-01-05 15:20
I just updated to current master and I'm still seeing the same behavior.

**Comment by scopatz** [comment] 2016-01-05 17:59
Hmm, I'll reopen the issue then.

**Comment by airdrik** [comment] 2016-04-11 19:47
Is there any alternative workaround for the behavior that you get from bash with $CDPATH? - that is to be able to specify a list of directories, and then have cd switch to the first of whichever of those directories contains the path specified, along with path completion of any (matching) paths in any of those directories?

**Comment by scopatz** [comment] 2016-04-11 20:16
Hi @airdrik, `cd` is just an alias, and so if you wanted to make modifications to how this works, you are welcome to do so and open up a PR, you can find cd here: https://github.com/scopatz/xonsh/blob/master/xonsh/dirstack.py#L49

**Comment by airdrik** [comment] 2016-04-11 22:14
Actually, it looks like the behavior is there when $CDPATH is defined.  You just run into the aforementioned issues when trying to use the path autocompletion with $CDPATH.

I do have one suggestion for the cd alias: change _try_cdpath to call expanduser on the paths from $CDPATH so that you can use the shortened paths in the path list.

**Comment by scopatz** [comment] 2016-04-11 23:02
Pull requests very welcome @airdrik :)

**Comment by laerus** [comment] 2016-09-09 15:00
Closing since i can't reproduce this and the completion mechanism has been improved a lot since xonsh 0.2.3. Feel free to reopen if the issue persists.

**Closed by laerus** 2016-09-09 15:00 UTC
Labels: bug

**Comment by airdrik** [comment] 2016-09-09 15:19
After updating to xonsh 4.0, using prompt_toolkit, the behavior seems to be fixed in most cases - even using $CDPATH works as expected.  
That said, I have observed a couple of cases where it did replace the whole path with the specific subdirectory, but I haven't been able to consistently reproduce it yet.  I will open a new case if I am able to consistently reproduce it.

Thanks for your help.
