### ISSUE TITLE
Unable to put a process in background

### ISSUE THREAD

**Issue by budgetinsight** [xonsh/xonsh#1607] opened 2016-08-22 13:23 UTC
The ^Z shortcut doesn't work (anymore?).

OS : Debian
Version of xonsh: upstream git
How to reproduce:

$ xonsh
$ vim
^Z

**Comment by gforsyth** [comment] 2016-08-22 15:35
Hey @budgetinsight, thanks for reporting! I can't reproduce this on current master.  Could you please post the output of `xonfig`?  Thanks!

**Comment by budgetinsight** [comment] 2016-08-22 15:52
<pre>
+------------------+-----------------+
| xonsh            | 0.4.5           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
</pre>

**Comment by budgetinsight** [comment] 2016-08-22 15:54
Same thing with prompt-toolkit:

<pre>
+------------------+-----------------+
| xonsh            | 0.4.5           |
| Git SHA          | None            |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | 1.0.3           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
</pre>

**Comment by gforsyth** [comment] 2016-08-22 15:57
Well, that's good, at least.  Job control really shouldn't depend on which shell you're using.  

Have you tried backgrounding anything else besides `vim`?

**Comment by scopatz** [comment] 2016-08-22 16:02
Also what is the value of `$XONSH_STORE_STDOUT`?

**Comment by budgetinsight** [comment] 2016-08-22 16:04
<pre>
$ echo $XONSH_STORE_STDOUT
True
</pre>

**Comment by gforsyth** [comment] 2016-08-22 16:15
ahh, ok.  yeah, there's an open bug where `$XONSH_STORE_STDOUT=True` breaks backgrounding.  If you set it to `False` it should work.

**Comment by budgetinsight** [comment] 2016-08-22 16:28
Ok, thanks.

**Comment by scopatz** [comment] 2017-02-15 06:14
I believe that this issue has now been fixed. Would you mind testing it out and closing this issue? Thanks!

**Comment by scopatz** [comment] 2017-02-25 06:59
Please feel free to reopen in needed!

**Closed by scopatz** 2017-02-25 06:59 UTC
Labels: bug, duplicate
