### ISSUE TITLE
Prompt disappears after running `source-bash $(docker-machine env default)`

### ISSUE THREAD

**Issue by mscottford** [xonsh/xonsh#1252] opened 2016-06-17 02:59 UTC
After I run `source-bash $(docker-machine env default)` the prompt is no longer displayed. I initially thought that the `source-bash` command had just never returned. It took me a while to figure out the the `$PROMPT` variable had been set to `''`. Here's some shell output that shows what's going on.

```
Last login: Thu Jun 16 22:48:13 on ttys000

mscottford@blaster ~
$ xonfig
+------------------+----------+
| xonsh            | 0.3.4    |
| Python           | 3.5.1    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | False    |
| on darwin        | True     |
| on windows       | False    |
| on cygwin        | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+

mscottford@blaster ~
$ $XONSH_SHOW_TRACEBACK=True

mscottford@blaster ~
$ source-bash $(docker-machine env default)

xonfig
+------------------+----------+
| xonsh            | 0.3.4    |
| Python           | 3.5.1    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | False    |
| on darwin        | True     |
| on windows       | False    |
| on cygwin        | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+

ls
Applications
Creative Cloud Files
Desktop
Documents
Downloads
Library
Movies
Music
Pictures
Projects
Public

$PROMPT
''

$PROMPT = '\n{BOLD_GREEN}{user}@{hostname} {BOLD_BLUE}{cwd}{branch_color}{curr_branch}\n{prompt_end}{NO_COLOR} '

mscottford@blaster ~
$ 
```

**Comment by scopatz** [comment] 2016-06-17 03:16
Hi @mscottford - thanks for reporting!  This might be a silly question, but what command are you running in your container? Is it xonsh?  

We recently started removing PROMPT from foreign shell commands (and stopped inheriting it from the calling env.) because it was causing fatal errors in many cases. The xonsh prompt is not necessarily valid in any other shell.

That said we *remove* the PROMPT variable - or are supposed to (right, @melund?). That means it shouldn't even be an empty string. Is there something in your container that is setting the PROMPT? It should simply provide the default, normally.

**Comment by scopatz** [comment] 2016-06-17 03:17
Also what does just `$(docker-machine env default)` return?

**Comment by melund** [comment] 2016-06-18 19:44
On windows we do a an ` with builtins.__xonsh_env__.swap(PROMPT='$P$G'):`
https://github.com/xonsh/xonsh/blob/master/xonsh/aliases.py#L284

to temporarily set it to a default value (`$P$G`). Are there any default values for POSIX. Is it even used.

**Comment by scopatz** [comment] 2016-06-18 20:50
Nope, PROMPT is not part of posix at all and should just not present

**Comment by mscottford** [comment] 2016-06-20 16:47
Thanks for the replies! Here's the output of running just `$(docker-machine env default)`

```
$ $(docker-machine env default)
'export DOCKER_TLS_VERIFY="1"\nexport DOCKER_HOST="tcp://192.168.99.100:2376"\nexport DOCKER_CERT_PATH="/Users/mscottford/.docker/machine/machines/default"\nexport DOCKER_MACHINE_NAME="default"\n# Run this command to configure your shell: \n# eval $(/usr/local/bin/docker-machine env default)\n'
```

In bash, all that does is set some environment variables that are used to control how the `docker` command functions. A way to replicate this without `docker` would look like this:

```
mscottford@blaster ~
$ $(echo export FIRST_VAR="Foo")
'export FIRST_VAR="Foo"\n'

mscottford@blaster ~
$ source-bash $(echo export FIRST_VAR="Foo")

$PROMPT
''
$FIRST_VAR
'Foo'
```

**Comment by mscottford** [comment] 2016-06-20 16:52
Trying to save `$PROMPT` in a temp variable also doesn't work:

```
mscottford@blaster ~
$ $OLD_PROMPT=$PROMPT

mscottford@blaster ~
$ $OLD_PROMPT
'\n{BOLD_GREEN}{user}@{hostname} {BOLD_BLUE}{cwd}{branch_color}{curr_branch}\n{prompt_end}{NO_COLOR} '

mscottford@blaster ~
$ source-bash $(echo export FIRST_VAR="Foo")
$OLD_PROMPT
''
$PROMPT
''
$FIRST_VAR
'Foo'
```

**Comment by scopatz** [comment] 2016-06-20 18:23
Oh shoot, I know what is happening. This is inadvertently caused by the removal of $PROMPT from env.detype() before a subprocess, and then the source-foreign sees that the prompt is not longer in the env, and assumes it has been removed by the foreign shell, and will thus remove it from the current env.  This should be a pretty quick fix.

**Comment by scopatz** [comment] 2016-06-21 02:17
Ok, @mscottford I can't reproduce this issue:

```
scopatz@artemis ~ $ xonsh --shell-type=readline -DXONSH_COLOR_STYLE=default
scopatz@artemis ~ $ source-bash $(echo export FIRST_VAR="Foo")
scopatz@artemis ~ $ $PROMPT
'{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} '
scopatz@artemis ~ $ $FIRST_VAR
'Foo'
```

I was wrong about the prompt  deletion stuff. That only seems to happen when xonsh first starts up for foreign shells that are loaded at startup.

Are you on master or on v0.3.4

**Comment by mscottford** [comment] 2016-06-22 03:37
I'm on version 0.3.4.

**Comment by mscottford** [comment] 2016-06-22 03:37
I'll give master a try.

**Comment by mscottford** [comment] 2016-06-22 03:47
I'm getting the same problem in master:

```
mscottford@blaster ~/src/xonsh master
$ /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh --shell-type=readline -DXONSH_COLOR_STYLE=default

mscottford@blaster ~/src/xonsh master
$ source-bash $(echo export FIRST_VAR="Foo")
$PROMPT
''
$FIRST_VAR
'Foo'
```

**Comment by scopatz** [comment] 2016-06-22 03:57
What is your prompt normally set to?  What are the contents of your xonshrc / config.json

**Comment by mscottford** [comment] 2016-06-22 04:13
I don't have xonshrc, so everything is getting loaded from config.json.

```
$ cat .config/xonsh/config.json
{
 "env": {
  "PATH": [
    "/Users/mscottford/.pyenv/shims",
    "/Users/mscottford/.plenv/shims",
    "/usr/local/share/npm/bin",
    "/usr/local/heroku/bin",
    "/Users/mscottford/.rbenv/shims",
    "/Users/mscottford/.rbenv/bin",
    "/Users/mscottford/bin",
    "/usr/local/bin",
    "/usr/local/sbin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
    "/usr/X11/bin",
    "/Users/mscottford/.go/bin"
  ],
  "PROMPT": "\n{BOLD_GREEN}{user}@{hostname} {BOLD_BLUE}{cwd}{branch_color}{curr_branch}\n{prompt_end}{NO_COLOR} ",
  "SHELL_TYPE": "best"
 },
 "foreign_shells": [
  {
   "shell": "bash"
  }
 ]
}
```

**Comment by mscottford** [comment] 2016-06-22 04:16
And thanks for helping me dive into this issue.

**Comment by scopatz** [comment] 2016-06-22 04:29
What happens if you get rid of the newline at the front of the PROMPT? There is a ptk bug about this: https://github.com/jonathanslenders/python-prompt-toolkit/issues/310

**Comment by mscottford** [comment] 2016-06-22 15:16
Ah! Good idea. I have a couple of newlines in my prompt. From this output, looks like something is assuming that the prompt is only a single line, because the first line has been preserved, but the second one is missing.

```
mscottford@blaster ~
$ $PROMPT
'{BOLD_GREEN}{user}@{hostname} {BOLD_BLUE}{cwd}{branch_color}{curr_branch}\n{prompt_end}{NO_COLOR} '
mscottford@blaster ~
$ source-bash $(echo export FIRST_VAR="Foo")
mscottford@blaster ~$PROMPT
'{BOLD_GREEN}{user}@{hostname} {BOLD_BLUE}{cwd}{branch_color}{curr_branch}'
mscottford@blaster ~
```

So when the first line of my prompt was `''` then that's what the prompt was set back to.

**Comment by scopatz** [comment] 2016-06-22 15:36
Ahh great! I am now able to reproduce this error.

**Comment by scopatz** [comment] 2016-06-22 17:30
I have figured out that this is because we are naively parsing the `env` command output as being newline delimited.

**Comment by scopatz** [comment] 2016-06-22 18:17
@mscottford - A potential fix is in #1313.  Would you mind trying it out, please?

**Comment by mscottford** [comment] 2016-06-23 02:47
Either it doesn't work or I'm not running from source correctly. Can you tell if there's anything that I've done wrong?

```
mscottford@blaster ~/src/xonsh nlp
$ git branch
  master
* nlp

mscottford@blaster ~/src/xonsh nlp
$ python setup.py install
                           ╓██▄
                          ╙██▀██╕
                         ▐██4Φ█▀█▌
                       ²██▄███▀██^██
                     -███╩▀ " ╒▄█████▀█
                      ║██▀▀W╤▄▀ ▐║█╘ ╝█
                 ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕
                 "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕
                  ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄
               ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗
               █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █
            ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌
           ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫
             ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐
               ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌
                ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌
                 ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌
                  ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M
                  ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║
                   ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █
                   ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌
                    ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █
                     ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌
                      ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █
                       ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌
                         ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █
                          `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ
                            ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘
                              █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀
                               █"█▌▌╟Å╓█╓█▀%`    ▄▀
                               ╙▌██`▒U▓U█%╗*     █
                                ▌╫║ ▌ÅÅ║▀╛¬`      `"█
                                ▌╫  ╫╟ █▄     ~╦%▒╥4^
                                ▌▌  "M█ `▀╕ X╕"╗▄▀^
                                █▌   ╓M   ╙▀e▀▀^
                                ╙██▄▄▀
                                  ^^

running install
Removed xonsh/parser_table.py
Removed xonsh/__amalgam__.py
Building lexer and parser tables.
Amalgamating xonsh
  excluding {'jupyter_kernel',
 'parser_table',
 'parser_test_table',
 'pyghooks',
 'winutils',
 'wizard'}
  collapsed 37 modules
Could not install Jupyter kernel spec, please install Jupyter/IPython.
running build
running build_py
copying xonsh/__amalgam__.py -> build/lib/xonsh
copying xonsh/__init__.py -> build/lib/xonsh
copying xonsh/parser_table.py -> build/lib/xonsh
package init file 'xontrib/__init__.py' not found (or not a regular file)
running build_scripts
running install_lib
copying build/lib/xonsh/__amalgam__.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/__init__.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/parser_table.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/__amalgam__.py to __amalgam__.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/__init__.py to __init__.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/parser_table.py to parser_table.cpython-35.pyc
running install_egg_info
running egg_info
writing top-level names to xonsh.egg-info/top_level.txt
writing entry points to xonsh.egg-info/entry_points.txt
writing xonsh.egg-info/PKG-INFO
writing dependency_links to xonsh.egg-info/dependency_links.txt
reading manifest file 'xonsh.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'xonsh.egg-info/SOURCES.txt'
removing '/Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh-0.3.4-py3.5.egg-info' (and everything under it)
Copying xonsh.egg-info to /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh-0.3.4-py3.5.egg-info
running install_scripts
changing mode of /Users/mscottford/.pyenv/versions/3.5.1/bin/xon.sh to 755
changing mode of /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh to 755

mscottford@blaster ~/src/xonsh nlp
$ changing mode of /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh
xonsh: subprocess mode: command not found: changing

mscottford@blaster ~/src/xonsh nlp
$ /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh

mscottford@blaster ~/src/xonsh nlp
$ source-bash $(echo export FIRST_VAR="Foo")
$PROMPT
''
$FIRST_VAR
'Foo'
```

**Comment by scopatz** [comment] 2016-06-23 02:59
You didn't actually pull down the remote PR branch. You just created a new branch called `nlp` that is the same as master.  In the xonsh source dir you need to run 

```
$ git pull https://github.com/xonsh/xonsh.git nlp
```

And then re-install again.  When you reinstall, you should see that `foreign_shells.py` is updated, which it is not in the output posed above.

**Comment by mscottford** [comment] 2016-06-23 03:03
I ran `git fetch` followed by `git checkout nlp`. `git diff nlp master` seems to match the content of this pull request as well. 

That output wasn't from the initial time that I ran install. Here's that output. I still had the history in my terminal window.

```
mscottford@blaster ~/src/xonsh master
$ git fetch
remote: Counting objects: 174, done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 174 (delta 105), reused 1 (delta 1), pack-reused 0
Receiving objects: 100% (174/174), 57.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (105/105), completed with 1 local object.
From github.com:xonsh/xonsh
   bf68a9f..f94f453  master     -> origin/master
 * [new branch]      nlp        -> origin/nlp
   74d4e6b..1f1a159  pytest_port -> origin/pytest_port

mscottford@blaster ~/src/xonsh master
$ git checkout nlp
Branch nlp set up to track remote branch nlp from origin.
Switched to a new branch 'nlp'

mscottford@blaster ~/src/xonsh nlp
$ python setup.py install
                           ╓██▄
                          ╙██▀██╕
                         ▐██4Φ█▀█▌
                       ²██▄███▀██^██
                     -███╩▀ " ╒▄█████▀█
                      ║██▀▀W╤▄▀ ▐║█╘ ╝█
                 ▄m▀%Φ▀▀  ╝*"    ,α█████▓▄,▄▀Γ"▀╕
                 "▀██¼"     ▄═╦█╟║█▀ ╓ `^`   ,▄ ╢╕
                  ,▀╫M█▐j╓╟▀ ╔▓▄█▀  '║ ╔    ╣║▌  ▀▄
               ▄m▀▀███╬█╝▀  █▀^      "ÜM  j▐╟╫╨▒   ╙▀≡═╤═m▀╗
               █æsæ╓  ╕, ,▄Ä   ▐'╕H   LU  ║║╠╫Å^2=⌐         █
            ▄æ%Å███╠█ª╙▄█▀      $1╙       ║║╟╫╩*T▄           ▌
           ╙╗%▄,╦██▌█▌█╢M         ╕      M║║║║█═⌐ⁿ"^         ╫
             ╙╣▀████@█░█    ▌╕╕   `      ▌║▐▐║█D═≈⌐¬ⁿ      s ║⌐
               ╙╬███▓║█`     ▌╚     ╕   ╕▌║▐▐╣▌⌐*▒▒Dù`       ▐▌
                ╙╬██╨U█      ╟      $ ▌ ▌▌▐▐▐M█▄═≤⌐%       ╓⌐ ▌
                 ║║█▄▌║             ╟ ▌ ▌M▐▐▐M█▀▒▒▒22,       ▐▌
                  ███╙^▌            ║ ▌ ⌐M▐▐▐M█≤⌐⌐¬──        ▐M
                  ║██ ▌╙   ╓       H║ ▌╒ M║▐▐M█"^^^^^"ⁿ      ║
                   ██╕╙@▓   ╕      ▌║ H'  ║▐▐▐█══=.,,,       █
                   ╙█▓╔╚╚█     ╠   ▌└╒ ▌▐ ╚║║║▀****ⁿ -      ╓▌
                    ╙█▌¼V╚▌   ▌  ╕ ▌ ║╒ ║ ▌▒╠█▀≤≤≤≤≤⌐       █
                     ╙█▌╔█╚▌     ┘ M ▌║ ╫ UUM██J^^"        ▐▌
                      ╙██╙█╙▌  ╕$j  ▐⌐▌ ▌║╝╟█Å%%%≈═        █
                       ╙╣█╣█^▌ ╠║▐  ║ ▌▐.DU██^[""ⁿ       -╒▌
                         ▀█▄█`▌ ░M▀ ▌▐ Å£╝╝█╜%≈═╓""w   ⁿ⌐ █
                          `▀▄▀`▌ ▌█▐⌐║▐UW╖██%≤═░*─    =z ▄Γ
                            ╙██╙▄▌█  ▌Å╛╣██╨%╤ƒⁿ=    -` ▄┘
                              █▌╢▓▌▌ W £6█╤,"ⁿ `   ▄≡▀▀▀
                               █"█▌▌╟Å╓█╓█▀%`    ▄▀
                               ╙▌██`▒U▓U█%╗*     █
                                ▌╫║ ▌ÅÅ║▀╛¬`      `"█
                                ▌╫  ╫╟ █▄     ~╦%▒╥4^
                                ▌▌  "M█ `▀╕ X╕"╗▄▀^
                                █▌   ╓M   ╙▀e▀▀^
                                ╙██▄▄▀
                                  ^^

running install
Removed xonsh/parser_table.py
Removed xonsh/__amalgam__.py
Building lexer and parser tables.
Amalgamating xonsh
  excluding {'jupyter_kernel',
 'parser_table',
 'parser_test_table',
 'pyghooks',
 'winutils',
 'wizard'}
  collapsed 37 modules
Could not install Jupyter kernel spec, please install Jupyter/IPython.
running build
running build_py
copying xonsh/__amalgam__.py -> build/lib/xonsh
copying xonsh/__init__.py -> build/lib/xonsh
copying xonsh/aliases.py -> build/lib/xonsh
copying xonsh/environ.py -> build/lib/xonsh
copying xonsh/foreign_shells.py -> build/lib/xonsh
copying xonsh/parser_table.py -> build/lib/xonsh
copying xonsh/tools.py -> build/lib/xonsh
copying xonsh/xoreutils/_which.py -> build/lib/xonsh/xoreutils
package init file 'xontrib/__init__.py' not found (or not a regular file)
running build_scripts
running install_lib
copying build/lib/xonsh/__amalgam__.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/__init__.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/aliases.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/environ.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/foreign_shells.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/parser_table.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/tools.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh
copying build/lib/xonsh/xoreutils/_which.py -> /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/xoreutils
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/__amalgam__.py to __amalgam__.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/__init__.py to __init__.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/aliases.py to aliases.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/environ.py to environ.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/foreign_shells.py to foreign_shells.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/parser_table.py to parser_table.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/tools.py to tools.cpython-35.pyc
byte-compiling /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh/xoreutils/_which.py to _which.cpython-35.pyc
running install_egg_info
running egg_info
writing top-level names to xonsh.egg-info/top_level.txt
writing entry points to xonsh.egg-info/entry_points.txt
writing dependency_links to xonsh.egg-info/dependency_links.txt
writing xonsh.egg-info/PKG-INFO
reading manifest file 'xonsh.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'xonsh.egg-info/SOURCES.txt'
removing '/Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh-0.3.4-py3.5.egg-info' (and everything under it)
Copying xonsh.egg-info to /Users/mscottford/.pyenv/versions/3.5.1/lib/python3.5/site-packages/xonsh-0.3.4-py3.5.egg-info
running install_scripts
changing mode of /Users/mscottford/.pyenv/versions/3.5.1/bin/xon.sh to 755
changing mode of /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh to 755

mscottford@blaster ~/src/xonsh nlp
$ /Users/mscottford/.pyenv/versions/3.5.1/bin/xonsh --shell-type=best -DXONSH_COLOR_STYLE=default

mscottford@blaster ~/src/xonsh nlp
$ source-bash $(echo export FIRST_VAR="Foo")
$PROMPT
''
$FIRST_VAR
'Foo'

```

**Comment by scopatz** [comment] 2016-06-23 03:12
Can you try running from a new terminal? Your current env might be messing up the new xonsh instance that you have running?  Alternatively, in the new xonsh instance, can you do the following and report back:

```
from xonsh import foreign_shells
print(foreign_shells.__file__)
```

This should be the newly installed xonsh....

**Comment by scopatz** [comment] 2016-06-25 17:30
@mscottford can you try master now, please?

**Comment by scopatz** [comment] 2017-02-25 06:16
Hi @mscottford - I am going to assume that this is fixed on master since there have been no further reports of it failing. Please feel free to reopen if it remains an issue!

**Closed by scopatz** 2017-02-25 06:16 UTC
Labels: bug
