### ISSUE TITLE
Auto-suggest flicker when typing a character

### ISSUE THREAD

**Issue by kahrkunne** [xonsh/xonsh#2689] opened 2018-06-20 21:53 UTC
```
$ xonfig info
+------------------+-----------------+
| xonsh            | 0.6.3           |
| Python           | 3.6.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

When an auto-suggestion (the kind turned on when enabling `$AUTO_SUGGEST`) is shown and I type a character it will briefly flicker (disappear, then reappear again). I'd expect (or at least, want) it to not do this.

**Comment by gforsyth** [comment] 2018-06-23 12:15
Hey @kahrkunne , thanks for reporting!  
The flicker is caused by redrawing the prompt on each keypress since we are syntax highlighting input on-the-fly.  Obviously the best solution to this is to make it faster so the flicker isn't appreciable, but in the interim you can disable the syntax highlighting by setting `$COLOR_INPUT=False`

**Comment by kahrkunne** [comment] 2018-06-23 14:09
I don't think that's the case. First of all, the only part that blinks is the auto-suggested part. Setting `$COLOR_INPUT` to `False` also does not alleviate the issue.

**Comment by gforsyth** [comment] 2018-06-23 14:13
Huh.  Well, I could reproduce the flickering this morning but I can't now (I've been reinstalling a bunch of packages, though).  To start, can you try upgrading to `0.6.7`?

**Comment by gforsyth** [comment] 2018-06-23 15:05
Also, @kahrkunne, this may not make a difference, but i uninstalled and reinstalled pygments, so you might try that if the flickering persists

**Comment by kahrkunne** [comment] 2018-06-23 17:21
Neither upgrading to 0.6.7 nor reinstalling pygments solved the problem.

**Comment by gforsyth** [comment] 2018-06-23 17:58
Sorry, @kahrkunne -- I can't seem to reproduce this anymore (although I definitely did have the same issue) and that's making it hard to diagnose.  If it's only the greyed-out auto-suggest bits then you can set `$AUTO_SUGGEST=False` as relief from the flickering, but I understand that that's a less than satisfactory solution.

I don't think that this is part of it, but just so we know, are you installing from the AUR or `pip` or something else?

**Comment by gforsyth** [comment] 2018-06-23 18:13
This seems like a duplicate of #2499

**Closed** 2021-02-12 11:05 UTC
Labels: duplicate
