### ISSUE TITLE
Stdout redirection behaviour

### ISSUE THREAD

**Issue by dosimple** [xonsh/xonsh#2595] opened 2018-03-20 02:31 UTC
```
def fun():
    $[ls /]
@(fun) | grep lib
```

Output from `ls` is displayed without being filtered by `grep`. Then grep hangs.

Should the the expected behaviour be that the output from `ls` being piped to `grep`?

**Comment by scopatz** [comment] 2018-03-23 16:30
Hi @dosimple - you are on the right track, but you are missing a couple of pieces.  Namely, you have to tie the I/O handles together to get the piping behaviour you want.  [Note that](http://xon.sh/tutorial.html#uncaptured-subprocess-with-and), `$[]` is an uncaptured subrpocess and that "the subprocess’s stdout passes directly through xonsh and to the screen."  You probably want to use `!()` instead, so that the output is captured (so that it can be redirected).

Also, your function doesn't accept I/O streams to pass onto.  [From this section](http://xon.sh/tutorial.html#aliases), your function should accept at least the stdout handle.  Therefore you'd probably want something like:

```python
def fun(args, stdin=None, stdout=None):
    for line in !(ls /):
        print(line, file=stdout)

@(fun) | grep lib
```

**Comment by dosimple** [comment] 2018-03-24 10:34
Thank you, scopatz, for the elaborate answare. My original intention was to just force `ls /` to run as subprocess-mode. How would you do it?

Sould uncaptured subprocess be binded to the current stdout by default, what ever it may really be?

**Comment by scopatz** [comment] 2018-04-03 23:43
Hi @dosimple - the problem you are running into is that there are different contexts in which subprocesses can run.  In this particular case, you are running within an alias function, which requires explicit binding if you then want it to behave correctly with other subprocesses.  

In fact, the issue is that each subprocess is connected to the true stdout, but we have no way of knowing that a subprocess is being run within an alias function and should be redirected to be the stdin of the next function.  Maybe we could add this fanciness in the future, but right now xonsh isn't *that* magical.

**Comment by scopatz** [comment] 2018-04-04 15:29
Hi @dosimple - sorry I misunderstood / misread your original example.  

```python
# this...
def fun():
    ls /

# ... is equivalent to
def fun():
    ![ls /]
```

All implicit subprocess commands `ls /` are wrapped by xonsh in the `![cmd]` operator. You can always wrap any command in `![]`, and if fact, doing so makes it easier on the parser by explicitly letting it know that you are running a subprocess.

In the original example you used `$[]`, which runs the command, streams its output, and returns None.  Whereas `![]` returns a command pipeline object.

**Comment by dosimple** [comment] 2018-04-05 04:53
Thanks, `![ls /]` was what I wanted. So apart from the return value, there is a subtle difference, how the outputs of `![ls /]` and `$[ls /]` redirected? This difference is so unexpected to me.

**Comment by scopatz** [comment] 2018-04-05 15:14
Yeah, that is slightly odd, but I think it may be a consequence of blocking behavior. It is worth looking into...

**Comment by gforsyth** [comment] 2018-04-24 23:57
I'm going to close this out as I think the original question is settled, but please reopen if you want to continue the discussion!

**Closed by gforsyth** 2018-04-24 23:57 UTC
Labels: question
