### ISSUE TITLE
Wizard fails on Windows

### ISSUE THREAD

**Issue by Siecje** [xonsh/xonsh#1832] opened 2016-10-11 18:14 UTC
I just install xonsh (`pip install xonsh`) on Windows 10 with Python 3.5 using `cmd`.

When I run `xonsh` it runs the wizard and after I accept the default of no for the first question there is a traceback.

This does not happen if I install `pip install xonsh[ptk]`

To get the full traceback I set `$XONSH_SHOW_TRACEBACK = True` then ran 

``` shell
 $ from xonsh import xonfig
 $ xonfig.xonfig_main(['wizard'])
```

``` shell
# ...
Would you like to load an existing file, yes or no [default: no]?
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 12769, in _wizard
    pv.visit()
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 485, in visit
    rtn = super().visit(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 306, in visit
    rtn = meth(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 543, in visit_wizard
    self.visit(child)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 485, in visit
    rtn = super().visit(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 306, in visit
    rtn = meth(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 639, in visit_load
    do_load = self.visit(asker)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 485, in visit
    rtn = super().visit(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 306, in visit
    rtn = meth(node)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\wizard.py", line 563, in visit_input
    raw = self.shell.singleline(**self.shell_kwargs)
  File "C:\Users\cody\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 14259, in singleline
    readline.remove_history_item(pos)
AttributeError: module 'readline' has no attribute 'remove_history_item'
 $
```

**Comment by scopatz** [comment] 2016-10-14 02:18
Thanks for reporting @Siecje.  I think we basically still require PTK on windows.  You'd have to have cygwin or some other form or readline.  @astronouth7303, is there an easy way to make PTK default on Windows?

**Comment by Siecje** [comment] 2016-10-14 13:34
Check for Windows and add ```prompt-toolkit``` and ```pygments``` to ```install_requires```?

**Comment by scopatz** [comment] 2016-10-14 14:58
Yeah, please anyone feel free to put in a PR for this.

**Comment by astronouth7303** [comment] 2016-10-14 16:56
@scopatz you can detect windows in setup.py and add it to the dependencies, but that means you'll need platform-specific "binary" distributions. (PyPI is currently source only, idk conda.)

@Siecje `ptk` is an extra, so the recommendation for windows today would be `pip install xonsh[ptk]`.

**Comment by scopatz** [comment] 2016-10-14 22:19
Maybe we can changes the windows docs then to reflect this?

**Comment by astronouth7303** [comment] 2016-10-15 01:28
Yeah, I didn't realize the recommendation for windows was so strong, and conda doesn't really do "optional features" well.

**Comment by scopatz** [comment] 2016-10-15 18:15
Yeah, xonsh really doesn't work without PTK on windows is my understanding.

**Comment by melund** [comment] 2016-10-15 19:55
Not true for Windows 10 which support ANSI color codes. I really like readline as it much much faster... If the wizard doesn't work that is not nice. But I don't think the wizards should be presented to new users anyway. We should have well come screen instead and make the wizard optional.

**Comment by laerus** [comment] 2016-10-15 20:23
which terminal application do you use @melund?

 I think we must make readline work on windows and not force PTK as the default. Please correctly me but atm it seems that we only depend on readline for line editing and nothing else, we do history/completions ourselves.

**Comment by melund** [comment] 2016-10-15 20:42
No special terminal application. Just Windows conhost which is what you get when you start cmd.exe...

**Comment by scopatz** [comment] 2016-10-19 00:22
> I think we must make readline work on windows and not force PTK as the default.

Can you explain why we need this? Personally, I think it is a huge waste of time to try to get readline working on systems where it doesn't already exist.  The Jupyter/IPython folks have been burned by readline support historically, and ultimately moved away from it. Just my two cents, but even though, I think we'd happily have better readline support, I would not recommend that folks spend a lot of time on it.

**Comment by laerus** [comment] 2016-10-19 08:53
So windows users can have at least one more option, maybe ptk breaks too in windows for some reason or it's very slow. then we could not run xonsh at all. I mean i know it's a huge pain to make something like this cross-platform, kudos to the ptk guys that managed it, apparently windows doesn't like terminals. But i would expect  xonsh to have a bultin frontend for terminal control in the future (maybe for a fallback mode) with no readline/ptk dependencies, do you think that's something worth working on?

**Comment by laerus** [comment] 2016-10-19 08:58
Btw i'm all for dropping readline on windows, even our wrapper is a little mess, it would benefit from a platform specific refactor. Atm though there is no alternative on windows and i feel that xonsh is getting coupled with ptk a lot.

**Comment by scopatz** [comment] 2017-02-26 20:49
Closing this as a duplicate of the other readline and windows bugs. Please feel free to reopen if needed.

**Closed by scopatz** 2017-02-26 20:49 UTC
Labels: bug
