### ISSUE TITLE
When using "Open In Terminal" option in Nautilus/Nemo, Xonsh starts in ~ instead of the current directory.

### ISSUE THREAD

**Issue by lots0logs** [xonsh/xonsh#441] opened 2015-10-28 02:13 UTC
I can't figure out if this is a configuration error on my part or a yet-to-be-implemented feature. Currently I have gnome-terminal configured to launch `xonsh` instead of my default shell. It always launches it in my home directory. I've tried numerous hacks to make it work but was unsuccessful :confused:

**Comment by auscompgeek** [comment] 2015-10-28 12:36
This is a GNOME Terminal bug, I can reproduce this with every command I've tried.

**Comment by scopatz** [comment] 2015-10-30 03:56
This is almost certainly because whatever program is opening up xonsh/bash/whatever is not setting the `$PWD` variable correctly.

**Comment by lots0logs** [comment] 2015-10-30 04:29
Well it works properly when I don't configure it to launch xonsh instead of bash. It may very well be a gnome-terminal bug, I'm not sure. What is the officially recommended method for using **xonsh** by default for manually launched terminals (obviously it can't be the default for the environment)

**Comment by scopatz** [comment] 2015-10-31 18:50
HI @lots0logs - It seems like gnome-terminal uses the `--working-directory` flag, as you can see [here](http://askubuntu.com/a/250909). If you could figure out what this actually does (does it change the enviornment? does it append arguments to the shell command that it runs?) then would could probably add support pretty easily.  The obvious thing for it to do would be to set $PWD, but they are not doing that.  Maybe they are setting $OLDPWD or $DIRSTACK or something and we are missing that on startup. Thanks

**Comment by lots0logs** [comment] 2015-10-31 20:32
@scopatz I tried to figure that out by setting it to launch a shell script and then dumping the env and command line arguments to a file. There were no command arguments and AFIACT, nothing was added to the env. PWD and CWD were both not set. I'll try and look at the code as soon as I have more time and let you know what I find. Cheers!

**Comment by auscompgeek** [comment] 2015-10-31 23:39
> This is almost certainly because whatever program is opening up xonsh/bash/whatever is not setting the $PWD variable correctly.

Why would changing the working directory directly cause a change to the environment? The current working directory of a process is simply its current working directory, no more. Nothing in the environment changes when a `chdir()` system call occurs.

Anyway, as I mentioned before, this is an issue with GNOME Terminal, nothing else. xonsh doesn't need to do anything, and shouldn't *(mustn't)* do anything. Oddly enough, [it appears this behaviour was intended](https://github.com/GNOME/gnome-terminal/blob/4161dbbb2091c1fa0dd57f86b89955569f2e998d/src/terminal-screen.c#L1347-L1351).

**Comment by scopatz** [comment] 2015-10-31 23:41
Weird - I moved away from gnome-terminal about a 6 months ago because of the design decisions that they were making. Pretty happy with terminator so far.

**Comment by laerus** [comment] 2016-08-03 11:45
this is fixed on current master, feel free to reopen!

**Closed by laerus** 2016-08-03 11:45 UTC
Labels: question
