### ISSUE TITLE
Takes a long time to show prompt

### ISSUE THREAD

**Issue by MareinK** [xonsh/xonsh#2591] opened 2018-03-01 09:58 UTC
When starting xonsh, it takes about a second before the initial prompt is shown. I'm not sure if this is to be expected but it does break up my workflow so I am wondering if there is any way to improve it. I looked around the existing issues on slowness and have gathered the following diagnostics.

First off to show empirically the time it takes to get to the prompt, I run `time xonsh` in bash, then hold down Ctrl+D to get out of the prompt as soon as I can. The result:

```
real	0m1.149s
user	0m1.054s
sys	0m0.207s
```

Compare to `time bash` and holding Ctrl+D:

```
real	0m0.072s
user	0m0.048s
sys	0m0.007s
```

The reason I show the timing in this way, is because the delay does **not** show up in `xonsh --timings`:

```
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.034   |   0.034   |
|post_execer_init  |   0.115   |   0.081   |
|on_pre_rc         |   0.115   |   0.001   |
|on_post_rc        |   0.198   |   0.083   |
|on_ptk_create     |   0.286   |   0.087   |
|on_post_init      |   0.286   |   0.000   |
|on_pre_cmdloop    |   0.286   |   0.000   |
|on_pre_prompt     |   0.286   |   0.000   |
|------------------|-----------|-----------|
```

**Nor** using `time xonsh -c exit`:

```
real	0m0.295s
user	0m0.261s
sys	0m0.035s
```

There is some improvement when using `time xonsh --shell-type readline` and holding Ctrl+D:

```
real	0m0.718s
user	0m0.571s
sys	0m0.099s
```

And a little bit when using `time xonsh --no-rc` and holding Ctrl+D:

```
real	0m1.002s
user	0m0.943s
sys	0m0.185s
```

My  `xontrib list` looks like this:

```
apt_tabcomplete     not-installed  not-loaded
autoxsh             installed      loaded
bashisms            installed      not-loaded
coreutils           installed      not-loaded
distributed         installed      not-loaded
docker_tabcomplete  not-installed  not-loaded
jedi                installed      not-loaded
mpl                 installed      loaded
prompt_ret_code     installed      not-loaded
free_cwd            installed      not-loaded
whole_word_jumping  installed      not-loaded
scrapy_tabcomplete  not-installed  not-loaded
vox                 installed      not-loaded
vox_tabcomplete     not-installed  not-loaded
xo                  not-installed  not-loaded
xonda               not-installed  not-loaded
avox                not-installed  not-loaded
z                   installed      loaded
powerline           not-installed  not-loaded
prompt_vi_mode      not-installed  not-loaded
click_tabcomplete   not-installed  not-loaded
fzf-widgets         not-installed  not-loaded
schedule            not-installed  not-loaded
```

I tried uninstalling `autoxsh` and `z` (couldn't figure out if it was possible to uninstall `mpl`). This seems to have no effect on `time xonsh` and holding Ctrl+D:

```
real	0m1.164s
user	0m1.081s
sys	0m0.210s
```

My `xonfig` is as follows:

```
+------------------+-----------------+
| xonsh            | 0.6.0           |
| Python           | 3.6.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit  |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

I'd love to hear of any possibilities to improve the speed. Please let me know if I can provide any more information.

**Comment by gforsyth** [comment] 2018-03-04 14:29
Hi @MareinK -- thanks for reporting.  

How did you install `xonsh`?  Sometimes a slowdown like this is caused if the parser table is being rebuilt every time  you start.

Also, can you try timing with `xonsh --no-rc` so we can remove any customizations from the timings?  And have you set anything in `~/.config/xonsh/config.json`?

Thanks

**Comment by MareinK** [comment] 2018-03-05 14:54
Hey, thanks for your reply.

I'm on Arch Linux and I installed the [`xonsh` AUR package](https://aur.archlinux.org/packages/xonsh/) using [`yaourt`](https://archlinux.fr/yaourt-en).

Running `time xonsh --no-rc` and holding Ctrl+D:

```
real	0m1.029s
user	0m0.957s
sys	0m0.229s
```

Contents of `~/.config/xonsh/config.json`:

```
{
 "foreign_shells": [
  {
   "shell": "bash"
  }
 ],
 "xontribs": [
  "autoxsh",
  "mpl",
  "z"
 ]
}
```

**Comment by MareinK** [comment] 2018-03-06 09:44
It seems to make a small difference (using `time xonsh --no-rc` and holding Ctrl+D, with `config.json` renamed):

```
real	0m0.972s
user	0m0.891s
sys	0m0.228s
```

**Comment by scopatz** [comment] 2018-03-23 17:55
Thanks for reporting @MareinK!  Wasn't the Arch package broken with exactly this problem @gforsyth? I thought it was fixed, but maybe it has cropped up again.

**Comment by gforsyth** [comment] 2018-03-24 22:44
Yes, it was, and it was fixed, although it may have regressed?

@MareinK can you check in your python `site-packages/xonsh` directory and see if there is a `parser_table.py` file there?  The previous issue with the Arch install resulted in that file being regenerated at each startup, which takes a chunk of time.

It should be in `/usr/lib/python3.6/site-packages/xonsh`

Thanks!

**Comment by aut0** [comment] 2018-07-01 17:29
I have the same issue on arch. When I start xonsh --no-rc --timings:
```
Debug level: Off  
|------------------|-----------|-----------|  
|Event name        | Time (s)  | Delta (s) |  
|------------------|-----------|-----------|  
|start             |   0.000   |   0.000   |  
|pre_execer_init   |   0.050   |   0.050   |  
|post_execer_init  |   0.419   |   0.369   |  
|on_pre_rc         |   0.419   |   0.000   |   
|on_post_rc        |   0.419   |   0.000   |  
|on_ptk_create     |   0.491   |   0.072   |  
|on_post_init      |   0.491   |   0.000   |  
|on_pre_cmdloop    |   0.560   |   0.069   |  
|on_pre_prompt     |   0.560   |   0.000   |  
|------------------|-----------|-----------|
```

When I temporarily rename the parser_table.py
```
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.049   |   0.049   |
|post_execer_init  |   0.110   |   0.062   |
|on_pre_rc         |   0.110   |   0.000   |
|on_post_rc        |   0.111   |   0.000   |
|on_ptk_create     |   2.325   |   2.214   |
|on_post_init      |   2.325   |   0.000   |
|on_pre_cmdloop    |   2.392   |   0.067   |
|on_pre_prompt     |   2.392   |   0.000   |
|------------------|-----------|-----------|
```

How can I help to debug this?

**Comment by anki-code** [comment] 2020-11-04 11:54
Hi @MareinK and @aut0!
Could you please install xonsh from master and try again? Install:
```bash
pip install -U git+https://github.com/xonsh/xonsh
```
If you still see the lags please run:
```bash
# bash
COMMANDS_CACHE_SIZE_WARNING=1 xonsh --timings
```
and post here the output please.

**Comment by MareinK** [comment] 2020-11-04 12:25
Hi @anki-code, I've installed the git version and repeated most of the timings from my original post.

This is on a different computer, so they might not be directly comparable. I'm on Manjaro Linux now.

There seems to be a small reduction, about 10% in most measurements (except for `xonsh --timings`, which gives much higher values).

`time xonsh` while holding Ctrl+D:

```
real	0m1.051s
user	0m0.922s
sys	0m0.212s
```

`time bash` while holding Ctrl+D:

```
real	0m0.059s
user	0m0.006s
sys	0m0.002s
```

`xonsh --timings`:

```
 Debug level: Off
|-------------------------|-----------|-----------|
|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.024   |   0.024   |
|post_execer_init         |   0.093   |   0.068   |
|on_pre_rc                |   0.093   |   0.000   |
|on_post_rc               |   0.103   |   0.010   |
|on_ptk_create            |   0.233   |   0.130   |
|on_post_init             |   0.233   |   0.000   |
|on_pre_cmdloop           |   0.233   |   0.000   |
|on_pre_prompt_format     |   0.233   |   0.000   |
|on_pre_prompt_tokenize   |   0.317   |   0.084   |
|on_post_prompt_tokenize  |   0.616   |   0.299   |
|on_pre_prompt_style      |   0.616   |   0.000   |
|on_post_prompt_style     |   0.683   |   0.067   |
|on_pre_prompt            |   0.683   |   0.000   |
|-------------------------|-----------|-----------|
```

`time xonsh -c exit':

```
real	0m0.272s
user	0m0.228s
sys	0m0.050s
```

`time xonsh --shell-type readline` and holding Ctrl+D:

```
real	0m0.620s
user	0m0.539s
sys	0m0.132s
```

`time xonsh --no-rc` and holding Ctrl+D:

```
real	0m0.993s
user	0m0.875s
sys	0m0.183s
```

And the additional output that you asked for, using `COMMANDS_CACHE_SIZE_WARNING=1 xonsh --timings` (the TRACEBACK and NO_COLOR warnings are also shown when running xonsh normally):

```
Warning! Found 3,751 executable files in the PATH directories!
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
NO_COLOR is deprecated and should be replaced with RESET.
 Debug level: Off
|-------------------------|-----------|-----------|
|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.023   |   0.023   |
|post_execer_init         |   0.092   |   0.069   |
|on_pre_rc                |   0.092   |   0.000   |
|on_post_rc               |   0.102   |   0.010   |
|on_ptk_create            |   0.233   |   0.130   |
|on_post_init             |   0.233   |   0.000   |
|on_pre_cmdloop           |   0.233   |   0.000   |
|on_pre_prompt_format     |   0.233   |   0.000   |
|on_pre_prompt_tokenize   |   0.313   |   0.080   |
|on_post_prompt_tokenize  |   0.582   |   0.268   |
|on_pre_prompt_style      |   0.582   |   0.000   |
|on_post_prompt_style     |   0.653   |   0.072   |
|on_pre_prompt            |   0.654   |   0.000   |
|-------------------------|-----------|-----------|
```

I hope this information is useful!

As in my original post, the 1-second lag (compared to milliseconds for bash) is enough to keep me from integrating xonsh in my workflow, so I won't close the issue.

**Comment by anki-code** [comment] 2020-11-04 12:45
@MareinK thank you for the fast feedback and the logs!

Not the when you measure the first start you can get x2 time than other runs because it takes time to compile Python code. The best way is to do 3-5 runs and then measure the time.

As I see you have 1 sec on `xonsh --no-rc` and it's strange.

**Comment by anki-code** [comment] 2020-11-04 13:06
> and holding Ctrl+D:

Alternative:
```python
# bash
echo 'import time; print(time.time())' > time.py
TIME=$(python time.py) xonsh -c 'import time; print(time.time()-float($TIME))' -i --no-rc
TIME=$(python time.py) xonsh -c 'import time; print(time.time()-float($TIME))' -i
```
On Ubuntu 20.04 I have around 1 sec with my huge RC and around 0.13 sec with no-rc.

**Comment by MareinK** [comment] 2020-11-04 13:06
> @MareinK thank you for the fast feedback and the logs!

No problem!

> Note that when you measure the first start you can get x2 time than other runs because it takes time to compile Python code. The best way is to do 3-5 runs and then measure the time.

I ran just `xonsh` a bunch of times in the terminal before doing any of the timings, to account for the possibility of something like that. I also repeated most of the timings a number of times to make sure I didn't have a bad case.

**Comment by MareinK** [comment] 2020-11-04 13:11
> > and holding Ctrl+D:
> 
> Alternative:
> 
> ```python
> # bash
> echo 'import time; print(time.time())' > time.py
> TIME=$(python time.py) xonsh -c 'import time; print(time.time()-float($TIME))' -i --no-rc
> TIME=$(python time.py) xonsh -c 'import time; print(time.time()-float($TIME))' -i
> ```
> 
> On Ubuntu 20.04 I have around 1 sec with my huge RC and around 0.13 sec with no-rc.

Interesting method! I got 0.24 and 0.27 seconds respectively. That is in the order of the commands in your snippet.

**Comment by anki-code** [comment] 2020-11-04 13:13
Hm... In this case I don't understand why you got:
>time xonsh --no-rc and holding Ctrl+D:
> real	0m0.993s

**Comment by anki-code** [comment] 2021-02-13 19:36
I'm going to close this issue because I can't reproduce and this looks like issue with the user`s system. Only diving into xonsh source code on this system can help.

We need to improve the timing mode for this cases.

**Closed by anki-code** 2021-02-13 19:36 UTC
