### ISSUE TITLE
Setup fails without setuptools

### ISSUE THREAD

**Issue by rtpg** [xonsh/xonsh#1922] opened 2016-11-01 12:47 UTC
there seems to be some `setup.py` infrastructure for handling lack of setuptools, but I just tried (on a clean machine with just python3 and pip) to install `xonsh` and it was failing due to lack of `setuptools`.

 ```
>>> pip3 install xonsh

Collecting xonsh
  Using cached xonsh-0.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vtu34nl8/xonsh/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by astronouth7303** [comment] 2016-11-01 13:47
What's your OS? I was under the impression that pip required `setuptools`.

**Comment by rtpg** [comment] 2016-11-01 15:09
This was a fresh Ubuntu 16.04 instance. I installed `pip` via the `python3-pip` package [found here](http://packages.ubuntu.com/yakkety/python3-pip). This might not have been the best way to go about things

**Comment by scopatz** [comment] 2016-11-01 15:38
Thanks for reporting @rtpg. I don't think that this is a xonsh issue.  @astronouth7303 is right that pip requires setuptools...

**Comment by astronouth7303** [comment] 2016-11-01 16:08
@rtpg No, that should be a case we support...

That's extremely odd. `python3-pip` only _suggests_ `python3-setuptools`.

Oh. I think I can see how that can be. pip does use setuptools for its own `setup.py`, and the usual independent install scripts (ie `get-pip.py`) will install it. However, since deb packages are less "do these things" and more "unpack this bundle", it doesn't need to run `setup.py` and therefore doesn't need setuptools.

However, I'm very certain that this was the wrong choice on ubuntu's part just because of the amount of packages that implicitly depend on setuptools.

**Comment by Siecje** [comment] 2016-11-01 16:08
It is possible to install ```pip``` without ```setuptools``` but you can't install sdist or vcs distributions, only wheels.

**Comment by gforsyth** [comment] 2016-11-01 16:22
Should we just shell out to `get-pip.py` or something similar if setuptools is unavailable?

**Comment by scopatz** [comment] 2016-11-01 16:24
@gforsyth in general? Or when run from pip?

**Comment by Siecje** [comment] 2016-11-01 16:25
@gforsyth To install setuptools?
@scopatz How would you tell it was run from pip?

**Comment by scopatz** [comment] 2016-11-01 16:26
@Siecje Beats me, hopefully there is a way, though.

**Comment by gforsyth** [comment] 2016-11-01 16:40
@scopatz I guess I was thinking just generally -- there's still the edge case of having python and no pip
@Siecje yeah, that was my thought

**Comment by scopatz** [comment] 2016-11-01 16:43
@gforsyth -  Yeah, I'd really prefer to not require setuptools or pip.  setuptools - via pkg_resources - was responsible for so much of the startup slow down I have lost trust in it until it undergoes a serious refactor and have started removing it from most other projects I work on. It isn't worth it in my opinion.

**Comment by Siecje** [comment] 2016-11-01 16:57
From a fresh Ubuntu 16.04 Server when I install ```python3-pip``` I get ```setuptools```.

**Comment by Siecje** [comment] 2016-11-01 17:07
Another thing that is strange is that with that version of ```pip``` you should get a message if you don't have ```setuptools```.

```
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
```

**Comment by rtpg** [comment] 2016-11-02 01:47
Odd, I don't think I did anything particular to my 16.04 setup... the main thing here that is weird to me is that xonsh's `setup.py` clearly has code for the "no `setuptools`" state, but it doesn't seem to actually handle that state properly?

 This might be an issue with how my machine was setup but like I said I haven't really done anything on this machine yet.

**Comment by Siecje** [comment] 2016-11-02 14:14
@rtpg To install ```pip``` you did ```sudo apt-get install python3-pip```?

Can you see if you get an error when you do

```shell
$ python3
>>> import setuptools
```

I believe something about your setup is confusing the check inside ```pip``` about whether ```setuptools``` is available.

**Comment by Siecje** [comment] 2016-11-03 14:25
Okay I am able to reproduce this.

Starting from a fresh Ubuntu Server 16.04
```shell
$ sudo apt-get update
$ sudo apt-get install python3-pip
$ sudo apt-get remove python3-wheel
$ sudo apt-get remove python3-setuptools
$ sudo apt-get remove python3-dev
$ pip3 install xonsh
```

**Comment by Siecje** [comment] 2016-11-03 14:38
When I upgrade pip to 9.0.0 with 

```shell
$ pip3 install --upgrade pip
```

I was surprised that ```sudo``` wasn't required.

The proper error message that setuptools is required is shown.

```
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
```

I vote to close this.

**Comment by scopatz** [comment] 2016-11-03 16:55
I am happy to close this with the note to update pip. Does that sound OK to the rest of you?

**Comment by astronouth7303** [comment] 2016-11-03 21:04
Yeah. Given just how much of the Python community now implicitly depends on setuptools, I'm not sure this is something we should expend a lot of effort fixing.

**Closed** 2016-11-18 21:08 UTC
