### ISSUE TITLE
bottom terminal line unused

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#2828] opened 2018-09-19 18:51 UTC
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.7.9           |
| Python           | 3.6.6           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit1 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | Fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

hitting return a number of times I expect to reach the bottom line of the terminal

## Current Behavior

the bottom line in the terminal window is always empy

## Steps to Reproduce

just keep hitting the return key in a terminal window

**Comment by scopatz** [comment] 2018-09-21 14:44
Hi @mburo - Do you see this on PTK v2 as well?

**Comment by mburo** [comment] 2018-09-21 18:20
Sorry, but I don't know how to test that

**Comment by MrQubo** [comment] 2018-09-21 19:56
It's the same for me. The problem isn't present on ptk2. It looks like this:
![screenshot_20180921_214338](https://user-images.githubusercontent.com/16545322/45902708-a483db80-bde7-11e8-8324-015c40ade003.png)
As you can see hitting <kbd>Enter</kbd> prints one new prompt line but leaves the bottom line empty.

**Comment by MrQubo** [comment] 2018-09-21 20:02
@mburo On ArchLinux installing `community/python-prompt_toolkit` from `pacman` yields outdated `1.0.15-2` version. It might be similar on other distributions and package managers. You can install the latest `prompt_toolkit` with `pip`.

**Comment by gforsyth** [comment] 2018-09-25 13:19
The bottom line is currently reserved for the bottom toolbar.  It should be possible to only use that space when the toolbar is set to something, but it will require editing the prompt layout that we inherit from prompt toolkit.

**Comment by mburo** [comment] 2018-09-25 15:17
I think it wouold help xonsh to be adopted more if it behaved like bash out of the box without resorting to semi-hidden tweaks

**Comment by scopatz** [comment] 2018-09-25 15:28
If you want a more bash like experience, you can use the readline shell, instead of prompt toolkit

**Comment by anki-code** [comment] 2021-01-30 21:17
This issue looks not actual - the bottom line is used in the latest xonsh 0.9.25:

![image](https://user-images.githubusercontent.com/1708680/106368276-80424d00-6359-11eb-9ff2-fa6f2183ccf1.png)

@gforsyth please close this issue.

**Closed** 2021-01-30 21:43 UTC
Labels: bug
