### ISSUE TITLE
Background color escape character does not end when line ends if line wraps in some terms

### ISSUE THREAD

**Issue by gregdan3** [xonsh/xonsh#4246] opened 2021-04-26 20:54 UTC
## xonfig
Default config on fresh install.

<details>
```
gregdan3@Theros ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.9.27          |
| Python           | 3.9.3           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.18          |
| shell type       | prompt_toolkit  |
| pygments         | 2.8.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```
</details>

## Expected Behavior
Background color escape character should be capped by a reset character regardless of if the input line ended on the same line of the terminal or not.

For reference, the target behavior in `fish` running in `st`:

![2021-04-26-153742_485x65_scrot](https://user-images.githubusercontent.com/28300107/116147461-47ebaa00-a6cf-11eb-86a0-13d74b9ff02a.png)

The object, which is a broken symlink, changes its color and background color when printed. My terminal is not wide enough to fit the whole line, so it wraps, but there is still an applied reset character.

## Current Behavior
![2021-04-26-154425_899x119_scrot](https://user-images.githubusercontent.com/28300107/116148264-35be3b80-a6d0-11eb-8609-217740a46fe4.png)
No reset character is applied onto the end of a wrapped line containing a background color escape character.
This does not occur if the line is wrapped but ends before another background color escape character begins, or if the line never wraps.

## Steps to Reproduce
Run a command that prints a background color escape character into the terminal that would cover too much text to print on one line, i.e. such that the text wraps. Observe that the background color continues beyond the end of the wrapped text, to the end of the wrapped line.

I was able to replicate this issue in `st` and `urxvt`. I could not replicate it in Termite.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment] 2021-04-27 07:45
I can reproduce this in Konsole on Arch:
```python
# Open Konsole window and make it small

xonsh --no-rc
cd /tmp
ln -s qwe/qwe/qwe/qwe/qwe/qwe/qwe/qwe qwe
ls -la
```
The result:
![image](https://user-images.githubusercontent.com/1708680/116204499-81f79300-a745-11eb-90ca-a35436f5b85d.png)

**Comment by anki-code** [comment] 2021-04-27 07:46
Hi @dyuri ! Could you please take a look into this?

**Comment by dyuri** [comment] 2021-04-27 07:59
This might not be `xonsh` related, but `LS_COLORS` and terminal specific, works fine in `kitty` for me:
![image](https://user-images.githubusercontent.com/126637/116206590-41951680-a73f-11eb-9181-de04aa1da5a5.png)

(Going to take a look though.)

**Comment by dyuri** [comment] 2021-04-27 08:03
Yep, fails in `xterm` + `bash` combo as well (with the same `LS_COLORS`):
![image](https://user-images.githubusercontent.com/126637/116207080-c7b15d00-a73f-11eb-9b73-c785c5c294a6.png)

**Comment by anki-code** [comment] 2021-04-27 08:44
Thanks @dyuri ! What if you will run bash not from xonsh? I mean that maybe the xonsh has wrong LS_COLORS?

If we can repeat the issue just for bash and terminal we can close this issue as unrelated to xonsh.

**Comment by dyuri** [comment] 2021-04-27 08:53
Well, when using `xterm -e bash`, it's even stranger:
![image](https://user-images.githubusercontent.com/126637/116214262-d2bbbb80-a746-11eb-91ff-28f2d290797e.png)

Sometimes OK, sometimes buggy.

**Comment by anki-code** [comment] 2021-04-27 09:02
Thanks @dyuri! We can repeat this in bash without using xonsh.
I've also retested the `xonsh --no-rc` in fresh Konsole and can't repeat the issue.
@gregdan3 this looks like terminal emulator issue and I'm going to close this issue until we have detailed info that based on experiments with bash.

**Closed by anki-code** 2021-04-27 09:02 UTC
