### ISSUE TITLE
`parallel` command failed on xonsh

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#1820] opened 2016-10-09 10:35 UTC
Running `seq 10 | parallel echo` fails on xonsh (works on bash) while `seq 10 | xargs echo` works

also seems related to #1758

**Comment by astronouth7303** [comment] 2016-10-10 13:15
What version of xonsh?

Where is parallel from?

**Comment by blahgeek** [comment] 2016-10-11 03:54
I'm using current master version of xonsh (b8e4adbaf3b)

parallel is installed from homebrew (GNU parallel 20160922).

I did some more tests:

```
seq 10 | parallel echo  # does not work
seq 10 > tmp.txt
parallel echo < tmp.txt  # this works
```

I think this bug may be related some complex behaviors in parallel (e.g. fork, stdout/stderr redirect, etc.) but is not specific to parallel 

I can confirm that this bug is introduced by #1758 , so maybe @scopatz would like to take a look? Thanks!

**Comment by blahgeek** [comment] 2016-10-11 04:04
ps: `ls | parallel ls` also fails (it's more generic since `echo` is a shell builtin)

**Comment by scopatz** [comment] 2016-10-11 04:32
Yeah, I'll take a look. Sorry about the issues you have been having

**Comment by scopatz** [comment] 2016-10-14 03:38
This might actually be a bug with parallel exiting too soon if the stdin buffer is not full / contains an EOF.  Note that both `seq 100000 | parallel echo` and `sleep 0.1 | seq 10 | parallel echo` work for me.  Also, echo is not a builtin in xonsh (or in Bash I don't think if it is an argument to another command).

**Comment by scopatz** [comment] 2016-10-14 03:42
Note that the bug seems to be present no matter if we use Popen or PopenThread.

**Comment by scopatz** [comment] 2016-10-14 03:44
Or maybe we are just doing it wrong...

**Comment by scopatz** [comment] 2016-10-14 05:26
Ok, I have a tentative fix, but I am not happy with it yet.  Let me think on this one some more....

**Comment by scopatz** [comment] 2016-10-16 15:25
Hi @blahgeek, can you try out #1859, which fixes this issue for me, please? Thanks!

**Comment by blahgeek** [comment] 2016-10-16 15:38
@scopatz Thanks a lot! But it does not seem work for me. If I run `seq 10 | parallel echo`, xonsh freezes about 1 second and then prints only the header part of parallel and exit:

```
> seq 10 | parallel echo
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence the citation notice: run 'parallel --citation'.
```

**Comment by scopatz** [comment] 2016-10-16 16:01
Ok! can you try it now, please?

**Comment by blahgeek** [comment] 2016-10-17 00:34
No, there's still no output :(

https://asciinema.org/a/3h4428xlqy23u8vc9cz06n2sz

**Comment by scopatz** [comment] 2016-10-19 00:17
Hi @blahgeek, that fix should have worked.  Can you do another asciinema where you run `xonfig` so we can be sure that you are actually on that branch, please? Thanks

**Comment by blahgeek** [comment] 2016-10-19 02:36
sure

here it it: https://asciinema.org/a/0roas6lliscd17pr7cx7e001d

**Comment by scopatz** [comment] 2016-10-19 04:33
I am inclined to say that you are having some mac specific problem.  That other PR fixes it for me on Ubuntu and should probably be merged in regardless of the additional issue here, which we can continue to work through.  I don't have access to a mac to try to debug this though, so any additional information you can give me would be most helpful.

**Comment by blahgeek** [comment] 2016-10-20 10:11
Hi @scopatz I found that if I set **both** `$XONSH_PROC_FREQUENCY = 0.01` **and** `$PARALLEL_SHELL = '/bin/bash'` then it will work, does that make any sense?

**Comment by scopatz** [comment] 2017-03-03 06:03
Just checking in to see if this is still an issue @blahgeek.

**Comment by mitnk** [comment] 2017-03-03 10:06
Just checked these two command on mac: `ls | parallel ls` and `seq 10 | parallel echo`. Both works for me.

**Comment by gforsyth** [comment] 2019-07-14 17:01
We haven't been able to reproduce this and there doesn't seem to be much movement.  I'm closing it, but please ping if you have followup questions or comments.

**Closed by gforsyth** 2019-07-14 17:01 UTC
Labels: bug-irreproducible, mac osx
