### ISSUE TITLE
Tab completion fails with IndexError on Windows

### ISSUE THREAD

**Issue by sopoforic** [xonsh/xonsh#2305] opened 2017-03-08 19:04 UTC
I have a directory:

```
$ ls
.  ..  __pycache__  bot.py  db.py  sleepy-bot.conf  sleepy.db
```

If I type `py[TAB]` I get the expected selection of possible completions beginning with 'py'. If, instead, I type `python [TAB]`, I get an Exception:

```
$ python Exception in thread Thread-81:
Traceback (most recent call last):
  File "C:\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python35-32\lib\site-packages\prompt_toolkit\interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Python35-32\lib\site-packages\xonsh\ptk\completer.py", line 49, in get_completions
    self.ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\completers\__amalgam__.py", line 1442, in complete_from_bash
    command = xp.bash_command()
  File "C:\Python35-32\lib\site-packages\xonsh\__amalgam__.py", line 1664, in bash_command
    bc = windows_bash_command()
  File "C:\Python35-32\lib\site-packages\xonsh\__amalgam__.py", line 1629, in windows_bash_command
    bash_works = 'pc-linux-gnu' not in out.splitlines()[0]
IndexError: list index out of range
```

I get the same result with e.g. `python b[TAB]`.

My xonfig:

```
+------------------+---------------------+
| xonsh            | 0.5.7               |
| Git SHA          | f35ac0f             |
| Commit Date      | Mar 1 02:53:16 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | False               |
| prompt toolkit   | 1.0.3               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | False               |
| on linux         | False               |
| on darwin        | False               |
| on windows       | True                |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by gforsyth** [comment] 2017-03-08 21:01
Hi @sopoforic -- thanks for reporting! 
So it looks like a problem with detecting whichever version of bash you have installed is causing this error. The `py<tab>` completions work since that's hitting our python-based completer. The failure is coming when we fall back to the bash completion since we don't find anything python-based to complete.

Is there any output from 

```console
which bash
```

or

```console
bash --version
```

when you run those commands within xonsh?

And is this Windows 10? And do you have the Windows Subsystem for Linux?

Thanks!

**Comment by sopoforic** [comment] 2017-03-08 22:31
Windows 10, yes. I have the Windows Subsystem for Linux installed, though I don't use it.

`which bash` gives:

```
$ which bash
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'PATH'
```

`bash --version` returns with no output.

**Comment by gforsyth** [comment] 2017-03-08 22:34
Ahh, ok. So there's no `bash` on path and we used to catch that exception. Maybe @melund can help out with this?

**Comment by gforsyth** [comment] 2017-03-08 22:37
Wait... what? This is weird. It's entering the `if bash_on_path` in https://github.com/xonsh/xonsh/blob/master/xonsh/completers/bash_completion.py#L34 but it shouldn't...

@sopoforic can I ask you to try the following in a Python session and tell me what the output is?

```python
import shutil
shutil.which('bash')
```

Thanks!

**Comment by sopoforic** [comment] 2017-03-09 00:03
```
>>> import shutil
>>> shutil.which('bash')
'C:\\Program Files\\OpenSSH\\bin\\bash.EXE'
```

**Comment by melund** [comment] 2017-03-09 07:28
@sopoforic 

The problem with `which` 
```
which bash
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'PATH'
```
is a regression in 0.5.7. I it fixed on master and 0.5.8. I don't know if that is what triggers the first bug. What is the output of `C:\\Program Files\\OpenSSH\\bin\\bash.EXE`? 

Btw. I can recommend the having bash from "git for windows" installed. It will give you git completions tab completions in xonsh.

**Comment by melund** [comment] 2017-03-09 07:56
I have put in a fix @2307.  @sopoforic Can you see if it fixes it for you?

**Comment by sopoforic** [comment] 2017-03-09 14:37
I get an exception from a different place with that version:

```
$ python boException in thread Thread-73:
Traceback (most recent call last):
  File "C:\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python35-32\lib\site-packages\prompt_toolkit\interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Python35-32\lib\site-packages\xonsh\ptk\completer.py", line 49, in get_completions
    self.ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\completers\__amalgam__.py", line 1444, in complete_from_bash
    command=command, quote_paths=_quote_paths)
  File "C:\Python35-32\lib\site-packages\xonsh\completers\__amalgam__.py", line 376, in bash_completions
    complete_stmt = out[0]
IndexError: list index out of range
```

**Comment by sopoforic** [comment] 2017-03-09 16:34
Oh, I missed a part. `C:\\Program Files\\OpenSSH\\bin\\bash.EXE --version` returns with no output. Running it without the switch does the same thing. I wonder if that's the expected behavior for that program--it's a tiny 8kb file, whereas git bash's sh.exe is over 500kb.

**Comment by astronouth7303** [comment] 2017-03-09 16:39
@sopoforic how many bashes do you have installed?

**Comment by sopoforic** [comment] 2017-03-09 17:15
Three, as far as I can see--one from OpenSSH, one from git, and one from Windows.

**Comment by melund** [comment] 2017-03-09 19:43
It does seem like the ssh bash is not functional. Of course the bash completer shouldn't crash even if bash misbehaves. I have pushed a new commit that should fix that. Can you give it a try?

However, it shouldn't pick that version of bash if you have bash from "git for windows" installed. Can you try to do:
```
snail@sea ~\Documents\xonsh bashwin
$ from xonsh.platform import windows_bash_command
snail@sea ~\Documents\xonsh bashwin
$ windows_bash_command()
'C:\\Program Files\\Git\\bin\\bash.exe'
```
What does it return on your machine?

**Comment by sopoforic** [comment] 2017-03-09 21:51
```
$ windows_bash_command()
'bash'
```

**Comment by melund** [comment] 2017-03-09 22:08
This tells me that it haven't found git for windows, and then falls back to whatever is on the path. What is the output of 
```
snail@sea ~ 
$ from xonsh.platform import git_for_windows_path
snail@sea ~ 
$ git_for_windows_path()
```

**Comment by sopoforic** [comment] 2017-03-09 22:09
It returns with no output.

**Comment by melund** [comment] 2017-03-09 22:21
So what the last function does is  look in the registry to find where git for windows is installed. 
```python
def git_for_windows_path():
    """Returns the path to git for windows, if available and None otherwise."""
    import winreg
    try:
        key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                             'SOFTWARE\\GitForWindows')
        gfwp, _ = winreg.QueryValueEx(key, "InstallPath")
    except FileNotFoundError:
        gfwp = None
    return gfwp
````

Can you manually check what the entry for GitForWindows is in your registry? Then we can make the code a bit more generic.

**Comment by sopoforic** [comment] 2017-03-09 22:32
My installed git is fairly old--msysgit 1.9.5. There's a key pointing to it at `HKEY_CURRENT_USER\SOFTWARE\Git-Cheetah` called `PathToMsys`. So perhaps this is a problem that I can solve for myself by updating git; of course it'll be good to support the old version in case others have the same issue.

**Comment by melund** [comment] 2017-03-10 05:09
Ahh. That is certainly the issue. I may look at adding that. 

Without upgrading, do you still get the tab-completion crashes with #2307 ?

**Comment by sopoforic** [comment] 2017-03-10 22:56
With 95c1fe5 I get:

```
$ python instException in thread Thread-335:
Traceback (most recent call last):
  File "C:\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python35-32\lib\site-packages\prompt_toolkit\interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Python35-32\lib\site-packages\xonsh\ptk\completer.py", line 49, in get_completions
    self.ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "C:\Python35-32\lib\site-packages\xonsh\completers\__amalgam__.py", line 1444, in complete_from_bash
    """Xonsh hooks into bash completions."""
  File "C:\Python35-32\lib\site-packages\xonsh\completers\__amalgam__.py", line 376, in bash_completions
    try:
IndexError: list index out of range
```

**Comment by melund** [comment] 2017-03-11 08:22
`try: ` seems like a weird line to report such an error from.

@scopatz Could there be something wrong with how lines are reported? 

@sopoforic Can you try to run xonsh in debug mode. If you start xonsh from CMD then run the following before starting xonsh : 

```
set XONSH_DEBUG=1
``` 

It will prevent all the source code from being squashed into a single module (the `__amalgam__.py`), and make it a little easier to interpret the traceback

Also try to run the `xonfig` in xonsh and report the output.

**Comment by sopoforic** [comment] 2017-03-11 09:48
```
C:\Users\Tracy>set XONSH_DEBUG=1

C:\Users\Tracy>xonsh
Tracy@Archimedes ~
$ xonfig
+------------------+-----------------------------------------------+
| xonsh            | 0.5.8.dev5                                    |
| Git SHA          | 95c1fe5                                       |
| Commit Date      | Mar 9 15:30:59 2017                           |
| Python           | 3.5.2                                         |
| PLY              | 3.9                                           |
| have readline    | False                                         |
| prompt toolkit   | 1.0.3                                         |
| shell type       | prompt_toolkit                                |
| pygments         | 2.1.3                                         |
| on posix         | False                                         |
| on linux         | <xonsh.lazyasd.LazyBool object at 0x03213450> |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x03220650> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

Some weird behavior, now. That copy of xonsh I ran from cmd.exe doesn't exhibit the crash. I opened a new xonsh in my usual way (a new tab in conemu) and it doesn't crash either. An instance of xonsh I had running from before opening xonsh in cmd.exe does still exhibit the crash.

xonsh in conemu:

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.8.dev5          |
| Git SHA          | 95c1fe5             |
| Commit Date      | Mar 9 15:30:59 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | False               |
| prompt toolkit   | 1.0.3               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | False               |
| on linux         | False               |
| on darwin        | False               |
| on windows       | True                |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

The `xonfig` output is identical in the crashing and non-crashing instances of xonsh-in-conemu.

**Comment by melund** [comment] 2017-03-11 16:37
Yes. You probably didn't install correctly​. Maybe there is some issues if xonsh  is running while installing. Just a guess. Xonfig can not always be trusted in these cases. @santagada  also reported something similar with xonfig.   https://github.com/xonsh/xonsh/issues/2306#issuecomment-285815689

It seemed like the fix actually worked. So that is great.

**Comment by melund** [comment] 2017-03-11 16:37
It

**Comment by melund** [comment] 2017-03-11 20:01
Hmm. Did I just delete my post. Damn phone. 

Maybe something went wrong when installing. Could it happen if xonsh is running while installing? Just a guess. 

The issue with `xonfig` is a bit weird. @santagada reported something similar here: https://github.com/xonsh/xonsh/issues/2306#issuecomment-285815689 

Anyway. Seems like the fix in #2307 is working. That is at least something.

**Comment by sopoforic** [comment] 2017-03-11 20:27
I installed it by cloning the branch and doing `python setup.py install`, and I don't remember seeing any errors. Certainly files got properly replaced and the new version shows in on `xonfig`, at any rate.

I don't see anything strange about my `xonfig` output, though--that commit is the head of the branch in PR #2307, so it's showing the right thing.

**Comment by melund** [comment] 2017-03-11 21:05
This also what I normally do. But I have also seen some strange behaviour in rare cases. Maybe some of the *.pyc fails to update. I really don't know what is causing it.

**Comment by melund** [comment] 2017-03-11 21:06
Do you get the correct git completions if you update to the newest versiono of 'Git for Windows' ?

**Closed** 2017-03-12 00:21 UTC
Labels: bug, windows

**Comment by sopoforic** [comment] 2017-03-14 11:49
If by git completions you mean something like `git sh[TAB]` offering me `git show`, then I don't get that after updating, and I don't believe that I ever have in the past.

**Comment by melund** [comment] 2017-03-14 11:56
No. I was a bit unclear. I meant completions of branch names etc. 

```
git checkout ma<tab>
```

**Comment by sopoforic** [comment] 2017-03-14 12:00
No, I don't have that, either (except for it completing commands I've already typed).

**Comment by melund** [comment] 2017-03-16 11:32
@sopoforic .. Hmm. That is not how it should work. Here is screen shot from my terminal: 

![image](https://cloud.githubusercontent.com/assets/1038978/23994214/255985ba-0a44-11e7-8d43-27aa2dbfea73.png)

Did you update to newest 'Git for Windows'? 

If so the following you should get follwoing when running:
```
$ from xonsh.platform import bash_command
snail@sea ~
$ from xonsh.platform import bash_command, git_for_windows_path
snail@sea ~
$ git_for_windows_path()
'C:\\Program Files\\Git'
snail@sea ~
$ bash_command()
'C:\\Program Files\\Git\\bin\\bash.exe'
```

**Comment by sopoforic** [comment] 2017-03-16 12:28
I updated to the newest Git for Windows, yes.

```
$ from xonsh.platform import bash_command, git_for_windows_path
Tracy@Archimedes ~\Dropbox\code
$ git_for_windows_path()
Tracy@Archimedes ~\Dropbox\code
$ bash_command()
'bash'
```

My registry now has the key you mentioned previously: `HKEY_LOCAL_MACHINE\SOFTWARE\GitForWindows` has `InstallPath` set to `C:\Program Files\Git`, and I have a file `'C:\Program Files\Git\bin\bash.exe` which correctly starts bash when run.

**Comment by melund** [comment] 2017-03-16 12:55
So the `git_for_windows_path()` returns None for you? I am a bit out of ideas for now.

**Comment by melund** [comment] 2017-03-16 12:56
You can create bug report on this so we don't forget..
