### ISSUE TITLE
Odd behavior when previous output doesn't end with a newline

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#977] opened 2016-05-22 00:11 UTC
Try:

```
ryan@DevPC-LX ~ $ printf 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaryan@DevPC-LX ~ $ 
```

The cursor will end up in the middle of all the `a`s, so things that you type don't quite look right. (Try `echo "Hello, world!"`; the quote will cause some interesting results!)

**Comment by scopatz** [comment] 2016-05-22 00:18
This is true for many shells, and I believe is the correct behaviour. The shell shouldn't insert a newline for you that doesn't exist. Happy to have a conversation about it, but that is why it works the way it does now.

**Comment by kirbyfan64** [comment] 2016-05-22 00:30
@scopatz I understand. To me the bug isn't in the lack of newlines. If you actually try typing something, the cursor will always end up in the middle of the line. I mean, I *guess* it's technically ok, but, when you mesh it with what happens when you type in quotes like this, the result is a little...bizarre...

**Comment by scopatz** [comment] 2016-05-22 00:32
Oh yeah... that is a bug.  This may then be a duplicate of #959.

**Comment by laerus** [comment] 2016-09-01 00:34
i'm closing this since this is the behavior we actually want,
as for the other bug this seems solved on current master
```
>>> printf 'aaaaaaaaaaaa'
aaaaaaaaaaaa>>> | <--cursor here
```
feel free to reopen though!

**Closed by laerus** 2016-09-01 00:34 UTC
Labels: bug, question
