### ISSUE TITLE
`history` command shows 'fc' is not installed

### ISSUE THREAD

**Issue by metalseargolid** [xonsh/xonsh#1155] opened 2016-06-07 11:30 UTC
When I run the `history` command, I get the following error:

```
$ fc
xonsh: subprocess mode: command not found: fc
Did you mean one of the following?
    cc:  Command (/usr/bin/cc)
    6:   Alias
    bc:  Command (/usr/bin/bc)
    cp:  Command (/bin/cp)
    gc:  Alias

The program 'fc' is currently not installed. You can install it by typing:
```

`fc` is a shell built-in AFAIK though, so I'm not sure what the problem is. I am running ('xonsh/0.3.3',). `fc` works when invoking from bash or zsh directly.

**Comment by mitnk** [comment] 2016-06-07 16:12
@metalseargolid Thanks for reporting. From what you pasted, it seems you were running `fc` not `history`. Could you have a confirm and also provide the output of `xonfig`?

here's mine:
```
$ fc
xonsh: subprocess mode: command not found: fc
Did you mean one of the following?
    cc:   Command (/usr/bin/cc)
    nc:   Command (/bin/nc)
    ucf:  Command (/usr/bin/ucf)
    cd:   Alias
    [:    Command (/usr/bin/[)
pi@pi1 ~$
pi@pi1 ~$ history
 0  which pc
 1  which fc
 2  fc
pi@pi1 ~$ xonfig
+------------------+----------+
| xonsh            | 0.3.3    |
| Python           | 3.5.1    |
| PLY              | 3.7      |
| have readline    | True     |
| prompt toolkit   | None     |
| shell type       | readline |
| pygments         | None     |
| on posix         | True     |
| on linux         | True     |
| distro           | debian   |
| on darwin        | False    |
| on windows       | False    |
| is superuser     | False    |
| default encoding | utf-8    |
+------------------+----------+
pi@pi1 ~$
```

**Comment by metalseargolid** [comment] 2016-06-07 16:19
Ahhhhhh I set xonsh up to import my .zshrc, and it seems ZSH (or oh-my-zsh during setup) aliases the `history` command to `fc -l 1`. I should be able to fix it in my .zshrc when I get home like so:

```
if [[ $SHELL == "/usr/local/bin/xonsh" ]]; then
   unalias history
fi
```

**Comment by scopatz** [comment] 2016-06-07 23:35
Note that `$SHELL` is your default login shell, though, not the shell you are running with.

**Comment by laerus** [comment] 2016-08-17 10:00
closing this, feel free to reopen!

**Comment by mandarvaze** [comment] 2016-08-18 00:58
@metalseargolid Did your trick work ? as @scopatz mentioned above, I get the following inside the ``xonsh`` session

    mandar@MacBook-Pro ~ $ $SHELL
    '/bin/zsh'

So this is unlikely to work for me (unless I make ``xonsh`` my login shell - which I am not yet ready to do)

@laerus - Can you reopen this till there is a work around that works for everyone ? (Or leave the duplicate #1577 open)

**Comment by mandarvaze** [comment] 2016-08-19 06:47
Till the root cause is fixed, the workaround mentioned in https://github.com/xonsh/xonsh/issues/1577#issuecomment-240600295 works.
Adding here for reference for others who may run into this issue.

**Comment by laerus** [comment] 2016-08-23 19:54
maybe we should ignore alias changes on an existing alias when sourcing bash and zsh? and maybe throw a warning

**Comment by scopatz** [comment] 2016-08-23 21:26
> maybe we should ignore alias changes on an existing alias when sourcing bash and zsh? and maybe throw a warning

+1 to that!

**Closed** 2016-09-01 00:35 UTC
