### ISSUE TITLE
Problem with aliases that reference them self

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1240] opened 2016-06-15 11:29 UTC
I have a problem with aliases that reference them self. 

```
snail@sea ~ $ which ls -a
aliases['ls'] = ['ls', '--show-control-chars', '--color', '-X']
C:\Program Files\Git\usr\bin\ls.exe (from PATH element 28)
snail@sea ~ $ ls
xonsh: subprocess mode: command not found: ls
Did you mean one of the following?
    sl:   Alias
    ls:   Alias
    ll:   Alias
    cls:  Alias
    d:    Alias
```

@adqm Do you have an idea what caused this? 

Git bisect tells me the following.
```
faacb0a155b6a7bf26f6220e03749db96e449fe7 is the first bad commit
commit faacb0a155b6a7bf26f6220e03749db96e449fe7
Author: adam j hartz <hartz@mit.edu>
Date:   Mon Jun 13 14:09:04 2016 -0400

    possible fix for incorrect alias loading

:040000 040000 be15e5042516d9085b9fe8f03ff692d3ab7b2ecb d6ad861f80190d0ed4c7df44adf9f8538f8c1c36 M  xonsh
```

Just for reference: 
``` 
snail@sea ~ $ xonfig
+------------------+----------------+
| xonsh            | 0.3.4          |
| Python           | 3.5.1          |
| PLY              | 3.7            |
| have readline    | True           |
| prompt toolkit   | 1.0.0          |
| shell type       | prompt_toolkit |
| pygments         | 2.1.3          |
| on posix         | False          |
| on linux         | False          |
| on darwin        | False          |
| on windows       | True           |
| on cygwin        | False          |
| is superuser     | False          |
| default encoding | utf-8          |
+------------------+----------------+

```

**Comment by scopatz** [comment] 2016-06-15 15:56
I have noticed this issue too @melund

**Comment by gforsyth** [comment] 2016-06-15 16:00
Weird... I cannot reproduce

```console
gil@theo ~/tmp $ which -a ls
aliases['ls'] = ['ls', '--color=auto', '-v']
/usr/bin/ls (from PATH element 1)
gil@theo ~/tmp $ ls
Aur  Drip  Drop  aur  'bad name'  drip  drop  test.xsh
```

**Comment by scopatz** [comment] 2016-06-17 03:23
Double weirdness is that I get this on my laptop but not on my desktop.

**Comment by scopatz** [comment] 2016-06-19 18:09
Closing this issue because of #1271. Please feel free to reopen!

**Comment by astronouth7303** [comment] 2016-07-28 06:02
Not actually closed.

**Closed** 2016-07-28 06:43 UTC
Labels: bug
