### ISSUE TITLE
cat, pipes, and ctrl-d

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1102] opened 2016-06-05 03:24 UTC
cat | grep aaa
and typing some lines such as

aaa
bbb
ctrl-d

doesn't work as expected

bash prints aaa right after lines that contain aaa;
xonsh doesn't print anything, and execution doesn't stop after ctrl-d.

cat > xxx
aaa
bbb
ctrl-d

works!

xonfig
+------------------+----------+
| xonsh | 0.3.2 |
| Python | 3.4.3 |
| PLY | 3.7 |
| have readline | True |
| prompt toolkit | None |
| shell type | readline |
| pygments | None |
| on posix | True |
| on linux | True |
| distro | Fedora |
| on darwin | False |
| on windows | False |
| is superuser | False |
| default encoding | utf-8 |
+------------------+----------+

**Comment by adqm** [comment] 2016-06-05 03:25
I can confirm this.  I imagine it is because we are giving the terminal over to the last process in the pipeline, so stdin is trying to go to `grep` in your example, instead of to `cat`.  I can look into fixing this.

**Comment by adqm** [comment] 2016-06-05 03:42
Thanks for reporting, @mburo!

**Comment by mburo** [comment] 2016-06-17 04:15
just checked fix #1226 - seems to work for the test cases above.

**Comment by scopatz** [comment] 2016-06-17 04:29
Closing due to fix, feel free to reopen.

**Closed by scopatz** 2016-06-17 04:29 UTC
Labels: bug
