### ISSUE TITLE
Unicode prompt broken

### ISSUE THREAD

**Issue by 89z** [xonsh/xonsh#4704] opened 2022-03-08 19:56 UTC
If I start the shell, I see this:

~~~
Steven@DESKTOP-7TPE82S D:\Desktop $
~~~

**Comment by krader1961** [comment] 2022-03-09 04:31
What OS? What Xonsh version? What terminal? How did you define the prompt? Can you show us the UTF-8 encoded version of the prompt? Can you show us how the prompt is defined? It would help if you provided a minimal reproducible example.

**Comment by anki-code** [comment] 2022-03-09 07:47
I think it's windows. Please try to run in https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701

**Comment by 89z** [comment] 2022-03-09 13:14
I am using Windows Terminal. Thats whats weird, because Windows Terminal has excellent Unicode support.

**Comment by WRaezer** [comment] 2022-03-11 17:50
Is this issue still open?

**Comment by 89z** [comment] 2022-03-11 18:03
@WRaezer just look at the top of the page...

**Comment by hierosme-nova** [comment] 2022-03-14 22:20
Hello,

Normaly that is the terminal whois in charge to display. But it display what it can.
By exemple if you prompt use Devfonts Icons like OhMyBash or HoMyZsh, the font have to be install and selected in the terminal setting.

It have almost no chance for have Xonsh it convert a char to a  � by it self . Python unicode look like a string with back slash inside.

Then are you sure to havent a font trouble , with you terminal ?

I can take a look in the Xonsh code , but with python3 unicode trouble is uncommon .

PS: If you can copy / paste that char �, that is because that is not the original share, but one change by you terminal it self.
Then i can confirm you terminal deal well with unicode...

**Comment by 89z** [comment] 2022-03-14 22:25
> Then are you sure to havent a font trouble , with you terminal ?

I am certain its not a font issue. I know this, because I can use other shells just fine:

> ![Untitled](https://user-images.githubusercontent.com/73562167/158271039-a86f4216-f744-4bb8-bd6f-28ffc28a2630.png)

**Comment by yaxollum** [comment] 2022-03-18 22:22
Hi @89z , I also ran into this issue on Windows, and I was able to fix it by installing the `prompt-toolkit` shell:
```
 pip install prompt-toolkit
```

My original xonfig:
```
+------------------+-----------------+
| xonsh            | 0.10.1          |
| Python           | 3.10.3          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | None            |
| shell type       | readline        |
| history backend  | json            |
| pygments         | None            |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

After installing prompt-toolkit:
```
+------------------+-----------------+
| xonsh            | 0.10.1          |
| Python           | 3.10.3          |
| PLY              | 3.11            |
| have readline    | False           |
| prompt toolkit   | 3.0.28          |
| shell type       | prompt_toolkit  |
| history backend  | json            |
| pygments         | None            |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | True            |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

**Comment by 89z** [comment] 2022-03-18 22:32
It seems if you do this:

~~~
pip install xonsh
~~~

You **only** get Xonsh, nothing else. If you do this:

~~~
pip install 'xonsh[full]'
~~~

It does try to install `prompt-toolkit`, but also some other stuff:

~~~
 Building wheel for setproctitle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for setproctitle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'setproctitle' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with
"Microsoft C++ Build Tools":
https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for setproctitle
Successfully built pyperclip
Failed to build setproctitle
ERROR: Could not build wheels for setproctitle, which is required to install
pyproject.toml-based projects
~~~

I dont have "Microsoft C++ Build Tools", and I am not going to install it. Xonsh should have an option to just install Xonsh and `prompt-toolkit`, and any other packages that are strictly required for Xonsh to run. It seems currently the options are:

- Xonsh only, not even other packages required for running Xonsh
- Xonsh and EVERYTHING, even optional packages

Seems like another option should be available.

**Comment by gforsyth** [comment] 2022-03-21 04:00
There are several other options. I believe the one you want is `xonsh[ptk]`

**Comment by 89z** [comment] 2022-03-21 12:35
> There are several other options. I believe the one you want is `xonsh[ptk]`

that seems to be exactly what I am looking for. However, I do not see that mentioned here:

https://xon.sh

or here:

https://xon.sh/packages.html

**Comment by gforsyth** [comment] 2022-03-21 13:43
Yep, the docs can always use improvement

**Comment by hierosme-nova** [comment] 2022-03-21 15:56
**prompt_toolkit** if i remenber well it is one of the two big library it deal with termcap.
Normaly that the role of you system to provid that softare stack. More easy for a Unix/Linux user , for Windows user i presume the lib should be install by the user.

For have take time on xonsh source code:
xonsh have if own lib to identify the type of termcap and tty , (and if remenber it own system for stdout, stdin, stderror).
For me nothing on xonsh code check want is send to stdout and if termcap work well.

If Gnureadline or Prompt tollkit are require it should be write somewhere. May be just make the test about install  "Microsoft C++ Build Tools" or a "GCC" then try to install the prompt_toolkit python bind...

Unfortunally i'm on GNU/Linux can't help a lot for the troubleshooting.

**Comment by gforsyth** [comment] 2022-03-21 18:58
I think we're pretty clear about requiring either `prompt_toolkit` or `readline` -- and `pip` usually handles these installs without issue.

There appears to be a problem with the wheels built for Python 3.10 for the latest release of `setproctitle`, usually these installs wouldn't require building from source at install time.  I'm going to close this out.

**Closed by gforsyth** 2022-03-21 18:58 UTC
Labels: windows

**Comment by 89z** [comment] 2022-03-21 19:01
So, the current situation, seems to be exactly as it was, when I posted this issue. So why is the issue closed?

**Comment by gforsyth** [comment] 2022-03-21 19:09
Which issue?  Is Unicode broken on prompt_toolkit?
Or is this a docs issue? 
Or is this an issue with `setproctitle` installs?

If Unicode is broken on prompt_toolkit, we can reopen this
If it's a docs issue, anyone is welcome to open a PR, but I'm not leaving this issue open
If it's `setproctitle` installs, that's an upstream wheel packaging problem
