### ISSUE TITLE
Setting values for BASH_COMPLETIONS in xonfig wizard leads to TypeError, "not JSON serializable"

### ISSUE THREAD

**Issue by gotgenes** [xonsh/xonsh#1808] opened 2016-10-06 20:13 UTC
```
$BASH_COMPLETIONS
This is a list (or tuple) of strings that specifies where the
``bash_completion`` script may be found. For better performance,
bash-completion v2.x is recommended since it lazy-loads individual
completion scripts. Paths or directories of individual completion
scripts (like ``.../completes/ssh``) do not need to be included here.
The default values are platform dependent, but sane. To specify an
alternate list, do so in the run control file.
default value:
Normally this is:

    ``('/etc/bash_completion', )``

But, on Mac it is:

    ``('/usr/local/etc/bash_completion', )``

And on Arch Linux it is:

    ``('/usr/share/bash-completion/bash_completion', )``

Other OS-specific defaults may be added in the future.
current value: ['/usr/local/share/bash-completion/bash_completion', '/usr/local/etc/bash_completion']
>>> /usr/local/etc/bash_completion
Converted input '/usr/local/etc/bash_completion' to ['/usr/local/etc/bash_completion'].

[…]

'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'`-.,_,.-*'

xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
TypeError: ['/usr/local/etc/bash_completion'] is not JSON serializable
```

I have also entered the following values; I end up with the same error:
- `('/usr/local/etc/bash_completion', )`
- `['/usr/local/etc/bash_completion']`

```
clasher@clasher-MBP ~/development $ xonfig
+------------------+-----------------+
| xonsh            | 0.4.7.dev175    |
| Git SHA          | 9e67c21         |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by laerus** [comment] 2016-10-06 20:37
hey @gotgenes, thanks for reporting! This seems like a legitimate bug in the wizard.

**Comment by gforsyth** [comment] 2016-10-07 11:43
Hey @gotgenes -- I can't seem to reproduce this, but I'm not on OSX which may(?) have something to do with it?  Could you start `xonsh` in debug mode and also enable the full traceback and paste it here?  

To enable debug mode, just set `$XONSH_DEBUG=1` or something truthy, then start a new `xonsh` instance from there and set `$XONSH_SHOW_TRACEBACK=True`

Thanks!

**Comment by gotgenes** [comment] 2016-10-07 23:56
@gforsyth Thanks for your reply. Here is the traceback I got:

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/xonsh/xonfig.py", line 315, in _wizard
    pv.visit()
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 485, in visit
    rtn = super().visit(node)
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 306, in visit
    rtn = meth(node)
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 543, in visit_wizard
    self.visit(child)
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 485, in visit
    rtn = super().visit(node)
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 306, in visit
    rtn = meth(node)
  File "/usr/local/lib/python3.5/site-packages/xonsh/wizard.py", line 613, in visit_save
    jstate = json.dumps(self.state, indent=1, sort_keys=True)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ['/usr/local/etc/bash_completion'] is not JSON serializable
```

**Comment by gotgenes** [comment] 2016-10-11 16:51
I realize that traceback is less than helpful because it does not display what `self.state` is. Despite the fact that it `repr()`s like a list, the error raised by `json.dumps` indicates it does not believe it to be a list, but some sort of arbitrary Python object. `json.dumps` does not know by default how to serialize arbitrary Python objects.

Is there a way to run xonsh in a debugger like pudb so that I can inspect and report on `self.state`?

**Comment by scopatz** [comment] 2016-10-14 02:21
You should be able to run any python debugger in xonsh, but this may have been broken (mea culpa) recently.  I have been able to run xonsh in a debugger but we have gotten a couple reports of breakages.

**Comment by gotgenes** [comment] 2016-10-17 17:03
Okay, my suspicions were correct. Despite the appearance of 
```
TypeError: ['/usr/local/etc/bash_completion'] is not JSON serializable
```
indicating the `json` module can't serialize a list (wat?), `['/usr/local/etc/bash_completion']` is not a list. It is _actually_ an instance of `xonsh.tools.EnvPath`.

```
-> jstate = json.dumps(self.state, indent=1, sort_keys=True)
(Pdb) self.state
{'env': {'BASH_COMPLETIONS': ['/usr/local/etc/bash_completion']}}
(Pdb) self.state['BASH_COMPLETIONS']
*** KeyError: 'BASH_COMPLETIONS'
(Pdb) self.state['env']['BASH_COMPLETIONS']
['/usr/local/etc/bash_completion']
(Pdb) type(self.state['env']['BASH_COMPLETIONS'])
<class 'xonsh.__amalgam__.EnvPath'>
(Pdb) json.dumps(self.state['env']['BASH_COMPLETIONS'])
*** TypeError: ['/usr/local/etc/bash_completion'] is not JSON serializable
(Pdb)
```

By default, `json.dumps` does not handle arbitrary Python objects, and will instead raise a `TypeError` when encountered, like happens here. I'm surprised @gforsyth was not able to reproduce this bug. It is not specific to OS X, but general to the `json` module's behavior.

To fix this, JSON serializers for any Python objects that would appear in `self.state` must be written and passed in during the `json.dumps`. @hynek recently wrote [a beautiful article recently surveying JSON serialization](https://hynek.me/articles/serialization/). The `functools.singledispatch` looks promising and is in the standard library.

**Comment by gforsyth** [comment] 2016-10-17 17:10
Hey @gotgenes, thanks for tracking all of this down.  I _can_ reproduce this -- I didn't realize from your initial report that you were getting the error at the end of the wizard, not immediately after entering the bash completions path.

**Comment by gotgenes** [comment] 2016-10-17 17:42
> I didn't realize from your initial report that you were getting the error at the end of the wizard, not immediately after entering the bash completions path.

@gforsyth Sorry. I can see that the `[…]` in the copy-pasted output were a bit too subtle.

**Comment by zzamboni** [comment] 2017-02-23 18:01
Hi, I just started playing with Xonsh and encountered the same error, I get at the end of the wizard:
```
TypeError: Object of type 'EnvPath' is not JSON serializable
```
Any updates about a fix for this issue? Thanks in advance!

**Comment by astronouth7303** [comment] 2017-02-23 18:08
@zzamboni what is the output of `xonfig` for you?

**Comment by zzamboni** [comment] 2017-02-23 18:22
@astronouth7303 I'm running in on MacOS 10.12.3. Here's the output:
```
taazadi1@UM00104 ~ $ xonfig
+------------------+-----------------+
| xonsh            | 0.5.6           |
| Python           | 3.6.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.13          |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by scopatz** [comment] 2017-02-23 18:33
I think this is a legitimate problem with the EvnPath object right now. @zzamboni, we are trying to go through right now and squash all of the old bugs. We are now at only 42, (down from ~80 a few weeks ago). So hopefully it won't be too much longer before we get to this one.  Of course, pull requests are always welcome and a great way to make things happen faster :)

**Comment by zzamboni** [comment] 2017-02-23 20:49
@scopatz thanks for the response! I'll dive into the code if I have a chance and I'd be happy to submit a PR. Xonsh looks like a very nice project.

**Comment by scopatz** [comment] 2017-02-23 22:45
Thanks @zzamboni! Let us know if you need any help or guidance. There is also a developer's guide here: http://xon.sh/devguide.html

**Comment by scopatz** [comment] 2017-02-26 20:44
A potential fix is now available in #2270. Thanks for the link @gotgenes! It proved super helpful!

**Comment by gotgenes** [comment] 2017-02-26 21:39
@scopatz Nice!

**Comment by scopatz** [comment] 2017-02-27 16:29
Closing this because #2270 has been merged, please feel free to reopen if needed.

**Closed by scopatz** 2017-02-27 16:29 UTC
Labels: bug
