### ISSUE TITLE
xonsh-vox-tabcomplete fails with assertion on load

### ISSUE THREAD

**Issue by abingham** [xonsh/xonsh#3885] opened 2020-10-14 16:08 UTC
When I load xonsh-vox-tabcomplete with `xontrib load vox_tabcomplete`, fails with an assertion.

## xonfig

I'm not doing the loading via `.xonshrc`, but here it is in case it matters.

```
# XONSH WEBCONFIG START
$PROMPT = '{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {BOLD_BLUE}{prompt_end}{RESET} '
$XONSH_COLOR_STYLE = 'emacs'
xontrib load pyenv
# XONSH WEBCONFIG END

xontrib load vox
```

## Expected Behavior
I expect the `xontrib` call to load the module and make vox completion available.

## Current Behavior
I get an assertion when I run the `xontrib` call.

### Traceback (if applicable)

```
Traceback (most recent call last):
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10771, in xontribs_load
    update_context(name, ctx=ctx)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10716, in update_context
    modctx = xontrib_context(name)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 10682, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 24190, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23875, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23835, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23959, in _parse_ctx_free
    tree = self.parser.parse(
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/usr/local/Cellar/xonsh/0.9.23/libexec/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
Failed to load xontrib vox_tabcomplete.
```

## Steps to Reproduce

```
xpip install xonsh-vox-tabcomplete  # assuming it's not already installed
$XONSH_SHOW_TRACEBACK = True
xontrib load vox_tabcomplete
```

@scopatz hinted that this is probably related to python 3.9.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by laloch** [comment] 2020-10-15 09:26
Hi @abingham, thanks for reporting! I can confirm the issue.
Minimal code to reproduce the issue is `"".split()[-1]`. The parser chokes at the unary minus operator. I'll try to come with a fix ASAP.

**Comment by scopatz** [comment] 2020-10-15 14:50
Thanks @laloch!

**Comment by anki-code** [comment] 2021-05-08 12:24
Now I have the error:
```python
xpip install xonsh-vox-tabcomplete
xontrib load vox_tabcomplete
#    __xonsh_completers__['vox'] = _vox_completer
#NameError: name '__xonsh_completers__' is not defined
#Failed to load xontrib vox_tabcomplete.
```
It looks that the xontrib should be fixed in upstream.

**Closed by anki-code** 2021-05-08 12:25 UTC
Labels: bug, py39
