### ISSUE TITLE
[report] xonsh as a zipapp

### ISSUE THREAD

**Issue by AstraLuma** [xonsh/xonsh#3205] opened 2019-07-09 22:56 UTC
Ok, so I've been using xonsh as a zipapp as my shell for a few weeks now. I wanted to walk through how I did it and my experiences with it.

Previous discussions on this topic were #2459 

## How

https://gitlab.com/doyouevenclick/xonsh

1. [Build script](https://gitlab.com/doyouevenclick/xonsh/blob/master/buildxonsh.py) in CI
2. Upload the resulting artifact to my [salt](https://www.saltstack.com/) master
3. Use salt to install it on all my machines

Some of the highlights I did:
* The shebang uses the specific system python instead of `env` to maximize reliability in the face of all the python environments (venvs, pyenv, conda, etc etc etc). This is accomplished via distro-specific builds (although several of them could probably be shared).
* `-I` (isolate) is used to minimize the amount of whatever from entering the xonsh python environment (system packages still do, and this actually uncovered a bug in debian's pysocks)
* The use of system and zips means that there's not an installable location, so a specific user site is created and added.
* Stripped out `__amalgam__.py` because I'm a developer and I don't need that kind of obscurity.

## Changes to xonsh

Only one core change was needed to allow full functionality, which I mention below.

Two things I added:

* A new [launcher script](https://gitlab.com/doyouevenclick/xonsh/blob/master/main.py) which:
  1. Adds the xonsh user site (`~/.local/xonsh`) to the path via the `site` module
  2. (previously) monkey-patched `xonsh.xontrib` with the fix mentioned below
  3. Replaces `sys.executable` with `~/.local/xonsh/bin/python` so that Python code running in xonsh uses an executable that will inherit (most) of xonsh's environment
* A new xontrib [`xonshzip`](https://gitlab.com/doyouevenclick/xonsh/blob/master/xonshzip.py) (which is pretty mandatory) which:
  1. Sets `xpip` correctly from the user site bin
  2. Adds aliases to manage the user site

## Problems

First: #3169 / #3170, basically the `xontrib` command expected to find `xontribs.json` on the file system (based on `__file__`). This was an easy fix, which got PR'd and released.

Second: #3171, the xsh importer fails on zips. It is easy to identify the problem but the fix involves a bunch of fresh engineering (made harder by the fact that Python's version, `zipimport`, is C and not really extensible/copyable). `xonshzip` works around this by copying the bundled xsh-based xontribs into the user site on creation.

## Performance

I have a variety of machines with this on them, and here's my timings from all of them. (Taken just now, once each.) The command used was just `xonsh --timings`.

`cayde7`, my daily driver laptop with way too much stuff running (I blame electron and too many chrome tabs).

```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.264   |   0.264   |
|post_execer_init  |   1.059   |   0.794   |
|on_pre_rc         |   1.059   |   0.000   |
|on_post_rc        |   1.833   |   0.774   |
|on_ptk_create     |   2.171   |   0.338   |
|on_post_init      |   2.171   |   0.000   |
|on_pre_cmdloop    |   2.172   |   0.000   |
|on_pre_prompt     |   2.172   |   0.000   |
|------------------|-----------|-----------|
```

`inara`, my much more powerful desktop that doubles as my file, docker, and minikube server (mostly idle).

```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.564   |   0.564   |
|post_execer_init  |   1.800   |   1.236   |
|on_pre_rc         |   1.857   |   0.057   |
|on_post_rc        |   1.949   |   0.092   |
|on_ptk_create     |   2.609   |   0.659   |
|on_post_init      |   2.609   |   0.000   |
|on_pre_cmdloop    |   2.609   |   0.000   |
|on_pre_prompt     |   2.609   |   0.000   |
|------------------|-----------|-----------|
```

`master`, my salt master, server, metal, mini
```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.624   |   0.624   |
|post_execer_init  |   2.088   |   1.464   |
|on_pre_rc         |   2.092   |   0.004   |
|on_post_rc        |   8.072   |   5.980   |
|on_pre_prompt     |   8.888   |   0.816   |
|on_ptk_create     |   8.888   |   0.000   |
|on_pre_cmdloop    |   8.888   |   0.000   |
|on_post_init      |   8.888   |   0.000   |
|------------------|-----------|-----------|
```

`statichost-01`, a VM on a somewhat overloaded host.
```
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.416   |   0.416   |
|post_execer_init  |   1.052   |   0.636   |
|on_pre_rc         |   1.536   |   0.484   |
|on_post_rc        |   5.552   |   4.016   |
|on_pre_cmdloop    |   6.104   |   0.552   |
|on_post_init      |   6.104   |   0.000   |
|on_pre_prompt     |   6.104   |   0.000   |
|on_ptk_create     |   6.104   |   0.000   |
|------------------|-----------|-----------|
```

**Comment by astronouth7303** [comment] 2019-07-09 22:57
(This is not a bug, I just literally have no idea where's a better place to leave a write up like this.)

**Comment by scopatz** [comment] 2019-07-22 21:54
Thanks for writing this up @astronouth7303! Is that 8 / 6 sec timing real?  What does xonsh startup look like on those machines w/out zippapp?

Is this a good way to release xonsh in the future?

**Comment by astronouth7303** [comment] 2019-07-23 03:01
I'll have to get back to you about the comparison timing; they're having trouble downloading xonsh from PyPI at the moment? IDK, the internet is being stormy.

In general, I believe zipapps are a good way to distribute apps because they allow for better control of the python environment the application executes in. So, it's not a problem install two things that require different versions of the same library. It also gives better control of the xonsh environment vs the system environment vs the current environment (with regards to active conda, venvs, pyenv, etc) especially if xonsh is not your main shell.

There's also potential performance improvement benefits? Prior testing showed this to be a non-trivial comparison with mixed results, but it could be worth pulling this apart and understanding where exactly the performance problems lie and why amalgamation helps.

Also, single-file downloads just feel nice to me.

Aside: It's actually not simple what installation methods allow for venv interference? Like, from my vague quick tests, installing to the global system environment seems ok but installing to the system `--user` environment (is that the site?) allows it to break? I haven't thoroughly tested this yet.

The major problem with zipapps is that a naive shbang won't fix these problems, and a more complex solution is needed.

**Comment by cjrh** [comment] 2020-03-28 13:46
I played around with xonsh as a zipapp on my Windows box (Py 3.8) today.  While I didn't try to deal with any of the gnarly xpip stuff or USERBASE, it was pretty easy to get a pyz bundle to work for basic shelling and I thought it might be useful to add a few notes here:

Inside a xonsh source checkout directory on master:

```
$ mkdir build
$ python -m pip install -U '.[ptk,pygments]' -t build
$ python -m zipapp build -o xonsh.pyz -m "xonsh.main:main"
```

This produces a 13 MB `xonsh.pyz` file which you can copy into some other folder on the path (e.g. `~/bin/`).  Sadly, it isn't runnable from inside a xonsh shell, but it is runnable from `cmd.exe` and if the python launcher was installed and correctly associated, you only have to type the filename of the pyz:

```
Microsoft Windows [Version 10.0.18363.720]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\caleb>xonsh.pyz --version
xonsh/0.9.15

C:\Users\caleb>xonsh.pyz --no-rc --timings

                                          Welcome to the xonsh shell (0.9.15)

                                               ~ It cannot be that hard ~

--------------------------------------------------------------------------------------------------------------
xonfig tutorial    ->    Launch the tutorial in the browser
xonfig web         ->    Run the configuration tool in the browser and claim your shell
(Note: Run the configurationn tool or create a ~/.xonshrc file to suppress the welcome screen)

 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.239   |   0.239   |
|post_execer_init  |   1.445   |   1.206   |
|on_pre_rc         |   1.445   |   0.000   |
|on_post_rc        |   1.445   |   0.000   |
|on_ptk_create     |   1.498   |   0.053   |
|on_post_init      |   1.498   |   0.000   |
|on_pre_cmdloop    |   1.786   |   0.288   |
|on_pre_prompt     |   1.786   |   0.000   |
|------------------|-----------|-----------|
caleb@DESKTOP-953DM4F ~ $ exit



C:\Users\caleb>xonsh.pyz --timings
 Debug level: Off
|------------------|-----------|-----------|
|Event name        | Time (s)  | Delta (s) |
|------------------|-----------|-----------|
|start             |   0.000   |   0.000   |
|pre_execer_init   |   0.238   |   0.238   |
|post_execer_init  |   1.447   |   1.209   |
|on_pre_rc         |   1.448   |   0.001   |
|on_post_rc        |   1.543   |   0.095   |
|on_ptk_create     |   1.604   |   0.061   |
|on_post_init      |   1.604   |   0.000   |
|on_pre_cmdloop    |   1.604   |   0.000   |
|on_pre_prompt     |   1.604   |   0.000   |
|------------------|-----------|-----------|
~
$
```

As I said, I've not looked at xpip or xonsh user site settings yet, but the pyz produced by the above looks like it can do everything I need so far.

**Comment by cjrh** [comment] 2020-03-29 02:59
Based on instructions in the official zipapp docs, [Making a Windows executable](https://docs.python.org/3/library/zipapp.html#making-a-windows-executable), it seems easy to convert the `xonsh.pyz` file into an exe file, which _can_ be called from within xonsh itself.

## File `zastub.c`:

(This is verbatim from the Python docs)

```c
#define Py_LIMITED_API 1
#include "Python.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#ifdef WINDOWS
int WINAPI wWinMain(
    HINSTANCE hInstance,      /* handle to current instance */
    HINSTANCE hPrevInstance,  /* handle to previous instance */
    LPWSTR lpCmdLine,         /* pointer to command line */
    int nCmdShow              /* show state of window */
)
#else
int wmain()
#endif
{
    wchar_t **myargv = _alloca((__argc + 1) * sizeof(wchar_t*));
    myargv[0] = __wargv[0];
    memcpy(myargv + 1, __wargv, __argc * sizeof(wchar_t *));
    return Py_Main(__argc+1, myargv);
}
```

## File: distbuild.py

(This is verbatim from the Python docs)

```python
# distbuild.py
import distutils.sysconfig
import os
import sys
from distutils.ccompiler import new_compiler
from pathlib import Path


def compile(src):
    src = Path(src)
    cc = new_compiler()
    exe = src.stem
    cc.add_include_dir(distutils.sysconfig.get_python_inc())
    cc.add_library_dir(os.path.join(sys.base_exec_prefix, "libs"))
    # First the CLI executable
    objs = cc.compile([str(src)])
    cc.link_executable(objs, exe)
    # Now the GUI executable
    cc.define_macro("WINDOWS")
    objs = cc.compile([str(src)])
    cc.link_executable(objs, exe + "w")


if __name__ == "__main__":
    compile("zastub.c")
```

## Compile the stub to `zastub.exe`

```shell
F:/tmp/stub  
$ py -3.7 distbuild.py
zastub.c
Generating code
Finished generating code
zastub.c
Generating code
Finished generating code
```

## File concatenation: `zastub.exe` + `xonsh.pyz` ➡ `xonsh.exe`

(Could also concatenate with `$ type zastub.exe xonsh.pyz > xonsh.exe`, but my preference is to use python for these things because it's cross platform; although that may not matter here.)

```shell
F:/tmp/stub  
$ with open('xonsh.exe', 'wb') as out:
.     for fn in ['zastub.exe', 'xonsh.pyz']:
.         out.writelines(iter(open(fn, 'rb').read, b''))
.
F:/tmp/stub  
$ ll
total 25794
drwxr-xr-x 1 caleb 197121        0 Mar 29 12:33 .
drwxr-xr-x 1 caleb 197121        0 Mar 29 12:12 ..
-rw-r--r-- 1 caleb 197121      639 Mar 29 12:14 distbuild.py
-rwxr-xr-x 1 caleb 197121 13120978 Mar 29 12:45 xonsh.exe
-rw-r--r-- 1 caleb 197121 13110226 Mar 29 12:30 xonsh.pyz
-rw-r--r-- 1 caleb 197121      621 Mar 29 12:23 zastub.c
-rwxr-xr-x 1 caleb 197121    10752 Mar 29 12:25 zastub.exe
-rw-r--r-- 1 caleb 197121   144069 Mar 29 12:25 zastub.obj
-rwxr-xr-x 1 caleb 197121    10752 Mar 29 12:25 zastubw.exe
F:/tmp/stub  
$ ./xonsh.exe --version
xonsh/0.9.15
```

This resulting `xonsh.exe` appears to work the same as the pyz for me, and is callable from within xonsh.

**Comment by cjrh** [comment] 2020-03-29 03:04
As the docs stated, because the limited API is used it means that the `xonsh.exe` depends only on finding a `python3.dll` somewhere on path:

![image](https://user-images.githubusercontent.com/480395/77839176-cf5da580-71bd-11ea-8cb0-3b6749d4fa03.png)

**Comment by laloch** [comment] 2020-03-29 10:27
> As the docs stated, because the limited API is used it means that the `xonsh.exe` depends only on finding a `python3.dll` somewhere on path:

Since there's the zastub stuff anyway, the `python3.dll` could be bundled as a resource and unpacked at runtime to make the whole thing completely portable.

**Comment by cjrh** [comment] 2020-03-29 10:58
I think other files can still be required at runtime, it's just that python3.dll needs to be on the path.  For a distribution bundle that doesn't require python to be installed on the target machine, I think the `xonsh.exe` executable needs to be distributed with the embedded python installation, i.e. the file download `python-3.7.7-embed-amd64.zip` from python.org.  Unpacking that and putting the `xonsh.exe` binary into that folder seems to work:

![image](https://user-images.githubusercontent.com/480395/77847386-0785d800-7200-11ea-8fb3-9c3f5e659d5d.png)

**Comment by laloch** [comment] 2020-03-29 11:19
> For a distribution bundle that doesn't require python to be installed on the target machine, I think the xonsh.exe executable needs to be distributed with the embedded python installation...

I see! I thought that's what zipapps are. Sorry for the noise.

**Comment by astronouth7303** [comment] 2020-03-29 16:57
Technically, a zipapp is just a zip with a `__main__.py` in the root. The Python interpreter can run these directly, no fuss.

Windows detects executability based on a configured list of file extensions. Python on Windows adds stuff to support `.pyz` files.

Unix uses the execute permissions bits and hashbang lines, so on Unix you prepend the shbang line (`#!/usr/bin/python3`) and set `x`.

I do suggest setting `-I` so you're less dependent on the system configuration or the current environment.

You can look at my repo (linked in the original comment) for the full details of what I do.

**Comment by anki-code** [comment] 2021-03-12 08:39
I'm going to close this because:
* Zipapp still have no support and building system that allows to put it to release assets.
* We have pretty stable and documented well AppImage that has automatical building that putting it to the release assets.

If anybody wants to make zippapp great again feel free to reopen this issue and remember about automatisation of the building and enrich xonsh release assets and docs.

**Closed by anki-code** 2021-03-12 08:39 UTC
Labels: appimage, feature
