### ISSUE TITLE
Can't use neovim (previously: Alias resolution in threadable prediction is broken again?)

### ISSUE THREAD

**Issue by t184256** [xonsh/xonsh#2237] opened 2017-02-22 17:39 UTC
I use neovim (aliased to vim as aliases['vi'] = 'nvim'). Finding a commit where it works without touching `__xonsh_commands_cache__.threadable_predictors` is not an easy task:

* at debian's 0.5.2 it was working OK.
* at 7a44848d4cfbb542deb87fd282f1dbc945959e11 (recent and seemingly relevant commit by @scopatz) it works OK.
* at intermediate commits from [builtins.py history](https://github.com/xonsh/xonsh/commits/master/xonsh/built_ins.py) (e.g. 80d4afdd91797ecff3ffb9f4b63afd30c57ad907) neovim doesn't even start (`termios.error: (5, 'Input/output error')`)
* at 77d30597a6c5f21545f051a0f121de967d2666f0 and later commits it misbehaves badly, all keypresses are output in bold instead of commands being executed. unusable.

Seems like you've introduced those "threadable predictors" kludge, whatever magic it is, then recently they started to support aliases, but got broken nearly immediately after that.

This threadable prediction thing has to be some really worthy and unavoidable dark magic if you want to maintain it... How do other shells live without it?

If my findings are not well described enough, or my bug hunting was too sloppy, please tell me the direction in which to improve it.

**Comment by scopatz** [comment] 2017-02-22 18:57
Hi @t184256 Thanks for reporting. Have you tried it on v0.5.6? There was a bug in v0.5.5 related to this but it should be fixed now.

**Comment by t184256** [comment] 2017-02-22 19:49
Yes, and it's broken on 0.5.6 in this specific way:

> at 77d3059 and later commits it misbehaves badly, all keypresses are output in bold instead of commands being executed. unusable.

**Comment by scopatz** [comment] 2017-02-22 19:51
Ok, and what is the output of the `xonfig` command?

**Comment by t184256** [comment] 2017-02-22 19:53
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.5.6           |
| Python           | 3.5.3           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 1.0.9           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | debian          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by scopatz** [comment] 2017-02-23 18:28
Thanks for the detailed analysis here @t184256. I don't think that this is an alias resolution issue. Rather, it seems like it comes from the changes to some of out job control. @mitnk most recently touched that, so maybe he can chime in here.  As a quick test, though, can you try running `nvim` directly (without aliases) and test to see if it is still broken? I strongly suspect that it is.

**Comment by t184256** [comment] 2017-02-23 23:58
I hope I've understood your directions right. I installed xonsh from master, deleted aliases from my .xonshrc and executed `/usr/bin/nvim`; got the same bug. Reverted to 7a44848d4cfbb542deb87fd282f1dbc945959e11; the bug disappeared.

Additionally, on both 7a44848d4cfbb542deb87fd282f1dbc945959e11 and master:
1. If I use `vim`, `vim` just works OK
2. If I use `__xonsh_commands_cache__.threadable_predictors['nvim'] = lambda args: False` `nvim` works OK.

Maybe aliases are totally unrelated and I was misleading. In that case my point is simpler: on 7a44848d4cfbb542deb87fd282f1dbc945959e11 `nvim` worked OK. Now it doesn't.

**Comment by mitnk** [comment] 2017-02-24 02:05
Hi @t184256 

1. is your `/usr/bin/nvim` a binary or a soft link to another binary?

2. when you reproduce this issue, what's the command you typed? just a bare `nvim` (without file names?) ?

2. based on current latest master, does the following patch fix your issue?
```
diff --git a/xonsh/built_ins.py b/xonsh/built_ins.py
index 14c1b72..370f60f 100644
--- a/xonsh/built_ins.py
+++ b/xonsh/built_ins.py
@@ -677,8 +677,7 @@ def _update_last_spec(last):
         pass
     else:
         cmds_cache = builtins.__xonsh_commands_cache__
-        thable = (cmds_cache.predict_threadable(last.args) and
-                  cmds_cache.predict_threadable(last.cmd))
+        thable = cmds_cache.predict_threadable(last.args)
         if captured and thable:
             last.cls = PopenThread
         elif not thable:
```

------------

I tried mimic the issue by a `cp /usr/local/bin/vim /usr/local/bin/nvim`. But cannot reproduce the issue.

**Comment by mitnk** [comment] 2017-02-24 02:17
Ok, on your last comment, I guess `/usr/bin/nvim` is a script and not a regular binary? If so, what's the header of this script?

**Comment by scopatz** [comment] 2017-02-24 02:53
Yeah, nvim should normally just be a binary executable. But it isn't in our commands cache to skip. So maybe before the default commands cache was picking up that is should be predict false, but now it is timing out for some reason.

**Comment by mitnk** [comment] 2017-02-24 02:54
I think with latest master, mapping `nvim` to `vi` or `vim` with aliases would work. but this is a workaround.

I put a PR #2240 to flag `nvim` (we should treat it just as vim) as unthreadable.

**Closed** 2017-02-24 04:13 UTC

**Comment by scopatz** [comment] 2017-02-24 05:54
@t184256 let us know if @mitnk's PR didn't fix the issue and/or reopen this issue!

**Comment by t184256** [comment] 2017-02-24 08:21
It does. You know, because with this change it's
```
$ __xonsh_commands_cache__.threadable_predictors['nvim']
<function xonsh.__amalgam__.predict_false>
```
And this workaround worked in every version. I, for some reason, assumed nvim should work without it. Apparently I was wrong and misleading.

So the fact that nvim worked at 77d30597a6c5f21545f051a0f121de967d2666f0 is actually a bug? Whoa, `xonsh` is complicated.

Thanks for all your hard work and all other complicated stuff that I didn't bump into.

**Comment by scopatz** [comment] 2017-02-25 01:59
> Whoa, xonsh is complicated.

Yeah... Though we are trying to make it less complicated and more modular.

> Thanks for all your hard work and all other complicated stuff that I didn't bump into.

Thanks! I think we all appreciate this!
