### ISSUE TITLE
Xonsh crashes when I aborts the foreign shell installation and restart xonsh

### ISSUE THREAD

**Issue by minecraft2048** [xonsh/xonsh#1218] opened 2016-06-13 11:55 UTC
Here is the error log

```
feanor@silmaril ~> xonsh
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.4', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 236, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/main.py", line 223, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/shell.py", line 44, in __init__
    kwargs.get('cacheall', False))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/shell.py", line 84, in _init_environ
    self.execer = Execer(config=config, login=self.login, xonsh_ctx=self.ctx)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/execer.py", line 42, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/built_ins.py", line 635, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "/usr/local/lib/python3.5/dist-packages/xonsh/environ.py", line 1369, in default_env
    issue_warning=False)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/foreign_shells.py", line 506, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/foreign_shells.py", line 217, in foreign_shell_data
    shkey = CANON_SHELL_NAMES[shell]
KeyError: 'fish'
feanor@silmaril ~> 
```

I'm using xonsh from the pip installer, and unfortunately I forgot how to reproduce this problem, but it have something to do with me using the import foreign shell feature, using fish as the name, pressing enter, and cancelling it at the last minute. If someone can please give me instructions on how to fully reset my xonsh installation I can give you much more better repro steps

**Comment by gforsyth** [comment] 2016-06-13 13:20
Thanks for reporting, @minecraft2048.  This looks like your `config.json` file got a little borked.  In any case, xonsh shouldn't crash when this happens.  
If you want to reset your xonsh installation, remove the file `~/.config/xonsh/config.json` and that should get you back to square one.

**Comment by gforsyth** [comment] 2016-06-13 13:27
Ahh, scratch that -- your `config.json` file might be fine, but we don't support importing from fish.  That said, this still shouldn't crash xonsh.

**Comment by scopatz** [comment] 2016-06-13 19:37
That is, we don't support importing from fish by default, yet. You'd have to fill in the other keys of the foreign shell to use fish in your xonshrc - see here: http://xon.sh/xonshconfig.html#foreign-shells

That said, the work to do this for one person for fish is probably the same for everyone.  We'd really welcome a PR that adds fish defaults to `xonsh.foreign_shells`.  Happy to give anyone help / pointers who wants to implement this!

**Comment by minecraft2048** [comment] 2016-06-14 03:31
Deleting `config.json` does solve this problem, thanks and let me try to crash xonsh more!

**Comment by scopatz** [comment] 2017-02-20 02:16
Given the fallback shell, I think the bug part of this is closed. The remaining piece is a feature request for fish. That make this a duplicate of #485. Please feel free to reopen, if there is something that I have missed here. Thanks again for reporting!

**Closed by scopatz** 2017-02-20 02:16 UTC
Labels: bug
