### ISSUE TITLE
Ponysay shows empty lines instead of ponies

### ISSUE THREAD

**Issue by moigagoo** [xonsh/xonsh#2115] opened 2017-01-27 08:55 UTC
[Ponysay](https://github.com/erkin/ponysay) is a nicer version of cowsay. It used to work with xonsh, but now it doesn't. Instead of cute ponies, all I see are empty lines.

I have no idea where the root of this issue might be, sorry.

Tested on macOS Sierra, xonsh 0.5.2.

**Comment by scopatz** [comment] 2017-01-28 19:22
Thanks for reporting @moigagoo. Do you have a sample command that you were using that fails?

**Comment by scopatz** [comment] 2017-01-28 19:24
Also, simple commands like `ponysay LOL` seem to work for me on both readline and ptk

**Comment by moigagoo** [comment] 2017-01-28 19:43
Any `ponysay` command returns empty lines: `ponysay LOL`, `ponysay -q`, etc. Just `ponysay` does show the colorful help message though.

Here's a weird thing. I tried to record my terminal with Asciinema but the prompt is blinking dark:

https://asciinema.org/a/a3nwagiq0q7agr068wjzgui0p

You can see the commands returning nothing though, that's what I see as well.

**Comment by scopatz** [comment] 2017-01-28 19:49
What is the output of `xonfig` for you?

**Comment by moigagoo** [comment] 2017-01-28 19:52
```
 ~/Projects  xonfig
+------------------+---------------------+
| xonsh            | 0.5.2               |
| Git SHA          | f1f19f7             |
| Commit Date      | Jan 4 17:47:31 2017 |
| Python           | 3.6.0               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.9               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by moigagoo** [comment] 2017-01-28 19:53
```
 ~/Projects  cat ~/.config/xonsh/config.json
{
 "env": {
  "PROJECT_DIRS": ["~/Projects"],
  "XONSH_COLOR_STYLE": "paraiso-dark",
  "BASH_COMPLETIONS": ["/usr/local/etc/bash_completion.d/git-completion.bash"]
 },
 "xontribs": [
  "docker_tabcomplete",
  "vox",
  "vox_tabcomplete",
  "avox",
  "z",
  "powerline"
 ]
}
```

**Comment by scopatz** [comment] 2017-01-28 19:59
The  only thing that I can think of is it might be a terminal emulator thing? Have you tried on iterm2 term, etc? Also have you reported this upstream to ponysay?

**Comment by scopatz** [comment] 2017-01-28 20:00
Also, maybe can you try updating pygments to v2.2

**Comment by moigagoo** [comment] 2017-01-28 20:02
I'm using iTerm2, but I tried Terminal.app just to make sure. The result is the same.

I haven't reported it to Ponysay yet, but I will. Updating pygments didn't help.

**Comment by scopatz** [comment] 2017-01-28 20:12
Hmm yeah, this is a weird one. It definitely works on Linux...

**Comment by scopatz** [comment] 2017-02-07 04:13
I am not sure I understand @jristz. Does it work for you or not?

**Comment by moigagoo** [comment] 2017-02-07 04:23
@scopatz I think he means that he confirmed the issue on Linux.

**Comment by scopatz** [comment] 2017-02-07 04:28
In that case, @jristz, can you please provide the out put of the `xonfig` command and any xonshrc file. Since you said you are using stock xonsh I am not sure you have one.

**Comment by jristz** [comment] 2017-02-07 12:06
+------------------+-----------------+
| xonsh            | 0.5.3           |
| Python           | 3.6.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

**Comment by scopatz** [comment] 2017-02-08 06:15
Ok Can you try running ponysay and then reportig the value of pony in the `threadable_predictors` part of `__xonsh_commands_cache__`, like follows:

```console
scopatz@artemis ~ $ ponysay --version
ponysay 3.0.2
scopatz@artemis ~ $ __xonsh_commands_cache__.threadable_predictors['ponysay']
<function xonsh.__amalgam__.predict_false>
```

**Comment by scopatz** [comment] 2017-02-08 06:21
I think your value is being set to "predict_true" for some reason.

**Comment by scopatz** [comment] 2017-02-08 06:27
Also, are you writing to stderr normally?  Even with predict_true, ponysay seems to work if I redirect to stdout: `ponysay wow e>o`

**Comment by scopatz** [comment] 2017-02-08 06:31
Or, are you writing different parts to different streams?

**Comment by scopatz** [comment] 2017-02-08 06:32
It also seems to work if I  do `ponysay wow out>err`

**Comment by scopatz** [comment] 2017-02-08 06:39
Actually, given how ponysay is implemented , this looks like it might be a duplicate of #2129. Until that this adressed, the workarounds should help.

**Comment by moigagoo** [comment] 2017-02-08 06:59
@scopatz I just tried reproducing the issue, and surprisingly it works just fine! No idea what changed, maybe I've updated xonsh from the repo master branch.

Also, I'm not using powerline this time because of the error mentioned here https://github.com/xonsh/xonsh/issues/2143. Maybe this is related.

**Comment by moigagoo** [comment] 2017-02-08 07:05
http://take.ms/U1Qj7

**Comment by scopatz** [comment] 2017-02-11 20:42
Well I am glad it is working now. I think that it is a duplicate of #2129, and probably unrelated to #2143

**Comment by melund** [comment] 2017-03-01 13:54
#2283 Should ensure that it doesn't misbehave again. For a discussion of the underlying issue see: https://github.com/xonsh/xonsh/issues/2129#issuecomment-283261329

**Closed by melund** 2017-03-01 13:54 UTC
Labels: bug
