### ISSUE TITLE
SIGINT is not passed to subprocess when piped into an alias

### ISSUE THREAD

**Issue by azag0** [xonsh/xonsh#830] opened 2016-05-10 10:23 UTC
See the code below. I eventually killed the bash process from another terminal.

```
🐌 10:21 her@air ~ def _mycat(args, stdin):
.................    sys.stdout.write(stdin) 
.................    
🐌 10:22 her@air ~ aliases['mycat'] = _mycat
🐌 10:22 her@air ~ bash -c 'while true; do echo hey; sleep 1; done' | cat
hey
hey
hey
^C
🐌 10:22 her@air ~ bash -c 'while true; do echo hey; sleep 1; done' | mycat
^C^C^C^C^C^Chey
hey
hey
hey
hey
hey
hey
hey
🐌 10:22 her@air ~ 
```

**Comment by adqm** [comment] 2016-05-10 14:48
Yes, this is true.  Job control doesn't currently work on aliases.  As part of #742, which I will be coming back to soon, I had started to work some of this in.  That's still a work in progress.

**Comment by adqm** [comment] 2016-05-10 14:49
(more specifically, job control doesn't currently work on aliases specified as Python functions)

**Comment by scopatz** [comment] 2017-02-12 21:03
Potential fix in #2184

**Comment by mitnk** [comment] 2017-02-13 15:45
Have xonsh changed something on alias since then? I got following when try reproduce the issue:
```
$ bash -c 'while true; do echo hey; sleep 1; done' | mycat
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1330, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1159, in proxy_two
    return f(args, stdin)
  File "<xonsh-code>", line 2, in _mycat
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1044, in write
    r = h.write(s)
TypeError: write() argument must be str, not _io.TextIOWrapper
```

**Comment by scopatz** [comment] 2017-02-13 19:00
Yes, xonsh has changed.  My version of mycat now looks like:

```python
def _mycat(args, stdin):
    for line in stdin:
        sys.stdout.write(line) 
```

**Comment by scopatz** [comment] 2017-02-15 15:49
#2184 has been merged and so this is cloasable. Please feel free to reopen or open a new issue if problems persist.

**Closed by scopatz** 2017-02-15 15:49 UTC
Labels: bug

**Comment by azag0** [comment] 2017-02-16 08:08
Amazing. Time to give xonsh another round of trial!
