### ISSUE TITLE
cursor positioned at first position of line: overwrites prompt

### ISSUE THREAD

**Issue by lewisl** [xonsh/xonsh#456] opened 2015-10-31 21:35 UTC
With such a basic and obvious problem, xonsh is a dead letter for me.
1. xonsh changes the prompt to PS1="/u@/H /w $"
2. after the first command is entered, the caret appears on the first position of the next line, overwriting the prompt string.

This is issue #21 all over again and still unsolved.

So, two big problems:
I never asked xonsh to change the system prompt.  There is a Prompt command but from the cryptic api doc I can't see how to even run the command.  Seems like this is basic.  Turns out the environment variable $PROMPT sets this. You'd think a search in the doc would turn this up, but it doesn't.  If you read the sections on static config, run config, and environment variables you eventually discover $PROMPT.

But, then which way should I use to set the environment variable?  The run way or the static way?  A little product like this should have ONE way to do config, not TWO ways.  You avoid having to maintain two ways.  You avoid confusing users (me).  You avoid many bugs that you have to fix twice.  You avoid problems when a user sets up both ways of config and settings in the two conflict.

Have ONE way to do config.  Did I mention you should have just ONE way?  Don't be like uwsgi, which has 5 or more ways to do config.  Nothing is gained.  Figure out which is better and enables all the stuff you want to enable and stick to ONE way.

I used the static way.  It works just fine.  But, it appears this is still an open issue.

Also, you should really decide why you need static and runtime config.  Aren't they both invoked at the start of the session?  One after the other, but why can't they be combined?

Anyway, it's a nice improvement over bash, but there can be little traction for a non-standard shell.  If you want to share anything with other users it is very unlikely they'll have the dependencies so it is sort of a dead letter for that reason, too.  But, a great idea...

**Comment by scopatz** [comment] 2015-10-31 21:57
> This is issue #21 all over again and still unsolved.

This does seem like issue #21, and the fix is to use prompt-toolkit. Please try that and let us know how it goes.  I no longer have a Mac and was not able to reproduce this even when I had one. If you come up with a fix, I'd very gladly merge it.

> Turns out the environment variable $PROMPT sets this. You'd think a search in the doc would turn this up, but it doesn't.

This is gets its own section in the tutorial (http://xonsh.org/tutorial.html#customizing-the-prompt) and an entry on the environment variables page (http://xonsh.org/envvars.html). If you have suggestions on how to make this more clear, I'd love to hear them.

>  A little product like this should have ONE way to do config, not TWO ways.

To be overly pedantic, only the static way is configuration while the dynamic way is run control.  The reason for having both of these - which are both optional - is that we have the following startup:

1. static config
2. load foreign shell configuration (such as from Bash, zsh, etc)
3. dynamic run control

Dynamic run control comes after loading the foreign shells because, presumably, the user is loading things up from a previous setup. They want all of their prior environment settings to be there already, and not to be overwitten by something in bashrc or elsewhere.  However, not everyone wants or needs to load up foreign shells, and for some people it is a very expensive operation and they want to turn it off entirely.  Static config is there to handle this use case if you need it. If you don't need it, just use the run control.

After months of thinking about this problem, this is the only way that I saw to manage things. If you have a better suggestion I am all ears.  Those are the constraints on the problem though.

> If you want to share anything with other users it is very unlikely they'll have the dependencies so it is sort of a dead letter for that reason, too. But, a great idea...

I am confused a bit by this.  Can you please clarify? The dependcies are Python and PLY (which is one of the most commonly used, famous, and oldest Python packages out there). I have considered shipping PLY with xonsh, but no one has said that is actually necessary yet. Do you think it is?

**Comment by scopatz** [comment] 2016-08-21 23:04
Closing as it is a duplicate of #21, which is also closed

**Closed by scopatz** 2016-08-21 23:04 UTC
Labels: bug, duplicate
