### ISSUE TITLE
Cursor is on the beginning of prompt

### ISSUE THREAD

**Issue by dahlia** [xonsh/xonsh#21] opened 2015-03-12 13:50 UTC
See also: <http://asciinema.org/a/17584>.

Prompt should be followed by input cursor, but cursor is on the beginning of prompt.

**Comment by scopatz** [comment] 2015-03-12 14:06
Before I dive into this too deeply later today, are you on the current master HEAD?

**Comment by dahlia** [comment] 2015-03-12 15:26
Yes (10e51475ae137a22269bcae0b2b593f89c58440b).

**Comment by scopatz** [comment] 2015-03-12 23:33
There is nothing that is jumping out as obvious to me here.  Where does the cursor end up when you run the following:

```console
$ python -c "from cmd import Cmd; Cmd().cmdloop()"
```

**Comment by dahlia** [comment] 2015-03-13 09:09
`Cmd().cmdloop()` seems to work well: <https://asciinema.org/a/17634>.

**Comment by scopatz** [comment] 2015-03-14 00:43
What happens if you set your `$PROMPT = '>>> '`?

**Comment by dahlia** [comment] 2015-03-15 07:25
> What happens if you set your `$PROMPT = '>>> '`?

It does work well: <http://asciinema.org/a/17708>.

**Comment by dahlia** [comment] 2015-03-15 07:28
I just found that it seems to work correctly if I widen my terminal width: <http://asciinema.org/a/17709>.

**Comment by scopatz** [comment] 2015-03-15 07:31
Ahhhh OK.  That is super helpful to know.  Oddly, this seems like it might be a mac-specific issue because it works fine on my linux machine with a small terminal.  I'll try to reproduce on my mac tomorrow.

**Comment by scopatz** [comment] 2015-03-15 20:58
I cannot reproduce this locally.  I am going to put in a potential fix though.

**Comment by scopatz** [comment] 2015-03-17 04:07
Hi @dahlia sorry for taking so long on this. Could you try master now (8a5dad4) and see if it works, please? Thanks.

**Comment by dahlia** [comment] 2015-03-17 06:08
Unfortunately it still seems unchanged.

**Comment by scopatz** [comment] 2015-03-17 06:09
Shoot! Is that from a clean build?

**Comment by dahlia** [comment] 2015-03-17 09:00
@scopatz I tried using clean build again, but seems still the same.

**Comment by dahlia** [comment] 2015-03-17 09:02
We’d better reproduce it.  I have two different Mac laptops, and they share the same behavior.

**Comment by scopatz** [comment] 2015-03-18 23:33
@dahlia can you try again, please?  We just put in another mac-specific fix on master (a371800) and I am hoping that it will help here - though it might not.

**Comment by dahlia** [comment] 2015-03-19 13:27
The prompt looks slightly different now, but it still gets cut off: <http://asciinema.org/a/17837>.

**Comment by scopatz** [comment] 2015-04-02 23:58
Are you still seeing this issue @dahlia?

**Comment by dahlia** [comment] 2015-04-03 02:50
It still is unchanged, but I might just have a clue.  I’m using `vcprompt` in my `PS1`, could it be related?

```bash
export VCPROMPT_FORMAT='<%b%m%u>'                                               
export PS1='\[\e[0;35m\]\u\[\e[m\] \[\e[2;3m\]\w\[\e[m\] \[\e[0;34m\]$(vcprompt)\[\e[m\]\[\e[1;32m\]\$\[\e[m\] '
```

**Comment by dahlia** [comment] 2015-04-03 02:52
Oh, `xonsh` doesn’t seem to use `bash`’s `PS1`. Haha…

**Comment by scopatz** [comment] 2015-04-03 23:08
In your `~/.xonshrc` file, set `$TITLE = ''` and see if that makes a difference @dahlia.  Thanks!

**Comment by dahlia** [comment] 2015-04-04 01:55
It seems xonsh has a builtin vcprompt equivalent, isn’t it?

**Comment by scopatz** [comment] 2015-04-04 18:13
Yes, we do.

**Comment by scopatz** [comment] 2015-04-05 03:15
@dahlia - can you post what your bashrc is?

**Comment by dahlia** [comment] 2015-04-05 03:53
I don’t have .bashrc, but have .bash_profile:

```bash
if [[ "$(which brew)" = "" ]]; then
  export PATH="/usr/local/bin:$PATH"
fi
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Setting PATH for Python 3.2
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.2/bin:${PATH}"

# Setting PATH for Python 3.3
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.3/bin:${PATH}"

# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"

# Postgres.app
PATH="$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin"

PATH="$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH"
PATH="$HOME/Library/Haskell/bin:$PATH"
PATH="$HOME/.gem/ruby/2.0.0/bin:$PATH"

export GROOVY_HOME=/usr/local/opt/groovy/libexec

export VCPROMPT_FORMAT='<%b%m%u>'
export PS1='\[\e[0;35m\]\u\[\e[m\] \[\e[2;3m\]\w\[\e[m\] \[\e[0;34m\]$(vcprompt)\[\e[m\]\[\e[1;32m\]\$\[\e[m\] '

export PATH

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source $HOME/Library/Python/2.7/bin/virtualenvwrapper.sh
if [[ "$PWD" == "$PROJECT_HOME"* ]]; then
    for project in "$WORKON_HOME/"*/; do
        if [[ "$(cat $project/.project)" == "$PWD" ]]; then
            source "$project"bin/activate
            break
        fi
    done 
fi
 
alias ls='ls --color=auto --indicator-style=slash'
alias ack=ag
alias ack-grep=ag
alias gvim=mvim 

export LC_CTYPE=en_US.UTF-8

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
```

**Comment by scopatz** [comment] 2015-04-05 06:35
So you are sourcing a bunch of things in this profile.  I wonder if this has something to do with it.  Just as a test, what happens if you (temporarily) move the `.bash_profile` to a backup file (`.bash_profile.bak`) and then run xonsh.  Sorry we don't have a great way of starting up with out bash support yet.  If this works, I'll make sure to get a fix out tomorrow.

Alternatively,  you could try commenting out all of the virtualenv stuff (everything below `#virtualenvwrapper`), which is where I suspect the error is coming from.

**Comment by scopatz** [comment] 2015-04-05 06:35
...if it is coming from the bash startup, that is.

**Comment by dahlia** [comment] 2015-04-05 07:02
I renamed .bash_profile to .bash_profile.bak, but it still is unchanged.

**Comment by scopatz** [comment] 2015-04-05 07:06
hmmm Ok. I'll keep thinking about it.

**Comment by dahlia** [comment] 2015-04-05 07:12
The cursor is wrongly placed if my terminal width is narrower than 85 cols.  If its width reaches 85 cols, the cursor finally becomes well placed.  Note that my hostname is automatically generated by Mac:

```console
$ hostname
Hong-Minhees-MacBook-Pro.local
```

**Comment by dahlia** [comment] 2015-04-05 07:23
I just found one more clue. The cursor is correctly placed only if my terminal width is wider than double of the prompt.  For example, my prompt is `dahlia@Hong-Minhees-MacBook-Pro.local ~ $ ` and it consists of 42 characters.

**Comment by scopatz** [comment] 2015-04-05 07:27
Interesting!  Try setting the `$PROMPT` in your `~/.xonshrc` to the following:

```console
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR}{BOLD_BLUE} {cwd}{NO_COLOR}{BOLD_RED}{curr_branch}{NO_COLOR} {BOLD_BLUE}${NO_COLOR} '
```

**Comment by dahlia** [comment] 2015-04-05 07:30
Oh, I got a wrong clue.  Note that it’s my observation:

| Prompt                                                | Prompt width | Terminal width | Correctly placed? |
|-------------------------------------------------------|--------------|----------------|-------------------|
| `dahlia@Hong-Minhees-MacBook-Pro.local ~ $ `          | 42           | 84             | Incorrect         |
| `dahlia@Hong-Minhees-MacBook-Pro.local ~ $ `          | 42           | 85             | Correct           |
| `dahlia@Hong-Minhees-MacBook-Pro.local ~/Projects $ ` | 51           | 93             | Incorrect         |
| `dahlia@Hong-Minhees-MacBook-Pro.local ~/Projects $ ` | 51           | 94             | Correct           |

**Comment by dahlia** [comment] 2015-04-05 07:32
Changing ‘$PROMPT’ does not solve the problem: <http://asciinema.org/a/18388>.

**Comment by scopatz** [comment] 2015-04-05 07:37
Ok what if you take out all of the color, and everything and just set: 

```console
$PROMPT = '>' * 41 + ' '
```

Does this work with size 84 width terminal?

**Comment by scopatz** [comment] 2015-04-05 07:42
Also, since you are using virtualenv, inside of xonsh, what does the following print:

```python
>>> from xonsh import shell
>>> shell.RL_LIB
```

**Comment by dahlia** [comment] 2015-04-05 08:15
> ```$PROMPT = '>' * 41 + ' '```

It does work! <http://asciinema.org/a/18391>

**Comment by dahlia** [comment] 2015-04-05 08:15
```pycon
>>> from xonsh import shell
>>> shell.RL_LIB
<CDLL '/Users/dahlia/.local/venvs/xonsh/lib/python3.4/lib-dynload/readline.so', handle 100650680 at 10275a4a8>
```

**Comment by scopatz** [comment] 2015-04-05 19:01
Yes!  Great.  Now try this.  I want to see if it is a problem with the colors or with the hostname:

```console
$PROMPT = '{user}@{hostname} {cwd}{curr_branch} $ '
```

**Comment by dahlia** [comment] 2015-04-06 03:00
The cursor is placed well now!

**Comment by scopatz** [comment] 2015-04-06 03:02
Great!  What terminal are you using again?

**Comment by scopatz** [comment] 2015-04-06 03:09
Also, what does the following return (either in xonsh or in Python):

```python
import curses
curses.setupterm()
curses.tigetnum("colors")
```

**Comment by dahlia** [comment] 2015-04-06 04:10
I’m currently using Terminal app bundled by Mac OS X.

![screen shot 2015-04-06 at 1 09 41 pm](https://cloud.githubusercontent.com/assets/12431/7000456/36fcd062-dc5e-11e4-8296-610218cdb36d.png)

**Comment by dahlia** [comment] 2015-04-06 04:11
```pycon
>>> curses.tigetnum("colors")
256
```

**Comment by scopatz** [comment] 2015-04-06 04:41
OK. So maybe try the following.  Using a color prompt again, go to the Terminal settings, and under "Profiles" -> "Advanced" there is an option to "Declare terminal as".  I believe that right now yours is set to "xterm-256color".  Set this instead to just "xterm".  Open up a new terminal window (so the changes apply) and then start up xonsh again.

Also, what version of Mac OSX are you on?

**Comment by dahlia** [comment] 2015-04-06 06:09
Yes, I’ve used xterm-256color as you guessed.  I set this to xterm, but the cursor is still wrongly placed.

![screen shot 2015-04-06 at 3 09 23 pm](https://cloud.githubusercontent.com/assets/12431/7001201/ed6a23ee-dc6e-11e4-8721-49cce686a55b.png)

**Comment by scopatz** [comment] 2015-04-06 15:32
Can you try the current master? We just merged up a possible (though unlikely) fix.

**Comment by dahlia** [comment] 2015-04-06 17:29
Still unchanged.  :sweat_smile:

**Comment by scopatz** [comment] 2015-04-06 23:32
Hi @dahlia - could you try the following four prompts, please?

```console
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {cwd}{curr_branch}$ '
$PROMPT = '{BOLD_GREEN}{user}@{hostname}\001\033(B\033[m\002 {cwd}{curr_branch}$ '
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{BOLD_RED}{curr_branch} {BOLD_BLUE}$\001\033(B\033[m\002 '
$PROMPT = '{GREEN}{user}@{hostname}{BLUE} {cwd}{RED}{curr_branch} {BLUE}${NO_COLOR} '
```

Also, if you could tell me the output of, the following:

```python
import curses
curses.setupterm()
curses.tigetstr("sgr0")
```

I think we are narrowing in on what the problem is (colors) but finding the fix is proving tricky / annoying.  Part of the problem is that there is no standard for 256 terminal colors.  Thanks!

**Comment by dahlia** [comment] 2015-04-07 02:45
> Hi @dahlia - could you try the following four prompts, please?

<http://asciinema.org/a/18458>

> Also, if you could tell me the output of, the following:

```pycon
>>> import curses
>>> curses.setupterm()
>>> curses.tigetstr("sgr0")
'\x1b(B\x1b[m'
```

**Comment by scopatz** [comment] 2015-04-07 02:53
Wow fascinating,  OK.  two more to try and then I promise that is it (hopefully ~_~).

```console
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {BOLD_BLUE}{cwd}{NO_COLOR} {curr_branch} {BOLD_BLUE}${NO_COLOR} '
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {BOLD_BLUE}{cwd}{NO_COLOR} {BOLD_RED}{curr_branch}{NO_COLOR} {BOLD_BLUE}${NO_COLOR} '
```

**Comment by dahlia** [comment] 2015-04-07 02:58
> ```
> $PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {BOLD_BLUE}{cwd}{NO_COLOR} {curr_branch} {BOLD_BLUE}${NO_COLOR} '
> $PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {BOLD_BLUE}{cwd}{NO_COLOR} {BOLD_RED}{curr_branch}{NO_COLOR} {BOLD_BLUE}${NO_COLOR} '
> ```

<http://asciinema.org/a/18459>

**Comment by scopatz** [comment] 2015-04-07 03:14
Hmm, OK.  I really have no idea as to what the root cause of this is.  But at least we have some solutions.  I would recommend playing around with the colors - if you want them.  If you get an example that works with the maximum coloring, please let us know.  

I really don't know which piece of this is causing the problem. I'd love it if you run more permutations and determine what is messing things up.  But if you just want to continue of with what works now, I don't blame you :)

**Comment by dahlia** [comment] 2015-04-07 06:51
What permutations could be made?

**Comment by scopatz** [comment] 2015-04-08 01:44
Here are some:

```console
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {cwd}{curr_branch} $ '
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{NO_COLOR} {BOLD_BLUE}{cwd}{NO_COLOR}{curr_branch} $ '
$PROMPT = '{user}@{hostname} {BOLD_BLUE}{cwd}{NO_COLOR} {curr_branch} $ '
$PROMPT = '{user}@{hostname} {cwd} {BOLD_RED}{curr_branch}{NO_COLOR} $ '
$PROMPT = '{user}@{hostname} {cwd} {curr_branch} {BOLD_BLUE}${NO_COLOR} '
```

And so on.  Just move the colors around.

**Comment by krader1961** [comment] 2015-11-14 04:35
@dahlia Is this still an issue for you? I'm running xonsh 0.2.3 on Mac OS X 10.11 with iTerm2 and TERM=xterm-256 and can't reproduce this problem even with my terminal width set to 40 characters and using readline or prompt_toolkit for the $SHELL_TYPE variable.

Note that I am using the default prompt so if you have customized the prompt that could be a factor (although that seems unlikely to me).

**Comment by zenlc2000** [comment] 2015-11-18 02:45
I may have figured it out. It seems bash and zsh, at least, want to have delimiters around the colors: 

http://tldp.org/HOWTO/Bash-Prompt-HOWTO/nonprintingchars.html

Unfortunately, I believe the delimiters are different for bash and zsh.

Bash: \[ ... \]

Zsh: %{ ... %}

I don't know about other shells but I would assume they are similar.

I see in tools.py the color definitions:

    TERM_COLORS = {
        # Reset
        'NO_COLOR': '\001\033[0m\002',  # Text Reset
        # Regular Colors
        'BLACK': '\001\033[0;30m\002',  # BLACK
        'RED': '\001\033[0;31m\002',  # RED
        'GREEN': '\001\033[0;32m\002',  # GREEN

so perhaps we could have 

    if shell == 'zsh':
       prepend = '%{'
       append = '}%'
    elif shell == 'bash':
       prepend = '\['
       append = '\]'

etc.

    TERM_COLORS = {
        # Reset
        'NO_COLOR': prepend + '\001\033[0m\002' + append,  # Text Reset
        # Regular Colors
        'BLACK': prepend +'\001\033[0;30m\002' + append,  # BLACK
        'RED': prepend + '\001\033[0;31m\002' + append,  # RED
        'GREEN': prepend + '\001\033[0;32m\002' + append,  # GREEN

etc...

**Comment by scopatz** [comment] 2015-11-18 03:10
@zenlc2000 where do bash and zsh come into this? Are you running xonsh from within one of these other shells?

**Comment by zenlc2000** [comment] 2015-11-18 03:15
No, I jumped the gun a bit. I'm pretty sure it has to do with color handling, though. I'll try a couple of experiments and see if I can narrow it down.

**Comment by scopatz** [comment] 2015-11-18 03:43
Note that `\001` and `\002` are deliminator for when to stop counting characters as part of the string length and when to start respectively.

**Comment by scopatz** [comment] 2015-11-18 03:43
I am pretty sure that is a readline-specific thing.

**Comment by mitnk** [comment] 2016-06-07 10:16
Didn't reproduce it, it should have been a readline issue, better to try `gnureadline`, which is listed in [the doc](http://xon.sh/osx.html).

**Comment by scopatz** [comment] 2016-06-08 00:00
yeah I think that there are enough ways around this now
 please feel free to reopen.

**Closed** 2016-06-08 00:00 UTC
Labels: bug
