### ISSUE TITLE
Vim system fails when $SHELL is pointing to `xonsh`

### ISSUE THREAD

**Issue by igormorgado** [xonsh/xonsh#4343] opened 2021-06-29 17:28 UTC
## Current behavior

When running vim's commands `system` and `systemlist`  with `$SHELL = /usr/bin/xonsh`  (or to local pip installed xonsh. Vim fails with message:

```
E484: Can't open file /tmp/vlsyynp/4
```

The path is randomly generated to receive the vim output. But for some reason isn't created correctly. 

## Expected behavior

Of course, the expected output is receive the output of `ls` command as a string, or as a vim list (when calling `systemlist`)

## Steps to reproduce:

1. Start `xonsh`
2. Set `$SHELL = PATH_TO_XONSH`
3. Start `vim`
4.1. type `:echom system ('ls')`; or
4.2. type `:echom systemlist ('ls')`.

It works fine if $SHELL is let alone pointing to `/bin/bash`,  `/usr/bin/fish` or `/usr/bin/zsh`, hence I think that is somehow related to `xonsh`.

## xonfig
<details>

```
[127]@ xonfig info
+------------------+----------------------+
| xonsh            | 0.9.27               |
| Git SHA          | 71fe9014             |
| Commit Date      | Jan 29 08:58:58 2021 |
| Python           | 3.9.2                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.16               |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | True                 |
| jupyter kernel   | None                 |
| xontrib 1        | apt_tabcomplete      |
| xontrib 2        | autovox              |
| xontrib 3        | cmd_done             |
| xontrib 4        | gitinfo              |
| xontrib 5        | jedi                 |
| xontrib 6        | kitty                |
| xontrib 7        | mpl                  |
| xontrib 8        | pdb                  |
| xontrib 9        | prompt_bar           |
| xontrib 10       | prompt_ret_code      |
| xontrib 11       | prompt_vi_mode       |
| xontrib 12       | ssh_agent            |
| xontrib 13       | vox                  |
| xontrib 14       | voxapi               |
+------------------+----------------------+
```

</details>

## Xontrib list

<details>

```
[2]@ xontrib list
abbrevs             installed      not-loaded
apt_tabcomplete     installed      loaded
argcomplete         installed      not-loaded
autovox             installed      loaded
bashisms            installed      not-loaded
cmd_done            installed      loaded
coreutils           installed      not-loaded
distributed         installed      not-loaded
free_cwd            installed      not-loaded
gitinfo             installed      loaded
jedi                installed      loaded
kitty               installed      loaded
mpl                 installed      loaded
mplhooks            installed      not-loaded
onepath             installed      not-loaded
pdb                 installed      loaded
prompt_bar          installed      loaded
prompt_ret_code     installed      loaded
prompt_vi_mode      installed      loaded
ssh_agent           installed      loaded
vox                 installed      loaded
vox_tabcomplete     installed      not-loaded
voxapi              installed      loaded
whole_word_jumping  installed      not-loaded
xog                 installed      not-loaded
```

</details>

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment] 2021-06-30 21:21
Thanks for reporting @igormorgado!

The issue occurs because vim sends xonsh a command similar to:

```xonsh
(ls) > /tmp/vgeis6g/1
```

The intended purpose of the command is to redirect the output of `ls` into the file `/tmp/vgeis6g/1`, so that vim can capture it.

<hr>

When running that command with xonsh (outside of vim), this is the error:

```
Traceback (most recent call last):
  File "/home/yaxollum/dev/xonsh/xonsh/base_shell.py", line 497, in compile
    code = self.execer.compile(src, mode="single", glbs=self.ctx, locs=None)
  File "/home/yaxollum/dev/xonsh/xonsh/execer.py", line 138, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/home/yaxollum/dev/xonsh/xonsh/execer.py", line 96, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/yaxollum/dev/xonsh/xonsh/execer.py", line 241, in _parse_ctx_free
    raise original_error from None
  File "/home/yaxollum/dev/xonsh/xonsh/execer.py", line 222, in _parse_ctx_free
    tree = self.parser.parse(
  File "/home/yaxollum/dev/xonsh/xonsh/parsers/base.py", line 529, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/yaxollum/dev/xonsh/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/yaxollum/dev/xonsh/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/yaxollum/dev/xonsh/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/home/yaxollum/dev/xonsh/xonsh/parsers/base.py", line 3465, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/home/yaxollum/dev/xonsh/xonsh/parsers/base.py", line 656, in _parse_error
    raise_parse_error(msg, loc, self.xonsh_code, self.lines)
  File "/home/yaxollum/dev/xonsh/xonsh/parsers/base.py", line 238, in raise_parse_error
    raise err
SyntaxError: <xonsh-code>:1:7: ('code: /',)
(ls) > /tmp/vgeis6g/1
       ^
```

<hr>

The command works as intended when the brackets around `ls` are removed:

```xonsh
ls > /tmp/vgeis6g/1
```

It also works when the brackets are kept, but there is no leading slash (`/`) in the path - obviously you would need the current working directory to be the root directory in this case:

```xonsh
(ls) > tmp/vgeis6g/1
```

Finally, it also works when you wrap the entire command in `$[]`:

```xonsh
$[(ls) > /tmp/vgeis6g/1]
```

**Since the command works when you wrap it in `$[]` (bypassing the execer subprocess wrapping logic), I think this issue is caused by a bug in the execer.**

**Comment by igormorgado** [comment] 2021-06-30 21:42
Good to know, hope it get fixed.

**Comment by anki-code** [comment] 2021-07-01 08:05
May be this workaround approach could help - [xonsh-vim-read](https://github.com/anki-code/xonsh-vim-read).

**Comment by igormorgado** [comment] 2021-07-01 16:29
Unfortunately, this do not work for two reasons

1. The xonsh workaround output do not match  bash's vim output

<details>

**xonsh-vim-read output for** `systemlist('ls')`

```
['bin^I   Dropbox     litcorpt_data  Projects^I tensorflow_datasets  ZotLib', 'data^I   dsc^I       Music^I      Public^I tmp',  'Desktop    dwhelper    nltk_data      src^I valgrind', 'Documents  Games       pCloudDrive    Steam^I Videos', 'Downloads  gtk4env.sh  Pictures       Templates  Zotero']
```

**bash vim output for** `systemlist('ls')`
```
['bin', 'data', 'Desktop', 'Documents', 'Downloads', 'Dropbox', 'dsc', 'dwhelper', 'Games', 'gtk4env.sh', 'litcorpt_data', 'Music', 'nltk_data', 'pCloudDrive', 'Pictures', 'Projects', 'Public', 'src', 'Steam', 'Templates', 'tensorflow_datasets', 'tmp', 'valgrind', 'Videos', 'Zotero', 'ZotLib']
```


**xonsh-vim-read output for** `system('ls')`
```
bin^I   Dropbox     litcorpt_data  Projects^I tensorflow_datasets  ZotLib^@data^I   dsc^I       Music^I      Public^I tmp^@Desktop    dwhelper    nltk_data      src^I valgrind^@Documents  Games       pCloudDrive    Steam^I Videos^@Downloads  gtk4e
nv.sh  Pictures       Templates  Zotero^@
```

** bash vim output for** `system('ls')`
```
bin^@data^@Desktop^@Documents^@Downloads^@Dropbox^@dsc^@dwhelper^@Games^@gtk4env.sh^@litcorpt_data^@Music^@nltk_data^@pCloudDrive^@Pictures^@Projects^@Public^@src^@Steam^@Templates^@tensorflow_datasets^@tmp^@valgrind^@Videos^@Zotero^@ZotLib^@
```

</details>

2. Runtime difference is noticiable. Since a few plugins use `system` as a tool (questionable), this will sum  up badly and vim performance will be slugish. Just to give some data. It takes 4 seconds to showup a directory using `dirvish` with `vim-dirvish-git` using xonsh workaround vs instantaneous (I was not able to measure with a clock) using vim on bash.
3.

**Comment by jnoortheen** [comment] 2022-03-06 20:25
closing it with https://github.com/xonsh/xonsh/pull/4699

**Closed by jnoortheen** 2022-03-06 20:25 UTC
Labels: external
