### ISSUE TITLE
Troublesome command entering python mode

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#2002] opened 2016-12-07 21:37 UTC
I'm trying to run this command which I used to use often in zsh:
```
svn diff ./test.py | vim -R -
```
but it keeps trying to evaluate in Python mode. 

I can usually wrestle these types of troublesome commands into submission with `$()` and `@()` but I can't figure this one out.

**Comment by mitnk** [comment] 2016-12-11 08:48
I think this an old issue exists since xonsh born? :)
A simpler try is something like this: `ps ax | view -`.

**Comment by PaulReiber** [comment] 2016-12-11 23:41
Confirmed - this problem's been around for a while.

From one angle,  "this isn't bash, it's xonsh, it works subtly differently"
is certainly a reasonable stance... but from another angle, it sure would
be nice if xonsh could handle pipelines with "screen owning" commands like
"view", "vim", "vi", "emacs", etc contained in them better than it does
right now.

AFAIK Anthony and possibly some others on the Xonsh core team have been
working hard on a bunch of improvements related to "subprocess mode".  I've
been in a sort of holding pattern, hoping that gets resolved soon myself.

In terms of impact - this is the main thing keeping me from using Xonsh for
my day to day work right now.


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by astronouth7303** [comment] 2016-12-12 04:06
I do not believe the recent subprocess refactor affects how subprocesses are parsed, just how they're executed. (Disclaimer: I haven't worked on the parser or the executor.)

Since that looks like valid xonsh, that should not raise a syntax error, and this is a valid bug.

**Comment by adqm** [comment] 2016-12-12 13:12
I am not sure when this issue first came about, but I know the above commands parse properly on what I am running (which I forked from before 0.3.5).

**Comment by JohnLunzer** [comment] 2016-12-12 15:12
I came in just sort of looking for a workaround, but I think I would agree with @astronouth7303. This isn't a complicated command line by any measure. The only "exotic" features are the pipe and the stdin. 

In fact I can simply this to `svn diff | vim -` with the same results.

**Comment by scopatz** [comment] 2016-12-15 18:18
I am looking into this now.  @JohnLunzer  can you set `$XONSH_DEBUG = 2` before you run the command and report on the output, please? Thanks!

**Comment by scopatz** [comment] 2016-12-15 18:35
Also note that on master, this does not try to evaluate in Python for me. It explicitly is opening vim/view etc. In fact, if you replace `view -` with less, it does seem to work.

Historically, what we used to do was pipe the output of the first command into a physical named temporary file. Then we would replace the trailing `-` with the path to the file. This "worked" but had some undesirable repercussions:

1. vim et al. would display that they had opened the temp file, not stdin.
2. performance was bad since a real file had to be opened, rather than working from an in-memory pipe.

The refactor fixed these issues, but obviously something is still wrong. Serves me right for testing with less :)

**Comment by scopatz** [comment] 2016-12-15 20:28
Ok, I think I have figured out the problem and a potential fix.

**Comment by JohnLunzer** [comment] 2016-12-15 21:03
Sorry for the delay. Do you still need my debug output?

**Comment by scopatz** [comment] 2016-12-15 21:26
Nope, I don't, thanks!

**Comment by scopatz** [comment] 2016-12-15 21:29
A potential fix is now in #2017.  Thanks again for reporting!

**Comment by scopatz** [comment] 2016-12-15 21:32
Also, note that more was working for me on master before this fix.

**Comment by mitnk** [comment] 2016-12-17 11:35
I can confirm that  this issue have been fixed on my side.

**Closed** 2017-01-18 23:23 UTC
