### ISSUE TITLE
Python f-strings work strange in xonsh

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3454] opened 2020-02-24 20:14 UTC
Hi! Thank you for your great work!
 <table style="width:100%">
  <tr>
    <th>Python 3.7.6</th>
    <th>xonsh/0.9.13</th>
  </tr>
  <tr>
    <td>
<pre>
>>> test=123
>>> f"{{ {test} }}"
'{ 123 }'
>>> f"{{ ' {test} ' }}"
"{ ' 123 ' }"
>>> f"{{  {test} ' }}"  
"{  123 ' }"
</pre>
</td>
    <td>
<pre>
$ test=123
$ f"{{ {test} }}"
'{123}'
$ f"{{ ' {test} ' }}"
' {test} '
$ f"{{  {test} ' }}"
$ # no any output
</pre>
</td>
  </tr>
</table> 

Why the difference is so dramatic? Thanks!

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by astronouth7303** [comment] 2020-02-24 20:20
Thank you for giving me a real head-scratcher and questioning f-strings in general. I'm not sure either of these are 100% correct.

I would categorize those test cases as "pathological". And I assume you're filing these bugs because you tried to do this in real code for valid reasons. :sob:

**Comment by anki-code** [comment] 2020-02-24 20:47
> I would categorize those test cases as "pathological". 
It's just something like json `f"{{ 'key':{value}, 'key':{value} }}"`.

So `"".format()` works as expected :)

**Comment by laloch** [comment] 2020-02-25 15:19
Related to or duplicate of #3309.

**Comment by anki-code** [comment] 2020-02-25 17:15
@laloch are you sure with ticket number? ) There are no comments about f-strings or I'm wrong and it's depends?

**Comment by anki-code** [comment] 2020-02-25 17:15
@laloch are you sure with ticket number? ) There are no comments about f-strings or I'm wrong and it's depends?

**Comment by laloch** [comment] 2020-02-25 17:19
Nope. It should have been #3390 :wink: 
Thanks.

**Comment by anki-code** [comment] 2020-02-25 18:17
Now it could be related ) But in my case every f-string is correct enough.

**Closed** 2020-08-20 20:25 UTC
Labels: bug
