### ISSUE TITLE
Stdin lockup with xclip

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#2348] opened 2017-03-31 22:19 UTC
Simple reproduction:

```
echo | xclip
```

hangs indefinitely. Redirecting input from a file works normally, and this works normally in bash/sh/etc.

**Comment by mitnk** [comment] 2017-04-01 05:06
I tried `echo | pbcopy` on Mac and did reproduce it. Could you provide your `xonfig` here?

**Comment by kirbyfan64** [comment] 2017-04-04 21:09
@mitnk For me, it only reproduces with xclip in particular, e.g. other similar tools (like xsel) don't work.

xonfig:

```
+------------------+----------------------+
| xonsh            | 0.5.8.dev11          |
| Git SHA          | 8d78f359             |
| Commit Date      | Mar 12 06:04:50 2017 |
| Python           | 3.6.0                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.9                |
| shell type       | prompt_toolkit       |
| pygments         | 2.1.3                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | debian               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

**Comment by gforsyth** [comment] 2017-04-07 12:12
Hey @kirbyfan64 -- could you try adding the following to your `xonshrc` and see if it fixes it?

```
 __xonsh_commands_cache__.threadable_predictors['xclip'] = lambda args: False
```

**Comment by kirbyfan64** [comment] 2017-04-10 00:18
@gforsyth Nope. :(

**Comment by gforsyth** [comment] 2017-04-10 12:40
huh... that's weird. I can reproduce but adding it to `threadable_predictors` fixed the problem.  Would you mind updating to current master and trying again?

**Comment by jonjitsu** [comment] 2017-04-17 02:50
@gforsyth solution worked for me on 0.5.9

**Comment by gforsyth** [comment] 2017-04-21 13:17
Hey @kirbyfan64 -- I'm going to close this since I think it's fixed, but please ping me here if it's still an issue.

**Closed by gforsyth** 2017-04-21 13:17 UTC
